.TH "_buffer_t" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_buffer_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tunala\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBdata\fP [\fBMAX_DATA_SIZE\fP]"
.br
.ti -1c
.RI "unsigned int \fBused\fP"
.br
.ti -1c
.RI "unsigned long \fBtotal_in\fP"
.br
.ti -1c
.RI "unsigned long \fBtotal_out\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file tunala\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char data[\fBMAX_DATA_SIZE\fP]"

.PP
Definition at line 89 of file tunala\&.h\&.
.SS "unsigned long total_in"

.PP
Definition at line 95 of file tunala\&.h\&.
.SS "unsigned long total_out"

.PP
Definition at line 95 of file tunala\&.h\&.
.SS "unsigned int used"

.PP
Definition at line 90 of file tunala\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
