.TH "_select_sets_t" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_select_sets_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmax\fP"
.br
.ti -1c
.RI "fd_set \fBreads\fP"
.br
.ti -1c
.RI "fd_set \fBsends\fP"
.br
.ti -1c
.RI "fd_set \fBexcepts\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file tunala\&.c\&.
.SH "Field Documentation"
.PP 
.SS "fd_set excepts"

.PP
Definition at line 48 of file tunala\&.c\&.
.SS "int max"

.PP
Definition at line 46 of file tunala\&.c\&.
.SS "fd_set reads"

.PP
Definition at line 48 of file tunala\&.c\&.
.SS "fd_set sends"

.PP
Definition at line 48 of file tunala\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
