.TH "_tunala_world_t" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_tunala_world_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlisten_fd\fP"
.br
.ti -1c
.RI "\fBtunala_item_t\fP * \fBtunnels\fP"
.br
.ti -1c
.RI "unsigned int \fBtunnels_used\fP"
.br
.ti -1c
.RI "unsigned int \fBtunnels_size\fP"
.br
.ti -1c
.RI "\fBtunala_selector_t\fP \fBselector\fP"
.br
.ti -1c
.RI "\fBSSL_CTX\fP * \fBssl_ctx\fP"
.br
.ti -1c
.RI "int \fBserver_mode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file tunala\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int listen_fd"

.PP
Definition at line 62 of file tunala\&.c\&.
.SS "\fBtunala_selector_t\fP selector"

.PP
Definition at line 68 of file tunala\&.c\&.
.SS "int server_mode"

.PP
Definition at line 78 of file tunala\&.c\&.
.SS "\fBSSL_CTX\fP* ssl_ctx"

.PP
Definition at line 73 of file tunala\&.c\&.
.SS "\fBtunala_item_t\fP* tunnels"

.PP
Definition at line 64 of file tunala\&.c\&.
.SS "unsigned int tunnels_size"

.PP
Definition at line 66 of file tunala\&.c\&.
.SS "unsigned int tunnels_used"

.PP
Definition at line 66 of file tunala\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
