.TH "s2n/libcrypto-build/openssl/crypto/asn1/a_bitstr.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/a_bitstr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBASN1_BIT_STRING_set\fP (\fBASN1_BIT_STRING\fP *\fBx\fP, unsigned char *d, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBi2c_ASN1_BIT_STRING\fP (\fBASN1_BIT_STRING\fP *\fBa\fP, unsigned char **\fBpp\fP)"
.br
.ti -1c
.RI "\fBASN1_BIT_STRING\fP * \fBc2i_ASN1_BIT_STRING\fP (\fBASN1_BIT_STRING\fP **\fBa\fP, const unsigned char **\fBpp\fP, long \fBlen\fP)"
.br
.ti -1c
.RI "int \fBASN1_BIT_STRING_set_bit\fP (\fBASN1_BIT_STRING\fP *\fBa\fP, int n, int value)"
.br
.ti -1c
.RI "int \fBASN1_BIT_STRING_get_bit\fP (\fBASN1_BIT_STRING\fP *\fBa\fP, int n)"
.br
.ti -1c
.RI "int \fBASN1_BIT_STRING_check\fP (\fBASN1_BIT_STRING\fP *\fBa\fP, unsigned char *\fBflags\fP, int flags_len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ASN1_BIT_STRING_check (\fBASN1_BIT_STRING\fP * a, unsigned char * flags, int flags_len)"

.PP
Definition at line 244 of file a_bitstr\&.c\&.
.SS "int ASN1_BIT_STRING_get_bit (\fBASN1_BIT_STRING\fP * a, int n)"

.PP
Definition at line 227 of file a_bitstr\&.c\&.
.SS "int ASN1_BIT_STRING_set (\fBASN1_BIT_STRING\fP * x, unsigned char * d, int len)"

.PP
Definition at line 63 of file a_bitstr\&.c\&.
.SS "int ASN1_BIT_STRING_set_bit (\fBASN1_BIT_STRING\fP * a, int n, int value)"

.PP
Definition at line 188 of file a_bitstr\&.c\&.
.SS "\fBASN1_BIT_STRING\fP* c2i_ASN1_BIT_STRING (\fBASN1_BIT_STRING\fP ** a, const unsigned char ** pp, long len)"

.PP
Definition at line 125 of file a_bitstr\&.c\&.
.SS "int i2c_ASN1_BIT_STRING (\fBASN1_BIT_STRING\fP * a, unsigned char ** pp)"

.PP
Definition at line 68 of file a_bitstr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
