.TH "s2n/libcrypto-build/openssl/crypto/asn1/a_d2i_fp.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/a_d2i_fp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/asn1_mac\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHEADER_SIZE\fP   8"
.br
.ti -1c
.RI "#define \fBASN1_CHUNK_INITIAL_SIZE\fP   (16 * 1024)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBASN1_d2i_fp\fP (\fBvoid\fP *(*xnew)(\fBvoid\fP), d2i_of_void *\fBd2i\fP, FILE *\fBin\fP, \fBvoid\fP **\fBx\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBASN1_d2i_bio\fP (\fBvoid\fP *(*xnew)(\fBvoid\fP), d2i_of_void *\fBd2i\fP, \fBBIO\fP *\fBin\fP, \fBvoid\fP **\fBx\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBASN1_item_d2i_bio\fP (const \fBASN1_ITEM\fP *it, \fBBIO\fP *\fBin\fP, \fBvoid\fP *\fBx\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBASN1_item_d2i_fp\fP (const \fBASN1_ITEM\fP *it, FILE *\fBin\fP, \fBvoid\fP *\fBx\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASN1_CHUNK_INITIAL_SIZE   (16 * 1024)"

.PP
Definition at line 144 of file a_d2i_fp\&.c\&.
.SS "#define HEADER_SIZE   8"

.PP
Definition at line 143 of file a_d2i_fp\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP* ASN1_d2i_bio (\fBvoid\fP *(*)(\fBvoid\fP) xnew, d2i_of_void * d2i, \fBBIO\fP * in, \fBvoid\fP ** x)"

.PP
Definition at line 86 of file a_d2i_fp\&.c\&.
.SS "\fBvoid\fP* ASN1_d2i_fp (\fBvoid\fP *(*)(\fBvoid\fP) xnew, d2i_of_void * d2i, FILE * in, \fBvoid\fP ** x)"

.PP
Definition at line 70 of file a_d2i_fp\&.c\&.
.SS "\fBvoid\fP* ASN1_item_d2i_bio (const \fBASN1_ITEM\fP * it, \fBBIO\fP * in, \fBvoid\fP * x)"

.PP
Definition at line 107 of file a_d2i_fp\&.c\&.
.SS "\fBvoid\fP* ASN1_item_d2i_fp (const \fBASN1_ITEM\fP * it, FILE * in, \fBvoid\fP * x)"

.PP
Definition at line 127 of file a_d2i_fp\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
