.TH "s2n/libcrypto-build/openssl/crypto/asn1/a_object.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/a_object.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBi2d_ASN1_OBJECT\fP (\fBASN1_OBJECT\fP *\fBa\fP, unsigned char **\fBpp\fP)"
.br
.ti -1c
.RI "int \fBa2d_ASN1_OBJECT\fP (unsigned char *\fBout\fP, int olen, const char *buf, int \fBnum\fP)"
.br
.ti -1c
.RI "int \fBi2t_ASN1_OBJECT\fP (char *buf, int buf_len, \fBASN1_OBJECT\fP *\fBa\fP)"
.br
.ti -1c
.RI "int \fBi2a_ASN1_OBJECT\fP (\fBBIO\fP *\fBbp\fP, \fBASN1_OBJECT\fP *\fBa\fP)"
.br
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBd2i_ASN1_OBJECT\fP (\fBASN1_OBJECT\fP **\fBa\fP, const unsigned char **\fBpp\fP, long \fBlength\fP)"
.br
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBc2i_ASN1_OBJECT\fP (\fBASN1_OBJECT\fP **\fBa\fP, const unsigned char **\fBpp\fP, long \fBlen\fP)"
.br
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBASN1_OBJECT_new\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBASN1_OBJECT_free\fP (\fBASN1_OBJECT\fP *\fBa\fP)"
.br
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBASN1_OBJECT_create\fP (int \fBnid\fP, unsigned char *\fBdata\fP, int \fBlen\fP, const char *sn, const char *ln)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int a2d_ASN1_OBJECT (unsigned char * out, int olen, const char * buf, int num)"

.PP
Definition at line 88 of file a_object\&.c\&.
.SS "\fBASN1_OBJECT\fP* ASN1_OBJECT_create (int nid, unsigned char * data, int len, const char * sn, const char * ln)"

.PP
Definition at line 385 of file a_object\&.c\&.
.SS "\fBvoid\fP ASN1_OBJECT_free (\fBASN1_OBJECT\fP * a)"

.PP
Definition at line 360 of file a_object\&.c\&.
.SS "\fBASN1_OBJECT\fP* ASN1_OBJECT_new (\fBvoid\fP)"

.PP
Definition at line 342 of file a_object\&.c\&.
.SS "\fBASN1_OBJECT\fP* c2i_ASN1_OBJECT (\fBASN1_OBJECT\fP ** a, const unsigned char ** pp, long len)"

.PP
Definition at line 268 of file a_object\&.c\&.
.SS "\fBASN1_OBJECT\fP* d2i_ASN1_OBJECT (\fBASN1_OBJECT\fP ** a, const unsigned char ** pp, long length)"

.PP
Definition at line 240 of file a_object\&.c\&.
.SS "int i2a_ASN1_OBJECT (\fBBIO\fP * bp, \fBASN1_OBJECT\fP * a)"

.PP
Definition at line 218 of file a_object\&.c\&.
.SS "int i2d_ASN1_OBJECT (\fBASN1_OBJECT\fP * a, unsigned char ** pp)"

.PP
Definition at line 67 of file a_object\&.c\&.
.SS "int i2t_ASN1_OBJECT (char * buf, int buf_len, \fBASN1_OBJECT\fP * a)"

.PP
Definition at line 213 of file a_object\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
