.TH "s2n/libcrypto-build/openssl/crypto/asn1/a_octet.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/a_octet.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBASN1_OCTET_STRING_dup\fP (const \fBASN1_OCTET_STRING\fP *\fBx\fP)"
.br
.ti -1c
.RI "int \fBASN1_OCTET_STRING_cmp\fP (const \fBASN1_OCTET_STRING\fP *\fBa\fP, const \fBASN1_OCTET_STRING\fP *\fBb\fP)"
.br
.ti -1c
.RI "int \fBASN1_OCTET_STRING_set\fP (\fBASN1_OCTET_STRING\fP *\fBx\fP, const unsigned char *d, int \fBlen\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ASN1_OCTET_STRING_cmp (const \fBASN1_OCTET_STRING\fP * a, const \fBASN1_OCTET_STRING\fP * b)"

.PP
Definition at line 68 of file a_octet\&.c\&.
.SS "\fBASN1_OCTET_STRING\fP* ASN1_OCTET_STRING_dup (const \fBASN1_OCTET_STRING\fP * x)"

.PP
Definition at line 63 of file a_octet\&.c\&.
.SS "int ASN1_OCTET_STRING_set (\fBASN1_OCTET_STRING\fP * x, const unsigned char * d, int len)"

.PP
Definition at line 74 of file a_octet\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
