.TH "s2n/libcrypto-build/openssl/crypto/asn1/a_utf8.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/a_utf8.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBUTF8_getc\fP (const unsigned char *str, int \fBlen\fP, unsigned long *val)"
.br
.ti -1c
.RI "int \fBUTF8_putc\fP (unsigned char *str, int \fBlen\fP, unsigned long value)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int UTF8_getc (const unsigned char * str, int len, unsigned long * val)"

.PP
Definition at line 76 of file a_utf8\&.c\&.
.SS "int UTF8_putc (unsigned char * str, int len, unsigned long value)"

.PP
Definition at line 173 of file a_utf8\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
