.TH "added_obj_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
added_obj_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBobj\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 93 of file obj_dat\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBASN1_OBJECT\fP* obj"

.PP
Definition at line 95 of file obj_dat\&.c\&.
.SS "int type"

.PP
Definition at line 94 of file obj_dat\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
