.TH "s2n/libcrypto-build/openssl/apps/app_rand.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/apps/app_rand.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'apps\&.h'\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNON_MAIN\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBapp_RAND_load_file\fP (const char *\fBfile\fP, \fBBIO\fP *bio_e, int dont_warn)"
.br
.ti -1c
.RI "long \fBapp_RAND_load_files\fP (char *name)"
.br
.ti -1c
.RI "int \fBapp_RAND_write_file\fP (const char *\fBfile\fP, \fBBIO\fP *bio_e)"
.br
.ti -1c
.RI "\fBvoid\fP \fBapp_RAND_allow_write_file\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NON_MAIN"

.PP
Definition at line 112 of file app_rand\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP app_RAND_allow_write_file (\fBvoid\fP)"

.PP
Definition at line 214 of file app_rand\&.c\&.
.SS "int app_RAND_load_file (const char * file, \fBBIO\fP * bio_e, int dont_warn)"

.PP
Definition at line 121 of file app_rand\&.c\&.
.SS "long app_RAND_load_files (char * name)"

.PP
Definition at line 162 of file app_rand\&.c\&.
.SS "int app_RAND_write_file (const char * file, \fBBIO\fP * bio_e)"

.PP
Definition at line 193 of file app_rand\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
