.TH "s2n/libcrypto-build/openssl/ms/applink.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ms/applink.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <io\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAPPLINK_STDIN\fP   1"
.br
.ti -1c
.RI "#define \fBAPPLINK_STDOUT\fP   2"
.br
.ti -1c
.RI "#define \fBAPPLINK_STDERR\fP   3"
.br
.ti -1c
.RI "#define \fBAPPLINK_FPRINTF\fP   4"
.br
.ti -1c
.RI "#define \fBAPPLINK_FGETS\fP   5"
.br
.ti -1c
.RI "#define \fBAPPLINK_FREAD\fP   6"
.br
.ti -1c
.RI "#define \fBAPPLINK_FWRITE\fP   7"
.br
.ti -1c
.RI "#define \fBAPPLINK_FSETMOD\fP   8"
.br
.ti -1c
.RI "#define \fBAPPLINK_FEOF\fP   9"
.br
.ti -1c
.RI "#define \fBAPPLINK_FCLOSE\fP   10      /* should not be used */"
.br
.ti -1c
.RI "#define \fBAPPLINK_FOPEN\fP   11      /* solely for completeness */"
.br
.ti -1c
.RI "#define \fBAPPLINK_FSEEK\fP   12"
.br
.ti -1c
.RI "#define \fBAPPLINK_FTELL\fP   13"
.br
.ti -1c
.RI "#define \fBAPPLINK_FFLUSH\fP   14"
.br
.ti -1c
.RI "#define \fBAPPLINK_FERROR\fP   15"
.br
.ti -1c
.RI "#define \fBAPPLINK_CLEARERR\fP   16"
.br
.ti -1c
.RI "#define \fBAPPLINK_FILENO\fP   17      /* to be used with below */"
.br
.ti -1c
.RI "#define \fBAPPLINK_OPEN\fP   18      /* formally can'\fBt\fP be used, as \fBflags\fP can vary */"
.br
.ti -1c
.RI "#define \fBAPPLINK_READ\fP   19"
.br
.ti -1c
.RI "#define \fBAPPLINK_WRITE\fP   20"
.br
.ti -1c
.RI "#define \fBAPPLINK_LSEEK\fP   21"
.br
.ti -1c
.RI "#define \fBAPPLINK_CLOSE\fP   22"
.br
.ti -1c
.RI "#define \fBAPPLINK_MAX\fP   22      /* always same as last macro */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__declspec\fP (dllexport)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define APPLINK_CLEARERR   16"

.PP
Definition at line 17 of file applink\&.c\&.
.SS "#define APPLINK_CLOSE   22"

.PP
Definition at line 24 of file applink\&.c\&.
.SS "#define APPLINK_FCLOSE   10      /* should not be used */"

.PP
Definition at line 10 of file applink\&.c\&.
.SS "#define APPLINK_FEOF   9"

.PP
Definition at line 9 of file applink\&.c\&.
.SS "#define APPLINK_FERROR   15"

.PP
Definition at line 16 of file applink\&.c\&.
.SS "#define APPLINK_FFLUSH   14"

.PP
Definition at line 15 of file applink\&.c\&.
.SS "#define APPLINK_FGETS   5"

.PP
Definition at line 5 of file applink\&.c\&.
.SS "#define APPLINK_FILENO   17      /* to be used with below */"

.PP
Definition at line 18 of file applink\&.c\&.
.SS "#define APPLINK_FOPEN   11      /* solely for completeness */"

.PP
Definition at line 12 of file applink\&.c\&.
.SS "#define APPLINK_FPRINTF   4"

.PP
Definition at line 4 of file applink\&.c\&.
.SS "#define APPLINK_FREAD   6"

.PP
Definition at line 6 of file applink\&.c\&.
.SS "#define APPLINK_FSEEK   12"

.PP
Definition at line 13 of file applink\&.c\&.
.SS "#define APPLINK_FSETMOD   8"

.PP
Definition at line 8 of file applink\&.c\&.
.SS "#define APPLINK_FTELL   13"

.PP
Definition at line 14 of file applink\&.c\&.
.SS "#define APPLINK_FWRITE   7"

.PP
Definition at line 7 of file applink\&.c\&.
.SS "#define APPLINK_LSEEK   21"

.PP
Definition at line 23 of file applink\&.c\&.
.SS "#define APPLINK_MAX   22      /* always same as last macro */"

.PP
Definition at line 25 of file applink\&.c\&.
.SS "#define APPLINK_OPEN   18      /* formally can'\fBt\fP be used, as \fBflags\fP can vary */"

.PP
Definition at line 20 of file applink\&.c\&.
.SS "#define APPLINK_READ   19"

.PP
Definition at line 21 of file applink\&.c\&.
.SS "#define APPLINK_STDERR   3"

.PP
Definition at line 3 of file applink\&.c\&.
.SS "#define APPLINK_STDIN   1"

.PP
Definition at line 1 of file applink\&.c\&.
.SS "#define APPLINK_STDOUT   2"

.PP
Definition at line 2 of file applink\&.c\&.
.SS "#define APPLINK_WRITE   20"

.PP
Definition at line 22 of file applink\&.c\&.
.SH "Function Documentation"
.PP 
.SS "__declspec (dllexport)"

.PP
Definition at line 76 of file applink\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
