.TH "s2n/libcrypto-build/openssl/crypto/asn1/asn_mime.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/asn_mime.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include 'asn1_locl\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBMIME_PARAM\fP"
.br
.ti -1c
.RI "struct \fBMIME_HEADER\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_SMLEN\fP   1024"
.br
.ti -1c
.RI "#define \fBmime_debug\fP(\fBx\fP)                     /* \fBx\fP */"
.br
.ti -1c
.RI "#define \fBMIME_INVALID\fP   0"
.br
.ti -1c
.RI "#define \fBMIME_START\fP   1"
.br
.ti -1c
.RI "#define \fBMIME_TYPE\fP   2"
.br
.ti -1c
.RI "#define \fBMIME_NAME\fP   3"
.br
.ti -1c
.RI "#define \fBMIME_VALUE\fP   4"
.br
.ti -1c
.RI "#define \fBMIME_QUOTE\fP   5"
.br
.ti -1c
.RI "#define \fBMIME_COMMENT\fP   6"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBPEM_write_bio_ASN1_stream\fP (\fBBIO\fP *\fBout\fP, \fBASN1_VALUE\fP *val, \fBBIO\fP *\fBin\fP, int \fBflags\fP, const char *hdr, const \fBASN1_ITEM\fP *it)"
.br
.ti -1c
.RI "int \fBSMIME_write_ASN1\fP (\fBBIO\fP *bio, \fBASN1_VALUE\fP *val, \fBBIO\fP *\fBdata\fP, int \fBflags\fP, int ctype_nid, int econt_nid, \fBSTACK_OF\fP(\fBX509_ALGOR\fP)*mdalgs, const \fBASN1_ITEM\fP *it)"
.br
.ti -1c
.RI "\fBASN1_VALUE\fP * \fBSMIME_read_ASN1\fP (\fBBIO\fP *bio, \fBBIO\fP **bcont, const \fBASN1_ITEM\fP *it)"
.br
.ti -1c
.RI "int \fBSMIME_crlf_copy\fP (\fBBIO\fP *\fBin\fP, \fBBIO\fP *\fBout\fP, int \fBflags\fP)"
.br
.ti -1c
.RI "int \fBSMIME_text\fP (\fBBIO\fP *\fBin\fP, \fBBIO\fP *\fBout\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_SMLEN   1024"

.SS "#define MIME_COMMENT   6"

.PP
Definition at line 645 of file asn_mime\&.c\&.
.SS "#define mime_debug(\fBx\fP)   /* \fBx\fP */"

.SS "#define MIME_INVALID   0"

.PP
Definition at line 639 of file asn_mime\&.c\&.
.SS "#define MIME_NAME   3"

.PP
Definition at line 642 of file asn_mime\&.c\&.
.SS "#define MIME_QUOTE   5"

.PP
Definition at line 644 of file asn_mime\&.c\&.
.SS "#define MIME_START   1"

.PP
Definition at line 640 of file asn_mime\&.c\&.
.SS "#define MIME_TYPE   2"

.PP
Definition at line 641 of file asn_mime\&.c\&.
.SS "#define MIME_VALUE   4"

.PP
Definition at line 643 of file asn_mime\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int PEM_write_bio_ASN1_stream (\fBBIO\fP * out, \fBASN1_VALUE\fP * val, \fBBIO\fP * in, int flags, const char * hdr, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 171 of file asn_mime\&.c\&.
.SS "int SMIME_crlf_copy (\fBBIO\fP * in, \fBBIO\fP * out, int flags)"

.PP
Definition at line 525 of file asn_mime\&.c\&.
.SS "\fBASN1_VALUE\fP* SMIME_read_ASN1 (\fBBIO\fP * bio, \fBBIO\fP ** bcont, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 420 of file asn_mime\&.c\&.
.SS "int SMIME_text (\fBBIO\fP * in, \fBBIO\fP * out)"

.PP
Definition at line 560 of file asn_mime\&.c\&.
.SS "int SMIME_write_ASN1 (\fBBIO\fP * bio, \fBASN1_VALUE\fP * val, \fBBIO\fP * data, int flags, int ctype_nid, int econt_nid, \fBSTACK_OF\fP(\fBX509_ALGOR\fP)* mdalgs, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 272 of file asn_mime\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
