.TH "bi_ige_test" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bi_ige_test \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const unsigned char \fBkey1\fP [32]"
.br
.ti -1c
.RI "const unsigned char \fBkey2\fP [32]"
.br
.ti -1c
.RI "const unsigned char \fBiv\fP [64]"
.br
.ti -1c
.RI "const unsigned char \fBin\fP [\fBMAX_VECTOR_SIZE\fP]"
.br
.ti -1c
.RI "const unsigned char \fBout\fP [\fBMAX_VECTOR_SIZE\fP]"
.br
.ti -1c
.RI "const size_t \fBkeysize\fP"
.br
.ti -1c
.RI "const size_t \fBlength\fP"
.br
.ti -1c
.RI "const int \fBencrypt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 119 of file igetest\&.c\&.
.SH "Field Documentation"
.PP 
.SS "const int encrypt"

.PP
Definition at line 127 of file igetest\&.c\&.
.SS "const unsigned char in[\fBMAX_VECTOR_SIZE\fP]"

.PP
Definition at line 123 of file igetest\&.c\&.
.SS "const unsigned char iv[64]"

.PP
Definition at line 122 of file igetest\&.c\&.
.SS "const unsigned char key1[32]"

.PP
Definition at line 120 of file igetest\&.c\&.
.SS "const unsigned char key2[32]"

.PP
Definition at line 121 of file igetest\&.c\&.
.SS "const size_t keysize"

.PP
Definition at line 125 of file igetest\&.c\&.
.SS "const size_t length"

.PP
Definition at line 126 of file igetest\&.c\&.
.SS "const unsigned char out[\fBMAX_VECTOR_SIZE\fP]"

.PP
Definition at line 124 of file igetest\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
