.TH "bignum_ctx_stack" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bignum_ctx_stack \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int * \fBindexes\fP"
.br
.ti -1c
.RI "unsigned int \fBdepth\fP"
.br
.ti -1c
.RI "unsigned int \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 118 of file bn_ctx\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int depth"

.PP
Definition at line 122 of file bn_ctx\&.c\&.
.SS "unsigned int* indexes"

.PP
Definition at line 120 of file bn_ctx\&.c\&.
.SS "unsigned int size"

.PP
Definition at line 122 of file bn_ctx\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
