.TH "s2n/libcrypto-build/openssl/crypto/evp/bio_enc.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/evp/bio_enc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBenc_struct\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENC_BLOCK_SIZE\fP   (1024*4)"
.br
.ti -1c
.RI "#define \fBBUF_OFFSET\fP   (\fBEVP_MAX_BLOCK_LENGTH\fP*2)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBenc_struct\fP \fBBIO_ENC_CTX\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBIO_METHOD\fP * \fBBIO_f_cipher\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBBIO_set_cipher\fP (\fBBIO\fP *\fBb\fP, const \fBEVP_CIPHER\fP *\fBc\fP, const unsigned char *\fBk\fP, const unsigned char *i, int \fBe\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUF_OFFSET   (\fBEVP_MAX_BLOCK_LENGTH\fP*2)"

.PP
Definition at line 78 of file bio_enc\&.c\&.
.SS "#define ENC_BLOCK_SIZE   (1024*4)"

.PP
Definition at line 77 of file bio_enc\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBenc_struct\fP  \fBBIO_ENC_CTX\fP"

.SH "Function Documentation"
.PP 
.SS "\fBBIO_METHOD\fP* BIO_f_cipher (\fBvoid\fP)"

.PP
Definition at line 106 of file bio_enc\&.c\&.
.SS "\fBvoid\fP BIO_set_cipher (\fBBIO\fP * b, const \fBEVP_CIPHER\fP * c, const unsigned char * k, const unsigned char * i, int e)"

.PP
Definition at line 409 of file bio_enc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
