.TH "bio_dgram_sctp_save_message_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bio_dgram_sctp_save_message_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBIO\fP * \fBbio\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 172 of file bss_dgram\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBBIO\fP* bio"

.PP
Definition at line 173 of file bss_dgram\&.c\&.
.SS "char* data"

.PP
Definition at line 174 of file bss_dgram\&.c\&.
.SS "int length"

.PP
Definition at line 175 of file bss_dgram\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
