.TH "s2n/libcrypto-build/openssl/crypto/evp/bio_ok.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/evp/bio_ok.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBok_struct\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOK_BLOCK_SIZE\fP   (1024*4)"
.br
.ti -1c
.RI "#define \fBOK_BLOCK_BLOCK\fP   4"
.br
.ti -1c
.RI "#define \fBIOBS\fP   (\fBOK_BLOCK_SIZE\fP+ \fBOK_BLOCK_BLOCK\fP+ 3*\fBEVP_MAX_MD_SIZE\fP)"
.br
.ti -1c
.RI "#define \fBWELLKNOWN\fP   'The quick brown fox jumped over the lazy dog's back\&.'"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBok_struct\fP \fBBIO_OK_CTX\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBIO_METHOD\fP * \fBBIO_f_reliable\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IOBS   (\fBOK_BLOCK_SIZE\fP+ \fBOK_BLOCK_BLOCK\fP+ 3*\fBEVP_MAX_MD_SIZE\fP)"

.PP
Definition at line 142 of file bio_ok\&.c\&.
.SS "#define OK_BLOCK_BLOCK   4"

.PP
Definition at line 141 of file bio_ok\&.c\&.
.SS "#define OK_BLOCK_SIZE   (1024*4)"

.PP
Definition at line 140 of file bio_ok\&.c\&.
.SS "#define WELLKNOWN   'The quick brown fox jumped over the lazy dog's back\&.'"

.PP
Definition at line 143 of file bio_ok\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBok_struct\fP  \fBBIO_OK_CTX\fP"

.SH "Function Documentation"
.PP 
.SS "\fBBIO_METHOD\fP* BIO_f_reliable (\fBvoid\fP)"

.PP
Definition at line 170 of file bio_ok\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
