.TH "s2n/libcrypto-build/openssl/crypto/evp/bio_b64.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/evp/bio_b64.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBb64_struct\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBB64_BLOCK_SIZE\fP   1024"
.br
.ti -1c
.RI "#define \fBB64_BLOCK_SIZE2\fP   768"
.br
.ti -1c
.RI "#define \fBB64_NONE\fP   0"
.br
.ti -1c
.RI "#define \fBB64_ENCODE\fP   1"
.br
.ti -1c
.RI "#define \fBB64_DECODE\fP   2"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBb64_struct\fP \fBBIO_B64_CTX\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBIO_METHOD\fP * \fBBIO_f_base64\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define B64_BLOCK_SIZE   1024"

.PP
Definition at line 75 of file bio_b64\&.c\&.
.SS "#define B64_BLOCK_SIZE2   768"

.PP
Definition at line 76 of file bio_b64\&.c\&.
.SS "#define B64_DECODE   2"

.PP
Definition at line 79 of file bio_b64\&.c\&.
.SS "#define B64_ENCODE   1"

.PP
Definition at line 78 of file bio_b64\&.c\&.
.SS "#define B64_NONE   0"

.PP
Definition at line 77 of file bio_b64\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBb64_struct\fP  \fBBIO_B64_CTX\fP"

.SH "Function Documentation"
.PP 
.SS "\fBBIO_METHOD\fP* BIO_f_base64 (\fBvoid\fP)"

.PP
Definition at line 109 of file bio_b64\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
