.TH "bio_dgram_sctp_data_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bio_dgram_sctp_data_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct sockaddr \fBsa\fP"
.br
.ti -1c
.RI "   struct sockaddr_in \fBsa_in\fP"
.br
.ti -1c
.RI "} \fBpeer\fP"
.br
.ti -1c
.RI "unsigned int \fBconnected\fP"
.br
.ti -1c
.RI "unsigned int \fB_errno\fP"
.br
.ti -1c
.RI "unsigned int \fBmtu\fP"
.br
.ti -1c
.RI "struct \fBbio_dgram_sctp_sndinfo\fP \fBsndinfo\fP"
.br
.ti -1c
.RI "struct \fBbio_dgram_sctp_rcvinfo\fP \fBrcvinfo\fP"
.br
.ti -1c
.RI "struct \fBbio_dgram_sctp_prinfo\fP \fBprinfo\fP"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBhandle_notifications\fP )(\fBBIO\fP *bio, \fBvoid\fP *context, \fBvoid\fP *buf)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBnotification_context\fP"
.br
.ti -1c
.RI "int \fBin_handshake\fP"
.br
.ti -1c
.RI "int \fBccs_rcvd\fP"
.br
.ti -1c
.RI "int \fBccs_sent\fP"
.br
.ti -1c
.RI "int \fBsave_shutdown\fP"
.br
.ti -1c
.RI "int \fBpeer_auth_tested\fP"
.br
.ti -1c
.RI "\fBbio_dgram_sctp_save_message\fP \fBsaved_message\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 178 of file bss_dgram\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int _errno"

.PP
Definition at line 187 of file bss_dgram\&.c\&.
.SS "int ccs_rcvd"

.PP
Definition at line 195 of file bss_dgram\&.c\&.
.SS "int ccs_sent"

.PP
Definition at line 196 of file bss_dgram\&.c\&.
.SS "unsigned int connected"

.PP
Definition at line 186 of file bss_dgram\&.c\&.
.SS "\fBvoid\fP(* handle_notifications) (\fBBIO\fP *bio, \fBvoid\fP *context, \fBvoid\fP *buf)"

.PP
Definition at line 192 of file bss_dgram\&.c\&.
.SS "int in_handshake"

.PP
Definition at line 194 of file bss_dgram\&.c\&.
.SS "unsigned int mtu"

.PP
Definition at line 188 of file bss_dgram\&.c\&.
.SS "\fBvoid\fP* notification_context"

.PP
Definition at line 193 of file bss_dgram\&.c\&.
.SS "union { \&.\&.\&. }   peer"

.SS "int peer_auth_tested"

.PP
Definition at line 198 of file bss_dgram\&.c\&.
.SS "struct \fBbio_dgram_sctp_prinfo\fP prinfo"

.PP
Definition at line 191 of file bss_dgram\&.c\&.
.SS "struct \fBbio_dgram_sctp_rcvinfo\fP rcvinfo"

.PP
Definition at line 190 of file bss_dgram\&.c\&.
.SS "struct sockaddr sa"

.PP
Definition at line 180 of file bss_dgram\&.c\&.
.SS "struct sockaddr_in sa_in"

.PP
Definition at line 181 of file bss_dgram\&.c\&.
.SS "int save_shutdown"

.PP
Definition at line 197 of file bss_dgram\&.c\&.
.SS "\fBbio_dgram_sctp_save_message\fP saved_message"

.PP
Definition at line 199 of file bss_dgram\&.c\&.
.SS "struct \fBbio_dgram_sctp_sndinfo\fP sndinfo"

.PP
Definition at line 189 of file bss_dgram\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
