.TH "s2n/libcrypto-build/openssl/ssl/bio_ssl.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ssl/bio_ssl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <openssl/ssl\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBbio_ssl_st\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBbio_ssl_st\fP \fBBIO_SSL\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBIO_METHOD\fP * \fBBIO_f_ssl\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_new_buffer_ssl_connect\fP (\fBSSL_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_new_ssl_connect\fP (\fBSSL_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_new_ssl\fP (\fBSSL_CTX\fP *\fBctx\fP, int client)"
.br
.ti -1c
.RI "int \fBBIO_ssl_copy_session_id\fP (\fBBIO\fP *\fBt\fP, \fBBIO\fP *\fBf\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBBIO_ssl_shutdown\fP (\fBBIO\fP *\fBb\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBbio_ssl_st\fP  \fBBIO_SSL\fP"

.SH "Function Documentation"
.PP 
.SS "\fBBIO_METHOD\fP* BIO_f_ssl (\fBvoid\fP)"

.PP
Definition at line 97 of file bio_ssl\&.c\&.
.SS "\fBBIO\fP* BIO_new_buffer_ssl_connect (\fBSSL_CTX\fP * ctx)"

.PP
Definition at line 506 of file bio_ssl\&.c\&.
.SS "\fBBIO\fP* BIO_new_ssl (\fBSSL_CTX\fP * ctx, int client)"

.PP
Definition at line 546 of file bio_ssl\&.c\&.
.SS "\fBBIO\fP* BIO_new_ssl_connect (\fBSSL_CTX\fP * ctx)"

.PP
Definition at line 527 of file bio_ssl\&.c\&.
.SS "int BIO_ssl_copy_session_id (\fBBIO\fP * t, \fBBIO\fP * f)"

.PP
Definition at line 566 of file bio_ssl\&.c\&.
.SS "\fBvoid\fP BIO_ssl_shutdown (\fBBIO\fP * b)"

.PP
Definition at line 579 of file bio_ssl\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
