.TH "s2n/libcrypto-build/openssl/crypto/bio/bio_lib.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/bio/bio_lib.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/stack\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBIO\fP * \fBBIO_new\fP (\fBBIO_METHOD\fP *method)"
.br
.ti -1c
.RI "int \fBBIO_set\fP (\fBBIO\fP *bio, \fBBIO_METHOD\fP *method)"
.br
.ti -1c
.RI "int \fBBIO_free\fP (\fBBIO\fP *\fBa\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBBIO_vfree\fP (\fBBIO\fP *\fBa\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBBIO_clear_flags\fP (\fBBIO\fP *\fBb\fP, int \fBflags\fP)"
.br
.ti -1c
.RI "int \fBBIO_test_flags\fP (const \fBBIO\fP *\fBb\fP, int \fBflags\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBBIO_set_flags\fP (\fBBIO\fP *\fBb\fP, int \fBflags\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBBIO_set_callback\fP (\fBBIO\fP *\fBb\fP, long(*\fBcb\fP)(struct \fBbio_st\fP *, int, const char *, int,                                                                                                                               long, long))"
.br
.ti -1c
.RI "\fBvoid\fP \fBBIO_set_callback_arg\fP (\fBBIO\fP *\fBb\fP, char *\fBarg\fP)"
.br
.ti -1c
.RI "char * \fBBIO_get_callback_arg\fP (const \fBBIO\fP *\fBb\fP)"
.br
.ti -1c
.RI "const char * \fBBIO_method_name\fP (const \fBBIO\fP *\fBb\fP)"
.br
.ti -1c
.RI "int \fBBIO_method_type\fP (const \fBBIO\fP *\fBb\fP)"
.br
.ti -1c
.RI "int \fBBIO_read\fP (\fBBIO\fP *\fBb\fP, \fBvoid\fP *\fBout\fP, int outl)"
.br
.ti -1c
.RI "int \fBBIO_write\fP (\fBBIO\fP *\fBb\fP, const \fBvoid\fP *\fBin\fP, int inl)"
.br
.ti -1c
.RI "int \fBBIO_puts\fP (\fBBIO\fP *\fBb\fP, const char *\fBin\fP)"
.br
.ti -1c
.RI "int \fBBIO_gets\fP (\fBBIO\fP *\fBb\fP, char *\fBin\fP, int inl)"
.br
.ti -1c
.RI "int \fBBIO_indent\fP (\fBBIO\fP *\fBb\fP, int indent, int \fBmax\fP)"
.br
.ti -1c
.RI "long \fBBIO_int_ctrl\fP (\fBBIO\fP *\fBb\fP, int cmd, long larg, int iarg)"
.br
.ti -1c
.RI "char * \fBBIO_ptr_ctrl\fP (\fBBIO\fP *\fBb\fP, int cmd, long larg)"
.br
.ti -1c
.RI "long \fBBIO_ctrl\fP (\fBBIO\fP *\fBb\fP, int cmd, long larg, \fBvoid\fP *parg)"
.br
.ti -1c
.RI "long \fBBIO_callback_ctrl\fP (\fBBIO\fP *\fBb\fP, int cmd, \fBvoid\fP(*\fBfp\fP)(struct \fBbio_st\fP *, int, const char *, int,                                                                                                                                   long, long))"
.br
.ti -1c
.RI "size_t \fBBIO_ctrl_pending\fP (\fBBIO\fP *bio)"
.br
.ti -1c
.RI "size_t \fBBIO_ctrl_wpending\fP (\fBBIO\fP *bio)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_push\fP (\fBBIO\fP *\fBb\fP, \fBBIO\fP *bio)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_pop\fP (\fBBIO\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_get_retry_BIO\fP (\fBBIO\fP *bio, int *reason)"
.br
.ti -1c
.RI "int \fBBIO_get_retry_reason\fP (\fBBIO\fP *bio)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_find_type\fP (\fBBIO\fP *bio, int \fBtype\fP)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_next\fP (\fBBIO\fP *\fBb\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBBIO_free_all\fP (\fBBIO\fP *bio)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_dup_chain\fP (\fBBIO\fP *\fBin\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBBIO_copy_next_retry\fP (\fBBIO\fP *\fBb\fP)"
.br
.ti -1c
.RI "int \fBBIO_get_ex_new_index\fP (long argl, \fBvoid\fP *argp, \fBCRYPTO_EX_new\fP *new_func, \fBCRYPTO_EX_dup\fP *dup_func, \fBCRYPTO_EX_free\fP *\fBfree_func\fP)"
.br
.ti -1c
.RI "int \fBBIO_set_ex_data\fP (\fBBIO\fP *bio, int idx, \fBvoid\fP *\fBdata\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBBIO_get_ex_data\fP (\fBBIO\fP *bio, int idx)"
.br
.ti -1c
.RI "unsigned long \fBBIO_number_read\fP (\fBBIO\fP *bio)"
.br
.ti -1c
.RI "unsigned long \fBBIO_number_written\fP (\fBBIO\fP *bio)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "long(*)(struct \fBbio_st\fP *, int, const char *, int, long, long) \fBBIO_get_callback\fP (const \fBBIO\fP *\fBb\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "long BIO_callback_ctrl (\fBBIO\fP * b, int cmd, \fBvoid\fP(*)(struct \fBbio_st\fP *, int, const char *, int,                                                                                                                                   long, long) fp)"

.PP
Definition at line 366 of file bio_lib\&.c\&.
.SS "\fBvoid\fP BIO_clear_flags (\fBBIO\fP * b, int flags)"

.PP
Definition at line 143 of file bio_lib\&.c\&.
.SS "\fBvoid\fP BIO_copy_next_retry (\fBBIO\fP * b)"

.PP
Definition at line 559 of file bio_lib\&.c\&.
.SS "long BIO_ctrl (\fBBIO\fP * b, int cmd, long larg, \fBvoid\fP * parg)"

.PP
Definition at line 340 of file bio_lib\&.c\&.
.SS "size_t BIO_ctrl_pending (\fBBIO\fP * bio)"

.PP
Definition at line 399 of file bio_lib\&.c\&.
.SS "size_t BIO_ctrl_wpending (\fBBIO\fP * bio)"

.PP
Definition at line 404 of file bio_lib\&.c\&.
.SS "\fBBIO\fP* BIO_dup_chain (\fBBIO\fP * in)"

.PP
Definition at line 516 of file bio_lib\&.c\&.
.SS "\fBBIO\fP* BIO_find_type (\fBBIO\fP * bio, int type)"

.PP
Definition at line 471 of file bio_lib\&.c\&.
.SS "int BIO_free (\fBBIO\fP * a)"

.PP
Definition at line 107 of file bio_lib\&.c\&.
.SS "\fBvoid\fP BIO_free_all (\fBBIO\fP * bio)"

.PP
Definition at line 500 of file bio_lib\&.c\&.
.SS "char* BIO_get_callback_arg (const \fBBIO\fP * b)"

.PP
Definition at line 175 of file bio_lib\&.c\&.
.SS "\fBvoid\fP* BIO_get_ex_data (\fBBIO\fP * bio, int idx)"

.PP
Definition at line 577 of file bio_lib\&.c\&.
.SS "int BIO_get_ex_new_index (long argl, \fBvoid\fP * argp, \fBCRYPTO_EX_new\fP * new_func, \fBCRYPTO_EX_dup\fP * dup_func, \fBCRYPTO_EX_free\fP * free_func)"

.PP
Definition at line 565 of file bio_lib\&.c\&.
.SS "\fBBIO\fP* BIO_get_retry_BIO (\fBBIO\fP * bio, int * reason)"

.PP
Definition at line 448 of file bio_lib\&.c\&.
.SS "int BIO_get_retry_reason (\fBBIO\fP * bio)"

.PP
Definition at line 466 of file bio_lib\&.c\&.
.SS "int BIO_gets (\fBBIO\fP * b, char * in, int inl)"

.PP
Definition at line 283 of file bio_lib\&.c\&.
.SS "int BIO_indent (\fBBIO\fP * b, int indent, int max)"

.PP
Definition at line 310 of file bio_lib\&.c\&.
.SS "long BIO_int_ctrl (\fBBIO\fP * b, int cmd, long larg, int iarg)"

.PP
Definition at line 322 of file bio_lib\&.c\&.
.SS "const char* BIO_method_name (const \fBBIO\fP * b)"

.PP
Definition at line 180 of file bio_lib\&.c\&.
.SS "int BIO_method_type (const \fBBIO\fP * b)"

.PP
Definition at line 185 of file bio_lib\&.c\&.
.SS "\fBBIO\fP* BIO_new (\fBBIO_METHOD\fP * method)"

.PP
Definition at line 66 of file bio_lib\&.c\&.
.SS "\fBBIO\fP* BIO_next (\fBBIO\fP * b)"

.PP
Definition at line 493 of file bio_lib\&.c\&.
.SS "unsigned long BIO_number_read (\fBBIO\fP * bio)"

.PP
Definition at line 582 of file bio_lib\&.c\&.
.SS "unsigned long BIO_number_written (\fBBIO\fP * bio)"

.PP
Definition at line 589 of file bio_lib\&.c\&.
.SS "\fBBIO\fP* BIO_pop (\fBBIO\fP * b)"

.PP
Definition at line 428 of file bio_lib\&.c\&.
.SS "char* BIO_ptr_ctrl (\fBBIO\fP * b, int cmd, long larg)"

.PP
Definition at line 330 of file bio_lib\&.c\&.
.SS "\fBBIO\fP* BIO_push (\fBBIO\fP * b, \fBBIO\fP * bio)"

.PP
Definition at line 410 of file bio_lib\&.c\&.
.SS "int BIO_puts (\fBBIO\fP * b, const char * in)"

.PP
Definition at line 253 of file bio_lib\&.c\&.
.SS "int BIO_read (\fBBIO\fP * b, \fBvoid\fP * out, int outl)"

.PP
Definition at line 190 of file bio_lib\&.c\&.
.SS "int BIO_set (\fBBIO\fP * bio, \fBBIO_METHOD\fP * method)"

.PP
Definition at line 82 of file bio_lib\&.c\&.
.SS "\fBvoid\fP BIO_set_callback (\fBBIO\fP * b, long(*)(struct \fBbio_st\fP *, int, const char *, int,                                                                                                                               long, long) cb)"

.PP
Definition at line 163 of file bio_lib\&.c\&.
.SS "\fBvoid\fP BIO_set_callback_arg (\fBBIO\fP * b, char * arg)"

.PP
Definition at line 170 of file bio_lib\&.c\&.
.SS "int BIO_set_ex_data (\fBBIO\fP * bio, int idx, \fBvoid\fP * data)"

.PP
Definition at line 572 of file bio_lib\&.c\&.
.SS "\fBvoid\fP BIO_set_flags (\fBBIO\fP * b, int flags)"

.PP
Definition at line 153 of file bio_lib\&.c\&.
.SS "int BIO_test_flags (const \fBBIO\fP * b, int flags)"

.PP
Definition at line 148 of file bio_lib\&.c\&.
.SS "\fBvoid\fP BIO_vfree (\fBBIO\fP * a)"

.PP
Definition at line 138 of file bio_lib\&.c\&.
.SS "int BIO_write (\fBBIO\fP * b, const \fBvoid\fP * in, int inl)"

.PP
Definition at line 220 of file bio_lib\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "long(*)(struct \fBbio_st\fP *, int, const char *, int, long, long) BIO_get_callback(const \fBBIO\fP *\fBb\fP)"

.PP
Definition at line 158 of file bio_lib\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
