.TH "bio_ssl_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bio_ssl_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBSSL\fP * \fBssl\fP"
.br
.ti -1c
.RI "int \fBnum_renegotiates\fP"
.br
.ti -1c
.RI "unsigned long \fBrenegotiate_count\fP"
.br
.ti -1c
.RI "unsigned long \fBbyte_count\fP"
.br
.ti -1c
.RI "unsigned long \fBrenegotiate_timeout\fP"
.br
.ti -1c
.RI "unsigned long \fBlast_time\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file bio_ssl\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned long byte_count"

.PP
Definition at line 80 of file bio_ssl\&.c\&.
.SS "unsigned long last_time"

.PP
Definition at line 82 of file bio_ssl\&.c\&.
.SS "int num_renegotiates"

.PP
Definition at line 78 of file bio_ssl\&.c\&.
.SS "unsigned long renegotiate_count"

.PP
Definition at line 79 of file bio_ssl\&.c\&.
.SS "unsigned long renegotiate_timeout"

.PP
Definition at line 81 of file bio_ssl\&.c\&.
.SS "\fBSSL\fP* ssl"

.PP
Definition at line 76 of file bio_ssl\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
