.TH "s2n/libcrypto-build/openssl/crypto/bn/bn_exp2.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/bn/bn_exp2.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include 'bn_lcl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTABLE_SIZE\fP   32"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBBN_mod_exp2_mont\fP (\fBBIGNUM\fP *rr, const \fBBIGNUM\fP *a1, const \fBBIGNUM\fP *p1, const \fBBIGNUM\fP *a2, const \fBBIGNUM\fP *p2, const \fBBIGNUM\fP *m, \fBBN_CTX\fP *\fBctx\fP, \fBBN_MONT_CTX\fP *in_mont)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TABLE_SIZE   32"

.PP
Definition at line 116 of file bn_exp2\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int BN_mod_exp2_mont (\fBBIGNUM\fP * rr, const \fBBIGNUM\fP * a1, const \fBBIGNUM\fP * p1, const \fBBIGNUM\fP * a2, const \fBBIGNUM\fP * p2, const \fBBIGNUM\fP * m, \fBBN_CTX\fP * ctx, \fBBN_MONT_CTX\fP * in_mont)"

.PP
Definition at line 118 of file bn_exp2\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
