.TH "s2n/libcrypto-build/openssl/crypto/bn/bn_prime.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/bn/bn_prime.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNUMPRIMES\fP   2048"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned short \fBprime_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NUMPRIMES   2048"

.PP
Definition at line 60 of file bn_prime\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned short \fBprime_t\fP"

.PP
Definition at line 61 of file bn_prime\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
