.TH "s2n/libcrypto-build/openssl/crypto/bn/bn_sqr.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/bn/bn_sqr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include 'bn_lcl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBBN_sqr\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, \fBBN_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBbn_sqr_normal\fP (BN_ULONG *r, const BN_ULONG *\fBa\fP, int n, BN_ULONG *tmp)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int BN_sqr (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * a, \fBBN_CTX\fP * ctx)"

.PP
Definition at line 67 of file bn_sqr\&.c\&.
.SS "\fBvoid\fP bn_sqr_normal (BN_ULONG * r, const BN_ULONG * a, int n, BN_ULONG * tmp)"

.PP
Definition at line 157 of file bn_sqr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
