.TH "s2n/libcrypto-build/openssl/crypto/bio/bss_fd.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/bio/bss_fd.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include 'bio_lcl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSE_SOCKETS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBBIO_fd_should_retry\fP (int s)"
.br
.ti -1c
.RI "\fBBIO_METHOD\fP * \fBBIO_s_fd\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_new_fd\fP (int fd, int close_flag)"
.br
.ti -1c
.RI "int \fBBIO_fd_non_fatal_error\fP (int err)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define USE_SOCKETS"

.PP
Definition at line 61 of file bss_fd\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int BIO_fd_non_fatal_error (int err)"

.PP
Definition at line 284 of file bss_fd\&.c\&.
.SS "int BIO_fd_should_retry (int s)"

.PP
Definition at line 266 of file bss_fd\&.c\&.
.SS "\fBBIO\fP* BIO_new_fd (int fd, int close_flag)"

.PP
Definition at line 128 of file bss_fd\&.c\&.
.SS "\fBBIO_METHOD\fP* BIO_s_fd (\fBvoid\fP)"

.PP
Definition at line 123 of file bss_fd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
