.TH "s2n/libcrypto-build/openssl/crypto/bio/bss_rtcp.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/bio/bss_rtcp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <iodef\&.h>\fP
.br
\fC#include <starlet\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBio_status\fP"
.br
.ti -1c
.RI "struct \fBrpc_msg\fP"
.br
.ti -1c
.RI "struct \fBrpc_ctx\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRPC_HDR_SIZE\fP   (sizeof(struct \fBrpc_msg\fP) \- 4092)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned short \fBio_channel\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBIO_METHOD\fP * \fBBIO_s_rtcp\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RPC_HDR_SIZE   (sizeof(struct \fBrpc_msg\fP) \- 4092)"

.PP
Definition at line 93 of file bss_rtcp\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned short \fBio_channel\fP"

.PP
Definition at line 75 of file bss_rtcp\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBBIO_METHOD\fP* BIO_s_rtcp (\fBvoid\fP)"

.PP
Definition at line 121 of file bss_rtcp\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
