.TH "s2n/libcrypto-build/openssl/crypto/bio/bss_mem.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/bio/bss_mem.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBIO_METHOD\fP * \fBBIO_s_mem\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_new_mem_buf\fP (const \fBvoid\fP *buf, int \fBlen\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBBIO\fP* BIO_new_mem_buf (const \fBvoid\fP * buf, int len)"

.PP
Definition at line 95 of file bss_mem\&.c\&.
.SS "\fBBIO_METHOD\fP* BIO_s_mem (\fBvoid\fP)"

.PP
Definition at line 89 of file bss_mem\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
