.TH "s2n/libcrypto-build/openssl/crypto/comp/c_zlib.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/comp/c_zlib.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/comp\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCOMP_METHOD\fP * \fBCOMP_zlib\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCOMP_zlib_cleanup\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCOMP_METHOD\fP * COMP_zlib (\fBvoid\fP)"

.PP
Definition at line 343 of file c_zlib\&.c\&.
.SS "\fBvoid\fP COMP_zlib_cleanup (\fBvoid\fP)"

.PP
Definition at line 404 of file c_zlib\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
