.TH "s2n/libcrypto-build/openssl/crypto/camellia/camellia.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/camellia/camellia.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'camellia\&.h'\fP
.br
\fC#include 'cmll_locl\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRightRotate\fP(\fBx\fP,  s)   ( ((\fBx\fP) >> (s)) + ((\fBx\fP) << (32 \- s)) )"
.br
.ti -1c
.RI "#define \fBLeftRotate\fP(\fBx\fP,  s)   ( ((\fBx\fP) << (s)) + ((\fBx\fP) >> (32 \- s)) )"
.br
.ti -1c
.RI "#define \fBGETU32\fP(\fBp\fP)     (((\fBu32\fP)(\fBp\fP)[0] << 24) ^ ((\fBu32\fP)(\fBp\fP)[1] << 16) ^ ((\fBu32\fP)(\fBp\fP)[2] <<  8) ^ ((\fBu32\fP)(\fBp\fP)[3]))"
.br
.ti -1c
.RI "#define \fBPUTU32\fP(\fBp\fP,  v)   ((\fBp\fP)[0] = (\fBu8\fP)((v) >> 24), (\fBp\fP)[1] = (\fBu8\fP)((v) >> 16), (\fBp\fP)[2] = (\fBu8\fP)((v) >>  8), (\fBp\fP)[3] = (\fBu8\fP)(v))"
.br
.ti -1c
.RI "#define \fBSBOX1_1110\fP   Camellia_SBOX[0]"
.br
.ti -1c
.RI "#define \fBSBOX4_4404\fP   Camellia_SBOX[1]"
.br
.ti -1c
.RI "#define \fBSBOX2_0222\fP   Camellia_SBOX[2]"
.br
.ti -1c
.RI "#define \fBSBOX3_3033\fP   Camellia_SBOX[3]"
.br
.ti -1c
.RI "#define \fBCamellia_Feistel\fP(_s0,  _s1,  _s2,  _s3,  _key)"
.br
.ti -1c
.RI "#define \fBRotLeft128\fP(_s0,  _s1,  _s2,  _s3,  _n)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBCamellia_Ekeygen\fP (int keyBitLength, const \fBu8\fP *rawKey, \fBKEY_TABLE_TYPE\fP \fBk\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCamellia_EncryptBlock_Rounds\fP (int grandRounds, const \fBu8\fP plaintext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP ciphertext[])"
.br
.ti -1c
.RI "\fBvoid\fP \fBCamellia_EncryptBlock\fP (int keyBitLength, const \fBu8\fP plaintext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP ciphertext[])"
.br
.ti -1c
.RI "\fBvoid\fP \fBCamellia_DecryptBlock_Rounds\fP (int grandRounds, const \fBu8\fP ciphertext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP plaintext[])"
.br
.ti -1c
.RI "\fBvoid\fP \fBCamellia_DecryptBlock\fP (int keyBitLength, const \fBu8\fP plaintext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP ciphertext[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define Camellia_Feistel(_s0, _s1, _s2, _s3, _key)"
\fBValue:\fP
.PP
.nf
do {\
        register u32 _t0,_t1,_t2,_t3;\
\
        _t0  = _s0 ^ (_key)[0];\
        _t3  = SBOX4_4404[_t0&0xff];\
        _t1  = _s1 ^ (_key)[1];\
        _t3 ^= SBOX3_3033[(_t0 >> 8)&0xff];\
        _t2  = SBOX1_1110[_t1&0xff];\
        _t3 ^= SBOX2_0222[(_t0 >> 16)&0xff];\
        _t2 ^= SBOX4_4404[(_t1 >> 8)&0xff];\
        _t3 ^= SBOX1_1110[(_t0 >> 24)];\
        _t2 ^= _t3;\
        _t3  = RightRotate(_t3,8);\
        _t2 ^= SBOX3_3033[(_t1 >> 16)&0xff];\
        _s3 ^= _t3;\
        _t2 ^= SBOX2_0222[(_t1 >> 24)];\
        _s2 ^= _t2; \
        _s3 ^= _t2;\
} while(0)
.fi
.PP
Definition at line 330 of file camellia\&.c\&.
.SS "#define GETU32(\fBp\fP)   (((\fBu32\fP)(\fBp\fP)[0] << 24) ^ ((\fBu32\fP)(\fBp\fP)[1] << 16) ^ ((\fBu32\fP)(\fBp\fP)[2] <<  8) ^ ((\fBu32\fP)(\fBp\fP)[3]))"

.PP
Definition at line 132 of file camellia\&.c\&.
.SS "#define LeftRotate(\fBx\fP, s)   ( ((\fBx\fP) << (s)) + ((\fBx\fP) >> (32 \- s)) )"

.PP
Definition at line 128 of file camellia\&.c\&.
.SS "#define PUTU32(\fBp\fP, v)   ((\fBp\fP)[0] = (\fBu8\fP)((v) >> 24), (\fBp\fP)[1] = (\fBu8\fP)((v) >> 16), (\fBp\fP)[2] = (\fBu8\fP)((v) >>  8), (\fBp\fP)[3] = (\fBu8\fP)(v))"

.PP
Definition at line 133 of file camellia\&.c\&.
.SS "#define RightRotate(\fBx\fP, s)   ( ((\fBx\fP) >> (s)) + ((\fBx\fP) << (32 \- s)) )"

.PP
Definition at line 127 of file camellia\&.c\&.
.SS "#define RotLeft128(_s0, _s1, _s2, _s3, _n)"
\fBValue:\fP
.PP
.nf
do {\
        u32 _t0=_s0>>(32-_n);\
        _s0 = (_s0<<_n) | (_s1>>(32-_n));\
        _s1 = (_s1<<_n) | (_s2>>(32-_n));\
        _s2 = (_s2<<_n) | (_s3>>(32-_n));\
        _s3 = (_s3<<_n) | _t0;\
} while (0)
.fi
.PP
Definition at line 355 of file camellia\&.c\&.
.SS "#define SBOX1_1110   Camellia_SBOX[0]"

.PP
Definition at line 137 of file camellia\&.c\&.
.SS "#define SBOX2_0222   Camellia_SBOX[2]"

.PP
Definition at line 139 of file camellia\&.c\&.
.SS "#define SBOX3_3033   Camellia_SBOX[3]"

.PP
Definition at line 140 of file camellia\&.c\&.
.SS "#define SBOX4_4404   Camellia_SBOX[1]"

.PP
Definition at line 138 of file camellia\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP Camellia_DecryptBlock (int keyBitLength, const \fBu8\fP plaintext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP ciphertext[])"

.PP
Definition at line 579 of file camellia\&.c\&.
.SS "\fBvoid\fP Camellia_DecryptBlock_Rounds (int grandRounds, const \fBu8\fP ciphertext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP plaintext[])"

.PP
Definition at line 533 of file camellia\&.c\&.
.SS "int Camellia_Ekeygen (int keyBitLength, const \fBu8\fP * rawKey, \fBKEY_TABLE_TYPE\fP k)"

.PP
Definition at line 363 of file camellia\&.c\&.
.SS "\fBvoid\fP Camellia_EncryptBlock (int keyBitLength, const \fBu8\fP plaintext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP ciphertext[])"

.PP
Definition at line 526 of file camellia\&.c\&.
.SS "\fBvoid\fP Camellia_EncryptBlock_Rounds (int grandRounds, const \fBu8\fP plaintext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP ciphertext[])"

.PP
Definition at line 480 of file camellia\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
