.TH "ccs_header_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccs_header_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dtls1\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBtype\fP"
.br
.ti -1c
.RI "unsigned short \fBseq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 157 of file dtls1\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned short seq"

.PP
Definition at line 159 of file dtls1\&.h\&.
.SS "unsigned char type"

.PP
Definition at line 158 of file dtls1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
