.TH "cert_pkey_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cert_pkey_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ssl_locl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509\fP)*chain"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBX509\fP * \fBx509\fP"
.br
.ti -1c
.RI "\fBEVP_PKEY\fP * \fBprivatekey\fP"
.br
.ti -1c
.RI "const \fBEVP_MD\fP * \fBdigest\fP"
.br
.ti -1c
.RI "unsigned char * \fBserverinfo\fP"
.br
.ti -1c
.RI "size_t \fBserverinfo_length\fP"
.br
.ti -1c
.RI "int \fBvalid_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 536 of file ssl_locl\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBX509\fP)"

.SH "Field Documentation"
.PP 
.SS "const \fBEVP_MD\fP* digest"

.PP
Definition at line 540 of file ssl_locl\&.h\&.
.SS "\fBEVP_PKEY\fP* privatekey"

.PP
Definition at line 538 of file ssl_locl\&.h\&.
.SS "unsigned char* serverinfo"

.PP
Definition at line 551 of file ssl_locl\&.h\&.
.SS "size_t serverinfo_length"

.PP
Definition at line 552 of file ssl_locl\&.h\&.
.SS "int valid_flags"

.PP
Definition at line 559 of file ssl_locl\&.h\&.
.SS "\fBX509\fP* x509"

.PP
Definition at line 537 of file ssl_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
