.TH "cipher_order_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cipher_order_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBSSL_CIPHER\fP * \fBcipher\fP"
.br
.ti -1c
.RI "int \fBactive\fP"
.br
.ti -1c
.RI "int \fBdead\fP"
.br
.ti -1c
.RI "struct \fBcipher_order_st\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBcipher_order_st\fP * \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 221 of file ssl_ciph\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int active"

.PP
Definition at line 223 of file ssl_ciph\&.c\&.
.SS "const \fBSSL_CIPHER\fP* cipher"

.PP
Definition at line 222 of file ssl_ciph\&.c\&.
.SS "int dead"

.PP
Definition at line 224 of file ssl_ciph\&.c\&.
.SS "struct \fBcipher_order_st\fP* next"

.PP
Definition at line 225 of file ssl_ciph\&.c\&.
.SS "struct \fBcipher_order_st\fP * prev"

.PP
Definition at line 225 of file ssl_ciph\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
