.TH "s2n/libcrypto-build/openssl/demos/engines/cluster_labs/cluster_labs.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/demos/engines/cluster_labs/cluster_labs.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBcl_engine_init\fP(\fBvoid\fP)"
.br
.ti -1c
.RI "typedef int \fBcl_mod_exp\fP(\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *\fBp\fP, const \fBBIGNUM\fP *m, \fBBN_CTX\fP *cgx)"
.br
.ti -1c
.RI "typedef int \fBcl_mod_exp_crt\fP(\fBBIGNUM\fP *r, \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *\fBp\fP, const \fBBIGNUM\fP *\fBq\fP, const \fBBIGNUM\fP *dmp1, const \fBBIGNUM\fP *dmq1, const \fBBIGNUM\fP *iqmp, \fBBN_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "typedef int \fBcl_rsa_mod_exp\fP(\fBBIGNUM\fP *r0, const \fBBIGNUM\fP *\fBI\fP, \fBRSA\fP *rsa)"
.br
.ti -1c
.RI "typedef int \fBcl_rsa_pub_enc\fP(int flen, const unsigned char *from, unsigned char *to, \fBRSA\fP *rsa, int padding)"
.br
.ti -1c
.RI "typedef int \fBcl_rsa_pub_dec\fP(int flen, const unsigned char *from, unsigned char *to, \fBRSA\fP *rsa, int padding)"
.br
.ti -1c
.RI "typedef int \fBcl_rsa_priv_enc\fP(int flen, const unsigned char *from, unsigned char *to, \fBRSA\fP *rsa, int padding)"
.br
.ti -1c
.RI "typedef int \fBcl_rsa_priv_dec\fP(int flen, const unsigned char *from, unsigned char *to, \fBRSA\fP *rsa, int padding)"
.br
.ti -1c
.RI "typedef int \fBcl_rand_bytes\fP(unsigned char *buf, int \fBnum\fP)"
.br
.ti -1c
.RI "typedef \fBDSA_SIG\fP * \fBcl_dsa_sign\fP(const unsigned char *dgst, int dlen, \fBDSA\fP *dsa)"
.br
.ti -1c
.RI "typedef int \fBcl_dsa_verify\fP(const unsigned char *dgst, int dgst_len, \fBDSA_SIG\fP *sig, \fBDSA\fP *dsa)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBDSA_SIG\fP* cl_dsa_sign(const unsigned char *dgst, int dlen, \fBDSA\fP *dsa)"

.PP
Definition at line 18 of file cluster_labs\&.h\&.
.SS "typedef int cl_dsa_verify(const unsigned char *dgst, int dgst_len, \fBDSA_SIG\fP *sig, \fBDSA\fP *dsa)"

.PP
Definition at line 19 of file cluster_labs\&.h\&.
.SS "typedef int cl_engine_init(\fBvoid\fP)"

.PP
Definition at line 1 of file cluster_labs\&.h\&.
.SS "typedef int cl_mod_exp(\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *\fBp\fP, const \fBBIGNUM\fP *m, \fBBN_CTX\fP *cgx)"

.PP
Definition at line 2 of file cluster_labs\&.h\&.
.SS "typedef int cl_mod_exp_crt(\fBBIGNUM\fP *r, \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *\fBp\fP, const \fBBIGNUM\fP *\fBq\fP, const \fBBIGNUM\fP *dmp1, const \fBBIGNUM\fP *dmq1, const \fBBIGNUM\fP *iqmp, \fBBN_CTX\fP *\fBctx\fP)"

.PP
Definition at line 4 of file cluster_labs\&.h\&.
.SS "typedef int cl_rand_bytes(unsigned char *buf, int \fBnum\fP)"

.PP
Definition at line 17 of file cluster_labs\&.h\&.
.SS "typedef int cl_rsa_mod_exp(\fBBIGNUM\fP *r0, const \fBBIGNUM\fP *\fBI\fP, \fBRSA\fP *rsa)"

.PP
Definition at line 8 of file cluster_labs\&.h\&.
.SS "typedef int cl_rsa_priv_dec(int flen, const unsigned char *from, unsigned char *to, \fBRSA\fP *rsa, int padding)"

.PP
Definition at line 15 of file cluster_labs\&.h\&.
.SS "typedef int cl_rsa_priv_enc(int flen, const unsigned char *from, unsigned char *to, \fBRSA\fP *rsa, int padding)"

.PP
Definition at line 13 of file cluster_labs\&.h\&.
.SS "typedef int cl_rsa_pub_dec(int flen, const unsigned char *from, unsigned char *to, \fBRSA\fP *rsa, int padding)"

.PP
Definition at line 11 of file cluster_labs\&.h\&.
.SS "typedef int cl_rsa_pub_enc(int flen, const unsigned char *from, unsigned char *to, \fBRSA\fP *rsa, int padding)"

.PP
Definition at line 9 of file cluster_labs\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
