.TH "s2n/libcrypto-build/openssl/crypto/camellia/cmll_misc.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/camellia/cmll_misc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/opensslv\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/camellia\&.h>\fP
.br
\fC#include 'cmll_locl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBprivate_Camellia_set_key\fP (const unsigned char *userKey, const int \fBbits\fP, \fBCAMELLIA_KEY\fP *\fBkey\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCamellia_encrypt\fP (const unsigned char *\fBin\fP, unsigned char *\fBout\fP, const \fBCAMELLIA_KEY\fP *\fBkey\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCamellia_decrypt\fP (const unsigned char *\fBin\fP, unsigned char *\fBout\fP, const \fBCAMELLIA_KEY\fP *\fBkey\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBCAMELLIA_version\fP [] = 'CAMELLIA' OPENSSL_VERSION_PTEXT"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP Camellia_decrypt (const unsigned char * in, unsigned char * out, const \fBCAMELLIA_KEY\fP * key)"

.PP
Definition at line 76 of file cmll_misc\&.c\&.
.SS "\fBvoid\fP Camellia_encrypt (const unsigned char * in, unsigned char * out, const \fBCAMELLIA_KEY\fP * key)"

.PP
Definition at line 70 of file cmll_misc\&.c\&.
.SS "int private_Camellia_set_key (const unsigned char * userKey, const int bits, \fBCAMELLIA_KEY\fP * key)"

.PP
Definition at line 59 of file cmll_misc\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const char CAMELLIA_version[] = 'CAMELLIA' OPENSSL_VERSION_PTEXT"

.PP
Definition at line 57 of file cmll_misc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
