.TH "s2n/libcrypto-build/openssl/crypto/camellia/cmll_ecb.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/camellia/cmll_ecb.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <openssl/camellia\&.h>\fP
.br
\fC#include 'cmll_locl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNDEBUG\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBCamellia_ecb_encrypt\fP (const unsigned char *\fBin\fP, unsigned char *\fBout\fP, const \fBCAMELLIA_KEY\fP *\fBkey\fP, const int \fBenc\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NDEBUG"

.PP
Definition at line 54 of file cmll_ecb\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP Camellia_ecb_encrypt (const unsigned char * in, unsigned char * out, const \fBCAMELLIA_KEY\fP * key, const int enc)"

.PP
Definition at line 62 of file cmll_ecb\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
