.TH "s2n/libcrypto-build/openssl/crypto/cms/cms_att.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/cms/cms_att.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include 'cms\&.h'\fP
.br
\fC#include 'cms_lcl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBCMS_signed_get_attr_count\fP (const \fBCMS_SignerInfo\fP *si)"
.br
.ti -1c
.RI "int \fBCMS_signed_get_attr_by_NID\fP (const \fBCMS_SignerInfo\fP *si, int \fBnid\fP, int lastpos)"
.br
.ti -1c
.RI "int \fBCMS_signed_get_attr_by_OBJ\fP (const \fBCMS_SignerInfo\fP *si, \fBASN1_OBJECT\fP *\fBobj\fP, int lastpos)"
.br
.ti -1c
.RI "\fBX509_ATTRIBUTE\fP * \fBCMS_signed_get_attr\fP (const \fBCMS_SignerInfo\fP *si, int \fBloc\fP)"
.br
.ti -1c
.RI "\fBX509_ATTRIBUTE\fP * \fBCMS_signed_delete_attr\fP (\fBCMS_SignerInfo\fP *si, int \fBloc\fP)"
.br
.ti -1c
.RI "int \fBCMS_signed_add1_attr\fP (\fBCMS_SignerInfo\fP *si, \fBX509_ATTRIBUTE\fP *\fBattr\fP)"
.br
.ti -1c
.RI "int \fBCMS_signed_add1_attr_by_OBJ\fP (\fBCMS_SignerInfo\fP *si, const \fBASN1_OBJECT\fP *\fBobj\fP, int \fBtype\fP, const \fBvoid\fP *\fBbytes\fP, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBCMS_signed_add1_attr_by_NID\fP (\fBCMS_SignerInfo\fP *si, int \fBnid\fP, int \fBtype\fP, const \fBvoid\fP *\fBbytes\fP, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBCMS_signed_add1_attr_by_txt\fP (\fBCMS_SignerInfo\fP *si, const char *\fBattrname\fP, int \fBtype\fP, const \fBvoid\fP *\fBbytes\fP, int \fBlen\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBCMS_signed_get0_data_by_OBJ\fP (\fBCMS_SignerInfo\fP *si, \fBASN1_OBJECT\fP *oid, int lastpos, int \fBtype\fP)"
.br
.ti -1c
.RI "int \fBCMS_unsigned_get_attr_count\fP (const \fBCMS_SignerInfo\fP *si)"
.br
.ti -1c
.RI "int \fBCMS_unsigned_get_attr_by_NID\fP (const \fBCMS_SignerInfo\fP *si, int \fBnid\fP, int lastpos)"
.br
.ti -1c
.RI "int \fBCMS_unsigned_get_attr_by_OBJ\fP (const \fBCMS_SignerInfo\fP *si, \fBASN1_OBJECT\fP *\fBobj\fP, int lastpos)"
.br
.ti -1c
.RI "\fBX509_ATTRIBUTE\fP * \fBCMS_unsigned_get_attr\fP (const \fBCMS_SignerInfo\fP *si, int \fBloc\fP)"
.br
.ti -1c
.RI "\fBX509_ATTRIBUTE\fP * \fBCMS_unsigned_delete_attr\fP (\fBCMS_SignerInfo\fP *si, int \fBloc\fP)"
.br
.ti -1c
.RI "int \fBCMS_unsigned_add1_attr\fP (\fBCMS_SignerInfo\fP *si, \fBX509_ATTRIBUTE\fP *\fBattr\fP)"
.br
.ti -1c
.RI "int \fBCMS_unsigned_add1_attr_by_OBJ\fP (\fBCMS_SignerInfo\fP *si, const \fBASN1_OBJECT\fP *\fBobj\fP, int \fBtype\fP, const \fBvoid\fP *\fBbytes\fP, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBCMS_unsigned_add1_attr_by_NID\fP (\fBCMS_SignerInfo\fP *si, int \fBnid\fP, int \fBtype\fP, const \fBvoid\fP *\fBbytes\fP, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBCMS_unsigned_add1_attr_by_txt\fP (\fBCMS_SignerInfo\fP *si, const char *\fBattrname\fP, int \fBtype\fP, const \fBvoid\fP *\fBbytes\fP, int \fBlen\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBCMS_unsigned_get0_data_by_OBJ\fP (\fBCMS_SignerInfo\fP *si, \fBASN1_OBJECT\fP *oid, int lastpos, int \fBtype\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int CMS_signed_add1_attr (\fBCMS_SignerInfo\fP * si, \fBX509_ATTRIBUTE\fP * attr)"

.PP
Definition at line 90 of file cms_att\&.c\&.
.SS "int CMS_signed_add1_attr_by_NID (\fBCMS_SignerInfo\fP * si, int nid, int type, const \fBvoid\fP * bytes, int len)"

.PP
Definition at line 106 of file cms_att\&.c\&.
.SS "int CMS_signed_add1_attr_by_OBJ (\fBCMS_SignerInfo\fP * si, const \fBASN1_OBJECT\fP * obj, int type, const \fBvoid\fP * bytes, int len)"

.PP
Definition at line 97 of file cms_att\&.c\&.
.SS "int CMS_signed_add1_attr_by_txt (\fBCMS_SignerInfo\fP * si, const char * attrname, int type, const \fBvoid\fP * bytes, int len)"

.PP
Definition at line 114 of file cms_att\&.c\&.
.SS "\fBX509_ATTRIBUTE\fP* CMS_signed_delete_attr (\fBCMS_SignerInfo\fP * si, int loc)"

.PP
Definition at line 85 of file cms_att\&.c\&.
.SS "\fBvoid\fP* CMS_signed_get0_data_by_OBJ (\fBCMS_SignerInfo\fP * si, \fBASN1_OBJECT\fP * oid, int lastpos, int type)"

.PP
Definition at line 123 of file cms_att\&.c\&.
.SS "\fBX509_ATTRIBUTE\fP* CMS_signed_get_attr (const \fBCMS_SignerInfo\fP * si, int loc)"

.PP
Definition at line 80 of file cms_att\&.c\&.
.SS "int CMS_signed_get_attr_by_NID (const \fBCMS_SignerInfo\fP * si, int nid, int lastpos)"

.PP
Definition at line 69 of file cms_att\&.c\&.
.SS "int CMS_signed_get_attr_by_OBJ (const \fBCMS_SignerInfo\fP * si, \fBASN1_OBJECT\fP * obj, int lastpos)"

.PP
Definition at line 74 of file cms_att\&.c\&.
.SS "int CMS_signed_get_attr_count (const \fBCMS_SignerInfo\fP * si)"

.PP
Definition at line 64 of file cms_att\&.c\&.
.SS "int CMS_unsigned_add1_attr (\fBCMS_SignerInfo\fP * si, \fBX509_ATTRIBUTE\fP * attr)"

.PP
Definition at line 156 of file cms_att\&.c\&.
.SS "int CMS_unsigned_add1_attr_by_NID (\fBCMS_SignerInfo\fP * si, int nid, int type, const \fBvoid\fP * bytes, int len)"

.PP
Definition at line 172 of file cms_att\&.c\&.
.SS "int CMS_unsigned_add1_attr_by_OBJ (\fBCMS_SignerInfo\fP * si, const \fBASN1_OBJECT\fP * obj, int type, const \fBvoid\fP * bytes, int len)"

.PP
Definition at line 163 of file cms_att\&.c\&.
.SS "int CMS_unsigned_add1_attr_by_txt (\fBCMS_SignerInfo\fP * si, const char * attrname, int type, const \fBvoid\fP * bytes, int len)"

.PP
Definition at line 181 of file cms_att\&.c\&.
.SS "\fBX509_ATTRIBUTE\fP* CMS_unsigned_delete_attr (\fBCMS_SignerInfo\fP * si, int loc)"

.PP
Definition at line 151 of file cms_att\&.c\&.
.SS "\fBvoid\fP* CMS_unsigned_get0_data_by_OBJ (\fBCMS_SignerInfo\fP * si, \fBASN1_OBJECT\fP * oid, int lastpos, int type)"

.PP
Definition at line 191 of file cms_att\&.c\&.
.SS "\fBX509_ATTRIBUTE\fP* CMS_unsigned_get_attr (const \fBCMS_SignerInfo\fP * si, int loc)"

.PP
Definition at line 146 of file cms_att\&.c\&.
.SS "int CMS_unsigned_get_attr_by_NID (const \fBCMS_SignerInfo\fP * si, int nid, int lastpos)"

.PP
Definition at line 134 of file cms_att\&.c\&.
.SS "int CMS_unsigned_get_attr_by_OBJ (const \fBCMS_SignerInfo\fP * si, \fBASN1_OBJECT\fP * obj, int lastpos)"

.PP
Definition at line 140 of file cms_att\&.c\&.
.SS "int CMS_unsigned_get_attr_count (const \fBCMS_SignerInfo\fP * si)"

.PP
Definition at line 129 of file cms_att\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
