.TH "CMS_OriginatorInfo_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMS_OriginatorInfo_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cms_lcl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCMS_CertificateChoices\fP)*certificates"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCMS_RevocationInfoChoice\fP)*crls"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 160 of file cms_lcl\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBCMS_CertificateChoices\fP)"

.SS "STACK_OF (\fBCMS_RevocationInfoChoice\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
