.TH "s2n/libcrypto-build/openssl/crypto/cms/cms_lib.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/cms/cms_lib.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include 'cms\&.h'\fP
.br
\fC#include 'cms_lcl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBASN1_OBJECT\fP * \fBCMS_get0_type\fP (\fBCMS_ContentInfo\fP *cms)"
.br
.ti -1c
.RI "\fBCMS_ContentInfo\fP * \fBcms_Data_create\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBcms_content_bio\fP (\fBCMS_ContentInfo\fP *cms)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBCMS_dataInit\fP (\fBCMS_ContentInfo\fP *cms, \fBBIO\fP *icont)"
.br
.ti -1c
.RI "int \fBCMS_dataFinal\fP (\fBCMS_ContentInfo\fP *cms, \fBBIO\fP *cmsbio)"
.br
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP ** \fBCMS_get0_content\fP (\fBCMS_ContentInfo\fP *cms)"
.br
.ti -1c
.RI "const \fBASN1_OBJECT\fP * \fBCMS_get0_eContentType\fP (\fBCMS_ContentInfo\fP *cms)"
.br
.ti -1c
.RI "int \fBCMS_set1_eContentType\fP (\fBCMS_ContentInfo\fP *cms, const \fBASN1_OBJECT\fP *oid)"
.br
.ti -1c
.RI "int \fBCMS_is_detached\fP (\fBCMS_ContentInfo\fP *cms)"
.br
.ti -1c
.RI "int \fBCMS_set_detached\fP (\fBCMS_ContentInfo\fP *cms, int detached)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcms_DigestAlgorithm_set\fP (\fBX509_ALGOR\fP *alg, const \fBEVP_MD\fP *md)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBcms_DigestAlgorithm_init_bio\fP (\fBX509_ALGOR\fP *digestAlgorithm)"
.br
.ti -1c
.RI "int \fBcms_DigestAlgorithm_find_ctx\fP (\fBEVP_MD_CTX\fP *mctx, \fBBIO\fP *chain, \fBX509_ALGOR\fP *mdalg)"
.br
.ti -1c
.RI "\fBCMS_CertificateChoices\fP * \fBCMS_add0_CertificateChoices\fP (\fBCMS_ContentInfo\fP *cms)"
.br
.ti -1c
.RI "int \fBCMS_add0_cert\fP (\fBCMS_ContentInfo\fP *cms, \fBX509\fP *cert)"
.br
.ti -1c
.RI "int \fBCMS_add1_cert\fP (\fBCMS_ContentInfo\fP *cms, \fBX509\fP *cert)"
.br
.ti -1c
.RI "\fBCMS_RevocationInfoChoice\fP * \fBCMS_add0_RevocationInfoChoice\fP (\fBCMS_ContentInfo\fP *cms)"
.br
.ti -1c
.RI "int \fBCMS_add0_crl\fP (\fBCMS_ContentInfo\fP *cms, \fBX509_CRL\fP *crl)"
.br
.ti -1c
.RI "int \fBCMS_add1_crl\fP (\fBCMS_ContentInfo\fP *cms, \fBX509_CRL\fP *crl)"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509\fP)"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_CRL\fP)"
.br
.ti -1c
.RI "int \fBcms_ias_cert_cmp\fP (\fBCMS_IssuerAndSerialNumber\fP *ias, \fBX509\fP *cert)"
.br
.ti -1c
.RI "int \fBcms_keyid_cert_cmp\fP (\fBASN1_OCTET_STRING\fP *keyid, \fBX509\fP *cert)"
.br
.ti -1c
.RI "int \fBcms_set1_ias\fP (\fBCMS_IssuerAndSerialNumber\fP **pias, \fBX509\fP *cert)"
.br
.ti -1c
.RI "int \fBcms_set1_keyid\fP (\fBASN1_OCTET_STRING\fP **pkeyid, \fBX509\fP *cert)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int CMS_add0_cert (\fBCMS_ContentInfo\fP * cms, \fBX509\fP * cert)"

.PP
Definition at line 449 of file cms_lib\&.c\&.
.SS "\fBCMS_CertificateChoices\fP* CMS_add0_CertificateChoices (\fBCMS_ContentInfo\fP * cms)"

.PP
Definition at line 428 of file cms_lib\&.c\&.
.SS "int CMS_add0_crl (\fBCMS_ContentInfo\fP * cms, \fBX509_CRL\fP * crl)"

.PP
Definition at line 526 of file cms_lib\&.c\&.
.SS "\fBCMS_RevocationInfoChoice\fP* CMS_add0_RevocationInfoChoice (\fBCMS_ContentInfo\fP * cms)"

.PP
Definition at line 505 of file cms_lib\&.c\&.
.SS "int CMS_add1_cert (\fBCMS_ContentInfo\fP * cms, \fBX509\fP * cert)"

.PP
Definition at line 475 of file cms_lib\&.c\&.
.SS "int CMS_add1_crl (\fBCMS_ContentInfo\fP * cms, \fBX509_CRL\fP * crl)"

.PP
Definition at line 537 of file cms_lib\&.c\&.
.SS "\fBBIO\fP* cms_content_bio (\fBCMS_ContentInfo\fP * cms)"

.PP
Definition at line 89 of file cms_lib\&.c\&.
.SS "\fBCMS_ContentInfo\fP* cms_Data_create (\fBvoid\fP)"

.PP
Definition at line 77 of file cms_lib\&.c\&.
.SS "int CMS_dataFinal (\fBCMS_ContentInfo\fP * cms, \fBBIO\fP * cmsbio)"

.PP
Definition at line 157 of file cms_lib\&.c\&.
.SS "\fBBIO\fP* CMS_dataInit (\fBCMS_ContentInfo\fP * cms, \fBBIO\fP * icont)"

.PP
Definition at line 106 of file cms_lib\&.c\&.
.SS "int cms_DigestAlgorithm_find_ctx (\fBEVP_MD_CTX\fP * mctx, \fBBIO\fP * chain, \fBX509_ALGOR\fP * mdalg)"

.PP
Definition at line 379 of file cms_lib\&.c\&.
.SS "\fBBIO\fP* cms_DigestAlgorithm_init_bio (\fBX509_ALGOR\fP * digestAlgorithm)"

.PP
Definition at line 353 of file cms_lib\&.c\&.
.SS "\fBvoid\fP cms_DigestAlgorithm_set (\fBX509_ALGOR\fP * alg, const \fBEVP_MD\fP * md)"

.PP
Definition at line 338 of file cms_lib\&.c\&.
.SS "\fBASN1_OCTET_STRING\fP** CMS_get0_content (\fBCMS_ContentInfo\fP * cms)"

.PP
Definition at line 206 of file cms_lib\&.c\&.
.SS "const \fBASN1_OBJECT\fP* CMS_get0_eContentType (\fBCMS_ContentInfo\fP * cms)"

.PP
Definition at line 274 of file cms_lib\&.c\&.
.SS "const \fBASN1_OBJECT\fP* CMS_get0_type (\fBCMS_ContentInfo\fP * cms)"

.PP
Definition at line 72 of file cms_lib\&.c\&.
.SS "int cms_ias_cert_cmp (\fBCMS_IssuerAndSerialNumber\fP * ias, \fBX509\fP * cert)"

.PP
Definition at line 601 of file cms_lib\&.c\&.
.SS "int CMS_is_detached (\fBCMS_ContentInfo\fP * cms)"

.PP
Definition at line 299 of file cms_lib\&.c\&.
.SS "int cms_keyid_cert_cmp (\fBASN1_OCTET_STRING\fP * keyid, \fBX509\fP * cert)"

.PP
Definition at line 610 of file cms_lib\&.c\&.
.SS "int CMS_set1_eContentType (\fBCMS_ContentInfo\fP * cms, const \fBASN1_OBJECT\fP * oid)"

.PP
Definition at line 283 of file cms_lib\&.c\&.
.SS "int cms_set1_ias (\fBCMS_IssuerAndSerialNumber\fP ** pias, \fBX509\fP * cert)"

.PP
Definition at line 618 of file cms_lib\&.c\&.
.SS "int cms_set1_keyid (\fBASN1_OCTET_STRING\fP ** pkeyid, \fBX509\fP * cert)"

.PP
Definition at line 639 of file cms_lib\&.c\&.
.SS "int CMS_set_detached (\fBCMS_ContentInfo\fP * cms, int detached)"

.PP
Definition at line 310 of file cms_lib\&.c\&.
.SS "STACK_OF (\fBX509\fP)"

.PP
Definition at line 546 of file cms_lib\&.c\&.
.SS "STACK_OF (\fBX509_CRL\fP)"

.PP
Definition at line 574 of file cms_lib\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
