.TH "CMS_KeyTransRecipientInfo_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMS_KeyTransRecipientInfo_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cms_lcl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBversion\fP"
.br
.ti -1c
.RI "\fBCMS_RecipientIdentifier\fP * \fBrid\fP"
.br
.ti -1c
.RI "\fBX509_ALGOR\fP * \fBkeyEncryptionAlgorithm\fP"
.br
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBencryptedKey\fP"
.br
.ti -1c
.RI "\fBX509\fP * \fBrecip\fP"
.br
.ti -1c
.RI "\fBEVP_PKEY\fP * \fBpkey\fP"
.br
.ti -1c
.RI "\fBEVP_PKEY_CTX\fP * \fBpctx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 190 of file cms_lcl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBASN1_OCTET_STRING\fP* encryptedKey"

.PP
Definition at line 194 of file cms_lcl\&.h\&.
.SS "\fBX509_ALGOR\fP* keyEncryptionAlgorithm"

.PP
Definition at line 193 of file cms_lcl\&.h\&.
.SS "\fBEVP_PKEY_CTX\fP* pctx"

.PP
Definition at line 199 of file cms_lcl\&.h\&.
.SS "\fBEVP_PKEY\fP* pkey"

.PP
Definition at line 197 of file cms_lcl\&.h\&.
.SS "\fBX509\fP* recip"

.PP
Definition at line 196 of file cms_lcl\&.h\&.
.SS "\fBCMS_RecipientIdentifier\fP* rid"

.PP
Definition at line 192 of file cms_lcl\&.h\&.
.SS "long version"

.PP
Definition at line 191 of file cms_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
