.TH "CMS_EnvelopedData_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMS_EnvelopedData_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cms_lcl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCMS_RecipientInfo\fP)*recipientInfos"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ATTRIBUTE\fP)*unprotectedAttrs"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBversion\fP"
.br
.ti -1c
.RI "\fBCMS_OriginatorInfo\fP * \fBoriginatorInfo\fP"
.br
.ti -1c
.RI "\fBCMS_EncryptedContentInfo\fP * \fBencryptedContentInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 152 of file cms_lcl\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBCMS_RecipientInfo\fP)"

.SS "STACK_OF (\fBX509_ATTRIBUTE\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBCMS_EncryptedContentInfo\fP* encryptedContentInfo"

.PP
Definition at line 156 of file cms_lcl\&.h\&.
.SS "\fBCMS_OriginatorInfo\fP* originatorInfo"

.PP
Definition at line 154 of file cms_lcl\&.h\&.
.SS "long version"

.PP
Definition at line 153 of file cms_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
