.TH "s2n/libcrypto-build/openssl/crypto/cms/cms_smime.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/cms/cms_smime.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <openssl/cms\&.h>\fP
.br
\fC#include 'cms_lcl\&.h'\fP
.br
\fC#include 'asn1_locl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBCMS_data\fP (\fBCMS_ContentInfo\fP *cms, \fBBIO\fP *\fBout\fP, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "\fBCMS_ContentInfo\fP * \fBCMS_data_create\fP (\fBBIO\fP *\fBin\fP, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "int \fBCMS_digest_verify\fP (\fBCMS_ContentInfo\fP *cms, \fBBIO\fP *dcont, \fBBIO\fP *\fBout\fP, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "\fBCMS_ContentInfo\fP * \fBCMS_digest_create\fP (\fBBIO\fP *\fBin\fP, const \fBEVP_MD\fP *md, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "int \fBCMS_EncryptedData_decrypt\fP (\fBCMS_ContentInfo\fP *cms, const unsigned char *\fBkey\fP, size_t keylen, \fBBIO\fP *dcont, \fBBIO\fP *\fBout\fP, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "\fBCMS_ContentInfo\fP * \fBCMS_EncryptedData_encrypt\fP (\fBBIO\fP *\fBin\fP, const \fBEVP_CIPHER\fP *cipher, const unsigned char *\fBkey\fP, size_t keylen, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "int \fBCMS_verify\fP (\fBCMS_ContentInfo\fP *cms, \fBSTACK_OF\fP(\fBX509\fP)*certs, \fBX509_STORE\fP *store, \fBBIO\fP *dcont, \fBBIO\fP *\fBout\fP, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "int \fBCMS_verify_receipt\fP (\fBCMS_ContentInfo\fP *rcms, \fBCMS_ContentInfo\fP *ocms, \fBSTACK_OF\fP(\fBX509\fP)*certs, \fBX509_STORE\fP *store, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "\fBCMS_ContentInfo\fP * \fBCMS_sign\fP (\fBX509\fP *signcert, \fBEVP_PKEY\fP *pkey, \fBSTACK_OF\fP(\fBX509\fP)*certs, \fBBIO\fP *\fBdata\fP, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "\fBCMS_ContentInfo\fP * \fBCMS_sign_receipt\fP (\fBCMS_SignerInfo\fP *si, \fBX509\fP *signcert, \fBEVP_PKEY\fP *pkey, \fBSTACK_OF\fP(\fBX509\fP)*certs, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "\fBCMS_ContentInfo\fP * \fBCMS_encrypt\fP (\fBSTACK_OF\fP(\fBX509\fP)*certs, \fBBIO\fP *\fBdata\fP, const \fBEVP_CIPHER\fP *cipher, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "int \fBCMS_decrypt_set1_pkey\fP (\fBCMS_ContentInfo\fP *cms, \fBEVP_PKEY\fP *pk, \fBX509\fP *cert)"
.br
.ti -1c
.RI "int \fBCMS_decrypt_set1_key\fP (\fBCMS_ContentInfo\fP *cms, unsigned char *\fBkey\fP, size_t keylen, unsigned char *id, size_t idlen)"
.br
.ti -1c
.RI "int \fBCMS_decrypt_set1_password\fP (\fBCMS_ContentInfo\fP *cms, unsigned char *\fBpass\fP, \fBossl_ssize_t\fP \fBpasslen\fP)"
.br
.ti -1c
.RI "int \fBCMS_decrypt\fP (\fBCMS_ContentInfo\fP *cms, \fBEVP_PKEY\fP *pk, \fBX509\fP *cert, \fBBIO\fP *dcont, \fBBIO\fP *\fBout\fP, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "int \fBCMS_final\fP (\fBCMS_ContentInfo\fP *cms, \fBBIO\fP *\fBdata\fP, \fBBIO\fP *dcont, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "int \fBCMS_uncompress\fP (\fBCMS_ContentInfo\fP *cms, \fBBIO\fP *dcont, \fBBIO\fP *\fBout\fP, unsigned int \fBflags\fP)"
.br
.ti -1c
.RI "\fBCMS_ContentInfo\fP * \fBCMS_compress\fP (\fBBIO\fP *\fBin\fP, int comp_nid, unsigned int \fBflags\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCMS_ContentInfo\fP* CMS_compress (\fBBIO\fP * in, int comp_nid, unsigned int flags)"

.PP
Definition at line 830 of file cms_smime\&.c\&.
.SS "int CMS_data (\fBCMS_ContentInfo\fP * cms, \fBBIO\fP * out, unsigned int flags)"

.PP
Definition at line 140 of file cms_smime\&.c\&.
.SS "\fBCMS_ContentInfo\fP* CMS_data_create (\fBBIO\fP * in, unsigned int flags)"

.PP
Definition at line 156 of file cms_smime\&.c\&.
.SS "int CMS_decrypt (\fBCMS_ContentInfo\fP * cms, \fBEVP_PKEY\fP * pk, \fBX509\fP * cert, \fBBIO\fP * dcont, \fBBIO\fP * out, unsigned int flags)"

.PP
Definition at line 725 of file cms_smime\&.c\&.
.SS "int CMS_decrypt_set1_key (\fBCMS_ContentInfo\fP * cms, unsigned char * key, size_t keylen, unsigned char * id, size_t idlen)"

.PP
Definition at line 666 of file cms_smime\&.c\&.
.SS "int CMS_decrypt_set1_password (\fBCMS_ContentInfo\fP * cms, unsigned char * pass, \fBossl_ssize_t\fP passlen)"

.PP
Definition at line 702 of file cms_smime\&.c\&.
.SS "int CMS_decrypt_set1_pkey (\fBCMS_ContentInfo\fP * cms, \fBEVP_PKEY\fP * pk, \fBX509\fP * cert)"

.PP
Definition at line 596 of file cms_smime\&.c\&.
.SS "\fBCMS_ContentInfo\fP* CMS_digest_create (\fBBIO\fP * in, const \fBEVP_MD\fP * md, unsigned int flags)"

.PP
Definition at line 194 of file cms_smime\&.c\&.
.SS "int CMS_digest_verify (\fBCMS_ContentInfo\fP * cms, \fBBIO\fP * dcont, \fBBIO\fP * out, unsigned int flags)"

.PP
Definition at line 171 of file cms_smime\&.c\&.
.SS "\fBCMS_ContentInfo\fP* CMS_encrypt (\fBSTACK_OF\fP(\fBX509\fP)* certs, \fBBIO\fP * data, const \fBEVP_CIPHER\fP * cipher, unsigned int flags)"

.PP
Definition at line 538 of file cms_smime\&.c\&.
.SS "int CMS_EncryptedData_decrypt (\fBCMS_ContentInfo\fP * cms, const unsigned char * key, size_t keylen, \fBBIO\fP * dcont, \fBBIO\fP * out, unsigned int flags)"

.PP
Definition at line 214 of file cms_smime\&.c\&.
.SS "\fBCMS_ContentInfo\fP* CMS_EncryptedData_encrypt (\fBBIO\fP * in, const \fBEVP_CIPHER\fP * cipher, const unsigned char * key, size_t keylen, unsigned int flags)"

.PP
Definition at line 239 of file cms_smime\&.c\&.
.SS "int CMS_final (\fBCMS_ContentInfo\fP * cms, \fBBIO\fP * data, \fBBIO\fP * dcont, unsigned int flags)"

.PP
Definition at line 752 of file cms_smime\&.c\&.
.SS "\fBCMS_ContentInfo\fP* CMS_sign (\fBX509\fP * signcert, \fBEVP_PKEY\fP * pkey, \fBSTACK_OF\fP(\fBX509\fP)* certs, \fBBIO\fP * data, unsigned int flags)"

.PP
Definition at line 429 of file cms_smime\&.c\&.
.SS "\fBCMS_ContentInfo\fP* CMS_sign_receipt (\fBCMS_SignerInfo\fP * si, \fBX509\fP * signcert, \fBEVP_PKEY\fP * pkey, \fBSTACK_OF\fP(\fBX509\fP)* certs, unsigned int flags)"

.PP
Definition at line 469 of file cms_smime\&.c\&.
.SS "int CMS_uncompress (\fBCMS_ContentInfo\fP * cms, \fBBIO\fP * dcont, \fBBIO\fP * out, unsigned int flags)"

.PP
Definition at line 823 of file cms_smime\&.c\&.
.SS "int CMS_verify (\fBCMS_ContentInfo\fP * cms, \fBSTACK_OF\fP(\fBX509\fP)* certs, \fBX509_STORE\fP * store, \fBBIO\fP * dcont, \fBBIO\fP * out, unsigned int flags)"

.PP
Definition at line 299 of file cms_smime\&.c\&.
.SS "int CMS_verify_receipt (\fBCMS_ContentInfo\fP * rcms, \fBCMS_ContentInfo\fP * ocms, \fBSTACK_OF\fP(\fBX509\fP)* certs, \fBX509_STORE\fP * store, unsigned int flags)"

.PP
Definition at line 417 of file cms_smime\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
