.TH "s2n/libcrypto-build/openssl/crypto/conf/conf_sap.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/conf/conf_sap.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/conf\&.h>\fP
.br
\fC#include <openssl/dso\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBOPENSSL_config\fP (const char *config_name)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOPENSSL_no_config\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP OPENSSL_config (const char * config_name)"

.PP
Definition at line 79 of file conf_sap\&.c\&.
.SS "\fBvoid\fP OPENSSL_no_config (\fBvoid\fP)"

.PP
Definition at line 96 of file conf_sap\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
