.TH "conf_module_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conf_module_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDSO\fP * \fBdso\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBconf_init_func\fP * \fBinit\fP"
.br
.ti -1c
.RI "\fBconf_finish_func\fP * \fBfinish\fP"
.br
.ti -1c
.RI "int \fBlinks\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBusr_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file conf_mod\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBDSO\fP* dso"

.PP
Definition at line 78 of file conf_mod\&.c\&.
.SS "\fBconf_finish_func\fP* finish"

.PP
Definition at line 84 of file conf_mod\&.c\&.
.SS "\fBconf_init_func\fP* init"

.PP
Definition at line 82 of file conf_mod\&.c\&.
.SS "int links"

.PP
Definition at line 86 of file conf_mod\&.c\&.
.SS "char* name"

.PP
Definition at line 80 of file conf_mod\&.c\&.
.SS "\fBvoid\fP* usr_data"

.PP
Definition at line 87 of file conf_mod\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
