.TH "s2n/libcrypto-build/openssl/ssl/d1_lib.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ssl/d1_lib.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include 'ssl_locl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSE_SOCKETS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdtls1_listen\fP (\fBSSL\fP *s, struct sockaddr *client)"
.br
.ti -1c
.RI "long \fBdtls1_default_timeout\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBdtls1_new\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdtls1_free\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdtls1_clear\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "long \fBdtls1_ctrl\fP (\fBSSL\fP *s, int cmd, long larg, \fBvoid\fP *parg)"
.br
.ti -1c
.RI "const \fBSSL_CIPHER\fP * \fBdtls1_get_cipher\fP (unsigned int \fBu\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdtls1_start_timer\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "struct timeval * \fBdtls1_get_timeout\fP (\fBSSL\fP *s, struct timeval *timeleft)"
.br
.ti -1c
.RI "int \fBdtls1_is_timer_expired\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdtls1_double_timeout\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdtls1_stop_timer\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "int \fBdtls1_check_timeout_num\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "int \fBdtls1_handle_timeout\fP (\fBSSL\fP *s)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBdtls1_version_str\fP [] = 'DTLSv1' OPENSSL_VERSION_PTEXT"
.br
.ti -1c
.RI "\fBSSL3_ENC_METHOD\fP \fBDTLSv1_enc_data\fP"
.br
.ti -1c
.RI "\fBSSL3_ENC_METHOD\fP \fBDTLSv1_2_enc_data\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define USE_SOCKETS"

.PP
Definition at line 61 of file d1_lib\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int dtls1_check_timeout_num (\fBSSL\fP * s)"

.PP
Definition at line 462 of file d1_lib\&.c\&.
.SS "\fBvoid\fP dtls1_clear (\fBSSL\fP * s)"

.PP
Definition at line 232 of file d1_lib\&.c\&.
.SS "long dtls1_ctrl (\fBSSL\fP * s, int cmd, long larg, \fBvoid\fP * parg)"

.PP
Definition at line 280 of file d1_lib\&.c\&.
.SS "long dtls1_default_timeout (\fBvoid\fP)"

.PP
Definition at line 114 of file d1_lib\&.c\&.
.SS "\fBvoid\fP dtls1_double_timeout (\fBSSL\fP * s)"

.PP
Definition at line 442 of file d1_lib\&.c\&.
.SS "\fBvoid\fP dtls1_free (\fBSSL\fP * s)"

.PP
Definition at line 216 of file d1_lib\&.c\&.
.SS "const \fBSSL_CIPHER\fP* dtls1_get_cipher (unsigned int u)"

.PP
Definition at line 348 of file d1_lib\&.c\&.
.SS "struct timeval* dtls1_get_timeout (\fBSSL\fP * s, struct timeval * timeleft)"

.PP
Definition at line 384 of file d1_lib\&.c\&.
.SS "int dtls1_handle_timeout (\fBSSL\fP * s)"

.PP
Definition at line 487 of file d1_lib\&.c\&.
.SS "int dtls1_is_timer_expired (\fBSSL\fP * s)"

.PP
Definition at line 424 of file d1_lib\&.c\&.
.SS "int dtls1_listen (\fBSSL\fP * s, struct sockaddr * client)"

.PP
Definition at line 542 of file d1_lib\&.c\&.
.SS "int dtls1_new (\fBSSL\fP * s)"

.PP
Definition at line 123 of file d1_lib\&.c\&.
.SS "\fBvoid\fP dtls1_start_timer (\fBSSL\fP * s)"

.PP
Definition at line 360 of file d1_lib\&.c\&.
.SS "\fBvoid\fP dtls1_stop_timer (\fBSSL\fP * s)"

.PP
Definition at line 450 of file d1_lib\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const char dtls1_version_str[] = 'DTLSv1' OPENSSL_VERSION_PTEXT"

.PP
Definition at line 72 of file d1_lib\&.c\&.
.SS "\fBSSL3_ENC_METHOD\fP DTLSv1_2_enc_data"
\fBInitial value:\fP
.PP
.nf
= {
    tls1_enc,
    tls1_mac,
    tls1_setup_key_block,
    tls1_generate_master_secret,
    tls1_change_cipher_state,
    tls1_final_finish_mac,
    TLS1_FINISH_MAC_LENGTH,
    tls1_cert_verify_mac,
    TLS_MD_CLIENT_FINISH_CONST, TLS_MD_CLIENT_FINISH_CONST_SIZE,
    TLS_MD_SERVER_FINISH_CONST, TLS_MD_SERVER_FINISH_CONST_SIZE,
    tls1_alert_code,
    tls1_export_keying_material,
    SSL_ENC_FLAG_DTLS | SSL_ENC_FLAG_EXPLICIT_IV | SSL_ENC_FLAG_SIGALGS
        | SSL_ENC_FLAG_SHA256_PRF | SSL_ENC_FLAG_TLS1_2_CIPHERS,
    DTLS1_HM_HEADER_LENGTH,
    dtls1_set_handshake_header,
    dtls1_handshake_write
}
.fi
.PP
Definition at line 94 of file d1_lib\&.c\&.
.SS "\fBSSL3_ENC_METHOD\fP DTLSv1_enc_data"
\fBInitial value:\fP
.PP
.nf
= {
    tls1_enc,
    tls1_mac,
    tls1_setup_key_block,
    tls1_generate_master_secret,
    tls1_change_cipher_state,
    tls1_final_finish_mac,
    TLS1_FINISH_MAC_LENGTH,
    tls1_cert_verify_mac,
    TLS_MD_CLIENT_FINISH_CONST, TLS_MD_CLIENT_FINISH_CONST_SIZE,
    TLS_MD_SERVER_FINISH_CONST, TLS_MD_SERVER_FINISH_CONST_SIZE,
    tls1_alert_code,
    tls1_export_keying_material,
    SSL_ENC_FLAG_DTLS | SSL_ENC_FLAG_EXPLICIT_IV,
    DTLS1_HM_HEADER_LENGTH,
    dtls1_set_handshake_header,
    dtls1_handshake_write
}
.fi
.PP
Definition at line 75 of file d1_lib\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
