.TH "s2n/libcrypto-build/openssl/ssl/d1_srvr.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ssl/d1_srvr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'ssl_locl\&.h'\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/md5\&.h>\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <openssl/dh\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIMPLEMENT_dtls1_meth_func\fP (\fBDTLS1_VERSION\fP, \fBDTLSv1_server_method\fP, IMPLEMENT_dtls1_meth_func(\fBdtls1_accept\fP, IMPLEMENT_dtls1_meth_func(\fBssl_undefined_function\fP, IMPLEMENT_dtls1_meth_func(dtls1_get_server_method, \fBDTLSv1_enc_data\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "IMPLEMENT_dtls1_meth_func (\fBDTLS1_VERSION\fP, \fBDTLSv1_server_method\fP, IMPLEMENT_dtls1_meth_func( dtls1_accept, IMPLEMENT_dtls1_meth_func( ssl_undefined_function, IMPLEMENT_dtls1_meth_func( dtls1_get_server_method, \fBDTLSv1_enc_data\fP)"

.PP
Definition at line 144 of file d1_srvr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
