.TH "s2n/libcrypto-build/openssl/crypto/des/des_ver.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/des/des_ver.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/e_os2\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDES_version\fP   \fBOSSL_DES_version\fP"
.br
.ti -1c
.RI "#define \fBlibdes_version\fP   \fBOSSL_libdes_version\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBOPENSSL_EXTERN\fP const char \fBOSSL_DES_version\fP []"
.br
.ti -1c
.RI "\fBOPENSSL_EXTERN\fP const char \fBOSSL_libdes_version\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DES_version   \fBOSSL_DES_version\fP"

.PP
Definition at line 67 of file des_ver\&.h\&.
.SS "#define libdes_version   \fBOSSL_libdes_version\fP"

.PP
Definition at line 68 of file des_ver\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "\fBOPENSSL_EXTERN\fP const char OSSL_DES_version[]"

.PP
Definition at line 71 of file des_ver\&.h\&.
.SS "\fBOPENSSL_EXTERN\fP const char OSSL_libdes_version[]"

.PP
Definition at line 73 of file des_ver\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
