.TH "s2n/libcrypto-build/openssl/crypto/dh/dh_check.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/dh/dh_check.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <openssl/dh\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBDH_check\fP (const \fBDH\fP *dh, int *ret)"
.br
.ti -1c
.RI "int \fBDH_check_pub_key\fP (const \fBDH\fP *dh, const \fBBIGNUM\fP *pub_key, int *ret)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int DH_check (const \fBDH\fP * dh, int * ret)"

.PP
Definition at line 74 of file dh_check\&.c\&.
.SS "int DH_check_pub_key (const \fBDH\fP * dh, const \fBBIGNUM\fP * pub_key, int * ret)"

.PP
Definition at line 151 of file dh_check\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
