.TH "s2n/libcrypto-build/openssl/crypto/dh/dh_key.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/dh/dh_key.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include <openssl/dh\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBDH_generate_key\fP (\fBDH\fP *dh)"
.br
.ti -1c
.RI "int \fBDH_compute_key\fP (unsigned char *\fBkey\fP, const \fBBIGNUM\fP *pub_key, \fBDH\fP *dh)"
.br
.ti -1c
.RI "int \fBDH_compute_key_padded\fP (unsigned char *\fBkey\fP, const \fBBIGNUM\fP *pub_key, \fBDH\fP *dh)"
.br
.ti -1c
.RI "const \fBDH_METHOD\fP * \fBDH_OpenSSL\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int DH_compute_key (unsigned char * key, const \fBBIGNUM\fP * pub_key, \fBDH\fP * dh)"

.PP
Definition at line 85 of file dh_key\&.c\&.
.SS "int DH_compute_key_padded (unsigned char * key, const \fBBIGNUM\fP * pub_key, \fBDH\fP * dh)"

.PP
Definition at line 97 of file dh_key\&.c\&.
.SS "int DH_generate_key (\fBDH\fP * dh)"

.PP
Definition at line 73 of file dh_key\&.c\&.
.SS "const \fBDH_METHOD\fP* DH_OpenSSL (\fBvoid\fP)"

.PP
Definition at line 123 of file dh_key\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
