.TH "dh_method" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dh_method \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dh\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int(* \fBgenerate_key\fP )(\fBDH\fP *dh)"
.br
.ti -1c
.RI "int(* \fBcompute_key\fP )(unsigned char *\fBkey\fP, const \fBBIGNUM\fP *pub_key, \fBDH\fP *dh)"
.br
.ti -1c
.RI "int(* \fBbn_mod_exp\fP )(const \fBDH\fP *dh, \fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *\fBp\fP, const \fBBIGNUM\fP *m, \fBBN_CTX\fP *\fBctx\fP, \fBBN_MONT_CTX\fP *m_ctx)"
.br
.ti -1c
.RI "int(* \fBinit\fP )(\fBDH\fP *dh)"
.br
.ti -1c
.RI "int(* \fBfinish\fP )(\fBDH\fP *dh)"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "char * \fBapp_data\fP"
.br
.ti -1c
.RI "int(* \fBgenerate_params\fP )(\fBDH\fP *dh, int prime_len, int generator, \fBBN_GENCB\fP *\fBcb\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 117 of file dh\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char * app_data"

.PP
Definition at line 129 of file dh\&.h\&.
.SS "int(* bn_mod_exp)(const \fBDH\fP *dh, \fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *\fBp\fP, const \fBBIGNUM\fP *m, \fBBN_CTX\fP *\fBctx\fP, \fBBN_MONT_CTX\fP *m_ctx)"

.PP
Definition at line 123 of file dh\&.h\&.
.SS "int(* compute_key)(unsigned char *\fBkey\fP, const \fBBIGNUM\fP *pub_key, \fBDH\fP *dh)"

.PP
Definition at line 121 of file dh\&.h\&.
.SS "int(* finish)(\fBDH\fP *dh)"

.PP
Definition at line 127 of file dh\&.h\&.
.SS "int flags"

.PP
Definition at line 128 of file dh\&.h\&.
.SS "int(* generate_key)(\fBDH\fP *dh)"

.PP
Definition at line 120 of file dh\&.h\&.
.SS "int(* generate_params)(\fBDH\fP *dh, int prime_len, int generator, \fBBN_GENCB\fP *\fBcb\fP)"

.PP
Definition at line 131 of file dh\&.h\&.
.SS "int(* init)(\fBDH\fP *dh)"

.PP
Definition at line 126 of file dh\&.h\&.
.SS "const char * name"

.PP
Definition at line 118 of file dh\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
