.TH "DIST_POINT_NAME_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DIST_POINT_NAME_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <x509v3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   GENERAL_NAMES * \fBfullname\fP"
.br
.ti -1c
.RI "} \fBname\fP"
.br
.ti -1c
.RI "\fBX509_NAME\fP * \fBdpname\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   GENERAL_NAMES * \fBfullname\fP"
.br
.ti -1c
.RI "} \fBname\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   GENERAL_NAMES * \fBfullname\fP"
.br
.ti -1c
.RI "} \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 226 of file x509v3\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBX509_NAME\fP * dpname"

.PP
Definition at line 233 of file x509v3\&.h\&.
.SS "GENERAL_NAMES* fullname"

.PP
Definition at line 229 of file x509v3\&.h\&.
.SS "union { \&.\&.\&. }   name"

.SS "union { \&.\&.\&. }   name"

.SS "union { \&.\&.\&. }   name"

.SS "int type"

.PP
Definition at line 227 of file x509v3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
