.TH "s2n/libcrypto-build/openssl/crypto/dsa/dsa_sign.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/dsa/dsa_sign.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/dsa\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDSA_SIG\fP * \fBDSA_do_sign\fP (const unsigned char *dgst, int dlen, \fBDSA\fP *dsa)"
.br
.ti -1c
.RI "int \fBDSA_sign_setup\fP (\fBDSA\fP *dsa, \fBBN_CTX\fP *ctx_in, \fBBIGNUM\fP **kinvp, \fBBIGNUM\fP **rp)"
.br
.ti -1c
.RI "\fBDSA_SIG\fP * \fBDSA_SIG_new\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDSA_SIG_free\fP (\fBDSA_SIG\fP *sig)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBDSA_SIG\fP* DSA_do_sign (const unsigned char * dgst, int dlen, \fBDSA\fP * dsa)"

.PP
Definition at line 66 of file dsa_sign\&.c\&.
.SS "\fBvoid\fP DSA_SIG_free (\fBDSA_SIG\fP * sig)"

.PP
Definition at line 101 of file dsa_sign\&.c\&.
.SS "\fBDSA_SIG\fP* DSA_SIG_new (\fBvoid\fP)"

.PP
Definition at line 90 of file dsa_sign\&.c\&.
.SS "int DSA_sign_setup (\fBDSA\fP * dsa, \fBBN_CTX\fP * ctx_in, \fBBIGNUM\fP ** kinvp, \fBBIGNUM\fP ** rp)"

.PP
Definition at line 78 of file dsa_sign\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
