.TH "s2n/libcrypto-build/openssl/crypto/dsa/dsa_vrf.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/dsa/dsa_vrf.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/dsa\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBDSA_do_verify\fP (const unsigned char *dgst, int dgst_len, \fBDSA_SIG\fP *sig, \fBDSA\fP *dsa)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int DSA_do_verify (const unsigned char * dgst, int dgst_len, \fBDSA_SIG\fP * sig, \fBDSA\fP * dsa)"

.PP
Definition at line 64 of file dsa_vrf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
