.TH "DSA_SIG_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DSA_SIG_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dsa\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBIGNUM\fP * \fBr\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 124 of file dsa\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBBIGNUM\fP* r"

.PP
Definition at line 125 of file dsa\&.h\&.
.SS "\fBBIGNUM\fP* s"

.PP
Definition at line 126 of file dsa\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
