.TH "s2n/libcrypto-build/openssl/crypto/dsa/dsa_lib.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/dsa/dsa_lib.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <openssl/dsa\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br
\fC#include <openssl/dh\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBDSA_set_default_method\fP (const \fBDSA_METHOD\fP *meth)"
.br
.ti -1c
.RI "const \fBDSA_METHOD\fP * \fBDSA_get_default_method\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBDSA\fP * \fBDSA_new\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBDSA_set_method\fP (\fBDSA\fP *dsa, const \fBDSA_METHOD\fP *meth)"
.br
.ti -1c
.RI "\fBDSA\fP * \fBDSA_new_method\fP (\fBENGINE\fP *engine)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDSA_free\fP (\fBDSA\fP *r)"
.br
.ti -1c
.RI "int \fBDSA_up_ref\fP (\fBDSA\fP *r)"
.br
.ti -1c
.RI "int \fBDSA_size\fP (const \fBDSA\fP *r)"
.br
.ti -1c
.RI "int \fBDSA_get_ex_new_index\fP (long argl, \fBvoid\fP *argp, \fBCRYPTO_EX_new\fP *new_func, \fBCRYPTO_EX_dup\fP *dup_func, \fBCRYPTO_EX_free\fP *\fBfree_func\fP)"
.br
.ti -1c
.RI "int \fBDSA_set_ex_data\fP (\fBDSA\fP *d, int idx, \fBvoid\fP *\fBarg\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBDSA_get_ex_data\fP (\fBDSA\fP *d, int idx)"
.br
.ti -1c
.RI "\fBDH\fP * \fBDSA_dup_DH\fP (const \fBDSA\fP *r)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBDSA_version\fP [] = 'DSA' OPENSSL_VERSION_PTEXT"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBDH\fP* DSA_dup_DH (const \fBDSA\fP * r)"

.PP
Definition at line 290 of file dsa_lib\&.c\&.
.SS "\fBvoid\fP DSA_free (\fBDSA\fP * r)"

.PP
Definition at line 189 of file dsa_lib\&.c\&.
.SS "const \fBDSA_METHOD\fP* DSA_get_default_method (\fBvoid\fP)"

.PP
Definition at line 86 of file dsa_lib\&.c\&.
.SS "\fBvoid\fP* DSA_get_ex_data (\fBDSA\fP * d, int idx)"

.PP
Definition at line 284 of file dsa_lib\&.c\&.
.SS "int DSA_get_ex_new_index (long argl, \fBvoid\fP * argp, \fBCRYPTO_EX_new\fP * new_func, \fBCRYPTO_EX_dup\fP * dup_func, \fBCRYPTO_EX_free\fP * free_func)"

.PP
Definition at line 272 of file dsa_lib\&.c\&.
.SS "\fBDSA\fP* DSA_new (\fBvoid\fP)"

.PP
Definition at line 101 of file dsa_lib\&.c\&.
.SS "\fBDSA\fP* DSA_new_method (\fBENGINE\fP * engine)"

.PP
Definition at line 128 of file dsa_lib\&.c\&.
.SS "\fBvoid\fP DSA_set_default_method (const \fBDSA_METHOD\fP * meth)"

.PP
Definition at line 81 of file dsa_lib\&.c\&.
.SS "int DSA_set_ex_data (\fBDSA\fP * d, int idx, \fBvoid\fP * arg)"

.PP
Definition at line 279 of file dsa_lib\&.c\&.
.SS "int DSA_set_method (\fBDSA\fP * dsa, const \fBDSA_METHOD\fP * meth)"

.PP
Definition at line 106 of file dsa_lib\&.c\&.
.SS "int DSA_size (const \fBDSA\fP * r)"

.PP
Definition at line 250 of file dsa_lib\&.c\&.
.SS "int DSA_up_ref (\fBDSA\fP * r)"

.PP
Definition at line 235 of file dsa_lib\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const char DSA_version[] = 'DSA' OPENSSL_VERSION_PTEXT"

.PP
Definition at line 77 of file dsa_lib\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
