.TH "dtls1_bitmap_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtls1_bitmap_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dtls1\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBmap\fP"
.br
.ti -1c
.RI "unsigned char \fBmax_seq_num\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file dtls1\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned long map"

.PP
Definition at line 129 of file dtls1\&.h\&.
.SS "unsigned char max_seq_num"

.PP
Definition at line 131 of file dtls1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
