.TH "dtls1_retransmit_state" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtls1_retransmit_state \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dtls1\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEVP_CIPHER_CTX\fP * \fBenc_write_ctx\fP"
.br
.ti -1c
.RI "\fBEVP_MD_CTX\fP * \fBwrite_hash\fP"
.br
.ti -1c
.RI "\fBCOMP_CTX\fP * \fBcompress\fP"
.br
.ti -1c
.RI "\fBSSL_SESSION\fP * \fBsession\fP"
.br
.ti -1c
.RI "unsigned short \fBepoch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 135 of file dtls1\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBCOMP_CTX\fP * compress"

.PP
Definition at line 139 of file dtls1\&.h\&.
.SS "\fBEVP_CIPHER_CTX\fP * enc_write_ctx"

.PP
Definition at line 136 of file dtls1\&.h\&.
.SS "unsigned short epoch"

.PP
Definition at line 144 of file dtls1\&.h\&.
.SS "\fBSSL_SESSION\fP * session"

.PP
Definition at line 143 of file dtls1\&.h\&.
.SS "\fBEVP_MD_CTX\fP * write_hash"

.PP
Definition at line 137 of file dtls1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
