.TH "s2n/libcrypto-build/openssl/engines/e_aep.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/engines/e_aep.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/e_os2\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/dso\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/rsa\&.h>\fP
.br
\fC#include <openssl/dsa\&.h>\fP
.br
\fC#include <openssl/dh\&.h>\fP
.br
\fC#include 'vendor_defns/aep\&.h'\fP
.br
\fC#include 'e_aep_err\&.c'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAEP_LIB_NAME\fP   'aep engine'"
.br
.ti -1c
.RI "#define \fBFAIL_TO_SW\fP   0x10101010"
.br
.ti -1c
.RI "#define \fBAEP_CMD_SO_PATH\fP   \fBENGINE_CMD_BASE\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define AEP_CMD_SO_PATH   \fBENGINE_CMD_BASE\fP"

.PP
Definition at line 168 of file e_aep\&.c\&.
.SS "#define AEP_LIB_NAME   'aep engine'"

.PP
Definition at line 97 of file e_aep\&.c\&.
.SS "#define FAIL_TO_SW   0x10101010"

.PP
Definition at line 98 of file e_aep\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
