.TH "s2n/libcrypto-build/openssl/crypto/evp/e_bf.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/evp/e_bf.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include 'evp_locl\&.h'\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/blowfish\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBEVP_BF_KEY\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBdata\fP(\fBctx\fP)             \fBEVP_C_DATA\fP(\fBEVP_BF_KEY\fP,\fBctx\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIMPLEMENT_BLOCK_CIPHER\fP (bf, ks, BF, \fBEVP_BF_KEY\fP, NID_bf, 8, 16, 8, 64, \fBEVP_CIPH_VARIABLE_LENGTH\fP, bf_init_key, \fBNULL\fP, \fBEVP_CIPHER_set_asn1_iv\fP, \fBEVP_CIPHER_get_asn1_iv\fP, \fBNULL\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define data(\fBctx\fP)   \fBEVP_C_DATA\fP(\fBEVP_BF_KEY\fP,\fBctx\fP)"

.PP
Definition at line 74 of file e_bf\&.c\&.
.SH "Function Documentation"
.PP 
.SS "IMPLEMENT_BLOCK_CIPHER (bf, ks, BF, \fBEVP_BF_KEY\fP, NID_bf, 8, 16, 8, 64, \fBEVP_CIPH_VARIABLE_LENGTH\fP, bf_init_key, \fBNULL\fP, \fBEVP_CIPHER_set_asn1_iv\fP, \fBEVP_CIPHER_get_asn1_iv\fP, \fBNULL\fP)"

.PP
Definition at line 76 of file e_bf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
