.TH "s2n/libcrypto-build/openssl/engines/ccgost/e_gost_err.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/engines/ccgost/e_gost_err.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGOSTerr\fP(\fBf\fP,  r)   \fBERR_GOST_error\fP((\fBf\fP),(r),__FILE__,__LINE__)"
.br
.ti -1c
.RI "#define \fBGOST_F_DECODE_GOST_ALGOR_PARAMS\fP   99"
.br
.ti -1c
.RI "#define \fBGOST_F_ENCODE_GOST_ALGOR_PARAMS\fP   100"
.br
.ti -1c
.RI "#define \fBGOST_F_FILL_GOST2001_PARAMS\fP   101"
.br
.ti -1c
.RI "#define \fBGOST_F_FILL_GOST94_PARAMS\fP   102"
.br
.ti -1c
.RI "#define \fBGOST_F_GET_ENCRYPTION_PARAMS\fP   103"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST2001_COMPUTE_PUBLIC\fP   104"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST2001_DO_SIGN\fP   105"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST2001_DO_VERIFY\fP   106"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST2001_KEYGEN\fP   107"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST89_GET_ASN1_PARAMETERS\fP   108"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST89_SET_ASN1_PARAMETERS\fP   109"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST94_COMPUTE_PUBLIC\fP   110"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST_CIPHER_CTL\fP   111"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST_DO_SIGN\fP   112"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST_DO_VERIFY\fP   113"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST_IMIT_CTRL\fP   114"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST_IMIT_FINAL\fP   140"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST_IMIT_UPDATE\fP   115"
.br
.ti -1c
.RI "#define \fBGOST_F_GOST_SIGN_KEYGEN\fP   142"
.br
.ti -1c
.RI "#define \fBGOST_F_PARAM_COPY_GOST01\fP   116"
.br
.ti -1c
.RI "#define \fBGOST_F_PARAM_COPY_GOST94\fP   117"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST01CP_DECRYPT\fP   118"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST01CP_ENCRYPT\fP   119"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST01CP_KEYGEN\fP   120"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST01_PARAMGEN\fP   138"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST2001_DERIVE\fP   121"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST94CP_DECRYPT\fP   122"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST94CP_ENCRYPT\fP   123"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST94CP_KEYGEN\fP   124"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST94_PARAMGEN\fP   139"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST_CTRL\fP   125"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST_CTRL01_STR\fP   126"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST_CTRL94_STR\fP   127"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST_MAC_CTRL\fP   128"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST_MAC_CTRL_STR\fP   129"
.br
.ti -1c
.RI "#define \fBGOST_F_PKEY_GOST_MAC_KEYGEN\fP   130"
.br
.ti -1c
.RI "#define \fBGOST_F_PRINT_GOST_01\fP   131"
.br
.ti -1c
.RI "#define \fBGOST_F_PRIV_DECODE_GOST\fP   132"
.br
.ti -1c
.RI "#define \fBGOST_F_PUB_DECODE_GOST01\fP   133"
.br
.ti -1c
.RI "#define \fBGOST_F_PUB_DECODE_GOST94\fP   134"
.br
.ti -1c
.RI "#define \fBGOST_F_PUB_ENCODE_GOST01\fP   135"
.br
.ti -1c
.RI "#define \fBGOST_F_UNPACK_CC_SIGNATURE\fP   136"
.br
.ti -1c
.RI "#define \fBGOST_F_UNPACK_CP_SIGNATURE\fP   137"
.br
.ti -1c
.RI "#define \fBGOST_R_BAD_KEY_PARAMETERS_FORMAT\fP   99"
.br
.ti -1c
.RI "#define \fBGOST_R_BAD_PKEY_PARAMETERS_FORMAT\fP   100"
.br
.ti -1c
.RI "#define \fBGOST_R_CANNOT_PACK_EPHEMERAL_KEY\fP   101"
.br
.ti -1c
.RI "#define \fBGOST_R_CTRL_CALL_FAILED\fP   132"
.br
.ti -1c
.RI "#define \fBGOST_R_ERROR_COMPUTING_SHARED_KEY\fP   102"
.br
.ti -1c
.RI "#define \fBGOST_R_ERROR_PACKING_KEY_TRANSPORT_INFO\fP   103"
.br
.ti -1c
.RI "#define \fBGOST_R_ERROR_PARSING_KEY_TRANSPORT_INFO\fP   104"
.br
.ti -1c
.RI "#define \fBGOST_R_INCOMPATIBLE_ALGORITHMS\fP   105"
.br
.ti -1c
.RI "#define \fBGOST_R_INCOMPATIBLE_PEER_KEY\fP   131"
.br
.ti -1c
.RI "#define \fBGOST_R_INVALID_CIPHER_PARAMS\fP   106"
.br
.ti -1c
.RI "#define \fBGOST_R_INVALID_CIPHER_PARAM_OID\fP   107"
.br
.ti -1c
.RI "#define \fBGOST_R_INVALID_DIGEST_TYPE\fP   108"
.br
.ti -1c
.RI "#define \fBGOST_R_INVALID_GOST94_PARMSET\fP   109"
.br
.ti -1c
.RI "#define \fBGOST_R_INVALID_IV_LENGTH\fP   110"
.br
.ti -1c
.RI "#define \fBGOST_R_INVALID_MAC_KEY_LENGTH\fP   111"
.br
.ti -1c
.RI "#define \fBGOST_R_INVALID_PARAMSET\fP   112"
.br
.ti -1c
.RI "#define \fBGOST_R_KEY_IS_NOT_INITALIZED\fP   113"
.br
.ti -1c
.RI "#define \fBGOST_R_KEY_IS_NOT_INITIALIZED\fP   114"
.br
.ti -1c
.RI "#define \fBGOST_R_KEY_PARAMETERS_MISSING\fP   115"
.br
.ti -1c
.RI "#define \fBGOST_R_MAC_KEY_NOT_SET\fP   116"
.br
.ti -1c
.RI "#define \fBGOST_R_MALLOC_FAILURE\fP   117"
.br
.ti -1c
.RI "#define \fBGOST_R_NO_MEMORY\fP   118"
.br
.ti -1c
.RI "#define \fBGOST_R_NO_PARAMETERS_SET\fP   119"
.br
.ti -1c
.RI "#define \fBGOST_R_NO_PEER_KEY\fP   120"
.br
.ti -1c
.RI "#define \fBGOST_R_NO_PRIVATE_PART_OF_NON_EPHEMERAL_KEYPAIR\fP   121"
.br
.ti -1c
.RI "#define \fBGOST_R_PUBLIC_KEY_UNDEFINED\fP   122"
.br
.ti -1c
.RI "#define \fBGOST_R_RANDOM_GENERATOR_ERROR\fP   123"
.br
.ti -1c
.RI "#define \fBGOST_R_RANDOM_GENERATOR_FAILURE\fP   124"
.br
.ti -1c
.RI "#define \fBGOST_R_RANDOM_NUMBER_GENERATOR_FAILED\fP   125"
.br
.ti -1c
.RI "#define \fBGOST_R_SIGNATURE_MISMATCH\fP   126"
.br
.ti -1c
.RI "#define \fBGOST_R_SIGNATURE_PARTS_GREATER_THAN_Q\fP   127"
.br
.ti -1c
.RI "#define \fBGOST_R_UKM_NOT_SET\fP   128"
.br
.ti -1c
.RI "#define \fBGOST_R_UNSUPPORTED_CIPHER_CTL_COMMAND\fP   129"
.br
.ti -1c
.RI "#define \fBGOST_R_UNSUPPORTED_PARAMETER_SET\fP   130"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBERR_load_GOST_strings\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBERR_unload_GOST_strings\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBERR_GOST_error\fP (int function, int reason, char *\fBfile\fP, int line)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GOST_F_DECODE_GOST_ALGOR_PARAMS   99"

.PP
Definition at line 75 of file e_gost_err\&.h\&.
.SS "#define GOST_F_ENCODE_GOST_ALGOR_PARAMS   100"

.PP
Definition at line 76 of file e_gost_err\&.h\&.
.SS "#define GOST_F_FILL_GOST2001_PARAMS   101"

.PP
Definition at line 77 of file e_gost_err\&.h\&.
.SS "#define GOST_F_FILL_GOST94_PARAMS   102"

.PP
Definition at line 78 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GET_ENCRYPTION_PARAMS   103"

.PP
Definition at line 79 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST2001_COMPUTE_PUBLIC   104"

.PP
Definition at line 80 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST2001_DO_SIGN   105"

.PP
Definition at line 81 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST2001_DO_VERIFY   106"

.PP
Definition at line 82 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST2001_KEYGEN   107"

.PP
Definition at line 83 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST89_GET_ASN1_PARAMETERS   108"

.PP
Definition at line 84 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST89_SET_ASN1_PARAMETERS   109"

.PP
Definition at line 85 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST94_COMPUTE_PUBLIC   110"

.PP
Definition at line 86 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST_CIPHER_CTL   111"

.PP
Definition at line 87 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST_DO_SIGN   112"

.PP
Definition at line 88 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST_DO_VERIFY   113"

.PP
Definition at line 89 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST_IMIT_CTRL   114"

.PP
Definition at line 90 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST_IMIT_FINAL   140"

.PP
Definition at line 91 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST_IMIT_UPDATE   115"

.PP
Definition at line 92 of file e_gost_err\&.h\&.
.SS "#define GOST_F_GOST_SIGN_KEYGEN   142"

.PP
Definition at line 93 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PARAM_COPY_GOST01   116"

.PP
Definition at line 94 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PARAM_COPY_GOST94   117"

.PP
Definition at line 95 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST01_PARAMGEN   138"

.PP
Definition at line 99 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST01CP_DECRYPT   118"

.PP
Definition at line 96 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST01CP_ENCRYPT   119"

.PP
Definition at line 97 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST01CP_KEYGEN   120"

.PP
Definition at line 98 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST2001_DERIVE   121"

.PP
Definition at line 100 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST94_PARAMGEN   139"

.PP
Definition at line 104 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST94CP_DECRYPT   122"

.PP
Definition at line 101 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST94CP_ENCRYPT   123"

.PP
Definition at line 102 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST94CP_KEYGEN   124"

.PP
Definition at line 103 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST_CTRL   125"

.PP
Definition at line 105 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST_CTRL01_STR   126"

.PP
Definition at line 106 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST_CTRL94_STR   127"

.PP
Definition at line 107 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST_MAC_CTRL   128"

.PP
Definition at line 108 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST_MAC_CTRL_STR   129"

.PP
Definition at line 109 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PKEY_GOST_MAC_KEYGEN   130"

.PP
Definition at line 110 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PRINT_GOST_01   131"

.PP
Definition at line 111 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PRIV_DECODE_GOST   132"

.PP
Definition at line 112 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PUB_DECODE_GOST01   133"

.PP
Definition at line 113 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PUB_DECODE_GOST94   134"

.PP
Definition at line 114 of file e_gost_err\&.h\&.
.SS "#define GOST_F_PUB_ENCODE_GOST01   135"

.PP
Definition at line 115 of file e_gost_err\&.h\&.
.SS "#define GOST_F_UNPACK_CC_SIGNATURE   136"

.PP
Definition at line 116 of file e_gost_err\&.h\&.
.SS "#define GOST_F_UNPACK_CP_SIGNATURE   137"

.PP
Definition at line 117 of file e_gost_err\&.h\&.
.SS "#define GOST_R_BAD_KEY_PARAMETERS_FORMAT   99"

.PP
Definition at line 120 of file e_gost_err\&.h\&.
.SS "#define GOST_R_BAD_PKEY_PARAMETERS_FORMAT   100"

.PP
Definition at line 121 of file e_gost_err\&.h\&.
.SS "#define GOST_R_CANNOT_PACK_EPHEMERAL_KEY   101"

.PP
Definition at line 122 of file e_gost_err\&.h\&.
.SS "#define GOST_R_CTRL_CALL_FAILED   132"

.PP
Definition at line 123 of file e_gost_err\&.h\&.
.SS "#define GOST_R_ERROR_COMPUTING_SHARED_KEY   102"

.PP
Definition at line 124 of file e_gost_err\&.h\&.
.SS "#define GOST_R_ERROR_PACKING_KEY_TRANSPORT_INFO   103"

.PP
Definition at line 125 of file e_gost_err\&.h\&.
.SS "#define GOST_R_ERROR_PARSING_KEY_TRANSPORT_INFO   104"

.PP
Definition at line 126 of file e_gost_err\&.h\&.
.SS "#define GOST_R_INCOMPATIBLE_ALGORITHMS   105"

.PP
Definition at line 127 of file e_gost_err\&.h\&.
.SS "#define GOST_R_INCOMPATIBLE_PEER_KEY   131"

.PP
Definition at line 128 of file e_gost_err\&.h\&.
.SS "#define GOST_R_INVALID_CIPHER_PARAM_OID   107"

.PP
Definition at line 130 of file e_gost_err\&.h\&.
.SS "#define GOST_R_INVALID_CIPHER_PARAMS   106"

.PP
Definition at line 129 of file e_gost_err\&.h\&.
.SS "#define GOST_R_INVALID_DIGEST_TYPE   108"

.PP
Definition at line 131 of file e_gost_err\&.h\&.
.SS "#define GOST_R_INVALID_GOST94_PARMSET   109"

.PP
Definition at line 132 of file e_gost_err\&.h\&.
.SS "#define GOST_R_INVALID_IV_LENGTH   110"

.PP
Definition at line 133 of file e_gost_err\&.h\&.
.SS "#define GOST_R_INVALID_MAC_KEY_LENGTH   111"

.PP
Definition at line 134 of file e_gost_err\&.h\&.
.SS "#define GOST_R_INVALID_PARAMSET   112"

.PP
Definition at line 135 of file e_gost_err\&.h\&.
.SS "#define GOST_R_KEY_IS_NOT_INITALIZED   113"

.PP
Definition at line 136 of file e_gost_err\&.h\&.
.SS "#define GOST_R_KEY_IS_NOT_INITIALIZED   114"

.PP
Definition at line 137 of file e_gost_err\&.h\&.
.SS "#define GOST_R_KEY_PARAMETERS_MISSING   115"

.PP
Definition at line 138 of file e_gost_err\&.h\&.
.SS "#define GOST_R_MAC_KEY_NOT_SET   116"

.PP
Definition at line 139 of file e_gost_err\&.h\&.
.SS "#define GOST_R_MALLOC_FAILURE   117"

.PP
Definition at line 140 of file e_gost_err\&.h\&.
.SS "#define GOST_R_NO_MEMORY   118"

.PP
Definition at line 141 of file e_gost_err\&.h\&.
.SS "#define GOST_R_NO_PARAMETERS_SET   119"

.PP
Definition at line 142 of file e_gost_err\&.h\&.
.SS "#define GOST_R_NO_PEER_KEY   120"

.PP
Definition at line 143 of file e_gost_err\&.h\&.
.SS "#define GOST_R_NO_PRIVATE_PART_OF_NON_EPHEMERAL_KEYPAIR   121"

.PP
Definition at line 144 of file e_gost_err\&.h\&.
.SS "#define GOST_R_PUBLIC_KEY_UNDEFINED   122"

.PP
Definition at line 145 of file e_gost_err\&.h\&.
.SS "#define GOST_R_RANDOM_GENERATOR_ERROR   123"

.PP
Definition at line 146 of file e_gost_err\&.h\&.
.SS "#define GOST_R_RANDOM_GENERATOR_FAILURE   124"

.PP
Definition at line 147 of file e_gost_err\&.h\&.
.SS "#define GOST_R_RANDOM_NUMBER_GENERATOR_FAILED   125"

.PP
Definition at line 148 of file e_gost_err\&.h\&.
.SS "#define GOST_R_SIGNATURE_MISMATCH   126"

.PP
Definition at line 149 of file e_gost_err\&.h\&.
.SS "#define GOST_R_SIGNATURE_PARTS_GREATER_THAN_Q   127"

.PP
Definition at line 150 of file e_gost_err\&.h\&.
.SS "#define GOST_R_UKM_NOT_SET   128"

.PP
Definition at line 151 of file e_gost_err\&.h\&.
.SS "#define GOST_R_UNSUPPORTED_CIPHER_CTL_COMMAND   129"

.PP
Definition at line 152 of file e_gost_err\&.h\&.
.SS "#define GOST_R_UNSUPPORTED_PARAMETER_SET   130"

.PP
Definition at line 153 of file e_gost_err\&.h\&.
.SS "#define GOSTerr(\fBf\fP, r)   \fBERR_GOST_error\fP((\fBf\fP),(r),__FILE__,__LINE__)"

.PP
Definition at line 70 of file e_gost_err\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP ERR_GOST_error (int function, int reason, char * file, int line)"

.PP
Definition at line 216 of file e_gost_err\&.c\&.
.SS "\fBvoid\fP ERR_load_GOST_strings (\fBvoid\fP)"

.PP
Definition at line 182 of file e_gost_err\&.c\&.
.SS "\fBvoid\fP ERR_unload_GOST_strings (\fBvoid\fP)"

.PP
Definition at line 201 of file e_gost_err\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
