.TH "s2n/libcrypto-build/openssl/engines/e_ubsec.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/engines/e_ubsec.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/dso\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br
\fC#include <openssl/rsa\&.h>\fP
.br
\fC#include <openssl/dsa\&.h>\fP
.br
\fC#include <openssl/dh\&.h>\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include 'vendor_defns/hw_ubsec\&.h'\fP
.br
\fC#include 'e_ubsec_err\&.c'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUBSEC_LIB_NAME\fP   'ubsec engine'"
.br
.ti -1c
.RI "#define \fBFAIL_TO_SOFTWARE\fP   \-15"
.br
.ti -1c
.RI "#define \fBUBSEC_CMD_SO_PATH\fP   \fBENGINE_CMD_BASE\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FAIL_TO_SOFTWARE   \-15"

.PP
Definition at line 89 of file e_ubsec\&.c\&.
.SS "#define UBSEC_CMD_SO_PATH   \fBENGINE_CMD_BASE\fP"

.PP
Definition at line 136 of file e_ubsec\&.c\&.
.SS "#define UBSEC_LIB_NAME   'ubsec engine'"

.PP
Definition at line 86 of file e_ubsec\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
