.TH "ecdh_data_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecdh_data_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ech_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBinit\fP )(\fBEC_KEY\fP *)"
.br
.ti -1c
.RI "\fBENGINE\fP * \fBengine\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "const \fBECDH_METHOD\fP * \fBmeth\fP"
.br
.ti -1c
.RI "\fBCRYPTO_EX_DATA\fP \fBex_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file ech_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBENGINE\fP* engine"

.PP
Definition at line 92 of file ech_locl\&.h\&.
.SS "\fBCRYPTO_EX_DATA\fP ex_data"

.PP
Definition at line 95 of file ech_locl\&.h\&.
.SS "int flags"

.PP
Definition at line 93 of file ech_locl\&.h\&.
.SS "int(* init) (\fBEC_KEY\fP *)"

.PP
Definition at line 90 of file ech_locl\&.h\&.
.SS "const \fBECDH_METHOD\fP* meth"

.PP
Definition at line 94 of file ech_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
