.TH "s2n/libcrypto-build/openssl/crypto/ecdh/ech_lib.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ecdh/ech_lib.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ech_locl\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBECDH_set_default_method\fP (const \fBECDH_METHOD\fP *meth)"
.br
.ti -1c
.RI "const \fBECDH_METHOD\fP * \fBECDH_get_default_method\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBECDH_set_method\fP (\fBEC_KEY\fP *eckey, const \fBECDH_METHOD\fP *meth)"
.br
.ti -1c
.RI "\fBECDH_DATA\fP * \fBecdh_check\fP (\fBEC_KEY\fP *\fBkey\fP)"
.br
.ti -1c
.RI "int \fBECDH_get_ex_new_index\fP (long argl, \fBvoid\fP *argp, \fBCRYPTO_EX_new\fP *new_func, \fBCRYPTO_EX_dup\fP *dup_func, \fBCRYPTO_EX_free\fP *\fBfree_func\fP)"
.br
.ti -1c
.RI "int \fBECDH_set_ex_data\fP (\fBEC_KEY\fP *d, int idx, \fBvoid\fP *\fBarg\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBECDH_get_ex_data\fP (\fBEC_KEY\fP *d, int idx)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBECDH_version\fP [] = 'ECDH' OPENSSL_VERSION_PTEXT"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBECDH_DATA\fP* ecdh_check (\fBEC_KEY\fP * key)"

.PP
Definition at line 208 of file ech_lib\&.c\&.
.SS "const \fBECDH_METHOD\fP* ECDH_get_default_method (\fBvoid\fP)"

.PP
Definition at line 93 of file ech_lib\&.c\&.
.SS "\fBvoid\fP* ECDH_get_ex_data (\fBEC_KEY\fP * d, int idx)"

.PP
Definition at line 258 of file ech_lib\&.c\&.
.SS "int ECDH_get_ex_new_index (long argl, \fBvoid\fP * argp, \fBCRYPTO_EX_new\fP * new_func, \fBCRYPTO_EX_dup\fP * dup_func, \fBCRYPTO_EX_free\fP * free_func)"

.PP
Definition at line 242 of file ech_lib\&.c\&.
.SS "\fBvoid\fP ECDH_set_default_method (const \fBECDH_METHOD\fP * meth)"

.PP
Definition at line 88 of file ech_lib\&.c\&.
.SS "int ECDH_set_ex_data (\fBEC_KEY\fP * d, int idx, \fBvoid\fP * arg)"

.PP
Definition at line 249 of file ech_lib\&.c\&.
.SS "int ECDH_set_method (\fBEC_KEY\fP * eckey, const \fBECDH_METHOD\fP * meth)"

.PP
Definition at line 108 of file ech_lib\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const char ECDH_version[] = 'ECDH' OPENSSL_VERSION_PTEXT"

.PP
Definition at line 80 of file ech_lib\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
