.TH "s2n/libcrypto-build/openssl/crypto/ecdh/ech_key.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ecdh/ech_key.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ech_locl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBECDH_compute_key\fP (\fBvoid\fP *\fBout\fP, size_t outlen, const \fBEC_POINT\fP *pub_key, \fBEC_KEY\fP *eckey, \fBvoid\fP *(*KDF)(const \fBvoid\fP *\fBin\fP, size_t inlen, \fBvoid\fP *\fBout\fP,                                                                                                                                   size_t *outlen))"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ECDH_compute_key (\fBvoid\fP * out, size_t outlen, const \fBEC_POINT\fP * pub_key, \fBEC_KEY\fP * eckey, \fBvoid\fP *(*)(const \fBvoid\fP *\fBin\fP, size_t inlen, \fBvoid\fP *\fBout\fP,                                                                                                                                   size_t *outlen) KDF)"

.PP
Definition at line 72 of file ech_key\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
