.TH "s2n/libcrypto-build/openssl/crypto/ecdsa/ecs_locl.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ecdsa/ecs_locl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/ecdsa\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBecdsa_method\fP"
.br
.ti -1c
.RI "struct \fBecdsa_data_st\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBECDSA_METHOD_FLAG_ALLOCATED\fP   0x2"
.br
.ti -1c
.RI "#define \fBECDSA_FLAG_FIPS_METHOD\fP   0x1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBecdsa_data_st\fP \fBECDSA_DATA\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBECDSA_DATA\fP * \fBecdsa_check\fP (\fBEC_KEY\fP *eckey)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ECDSA_FLAG_FIPS_METHOD   0x1"

.PP
Definition at line 96 of file ecs_locl\&.h\&.
.SS "#define ECDSA_METHOD_FLAG_ALLOCATED   0x2"

.PP
Definition at line 87 of file ecs_locl\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBecdsa_data_st\fP  \fBECDSA_DATA\fP"

.SH "Function Documentation"
.PP 
.SS "\fBECDSA_DATA\fP* ecdsa_check (\fBEC_KEY\fP * eckey)"
ecdsa_check checks whether ECKEY->meth_data is a pointer to a ECDSA_DATA structure and if not it removes the old meth_data and creates a ECDSA_DATA structure\&. 
.PP
\fBParameters:\fP
.RS 4
\fIeckey\fP pointer to a EC_KEY object 
.RE
.PP
\fBReturns:\fP
.RS 4
pointer to a ECDSA_DATA structure 
.RE
.PP

.PP
Definition at line 186 of file ecs_lib\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
