.TH "err_state_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
err_state_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <err\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCRYPTO_THREADID\fP \fBtid\fP"
.br
.ti -1c
.RI "int \fBerr_flags\fP [\fBERR_NUM_ERRORS\fP]"
.br
.ti -1c
.RI "unsigned long \fBerr_buffer\fP [\fBERR_NUM_ERRORS\fP]"
.br
.ti -1c
.RI "char * \fBerr_data\fP [\fBERR_NUM_ERRORS\fP]"
.br
.ti -1c
.RI "int \fBerr_data_flags\fP [\fBERR_NUM_ERRORS\fP]"
.br
.ti -1c
.RI "const char * \fBerr_file\fP [\fBERR_NUM_ERRORS\fP]"
.br
.ti -1c
.RI "int \fBerr_line\fP [\fBERR_NUM_ERRORS\fP]"
.br
.ti -1c
.RI "int \fBtop\fP"
.br
.ti -1c
.RI "int \fBbottom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 148 of file err\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int bottom"

.PP
Definition at line 156 of file err\&.h\&.
.SS "unsigned long err_buffer"

.PP
Definition at line 151 of file err\&.h\&.
.SS "char * err_data"

.PP
Definition at line 152 of file err\&.h\&.
.SS "int err_data_flags"

.PP
Definition at line 153 of file err\&.h\&.
.SS "const char * err_file"

.PP
Definition at line 154 of file err\&.h\&.
.SS "int err_flags"

.PP
Definition at line 150 of file err\&.h\&.
.SS "int err_line"

.PP
Definition at line 155 of file err\&.h\&.
.SS "\fBCRYPTO_THREADID\fP tid"

.PP
Definition at line 149 of file err\&.h\&.
.SS "int top"

.PP
Definition at line 156 of file err\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
