.TH "ESS_cert_id" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ESS_cert_id \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ts\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBhash\fP"
.br
.ti -1c
.RI "\fBESS_ISSUER_SERIAL\fP * \fBissuer_serial\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 257 of file ts\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBASN1_OCTET_STRING\fP * \fBhash\fP"

.PP
Definition at line 258 of file ts\&.h\&.
.SS "\fBESS_ISSUER_SERIAL\fP * issuer_serial"

.PP
Definition at line 259 of file ts\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
