.TH "s2n/libcrypto-build/openssl/crypto/asn1/evp_asn1.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/evp_asn1.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/asn1_mac\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBASN1_TYPE_set_octetstring\fP (\fBASN1_TYPE\fP *\fBa\fP, unsigned char *\fBdata\fP, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBASN1_TYPE_get_octetstring\fP (\fBASN1_TYPE\fP *\fBa\fP, unsigned char *\fBdata\fP, int max_len)"
.br
.ti -1c
.RI "int \fBASN1_TYPE_set_int_octetstring\fP (\fBASN1_TYPE\fP *\fBa\fP, long \fBnum\fP, unsigned char *\fBdata\fP, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBASN1_TYPE_get_int_octetstring\fP (\fBASN1_TYPE\fP *\fBa\fP, long *\fBnum\fP, unsigned char *\fBdata\fP, int max_len)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ASN1_TYPE_get_int_octetstring (\fBASN1_TYPE\fP * a, long * num, unsigned char * data, int max_len)"

.PP
Definition at line 142 of file evp_asn1\&.c\&.
.SS "int ASN1_TYPE_get_octetstring (\fBASN1_TYPE\fP * a, unsigned char * data, int max_len)"

.PP
Definition at line 79 of file evp_asn1\&.c\&.
.SS "int ASN1_TYPE_set_int_octetstring (\fBASN1_TYPE\fP * a, long num, unsigned char * data, int len)"

.PP
Definition at line 98 of file evp_asn1\&.c\&.
.SS "int ASN1_TYPE_set_octetstring (\fBASN1_TYPE\fP * a, unsigned char * data, int len)"

.PP
Definition at line 64 of file evp_asn1\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
