.TH "evp_pkey_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evp_pkey_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ATTRIBUTE\fP)*attributes"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ATTRIBUTE\fP)*attributes"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ATTRIBUTE\fP)*attributes"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBsave_type\fP"
.br
.ti -1c
.RI "int \fBreferences\fP"
.br
.ti -1c
.RI "const \fBEVP_PKEY_ASN1_METHOD\fP * \fBameth\fP"
.br
.ti -1c
.RI "\fBENGINE\fP * \fBengine\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBptr\fP"
.br
.ti -1c
.RI "   struct \fBrsa_st\fP * \fBrsa\fP"
.br
.ti -1c
.RI "   struct \fBdsa_st\fP * \fBdsa\fP"
.br
.ti -1c
.RI "   struct \fBdh_st\fP * \fBdh\fP"
.br
.ti -1c
.RI "   struct \fBec_key_st\fP * \fBec\fP"
.br
.ti -1c
.RI "} \fBpkey\fP"
.br
.ti -1c
.RI "int \fBsave_parameters\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBptr\fP"
.br
.ti -1c
.RI "   struct \fBrsa_st\fP * \fBrsa\fP"
.br
.ti -1c
.RI "   struct \fBdsa_st\fP * \fBdsa\fP"
.br
.ti -1c
.RI "   struct \fBdh_st\fP * \fBdh\fP"
.br
.ti -1c
.RI "   struct \fBec_key_st\fP * \fBec\fP"
.br
.ti -1c
.RI "} \fBpkey\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBptr\fP"
.br
.ti -1c
.RI "   struct \fBrsa_st\fP * \fBrsa\fP"
.br
.ti -1c
.RI "   struct \fBdsa_st\fP * \fBdsa\fP"
.br
.ti -1c
.RI "   struct \fBdh_st\fP * \fBdh\fP"
.br
.ti -1c
.RI "   struct \fBec_key_st\fP * \fBec\fP"
.br
.ti -1c
.RI "} \fBpkey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 129 of file evp\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBX509_ATTRIBUTE\fP)"

.SS "STACK_OF (\fBX509_ATTRIBUTE\fP)"

.SS "STACK_OF (\fBX509_ATTRIBUTE\fP)"

.SH "Field Documentation"
.PP 
.SS "const \fBEVP_PKEY_ASN1_METHOD\fP * ameth"

.PP
Definition at line 133 of file evp\&.h\&.
.SS "struct \fBdh_st\fP* dh"

.PP
Definition at line 144 of file evp\&.h\&.
.SS "struct \fBdsa_st\fP* dsa"

.PP
Definition at line 141 of file evp\&.h\&.
.SS "struct \fBec_key_st\fP* ec"

.PP
Definition at line 147 of file evp\&.h\&.
.SS "\fBENGINE\fP * engine"

.PP
Definition at line 134 of file evp\&.h\&.
.SS "union { \&.\&.\&. }   pkey"

.SS "union { \&.\&.\&. }   pkey"

.SS "union { \&.\&.\&. }   pkey"

.SS "char* ptr"

.PP
Definition at line 136 of file evp\&.h\&.
.SS "int references"

.PP
Definition at line 132 of file evp\&.h\&.
.SS "struct \fBrsa_st\fP* rsa"

.PP
Definition at line 138 of file evp\&.h\&.
.SS "int save_parameters"

.PP
Definition at line 150 of file evp\&.h\&.
.SS "int save_type"

.PP
Definition at line 131 of file evp\&.h\&.
.SS "int type"

.PP
Definition at line 130 of file evp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
