.TH "evp_pkey_method_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
evp_pkey_method_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evp_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBpkey_id\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int(* \fBinit\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int(* \fBcopy\fP )(\fBEVP_PKEY_CTX\fP *dst, \fBEVP_PKEY_CTX\fP *src)"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBcleanup\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int(* \fBparamgen_init\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int(* \fBparamgen\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, \fBEVP_PKEY\fP *pkey)"
.br
.ti -1c
.RI "int(* \fBkeygen_init\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int(* \fBkeygen\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, \fBEVP_PKEY\fP *pkey)"
.br
.ti -1c
.RI "int(* \fBsign_init\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int(* \fBsign\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen)"
.br
.ti -1c
.RI "int(* \fBverify_init\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int(* \fBverify\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen)"
.br
.ti -1c
.RI "int(* \fBverify_recover_init\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int(* \fBverify_recover\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *rout, size_t *routlen, const unsigned char *sig, size_t siglen)"
.br
.ti -1c
.RI "int(* \fBsignctx_init\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, \fBEVP_MD_CTX\fP *mctx)"
.br
.ti -1c
.RI "int(* \fBsignctx\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *sig, size_t *siglen, \fBEVP_MD_CTX\fP *mctx)"
.br
.ti -1c
.RI "int(* \fBverifyctx_init\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, \fBEVP_MD_CTX\fP *mctx)"
.br
.ti -1c
.RI "int(* \fBverifyctx\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, const unsigned char *sig, int siglen, \fBEVP_MD_CTX\fP *mctx)"
.br
.ti -1c
.RI "int(* \fBencrypt_init\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int(* \fBencrypt\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBout\fP, size_t *outlen, const unsigned char *\fBin\fP, size_t inlen)"
.br
.ti -1c
.RI "int(* \fBdecrypt_init\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int(* \fBdecrypt\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBout\fP, size_t *outlen, const unsigned char *\fBin\fP, size_t inlen)"
.br
.ti -1c
.RI "int(* \fBderive_init\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int(* \fBderive\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBkey\fP, size_t *keylen)"
.br
.ti -1c
.RI "int(* \fBctrl\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, int \fBtype\fP, int p1, \fBvoid\fP *p2)"
.br
.ti -1c
.RI "int(* \fBctrl_str\fP )(\fBEVP_PKEY_CTX\fP *\fBctx\fP, const char *\fBtype\fP, const char *value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 290 of file evp_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBvoid\fP(* cleanup) (\fBEVP_PKEY_CTX\fP *\fBctx\fP)"

.PP
Definition at line 295 of file evp_locl\&.h\&.
.SS "int(* copy) (\fBEVP_PKEY_CTX\fP *dst, \fBEVP_PKEY_CTX\fP *src)"

.PP
Definition at line 294 of file evp_locl\&.h\&.
.SS "int(* ctrl) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, int \fBtype\fP, int p1, \fBvoid\fP *p2)"

.PP
Definition at line 325 of file evp_locl\&.h\&.
.SS "int(* ctrl_str) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, const char *\fBtype\fP, const char *value)"

.PP
Definition at line 326 of file evp_locl\&.h\&.
.SS "int(* decrypt) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBout\fP, size_t *outlen, const unsigned char *\fBin\fP, size_t inlen)"

.PP
Definition at line 321 of file evp_locl\&.h\&.
.SS "int(* decrypt_init) (\fBEVP_PKEY_CTX\fP *\fBctx\fP)"

.PP
Definition at line 320 of file evp_locl\&.h\&.
.SS "int(* derive) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBkey\fP, size_t *keylen)"

.PP
Definition at line 324 of file evp_locl\&.h\&.
.SS "int(* derive_init) (\fBEVP_PKEY_CTX\fP *\fBctx\fP)"

.PP
Definition at line 323 of file evp_locl\&.h\&.
.SS "int(* encrypt) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBout\fP, size_t *outlen, const unsigned char *\fBin\fP, size_t inlen)"

.PP
Definition at line 318 of file evp_locl\&.h\&.
.SS "int(* encrypt_init) (\fBEVP_PKEY_CTX\fP *\fBctx\fP)"

.PP
Definition at line 317 of file evp_locl\&.h\&.
.SS "int flags"

.PP
Definition at line 292 of file evp_locl\&.h\&.
.SS "int(* init) (\fBEVP_PKEY_CTX\fP *\fBctx\fP)"

.PP
Definition at line 293 of file evp_locl\&.h\&.
.SS "int(* keygen) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, \fBEVP_PKEY\fP *pkey)"

.PP
Definition at line 299 of file evp_locl\&.h\&.
.SS "int(* keygen_init) (\fBEVP_PKEY_CTX\fP *\fBctx\fP)"

.PP
Definition at line 298 of file evp_locl\&.h\&.
.SS "int(* paramgen) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, \fBEVP_PKEY\fP *pkey)"

.PP
Definition at line 297 of file evp_locl\&.h\&.
.SS "int(* paramgen_init) (\fBEVP_PKEY_CTX\fP *\fBctx\fP)"

.PP
Definition at line 296 of file evp_locl\&.h\&.
.SS "int pkey_id"

.PP
Definition at line 291 of file evp_locl\&.h\&.
.SS "int(* sign) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *sig, size_t *siglen, const unsigned char *tbs, size_t tbslen)"

.PP
Definition at line 301 of file evp_locl\&.h\&.
.SS "int(* sign_init) (\fBEVP_PKEY_CTX\fP *\fBctx\fP)"

.PP
Definition at line 300 of file evp_locl\&.h\&.
.SS "int(* signctx) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *sig, size_t *siglen, \fBEVP_MD_CTX\fP *mctx)"

.PP
Definition at line 312 of file evp_locl\&.h\&.
.SS "int(* signctx_init) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, \fBEVP_MD_CTX\fP *mctx)"

.PP
Definition at line 311 of file evp_locl\&.h\&.
.SS "int(* verify) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, const unsigned char *sig, size_t siglen, const unsigned char *tbs, size_t tbslen)"

.PP
Definition at line 304 of file evp_locl\&.h\&.
.SS "int(* verify_init) (\fBEVP_PKEY_CTX\fP *\fBctx\fP)"

.PP
Definition at line 303 of file evp_locl\&.h\&.
.SS "int(* verify_recover) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *rout, size_t *routlen, const unsigned char *sig, size_t siglen)"

.PP
Definition at line 308 of file evp_locl\&.h\&.
.SS "int(* verify_recover_init) (\fBEVP_PKEY_CTX\fP *\fBctx\fP)"

.PP
Definition at line 307 of file evp_locl\&.h\&.
.SS "int(* verifyctx) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, const unsigned char *sig, int siglen, \fBEVP_MD_CTX\fP *mctx)"

.PP
Definition at line 315 of file evp_locl\&.h\&.
.SS "int(* verifyctx_init) (\fBEVP_PKEY_CTX\fP *\fBctx\fP, \fBEVP_MD_CTX\fP *mctx)"

.PP
Definition at line 314 of file evp_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
