.TH "GENERAL_SUBTREE_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GENERAL_SUBTREE_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <x509v3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBGENERAL_NAME\fP * \fBbase\fP"
.br
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBminimum\fP"
.br
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBmaximum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 324 of file x509v3\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBGENERAL_NAME\fP * base"

.PP
Definition at line 325 of file x509v3\&.h\&.
.SS "\fBASN1_INTEGER\fP * maximum"

.PP
Definition at line 327 of file x509v3\&.h\&.
.SS "\fBASN1_INTEGER\fP * minimum"

.PP
Definition at line 326 of file x509v3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
