.TH "s2n/libcrypto-build/openssl/MacOS/GetHTTPS.src/GetHTTPS.cpp" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/MacOS/GetHTTPS.src/GetHTTPS.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CPStringUtils\&.hpp'\fP
.br
\fC#include 'ErrorHandling\&.hpp'\fP
.br
\fC#include 'MacSocket\&.h'\fP
.br
\fC#include 'Randomizer\&.h'\fP
.br
\fC#include <openssl/ssl\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <timer\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBkHTTPS_DNS\fP   'www\&.apache\-ssl\&.org'"
.br
.ti -1c
.RI "#define \fBkHTTPS_Port\fP   443"
.br
.ti -1c
.RI "#define \fBkHTTPS_URI\fP   '/'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "OSErr \fBMyMacSocket_IdleWaitCallback\fP (\fBvoid\fP *inUserRefPtr)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmain\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define kHTTPS_DNS   'www\&.apache\-ssl\&.org'"

.PP
Definition at line 42 of file GetHTTPS\&.cpp\&.
.SS "#define kHTTPS_Port   443"

.PP
Definition at line 43 of file GetHTTPS\&.cpp\&.
.SS "#define kHTTPS_URI   '/'"

.PP
Definition at line 44 of file GetHTTPS\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP main (\fBvoid\fP)"

.PP
Definition at line 70 of file GetHTTPS\&.cpp\&.
.SS "OSErr MyMacSocket_IdleWaitCallback (\fBvoid\fP * inUserRefPtr)"

.PP
Definition at line 53 of file GetHTTPS\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
