.TH "s2n/libcrypto-build/openssl/engines/ccgost/gosthash.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/engines/ccgost/gosthash.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'gost89\&.h'\fP
.br
\fC#include 'gosthash\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMYALLOC\fP(size)   malloc(size)"
.br
.ti -1c
.RI "#define \fBMYFREE\fP(\fBptr\fP)   free(\fBptr\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinit_gost_hash_ctx\fP (\fBgost_hash_ctx\fP *\fBctx\fP, const \fBgost_subst_block\fP *subst_block)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdone_gost_hash_ctx\fP (\fBgost_hash_ctx\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBstart_hash\fP (\fBgost_hash_ctx\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBhash_block\fP (\fBgost_hash_ctx\fP *\fBctx\fP, const \fBbyte\fP *block, size_t \fBlength\fP)"
.br
.ti -1c
.RI "int \fBfinish_hash\fP (\fBgost_hash_ctx\fP *\fBctx\fP, \fBbyte\fP *hashval)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MYALLOC(size)   malloc(size)"

.PP
Definition at line 24 of file gosthash\&.c\&.
.SS "#define MYFREE(\fBptr\fP)   free(\fBptr\fP)"

.PP
Definition at line 25 of file gosthash\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP done_gost_hash_ctx (\fBgost_hash_ctx\fP * ctx)"

.PP
Definition at line 172 of file gosthash\&.c\&.
.SS "int finish_hash (\fBgost_hash_ctx\fP * ctx, \fBbyte\fP * hashval)"

.PP
Definition at line 241 of file gosthash\&.c\&.
.SS "int hash_block (\fBgost_hash_ctx\fP * ctx, const \fBbyte\fP * block, size_t length)"

.PP
Definition at line 200 of file gosthash\&.c\&.
.SS "int init_gost_hash_ctx (\fBgost_hash_ctx\fP * ctx, const \fBgost_subst_block\fP * subst_block)"

.PP
Definition at line 154 of file gosthash\&.c\&.
.SS "int start_hash (\fBgost_hash_ctx\fP * ctx)"

.PP
Definition at line 184 of file gosthash\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
