.TH "s2n/libcrypto-build/openssl/demos/engines/cluster_labs/hw_cluster_labs.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/demos/engines/cluster_labs/hw_cluster_labs.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/dso\&.h>\fP
.br
\fC#include <openssl/des\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br
\fC#include 'vendor_defns/cluster_labs\&.h'\fP
.br
\fC#include 'hw_cluster_labs_err\&.c'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMSC_VER\fP   /* only used \fBcryptic\&.h\fP */"
.br
.ti -1c
.RI "#define \fBCL_LIB_NAME\fP   'cluster_labs engine'"
.br
.ti -1c
.RI "#define \fBCLUSTER_LABS_CMD_SO_PATH\fP   \fBENGINE_CMD_BASE\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBENGINE_load_cluster_labs\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CL_LIB_NAME   'cluster_labs engine'"

.PP
Definition at line 77 of file hw_cluster_labs\&.c\&.
.SS "#define CLUSTER_LABS_CMD_SO_PATH   \fBENGINE_CMD_BASE\fP"

.PP
Definition at line 134 of file hw_cluster_labs\&.c\&.
.SS "#define MSC_VER   /* only used \fBcryptic\&.h\fP */"

.PP
Definition at line 60 of file hw_cluster_labs\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP ENGINE_load_cluster_labs (\fBvoid\fP)"

.PP
Definition at line 251 of file hw_cluster_labs\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
