.TH "HWCryptoHook_PassphraseContextValue" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HWCryptoHook_PassphraseContextValue \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBUI_METHOD\fP * \fBui_method\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBcallback_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 255 of file e_chil\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBvoid\fP* callback_data"

.PP
Definition at line 257 of file e_chil\&.c\&.
.SS "\fBUI_METHOD\fP* ui_method"

.PP
Definition at line 256 of file e_chil\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
