.TH "s2n/libcrypto-build/openssl/crypto/idea/i_cbc.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/idea/i_cbc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/idea\&.h>\fP
.br
\fC#include 'idea_lcl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBidea_cbc_encrypt\fP (const unsigned char *\fBin\fP, unsigned char *\fBout\fP, long \fBlength\fP, \fBIDEA_KEY_SCHEDULE\fP *ks, unsigned char *iv, int encrypt)"
.br
.ti -1c
.RI "\fBvoid\fP \fBidea_encrypt\fP (unsigned long *d, \fBIDEA_KEY_SCHEDULE\fP *\fBkey\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP idea_cbc_encrypt (const unsigned char * in, unsigned char * out, long length, \fBIDEA_KEY_SCHEDULE\fP * ks, unsigned char * iv, int encrypt)"

.PP
Definition at line 62 of file i_cbc\&.c\&.
.SS "\fBvoid\fP idea_encrypt (unsigned long * d, \fBIDEA_KEY_SCHEDULE\fP * key)"

.PP
Definition at line 138 of file i_cbc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
