.TH "s2n/libcrypto-build/openssl/crypto/LPdir_wince.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/LPdir_wince.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'LPdir_win\&.c'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLP_SYS_WINCE\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LP_SYS_WINCE"

.PP
Definition at line 31 of file LPdir_wince\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
