.TH "s2n/libcrypto-build/openssl/crypto/LPdir_unix.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/LPdir_unix.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <dirent\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'LPdir\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBLP_dir_context_st\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLP_ENTRY_SIZE\fP   255"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBLP_find_file\fP (\fBLP_DIR_CTX\fP **\fBctx\fP, const char *directory)"
.br
.ti -1c
.RI "int \fBLP_find_file_end\fP (\fBLP_DIR_CTX\fP **\fBctx\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LP_ENTRY_SIZE   255"

.PP
Definition at line 62 of file LPdir_unix\&.c\&.
.SH "Function Documentation"
.PP 
.SS "const char* LP_find_file (\fBLP_DIR_CTX\fP ** ctx, const char * directory)"

.PP
Definition at line 70 of file LPdir_unix\&.c\&.
.SS "int LP_find_file_end (\fBLP_DIR_CTX\fP ** ctx)"

.PP
Definition at line 109 of file LPdir_unix\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
