.TH "s2n/libcrypto-build/openssl/crypto/LPdir_nyi.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/LPdir_nyi.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'LPdir\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBLP_dir_context_st\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBLP_find_file\fP (\fBLP_DIR_CTX\fP **\fBctx\fP, const char *directory)"
.br
.ti -1c
.RI "int \fBLP_find_file_end\fP (\fBLP_DIR_CTX\fP **\fBctx\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* LP_find_file (\fBLP_DIR_CTX\fP ** ctx, const char * directory)"

.PP
Definition at line 37 of file LPdir_nyi\&.c\&.
.SS "int LP_find_file_end (\fBLP_DIR_CTX\fP ** ctx)"

.PP
Definition at line 43 of file LPdir_nyi\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
