.TH "s2n/libcrypto-build/openssl/crypto/mdc2/mdc2dgst.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/mdc2/mdc2dgst.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/des\&.h>\fP
.br
\fC#include <openssl/mdc2\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBc2l\fP(\fBc\fP,  l)            "
.br
.ti -1c
.RI "#define \fBl2c\fP(l,  \fBc\fP)            "
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfips_md_init\fP (\fBMDC2\fP)"
.br
.ti -1c
.RI "int \fBMDC2_Update\fP (\fBMDC2_CTX\fP *\fBc\fP, const unsigned char *\fBin\fP, size_t \fBlen\fP)"
.br
.ti -1c
.RI "int \fBMDC2_Final\fP (unsigned char *md, \fBMDC2_CTX\fP *\fBc\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define c2l(\fBc\fP, l)"
\fBValue:\fP
.PP
.nf
(l =((DES_LONG)(*((c)++)))    , \
                         l|=((DES_LONG)(*((c)++)))<< 8L, \
                         l|=((DES_LONG)(*((c)++)))<<16L, \
                         l|=((DES_LONG)(*((c)++)))<<24L)
.fi
.PP
Definition at line 67 of file mdc2dgst\&.c\&.
.SS "#define l2c(l, \fBc\fP)"
\fBValue:\fP
.PP
.nf
(*((c)++)=(unsigned char)(((l)     )&0xff), \
                        *((c)++)=(unsigned char)(((l)>> 8L)&0xff), \
                        *((c)++)=(unsigned char)(((l)>>16L)&0xff), \
                        *((c)++)=(unsigned char)(((l)>>24L)&0xff))
.fi
.PP
Definition at line 73 of file mdc2dgst\&.c\&.
.SH "Function Documentation"
.PP 
.SS "fips_md_init (\fBMDC2\fP)"

.PP
Definition at line 79 of file mdc2dgst\&.c\&.
.SS "int MDC2_Final (unsigned char * md, \fBMDC2_CTX\fP * c)"

.PP
Definition at line 159 of file mdc2dgst\&.c\&.
.SS "int MDC2_Update (\fBMDC2_CTX\fP * c, const unsigned char * in, size_t len)"

.PP
Definition at line 88 of file mdc2dgst\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
