.TH "s2n/libcrypto-build/openssl/demos/x509/mkreq.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/demos/x509/mkreq.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <openssl/conf\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmkreq\fP (\fBX509_REQ\fP **x509p, \fBEVP_PKEY\fP **pkeyp, int \fBbits\fP, int serial, int days)"
.br
.ti -1c
.RI "int \fBadd_ext\fP (\fBSTACK_OF\fP(\fBX509_EXTENSION\fP)*sk, int \fBnid\fP, char *value)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int add_ext (\fBSTACK_OF\fP(\fBX509_EXTENSION\fP)* sk, int nid, char * value)"

.PP
Definition at line 159 of file mkreq\&.c\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 20 of file mkreq\&.c\&.
.SS "int mkreq (\fBX509_REQ\fP ** x509p, \fBEVP_PKEY\fP ** pkeyp, int bits, int serial, int days)"

.PP
Definition at line 65 of file mkreq\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
