.TH "s2n/libcrypto-build/openssl/crypto/modes/modes_lcl.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/modes/modes_lcl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/modes\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBu128\fP"
.br
.ti -1c
.RI "struct \fBgcm128_context\fP"
.br
.ti -1c
.RI "struct \fBxts128_context\fP"
.br
.ti -1c
.RI "struct \fBccm128_context\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBU64\fP(C)   C##ULL"
.br
.ti -1c
.RI "#define \fBSTRICT_ALIGNMENT\fP   1"
.br
.ti -1c
.RI "#define \fBGETU32\fP(\fBp\fP)             ((\fBu32\fP)(\fBp\fP)[0]<<24|(\fBu32\fP)(\fBp\fP)[1]<<16|(\fBu32\fP)(\fBp\fP)[2]<<8|(\fBu32\fP)(\fBp\fP)[3])"
.br
.ti -1c
.RI "#define \fBPUTU32\fP(\fBp\fP,  v)         ((\fBp\fP)[0]=(\fBu8\fP)((v)>>24),(\fBp\fP)[1]=(\fBu8\fP)((v)>>16),(\fBp\fP)[2]=(\fBu8\fP)((v)>>8),(\fBp\fP)[3]=(\fBu8\fP)(v))"
.br
.ti -1c
.RI "#define \fBTABLE_BITS\fP   4"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef long long \fBi64\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBu64\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBu32\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBu8\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GETU32(\fBp\fP)   ((\fBu32\fP)(\fBp\fP)[0]<<24|(\fBu32\fP)(\fBp\fP)[1]<<16|(\fBu32\fP)(\fBp\fP)[2]<<8|(\fBu32\fP)(\fBp\fP)[3])"

.PP
Definition at line 89 of file modes_lcl\&.h\&.
.SS "#define PUTU32(\fBp\fP, v)   ((\fBp\fP)[0]=(\fBu8\fP)((v)>>24),(\fBp\fP)[1]=(\fBu8\fP)((v)>>16),(\fBp\fP)[2]=(\fBu8\fP)((v)>>8),(\fBp\fP)[3]=(\fBu8\fP)(v))"

.PP
Definition at line 90 of file modes_lcl\&.h\&.
.SS "#define STRICT_ALIGNMENT   1"

.PP
Definition at line 27 of file modes_lcl\&.h\&.
.SS "#define TABLE_BITS   4"

.PP
Definition at line 103 of file modes_lcl\&.h\&.
.SS "#define U64(C)   C##ULL"

.PP
Definition at line 21 of file modes_lcl\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef long long \fBi64\fP"

.PP
Definition at line 19 of file modes_lcl\&.h\&.
.SS "typedef unsigned int \fBu32\fP"

.PP
Definition at line 24 of file modes_lcl\&.h\&.
.SS "typedef unsigned long long \fBu64\fP"

.PP
Definition at line 20 of file modes_lcl\&.h\&.
.SS "typedef unsigned char \fBu8\fP"

.PP
Definition at line 25 of file modes_lcl\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
