.TH "MYBLOB" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MYBLOB \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBpbData\fP"
.br
.ti -1c
.RI "int \fBcbData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file a_set\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int cbData"

.PP
Definition at line 67 of file a_set\&.c\&.
.SS "unsigned char* pbData"

.PP
Definition at line 66 of file a_set\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
