.TH "nistp_test_params" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nistp_test_params \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBEC_METHOD\fP *(* \fBmeth\fP )()"
.br
.ti -1c
.RI "int \fBdegree\fP"
.br
.ti -1c
.RI "const char * \fBp\fP"
.br
.ti -1c
.RI "const char * \fBa\fP"
.br
.ti -1c
.RI "const char * \fBb\fP"
.br
.ti -1c
.RI "const char * \fBQx\fP"
.br
.ti -1c
.RI "const char * \fBQy\fP"
.br
.ti -1c
.RI "const char * \fBGx\fP"
.br
.ti -1c
.RI "const char * \fBGy\fP"
.br
.ti -1c
.RI "const char * \fBorder\fP"
.br
.ti -1c
.RI "const char * \fBd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1589 of file ectest\&.c\&.
.SH "Field Documentation"
.PP 
.SS "const char * a"

.PP
Definition at line 1597 of file ectest\&.c\&.
.SS "const char * b"

.PP
Definition at line 1597 of file ectest\&.c\&.
.SS "const char * d"

.PP
Definition at line 1597 of file ectest\&.c\&.
.SS "int degree"

.PP
Definition at line 1591 of file ectest\&.c\&.
.SS "const char * Gx"

.PP
Definition at line 1597 of file ectest\&.c\&.
.SS "const char * Gy"

.PP
Definition at line 1597 of file ectest\&.c\&.
.SS "const \fBEC_METHOD\fP *(* meth)()"

.PP
Definition at line 1590 of file ectest\&.c\&.
.SS "const char * order"

.PP
Definition at line 1597 of file ectest\&.c\&.
.SS "const char * p"

.PP
Definition at line 1597 of file ectest\&.c\&.
.SS "const char * Qx"

.PP
Definition at line 1597 of file ectest\&.c\&.
.SS "const char * Qy"

.PP
Definition at line 1597 of file ectest\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
