.TH "s2n/libcrypto-build/openssl/crypto/o_dir.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/o_dir.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct OPENSSL_dir_context_st \fBOPENSSL_DIR_CTX\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBOPENSSL_DIR_read\fP (\fBOPENSSL_DIR_CTX\fP **\fBctx\fP, const char *directory)"
.br
.ti -1c
.RI "int \fBOPENSSL_DIR_end\fP (\fBOPENSSL_DIR_CTX\fP **\fBctx\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct OPENSSL_dir_context_st \fBOPENSSL_DIR_CTX\fP"

.PP
Definition at line 41 of file o_dir\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int OPENSSL_DIR_end (\fBOPENSSL_DIR_CTX\fP ** ctx)"

.SS "const char* OPENSSL_DIR_read (\fBOPENSSL_DIR_CTX\fP ** ctx, const char * directory)"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
