.TH "s2n/libcrypto-build/openssl/crypto/objects/obj_xref.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/objects/obj_xref.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include 'obj_xref\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBnid_triple\fP)"
.br
.ti -1c
.RI "\fBDECLARE_OBJ_BSEARCH_CMP_FN\fP (\fBnid_triple\fP, \fBnid_triple\fP, sig)"
.br
.ti -1c
.RI "\fBIMPLEMENT_OBJ_BSEARCH_CMP_FN\fP (\fBnid_triple\fP, \fBnid_triple\fP, sig)"
.br
.ti -1c
.RI "\fBDECLARE_OBJ_BSEARCH_CMP_FN\fP (const \fBnid_triple\fP *, const \fBnid_triple\fP *, sigx)"
.br
.ti -1c
.RI "\fBIMPLEMENT_OBJ_BSEARCH_CMP_FN\fP (const \fBnid_triple\fP *, const \fBnid_triple\fP *, sigx)"
.br
.ti -1c
.RI "int \fBOBJ_find_sigid_algs\fP (int signid, int *pdig_nid, int *ppkey_nid)"
.br
.ti -1c
.RI "int \fBOBJ_find_sigid_by_algs\fP (int *psignid, int dig_nid, int pkey_nid)"
.br
.ti -1c
.RI "int \fBOBJ_add_sigid\fP (int signid, int dig_id, int pkey_id)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOBJ_sigid_free\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DECLARE_OBJ_BSEARCH_CMP_FN (\fBnid_triple\fP, \fBnid_triple\fP, sig)"

.SS "DECLARE_OBJ_BSEARCH_CMP_FN (const \fBnid_triple\fP *, const \fBnid_triple\fP *, sigx)"

.SS "IMPLEMENT_OBJ_BSEARCH_CMP_FN (\fBnid_triple\fP, \fBnid_triple\fP, sig)"

.SS "IMPLEMENT_OBJ_BSEARCH_CMP_FN (const \fBnid_triple\fP *, const \fBnid_triple\fP *, sigx)"

.SS "int OBJ_add_sigid (int signid, int dig_id, int pkey_id)"

.PP
Definition at line 148 of file obj_xref\&.c\&.
.SS "int OBJ_find_sigid_algs (int signid, int * pdig_nid, int * ppkey_nid)"

.PP
Definition at line 92 of file obj_xref\&.c\&.
.SS "int OBJ_find_sigid_by_algs (int * psignid, int dig_nid, int pkey_nid)"

.PP
Definition at line 118 of file obj_xref\&.c\&.
.SS "\fBvoid\fP OBJ_sigid_free (\fBvoid\fP)"

.PP
Definition at line 185 of file obj_xref\&.c\&.
.SS "STACK_OF (\fBnid_triple\fP)"

.PP
Definition at line 64 of file obj_xref\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
