.TH "s2n/libcrypto-build/openssl/crypto/ocsp/ocsp_vfy.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ocsp/ocsp_vfy.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/ocsp\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBOCSP_basic_verify\fP (\fBOCSP_BASICRESP\fP *bs, \fBSTACK_OF\fP(\fBX509\fP)*certs, \fBX509_STORE\fP *st, unsigned long \fBflags\fP)"
.br
.ti -1c
.RI "int \fBOCSP_request_verify\fP (\fBOCSP_REQUEST\fP *req, \fBSTACK_OF\fP(\fBX509\fP)*certs, \fBX509_STORE\fP *store, unsigned long \fBflags\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int OCSP_basic_verify (\fBOCSP_BASICRESP\fP * bs, \fBSTACK_OF\fP(\fBX509\fP)* certs, \fBX509_STORE\fP * st, unsigned long flags)"

.PP
Definition at line 81 of file ocsp_vfy\&.c\&.
.SS "int OCSP_request_verify (\fBOCSP_REQUEST\fP * req, \fBSTACK_OF\fP(\fBX509\fP)* certs, \fBX509_STORE\fP * store, unsigned long flags)"

.PP
Definition at line 370 of file ocsp_vfy\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
