.TH "s2n/libcrypto-build/openssl/crypto/ocsp/ocsp_prn.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ocsp/ocsp_prn.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <openssl/ocsp\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBOCSP_TBLSTR\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBOCSP_response_status_str\fP (long s)"
.br
.ti -1c
.RI "const char * \fBOCSP_cert_status_str\fP (long s)"
.br
.ti -1c
.RI "const char * \fBOCSP_crl_reason_str\fP (long s)"
.br
.ti -1c
.RI "int \fBOCSP_REQUEST_print\fP (\fBBIO\fP *\fBbp\fP, \fBOCSP_REQUEST\fP *o, unsigned long \fBflags\fP)"
.br
.ti -1c
.RI "int \fBOCSP_RESPONSE_print\fP (\fBBIO\fP *\fBbp\fP, \fBOCSP_RESPONSE\fP *o, unsigned long \fBflags\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* OCSP_cert_status_str (long s)"

.PP
Definition at line 115 of file ocsp_prn\&.c\&.
.SS "const char* OCSP_crl_reason_str (long s)"

.PP
Definition at line 125 of file ocsp_prn\&.c\&.
.SS "int OCSP_REQUEST_print (\fBBIO\fP * bp, \fBOCSP_REQUEST\fP * o, unsigned long flags)"

.PP
Definition at line 140 of file ocsp_prn\&.c\&.
.SS "int OCSP_RESPONSE_print (\fBBIO\fP * bp, \fBOCSP_RESPONSE\fP * o, unsigned long flags)"

.PP
Definition at line 185 of file ocsp_prn\&.c\&.
.SS "const char* OCSP_response_status_str (long s)"

.PP
Definition at line 102 of file ocsp_prn\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
