.TH "s2n/libcrypto-build/openssl/crypto/ocsp/ocsp_ext.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ocsp/ocsp_ext.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <cryptlib\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/ocsp\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBOCSP_REQUEST_get_ext_count\fP (\fBOCSP_REQUEST\fP *\fBx\fP)"
.br
.ti -1c
.RI "int \fBOCSP_REQUEST_get_ext_by_NID\fP (\fBOCSP_REQUEST\fP *\fBx\fP, int \fBnid\fP, int lastpos)"
.br
.ti -1c
.RI "int \fBOCSP_REQUEST_get_ext_by_OBJ\fP (\fBOCSP_REQUEST\fP *\fBx\fP, \fBASN1_OBJECT\fP *\fBobj\fP, int lastpos)"
.br
.ti -1c
.RI "int \fBOCSP_REQUEST_get_ext_by_critical\fP (\fBOCSP_REQUEST\fP *\fBx\fP, int crit, int lastpos)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_REQUEST_get_ext\fP (\fBOCSP_REQUEST\fP *\fBx\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_REQUEST_delete_ext\fP (\fBOCSP_REQUEST\fP *\fBx\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBOCSP_REQUEST_get1_ext_d2i\fP (\fBOCSP_REQUEST\fP *\fBx\fP, int \fBnid\fP, int *crit, int *idx)"
.br
.ti -1c
.RI "int \fBOCSP_REQUEST_add1_ext_i2d\fP (\fBOCSP_REQUEST\fP *\fBx\fP, int \fBnid\fP, \fBvoid\fP *value, int crit, unsigned long \fBflags\fP)"
.br
.ti -1c
.RI "int \fBOCSP_REQUEST_add_ext\fP (\fBOCSP_REQUEST\fP *\fBx\fP, \fBX509_EXTENSION\fP *\fBex\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "int \fBOCSP_ONEREQ_get_ext_count\fP (\fBOCSP_ONEREQ\fP *\fBx\fP)"
.br
.ti -1c
.RI "int \fBOCSP_ONEREQ_get_ext_by_NID\fP (\fBOCSP_ONEREQ\fP *\fBx\fP, int \fBnid\fP, int lastpos)"
.br
.ti -1c
.RI "int \fBOCSP_ONEREQ_get_ext_by_OBJ\fP (\fBOCSP_ONEREQ\fP *\fBx\fP, \fBASN1_OBJECT\fP *\fBobj\fP, int lastpos)"
.br
.ti -1c
.RI "int \fBOCSP_ONEREQ_get_ext_by_critical\fP (\fBOCSP_ONEREQ\fP *\fBx\fP, int crit, int lastpos)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_ONEREQ_get_ext\fP (\fBOCSP_ONEREQ\fP *\fBx\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_ONEREQ_delete_ext\fP (\fBOCSP_ONEREQ\fP *\fBx\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBOCSP_ONEREQ_get1_ext_d2i\fP (\fBOCSP_ONEREQ\fP *\fBx\fP, int \fBnid\fP, int *crit, int *idx)"
.br
.ti -1c
.RI "int \fBOCSP_ONEREQ_add1_ext_i2d\fP (\fBOCSP_ONEREQ\fP *\fBx\fP, int \fBnid\fP, \fBvoid\fP *value, int crit, unsigned long \fBflags\fP)"
.br
.ti -1c
.RI "int \fBOCSP_ONEREQ_add_ext\fP (\fBOCSP_ONEREQ\fP *\fBx\fP, \fBX509_EXTENSION\fP *\fBex\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "int \fBOCSP_BASICRESP_get_ext_count\fP (\fBOCSP_BASICRESP\fP *\fBx\fP)"
.br
.ti -1c
.RI "int \fBOCSP_BASICRESP_get_ext_by_NID\fP (\fBOCSP_BASICRESP\fP *\fBx\fP, int \fBnid\fP, int lastpos)"
.br
.ti -1c
.RI "int \fBOCSP_BASICRESP_get_ext_by_OBJ\fP (\fBOCSP_BASICRESP\fP *\fBx\fP, \fBASN1_OBJECT\fP *\fBobj\fP, int lastpos)"
.br
.ti -1c
.RI "int \fBOCSP_BASICRESP_get_ext_by_critical\fP (\fBOCSP_BASICRESP\fP *\fBx\fP, int crit, int lastpos)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_BASICRESP_get_ext\fP (\fBOCSP_BASICRESP\fP *\fBx\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_BASICRESP_delete_ext\fP (\fBOCSP_BASICRESP\fP *\fBx\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBOCSP_BASICRESP_get1_ext_d2i\fP (\fBOCSP_BASICRESP\fP *\fBx\fP, int \fBnid\fP, int *crit, int *idx)"
.br
.ti -1c
.RI "int \fBOCSP_BASICRESP_add1_ext_i2d\fP (\fBOCSP_BASICRESP\fP *\fBx\fP, int \fBnid\fP, \fBvoid\fP *value, int crit, unsigned long \fBflags\fP)"
.br
.ti -1c
.RI "int \fBOCSP_BASICRESP_add_ext\fP (\fBOCSP_BASICRESP\fP *\fBx\fP, \fBX509_EXTENSION\fP *\fBex\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "int \fBOCSP_SINGLERESP_get_ext_count\fP (\fBOCSP_SINGLERESP\fP *\fBx\fP)"
.br
.ti -1c
.RI "int \fBOCSP_SINGLERESP_get_ext_by_NID\fP (\fBOCSP_SINGLERESP\fP *\fBx\fP, int \fBnid\fP, int lastpos)"
.br
.ti -1c
.RI "int \fBOCSP_SINGLERESP_get_ext_by_OBJ\fP (\fBOCSP_SINGLERESP\fP *\fBx\fP, \fBASN1_OBJECT\fP *\fBobj\fP, int lastpos)"
.br
.ti -1c
.RI "int \fBOCSP_SINGLERESP_get_ext_by_critical\fP (\fBOCSP_SINGLERESP\fP *\fBx\fP, int crit, int lastpos)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_SINGLERESP_get_ext\fP (\fBOCSP_SINGLERESP\fP *\fBx\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_SINGLERESP_delete_ext\fP (\fBOCSP_SINGLERESP\fP *\fBx\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBOCSP_SINGLERESP_get1_ext_d2i\fP (\fBOCSP_SINGLERESP\fP *\fBx\fP, int \fBnid\fP, int *crit, int *idx)"
.br
.ti -1c
.RI "int \fBOCSP_SINGLERESP_add1_ext_i2d\fP (\fBOCSP_SINGLERESP\fP *\fBx\fP, int \fBnid\fP, \fBvoid\fP *value, int crit, unsigned long \fBflags\fP)"
.br
.ti -1c
.RI "int \fBOCSP_SINGLERESP_add_ext\fP (\fBOCSP_SINGLERESP\fP *\fBx\fP, \fBX509_EXTENSION\fP *\fBex\fP, int \fBloc\fP)"
.br
.ti -1c
.RI "int \fBOCSP_request_add1_nonce\fP (\fBOCSP_REQUEST\fP *req, unsigned char *val, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBOCSP_basic_add1_nonce\fP (\fBOCSP_BASICRESP\fP *resp, unsigned char *val, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBOCSP_check_nonce\fP (\fBOCSP_REQUEST\fP *req, \fBOCSP_BASICRESP\fP *bs)"
.br
.ti -1c
.RI "int \fBOCSP_copy_nonce\fP (\fBOCSP_BASICRESP\fP *resp, \fBOCSP_REQUEST\fP *req)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_crlID_new\fP (char *url, long *n, char *tim)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_accept_responses_new\fP (char **oids)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_archive_cutoff_new\fP (char *tim)"
.br
.ti -1c
.RI "\fBX509_EXTENSION\fP * \fBOCSP_url_svcloc_new\fP (\fBX509_NAME\fP *issuer, char **urls)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBX509_EXTENSION\fP* OCSP_accept_responses_new (char ** oids)"

.PP
Definition at line 488 of file ocsp_ext\&.c\&.
.SS "\fBX509_EXTENSION\fP* OCSP_archive_cutoff_new (char * tim)"

.PP
Definition at line 510 of file ocsp_ext\&.c\&.
.SS "int OCSP_basic_add1_nonce (\fBOCSP_BASICRESP\fP * resp, unsigned char * val, int len)"

.PP
Definition at line 385 of file ocsp_ext\&.c\&.
.SS "int OCSP_BASICRESP_add1_ext_i2d (\fBOCSP_BASICRESP\fP * x, int nid, \fBvoid\fP * value, int crit, unsigned long flags)"

.PP
Definition at line 225 of file ocsp_ext\&.c\&.
.SS "int OCSP_BASICRESP_add_ext (\fBOCSP_BASICRESP\fP * x, \fBX509_EXTENSION\fP * ex, int loc)"

.PP
Definition at line 232 of file ocsp_ext\&.c\&.
.SS "\fBX509_EXTENSION\fP* OCSP_BASICRESP_delete_ext (\fBOCSP_BASICRESP\fP * x, int loc)"

.PP
Definition at line 213 of file ocsp_ext\&.c\&.
.SS "\fBvoid\fP* OCSP_BASICRESP_get1_ext_d2i (\fBOCSP_BASICRESP\fP * x, int nid, int * crit, int * idx)"

.PP
Definition at line 218 of file ocsp_ext\&.c\&.
.SS "\fBX509_EXTENSION\fP* OCSP_BASICRESP_get_ext (\fBOCSP_BASICRESP\fP * x, int loc)"

.PP
Definition at line 208 of file ocsp_ext\&.c\&.
.SS "int OCSP_BASICRESP_get_ext_by_critical (\fBOCSP_BASICRESP\fP * x, int crit, int lastpos)"

.PP
Definition at line 201 of file ocsp_ext\&.c\&.
.SS "int OCSP_BASICRESP_get_ext_by_NID (\fBOCSP_BASICRESP\fP * x, int nid, int lastpos)"

.PP
Definition at line 188 of file ocsp_ext\&.c\&.
.SS "int OCSP_BASICRESP_get_ext_by_OBJ (\fBOCSP_BASICRESP\fP * x, \fBASN1_OBJECT\fP * obj, int lastpos)"

.PP
Definition at line 194 of file ocsp_ext\&.c\&.
.SS "int OCSP_BASICRESP_get_ext_count (\fBOCSP_BASICRESP\fP * x)"

.PP
Definition at line 183 of file ocsp_ext\&.c\&.
.SS "int OCSP_check_nonce (\fBOCSP_REQUEST\fP * req, \fBOCSP_BASICRESP\fP * bs)"

.PP
Definition at line 405 of file ocsp_ext\&.c\&.
.SS "int OCSP_copy_nonce (\fBOCSP_BASICRESP\fP * resp, \fBOCSP_REQUEST\fP * req)"

.PP
Definition at line 442 of file ocsp_ext\&.c\&.
.SS "\fBX509_EXTENSION\fP* OCSP_crlID_new (char * url, long * n, char * tim)"

.PP
Definition at line 455 of file ocsp_ext\&.c\&.
.SS "int OCSP_ONEREQ_add1_ext_i2d (\fBOCSP_ONEREQ\fP * x, int nid, \fBvoid\fP * value, int crit, unsigned long flags)"

.PP
Definition at line 169 of file ocsp_ext\&.c\&.
.SS "int OCSP_ONEREQ_add_ext (\fBOCSP_ONEREQ\fP * x, \fBX509_EXTENSION\fP * ex, int loc)"

.PP
Definition at line 176 of file ocsp_ext\&.c\&.
.SS "\fBX509_EXTENSION\fP* OCSP_ONEREQ_delete_ext (\fBOCSP_ONEREQ\fP * x, int loc)"

.PP
Definition at line 159 of file ocsp_ext\&.c\&.
.SS "\fBvoid\fP* OCSP_ONEREQ_get1_ext_d2i (\fBOCSP_ONEREQ\fP * x, int nid, int * crit, int * idx)"

.PP
Definition at line 164 of file ocsp_ext\&.c\&.
.SS "\fBX509_EXTENSION\fP* OCSP_ONEREQ_get_ext (\fBOCSP_ONEREQ\fP * x, int loc)"

.PP
Definition at line 154 of file ocsp_ext\&.c\&.
.SS "int OCSP_ONEREQ_get_ext_by_critical (\fBOCSP_ONEREQ\fP * x, int crit, int lastpos)"

.PP
Definition at line 148 of file ocsp_ext\&.c\&.
.SS "int OCSP_ONEREQ_get_ext_by_NID (\fBOCSP_ONEREQ\fP * x, int nid, int lastpos)"

.PP
Definition at line 138 of file ocsp_ext\&.c\&.
.SS "int OCSP_ONEREQ_get_ext_by_OBJ (\fBOCSP_ONEREQ\fP * x, \fBASN1_OBJECT\fP * obj, int lastpos)"

.PP
Definition at line 143 of file ocsp_ext\&.c\&.
.SS "int OCSP_ONEREQ_get_ext_count (\fBOCSP_ONEREQ\fP * x)"

.PP
Definition at line 133 of file ocsp_ext\&.c\&.
.SS "int OCSP_REQUEST_add1_ext_i2d (\fBOCSP_REQUEST\fP * x, int nid, \fBvoid\fP * value, int crit, unsigned long flags)"

.PP
Definition at line 118 of file ocsp_ext\&.c\&.
.SS "int OCSP_request_add1_nonce (\fBOCSP_REQUEST\fP * req, unsigned char * val, int len)"

.PP
Definition at line 378 of file ocsp_ext\&.c\&.
.SS "int OCSP_REQUEST_add_ext (\fBOCSP_REQUEST\fP * x, \fBX509_EXTENSION\fP * ex, int loc)"

.PP
Definition at line 125 of file ocsp_ext\&.c\&.
.SS "\fBX509_EXTENSION\fP* OCSP_REQUEST_delete_ext (\fBOCSP_REQUEST\fP * x, int loc)"

.PP
Definition at line 108 of file ocsp_ext\&.c\&.
.SS "\fBvoid\fP* OCSP_REQUEST_get1_ext_d2i (\fBOCSP_REQUEST\fP * x, int nid, int * crit, int * idx)"

.PP
Definition at line 113 of file ocsp_ext\&.c\&.
.SS "\fBX509_EXTENSION\fP* OCSP_REQUEST_get_ext (\fBOCSP_REQUEST\fP * x, int loc)"

.PP
Definition at line 103 of file ocsp_ext\&.c\&.
.SS "int OCSP_REQUEST_get_ext_by_critical (\fBOCSP_REQUEST\fP * x, int crit, int lastpos)"

.PP
Definition at line 97 of file ocsp_ext\&.c\&.
.SS "int OCSP_REQUEST_get_ext_by_NID (\fBOCSP_REQUEST\fP * x, int nid, int lastpos)"

.PP
Definition at line 84 of file ocsp_ext\&.c\&.
.SS "int OCSP_REQUEST_get_ext_by_OBJ (\fBOCSP_REQUEST\fP * x, \fBASN1_OBJECT\fP * obj, int lastpos)"

.PP
Definition at line 90 of file ocsp_ext\&.c\&.
.SS "int OCSP_REQUEST_get_ext_count (\fBOCSP_REQUEST\fP * x)"

.PP
Definition at line 79 of file ocsp_ext\&.c\&.
.SS "int OCSP_SINGLERESP_add1_ext_i2d (\fBOCSP_SINGLERESP\fP * x, int nid, \fBvoid\fP * value, int crit, unsigned long flags)"

.PP
Definition at line 278 of file ocsp_ext\&.c\&.
.SS "int OCSP_SINGLERESP_add_ext (\fBOCSP_SINGLERESP\fP * x, \fBX509_EXTENSION\fP * ex, int loc)"

.PP
Definition at line 284 of file ocsp_ext\&.c\&.
.SS "\fBX509_EXTENSION\fP* OCSP_SINGLERESP_delete_ext (\fBOCSP_SINGLERESP\fP * x, int loc)"

.PP
Definition at line 267 of file ocsp_ext\&.c\&.
.SS "\fBvoid\fP* OCSP_SINGLERESP_get1_ext_d2i (\fBOCSP_SINGLERESP\fP * x, int nid, int * crit, int * idx)"

.PP
Definition at line 272 of file ocsp_ext\&.c\&.
.SS "\fBX509_EXTENSION\fP* OCSP_SINGLERESP_get_ext (\fBOCSP_SINGLERESP\fP * x, int loc)"

.PP
Definition at line 262 of file ocsp_ext\&.c\&.
.SS "int OCSP_SINGLERESP_get_ext_by_critical (\fBOCSP_SINGLERESP\fP * x, int crit, int lastpos)"

.PP
Definition at line 256 of file ocsp_ext\&.c\&.
.SS "int OCSP_SINGLERESP_get_ext_by_NID (\fBOCSP_SINGLERESP\fP * x, int nid, int lastpos)"

.PP
Definition at line 245 of file ocsp_ext\&.c\&.
.SS "int OCSP_SINGLERESP_get_ext_by_OBJ (\fBOCSP_SINGLERESP\fP * x, \fBASN1_OBJECT\fP * obj, int lastpos)"

.PP
Definition at line 250 of file ocsp_ext\&.c\&.
.SS "int OCSP_SINGLERESP_get_ext_count (\fBOCSP_SINGLERESP\fP * x)"

.PP
Definition at line 240 of file ocsp_ext\&.c\&.
.SS "\fBX509_EXTENSION\fP* OCSP_url_svcloc_new (\fBX509_NAME\fP * issuer, char ** urls)"

.PP
Definition at line 531 of file ocsp_ext\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
