.TH "OCSPResponse" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OCSPResponse \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBASN1_ENUMERATED\fP * \fBresponseStatus\fP"
.br
.ti -1c
.RI "\fBResponseBytes\fP * \fBresponseBytes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 212 of file ocsp\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBResponseBytes\fP* responseBytes"

.PP
Definition at line 214 of file ocsp\&.c\&.
.SS "\fBASN1_ENUMERATED\fP* responseStatus"

.PP
Definition at line 213 of file ocsp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
