.TH "openssl_ssl_test_functions" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
openssl_ssl_test_functions \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ssl_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBp_ssl_init_wbio_buffer\fP )(\fBSSL\fP *s, int push)"
.br
.ti -1c
.RI "int(* \fBp_ssl3_setup_buffers\fP )(\fBSSL\fP *s)"
.br
.ti -1c
.RI "int(* \fBp_tls1_process_heartbeat\fP )(\fBSSL\fP *s)"
.br
.ti -1c
.RI "int(* \fBp_dtls1_process_heartbeat\fP )(\fBSSL\fP *s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1049 of file ssl_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int(* p_dtls1_process_heartbeat) (\fBSSL\fP *s)"

.PP
Definition at line 1053 of file ssl_locl\&.h\&.
.SS "int(* p_ssl3_setup_buffers) (\fBSSL\fP *s)"

.PP
Definition at line 1051 of file ssl_locl\&.h\&.
.SS "int(* p_ssl_init_wbio_buffer) (\fBSSL\fP *s, int push)"

.PP
Definition at line 1050 of file ssl_locl\&.h\&.
.SS "int(* p_tls1_process_heartbeat) (\fBSSL\fP *s)"

.PP
Definition at line 1052 of file ssl_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
