.TH "s2n/libcrypto-build/openssl/apps/openssl.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/apps/openssl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'apps\&.h'\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include <openssl/lhash\&.h>\fP
.br
\fC#include <openssl/conf\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <openssl/ssl\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br
\fC#include 'progs\&.h'\fP
.br
\fC#include 's_apps\&.h'\fP
.br
\fC#include <openssl/err\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOPENSSL_C\fP"
.br
.ti -1c
.RI "#define \fBUSE_SOCKETS\fP"
.br
.ti -1c
.RI "#define \fBARGV\fP   Argv"
.br
.ti -1c
.RI "#define \fBPROG_NAME_SIZE\fP   39"
.br
.ti -1c
.RI "#define \fBLIST_STANDARD_COMMANDS\fP   'list\-standard\-commands'"
.br
.ti -1c
.RI "#define \fBLIST_MESSAGE_DIGEST_COMMANDS\fP   'list\-message\-digest\-commands'"
.br
.ti -1c
.RI "#define \fBLIST_MESSAGE_DIGEST_ALGORITHMS\fP   'list\-message\-digest\-algorithms'"
.br
.ti -1c
.RI "#define \fBLIST_CIPHER_COMMANDS\fP   'list\-cipher\-commands'"
.br
.ti -1c
.RI "#define \fBLIST_CIPHER_ALGORITHMS\fP   'list\-cipher\-algorithms'"
.br
.ti -1c
.RI "#define \fBLIST_PUBLIC_KEY_ALGORITHMS\fP   'list\-public\-\fBkey\fP\-algorithms'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int Argc, char *\fBARGV\fP[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ARGV   Argv"

.PP
Definition at line 215 of file openssl\&.c\&.
.SS "#define LIST_CIPHER_ALGORITHMS   'list\-cipher\-algorithms'"

.PP
Definition at line 451 of file openssl\&.c\&.
.SS "#define LIST_CIPHER_COMMANDS   'list\-cipher\-commands'"

.PP
Definition at line 450 of file openssl\&.c\&.
.SS "#define LIST_MESSAGE_DIGEST_ALGORITHMS   'list\-message\-digest\-algorithms'"

.PP
Definition at line 449 of file openssl\&.c\&.
.SS "#define LIST_MESSAGE_DIGEST_COMMANDS   'list\-message\-digest\-commands'"

.PP
Definition at line 448 of file openssl\&.c\&.
.SS "#define LIST_PUBLIC_KEY_ALGORITHMS   'list\-public\-\fBkey\fP\-algorithms'"

.PP
Definition at line 452 of file openssl\&.c\&.
.SS "#define LIST_STANDARD_COMMANDS   'list\-standard\-commands'"

.PP
Definition at line 447 of file openssl\&.c\&.
.SS "#define OPENSSL_C"
\fBValue:\fP
.PP
.nf
/* tells apps\&.h to use complete
                                 * apps_startup() */
.fi
.PP
Definition at line 115 of file openssl\&.c\&.
.SS "#define PROG_NAME_SIZE   39"

.SS "#define USE_SOCKETS"
\fBValue:\fP
.PP
.nf
/* needed for the _O_BINARY defs in the MS
                                 * world */
.fi
.PP
Definition at line 129 of file openssl\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (int Argc, char * ARGV[])"

.PP
Definition at line 218 of file openssl\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
