.TH "s2n/libcrypto-build/openssl/crypto/pkcs12/p12_attr.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/pkcs12/p12_attr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/pkcs12\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBPKCS12_add_localkeyid\fP (\fBPKCS12_SAFEBAG\fP *bag, unsigned char *name, int namelen)"
.br
.ti -1c
.RI "int \fBPKCS8_add_keyusage\fP (\fBPKCS8_PRIV_KEY_INFO\fP *p8, int \fBusage\fP)"
.br
.ti -1c
.RI "int \fBPKCS12_add_friendlyname_asc\fP (\fBPKCS12_SAFEBAG\fP *bag, const char *name, int namelen)"
.br
.ti -1c
.RI "int \fBPKCS12_add_friendlyname_uni\fP (\fBPKCS12_SAFEBAG\fP *bag, const unsigned char *name, int namelen)"
.br
.ti -1c
.RI "int \fBPKCS12_add_CSPName_asc\fP (\fBPKCS12_SAFEBAG\fP *bag, const char *name, int namelen)"
.br
.ti -1c
.RI "\fBASN1_TYPE\fP * \fBPKCS12_get_attr_gen\fP (\fBSTACK_OF\fP(\fBX509_ATTRIBUTE\fP)*attrs, int attr_nid)"
.br
.ti -1c
.RI "char * \fBPKCS12_get_friendlyname\fP (\fBPKCS12_SAFEBAG\fP *bag)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int PKCS12_add_CSPName_asc (\fBPKCS12_SAFEBAG\fP * bag, const char * name, int namelen)"

.PP
Definition at line 111 of file p12_attr\&.c\&.
.SS "int PKCS12_add_friendlyname_asc (\fBPKCS12_SAFEBAG\fP * bag, const char * name, int namelen)"

.PP
Definition at line 91 of file p12_attr\&.c\&.
.SS "int PKCS12_add_friendlyname_uni (\fBPKCS12_SAFEBAG\fP * bag, const unsigned char * name, int namelen)"

.PP
Definition at line 101 of file p12_attr\&.c\&.
.SS "int PKCS12_add_localkeyid (\fBPKCS12_SAFEBAG\fP * bag, unsigned char * name, int namelen)"

.PP
Definition at line 66 of file p12_attr\&.c\&.
.SS "\fBASN1_TYPE\fP* PKCS12_get_attr_gen (\fBSTACK_OF\fP(\fBX509_ATTRIBUTE\fP)* attrs, int attr_nid)"

.PP
Definition at line 120 of file p12_attr\&.c\&.
.SS "char* PKCS12_get_friendlyname (\fBPKCS12_SAFEBAG\fP * bag)"

.PP
Definition at line 138 of file p12_attr\&.c\&.
.SS "int PKCS8_add_keyusage (\fBPKCS8_PRIV_KEY_INFO\fP * p8, int usage)"

.PP
Definition at line 78 of file p12_attr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
