.TH "s2n/libcrypto-build/openssl/crypto/x509v3/pcy_cache.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/x509v3/pcy_cache.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br
\fC#include 'pcy_int\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBpolicy_cache_free\fP (\fBX509_POLICY_CACHE\fP *cache)"
.br
.ti -1c
.RI "const \fBX509_POLICY_CACHE\fP * \fBpolicy_cache_set\fP (\fBX509\fP *\fBx\fP)"
.br
.ti -1c
.RI "\fBX509_POLICY_DATA\fP * \fBpolicy_cache_find_data\fP (const \fBX509_POLICY_CACHE\fP *cache, const \fBASN1_OBJECT\fP *id)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBX509_POLICY_DATA\fP* policy_cache_find_data (const \fBX509_POLICY_CACHE\fP * cache, const \fBASN1_OBJECT\fP * id)"

.PP
Definition at line 243 of file pcy_cache\&.c\&.
.SS "\fBvoid\fP policy_cache_free (\fBX509_POLICY_CACHE\fP * cache)"

.PP
Definition at line 219 of file pcy_cache\&.c\&.
.SS "const \fBX509_POLICY_CACHE\fP* policy_cache_set (\fBX509\fP * x)"

.PP
Definition at line 230 of file pcy_cache\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
