.TH "s2n/libcrypto-build/openssl/crypto/ppc_arch.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ppc_arch.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPPC_FPU64\fP   (1<<0)"
.br
.ti -1c
.RI "#define \fBPPC_ALTIVEC\fP   (1<<1)"
.br
.ti -1c
.RI "#define \fBPPC_CRYPTO207\fP   (1<<2)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned int \fBOPENSSL_ppccap_P\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PPC_ALTIVEC   (1<<1)"

.PP
Definition at line 7 of file ppc_arch\&.h\&.
.SS "#define PPC_CRYPTO207   (1<<2)"

.PP
Definition at line 8 of file ppc_arch\&.h\&.
.SS "#define PPC_FPU64   (1<<0)"

.PP
Definition at line 6 of file ppc_arch\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "unsigned int OPENSSL_ppccap_P"

.PP
Definition at line 15 of file ppccap\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
