.TH "pw_cb_data" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pw_cb_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <apps\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBvoid\fP * \fBpassword\fP"
.br
.ti -1c
.RI "const char * \fBprompt_info\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 220 of file apps\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const \fBvoid\fP* password"

.PP
Definition at line 221 of file apps\&.h\&.
.SS "const char* prompt_info"

.PP
Definition at line 222 of file apps\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
