.TH "s2n/libcrypto-build/openssl/crypto/des/qud_cksm.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/des/qud_cksm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'des_locl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBQ_B0\fP(\fBa\fP)   (((DES_LONG)(\fBa\fP)))"
.br
.ti -1c
.RI "#define \fBQ_B1\fP(\fBa\fP)   (((DES_LONG)(\fBa\fP))<<8)"
.br
.ti -1c
.RI "#define \fBQ_B2\fP(\fBa\fP)   (((DES_LONG)(\fBa\fP))<<16)"
.br
.ti -1c
.RI "#define \fBQ_B3\fP(\fBa\fP)   (((DES_LONG)(\fBa\fP))<<24)"
.br
.ti -1c
.RI "#define \fBNOISE\fP   ((DES_LONG)83653421L)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "DES_LONG \fBDES_quad_cksum\fP (const unsigned char *input, \fBDES_cblock\fP output[], long \fBlength\fP, int out_count, \fBDES_cblock\fP *\fBseed\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NOISE   ((DES_LONG)83653421L)"

.PP
Definition at line 75 of file qud_cksm\&.c\&.
.SS "#define Q_B0(\fBa\fP)   (((DES_LONG)(\fBa\fP)))"

.PP
Definition at line 68 of file qud_cksm\&.c\&.
.SS "#define Q_B1(\fBa\fP)   (((DES_LONG)(\fBa\fP))<<8)"

.PP
Definition at line 69 of file qud_cksm\&.c\&.
.SS "#define Q_B2(\fBa\fP)   (((DES_LONG)(\fBa\fP))<<16)"

.PP
Definition at line 70 of file qud_cksm\&.c\&.
.SS "#define Q_B3(\fBa\fP)   (((DES_LONG)(\fBa\fP))<<24)"

.PP
Definition at line 71 of file qud_cksm\&.c\&.
.SH "Function Documentation"
.PP 
.SS "DES_LONG DES_quad_cksum (const unsigned char * input, \fBDES_cblock\fP output[], long length, int out_count, \fBDES_cblock\fP * seed)"

.PP
Definition at line 77 of file qud_cksm\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
