.TH "s2n/libcrypto-build/openssl/crypto/rand/rand_lib.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/rand/rand_lib.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBRAND_set_rand_method\fP (const \fBRAND_METHOD\fP *meth)"
.br
.ti -1c
.RI "const \fBRAND_METHOD\fP * \fBRAND_get_rand_method\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBRAND_set_rand_engine\fP (\fBENGINE\fP *engine)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRAND_cleanup\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRAND_seed\fP (const \fBvoid\fP *buf, int \fBnum\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRAND_add\fP (const \fBvoid\fP *buf, int \fBnum\fP, double entropy)"
.br
.ti -1c
.RI "int \fBRAND_bytes\fP (unsigned char *buf, int \fBnum\fP)"
.br
.ti -1c
.RI "int \fBRAND_pseudo_bytes\fP (unsigned char *buf, int \fBnum\fP)"
.br
.ti -1c
.RI "int \fBRAND_status\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP RAND_add (const \fBvoid\fP * buf, int num, double entropy)"

.PP
Definition at line 148 of file rand_lib\&.c\&.
.SS "int RAND_bytes (unsigned char * buf, int num)"

.PP
Definition at line 155 of file rand_lib\&.c\&.
.SS "\fBvoid\fP RAND_cleanup (\fBvoid\fP)"

.PP
Definition at line 133 of file rand_lib\&.c\&.
.SS "const \fBRAND_METHOD\fP* RAND_get_rand_method (\fBvoid\fP)"

.PP
Definition at line 92 of file rand_lib\&.c\&.
.SS "int RAND_pseudo_bytes (unsigned char * buf, int num)"

.PP
Definition at line 163 of file rand_lib\&.c\&.
.SS "\fBvoid\fP RAND_seed (const \fBvoid\fP * buf, int num)"

.PP
Definition at line 141 of file rand_lib\&.c\&.
.SS "int RAND_set_rand_engine (\fBENGINE\fP * engine)"

.PP
Definition at line 114 of file rand_lib\&.c\&.
.SS "int RAND_set_rand_method (const \fBRAND_METHOD\fP * meth)"

.PP
Definition at line 80 of file rand_lib\&.c\&.
.SS "int RAND_status (\fBvoid\fP)"

.PP
Definition at line 171 of file rand_lib\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
