.TH "s2n/libcrypto-build/openssl/crypto/rc4/rc4_skey.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/rc4/rc4_skey.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/rc4\&.h>\fP
.br
\fC#include 'rc4_locl\&.h'\fP
.br
\fC#include <openssl/opensslv\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSK_LOOP\fP(d,  n)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBRC4_options\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBprivate_RC4_set_key\fP (\fBRC4_KEY\fP *\fBkey\fP, int \fBlen\fP, const unsigned char *\fBdata\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBRC4_version\fP [] = 'RC4' OPENSSL_VERSION_PTEXT"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SK_LOOP(d, n)"
\fBValue:\fP
.PP
.nf
{ \
                tmp=d[(n)]; \
                id2 = (data[id1] + tmp + id2) & 0xff; \
                if (++id1 == len) id1=0; \
                d[(n)]=d[id2]; \
                d[id2]=tmp; }
.fi
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP private_RC4_set_key (\fBRC4_KEY\fP * key, int len, const unsigned char * data)"

.PP
Definition at line 89 of file rc4_skey\&.c\&.
.SS "const char* RC4_options (\fBvoid\fP)"

.PP
Definition at line 65 of file rc4_skey\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const char RC4_version[] = 'RC4' OPENSSL_VERSION_PTEXT"

.PP
Definition at line 63 of file rc4_skey\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
