.TH "rc5_key_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rc5_key_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rc5\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBrounds\fP"
.br
.ti -1c
.RI "\fBRC5_32_INT\fP \fBdata\fP [2 *(\fBRC5_16_ROUNDS\fP+1)]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 89 of file rc5\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBRC5_32_INT\fP data[2 *(\fBRC5_16_ROUNDS\fP+1)]"

.PP
Definition at line 92 of file rc5\&.h\&.
.SS "int rounds"

.PP
Definition at line 91 of file rc5\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
