.TH "rfc5114_td" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rfc5114_td \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDH\fP *(* \fBget_param\fP )(\fBvoid\fP)"
.br
.ti -1c
.RI "const unsigned char * \fBxA\fP"
.br
.ti -1c
.RI "size_t \fBxA_len\fP"
.br
.ti -1c
.RI "const unsigned char * \fByA\fP"
.br
.ti -1c
.RI "size_t \fByA_len\fP"
.br
.ti -1c
.RI "const unsigned char * \fBxB\fP"
.br
.ti -1c
.RI "size_t \fBxB_len\fP"
.br
.ti -1c
.RI "const unsigned char * \fByB\fP"
.br
.ti -1c
.RI "size_t \fByB_len\fP"
.br
.ti -1c
.RI "const unsigned char * \fBZ\fP"
.br
.ti -1c
.RI "size_t \fBZ_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 499 of file dhtest\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBDH\fP *(* get_param)(\fBvoid\fP)"

.PP
Definition at line 500 of file dhtest\&.c\&.
.SS "const unsigned char * xA"

.PP
Definition at line 501 of file dhtest\&.c\&.
.SS "size_t xA_len"

.PP
Definition at line 502 of file dhtest\&.c\&.
.SS "const unsigned char * xB"

.PP
Definition at line 505 of file dhtest\&.c\&.
.SS "size_t xB_len"

.PP
Definition at line 506 of file dhtest\&.c\&.
.SS "const unsigned char * yA"

.PP
Definition at line 503 of file dhtest\&.c\&.
.SS "size_t yA_len"

.PP
Definition at line 504 of file dhtest\&.c\&.
.SS "const unsigned char * yB"

.PP
Definition at line 507 of file dhtest\&.c\&.
.SS "size_t yB_len"

.PP
Definition at line 508 of file dhtest\&.c\&.
.SS "const unsigned char * Z"

.PP
Definition at line 509 of file dhtest\&.c\&.
.SS "size_t Z_len"

.PP
Definition at line 510 of file dhtest\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
