.TH "rpc_msg" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rpc_msg \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBchannel\fP"
.br
.ti -1c
.RI "char \fBfunction\fP"
.br
.ti -1c
.RI "unsigned short int \fBlength\fP"
.br
.ti -1c
.RI "char \fBdata\fP [4092]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 83 of file bss_rtcp\&.c\&.
.SH "Field Documentation"
.PP 
.SS "char channel"

.PP
Definition at line 85 of file bss_rtcp\&.c\&.
.SS "char data"

.PP
Definition at line 91 of file bss_rtcp\&.c\&.
.SS "char function"

.PP
Definition at line 87 of file bss_rtcp\&.c\&.
.SS "unsigned short int length"

.PP
Definition at line 89 of file bss_rtcp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
