.TH "rpc_ctx" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rpc_ctx \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfilled\fP"
.br
.ti -1c
.RI "int \fBpos\fP"
.br
.ti -1c
.RI "struct \fBrpc_msg\fP \fBmsg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file bss_rtcp\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int filled"

.PP
Definition at line 96 of file bss_rtcp\&.c\&.
.SS "struct \fBrpc_msg\fP msg"

.PP
Definition at line 97 of file bss_rtcp\&.c\&.
.SS "int pos"

.PP
Definition at line 96 of file bss_rtcp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
