.TH "s2n/libcrypto-build/openssl/demos/engines/rsaref/rsaref.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/demos/engines/rsaref/rsaref.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include '\&./source/global\&.h'\fP
.br
\fC#include '\&./source/rsaref\&.h'\fP
.br
\fC#include '\&./source/rsa\&.h'\fP
.br
\fC#include '\&./source/des\&.h'\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br
\fC#include 'rsaref_err\&.c'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOPENSSL_NO_MD2\fP"
.br
.ti -1c
.RI "#define \fBOPENSSL_NO_MD5\fP"
.br
.ti -1c
.RI "#define \fBRSAREF_LIB_NAME\fP   'rsaref engine'"
.br
.ti -1c
.RI "#define \fBdata\fP(\fBctx\fP)   ((DES_CBC_CTX *)(\fBctx\fP)\->cipher_data)"
.br
.ti -1c
.RI "#define \fBdata\fP(\fBctx\fP)   ((DES3_CBC_CTX *)(\fBctx\fP)\->cipher_data)"
.br
.ti -1c
.RI "#define \fBdata\fP(\fBctx\fP)   ((DESX_CBC_CTX *)(\fBctx\fP)\->cipher_data)"
.br
.ti -1c
.RI "#define \fBdata\fP(\fBctx\fP)   ((\fBMD2_CTX\fP *)(\fBctx\fP)\->md_data)"
.br
.ti -1c
.RI "#define \fBdata\fP(\fBctx\fP)   ((\fBMD5_CTX\fP *)(\fBctx\fP)\->md_data)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBENGINE_load_rsaref\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define data(\fBctx\fP)   ((DES_CBC_CTX *)(\fBctx\fP)\->cipher_data)"

.PP
Definition at line 695 of file rsaref\&.c\&.
.SS "#define data(\fBctx\fP)   ((DES3_CBC_CTX *)(\fBctx\fP)\->cipher_data)"

.PP
Definition at line 695 of file rsaref\&.c\&.
.SS "#define data(\fBctx\fP)   ((DESX_CBC_CTX *)(\fBctx\fP)\->cipher_data)"

.PP
Definition at line 695 of file rsaref\&.c\&.
.SS "#define data(\fBctx\fP)   ((\fBMD2_CTX\fP *)(\fBctx\fP)\->md_data)"

.PP
Definition at line 695 of file rsaref\&.c\&.
.SS "#define data(\fBctx\fP)   ((\fBMD5_CTX\fP *)(\fBctx\fP)\->md_data)"

.PP
Definition at line 695 of file rsaref\&.c\&.
.SS "#define OPENSSL_NO_MD2"

.PP
Definition at line 14 of file rsaref\&.c\&.
.SS "#define OPENSSL_NO_MD5"

.PP
Definition at line 15 of file rsaref\&.c\&.
.SS "#define RSAREF_LIB_NAME   'rsaref engine'"

.PP
Definition at line 20 of file rsaref\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP ENGINE_load_rsaref (\fBvoid\fP)"

.PP
Definition at line 262 of file rsaref\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
