.TH "s2n/libcrypto-build/openssl/ssl/s2_enc.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ssl/s2_enc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ssl_locl\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBssl2_enc_init\fP (\fBSSL\fP *s, int client)"
.br
.ti -1c
.RI "int \fBssl2_enc\fP (\fBSSL\fP *s, int send)"
.br
.ti -1c
.RI "\fBvoid\fP \fBssl2_mac\fP (\fBSSL\fP *s, unsigned char *md, int send)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ssl2_enc (\fBSSL\fP * s, int send)"

.PP
Definition at line 127 of file s2_enc\&.c\&.
.SS "int ssl2_enc_init (\fBSSL\fP * s, int client)"

.PP
Definition at line 63 of file s2_enc\&.c\&.
.SS "\fBvoid\fP ssl2_mac (\fBSSL\fP * s, unsigned char * md, int send)"

.PP
Definition at line 159 of file s2_enc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
