.TH "s2n/libcrypto-build/openssl/ssl/s2_pkt.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ssl/s2_pkt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ssl_locl\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSE_SOCKETS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBssl2_read\fP (\fBSSL\fP *s, \fBvoid\fP *buf, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBssl2_peek\fP (\fBSSL\fP *s, \fBvoid\fP *buf, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBssl2_write\fP (\fBSSL\fP *s, const \fBvoid\fP *_buf, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBssl2_part_read\fP (\fBSSL\fP *s, unsigned long \fBf\fP, int i)"
.br
.ti -1c
.RI "int \fBssl2_do_write\fP (\fBSSL\fP *s)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define USE_SOCKETS"

.PP
Definition at line 116 of file s2_pkt\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int ssl2_do_write (\fBSSL\fP * s)"

.PP
Definition at line 677 of file s2_pkt\&.c\&.
.SS "int ssl2_part_read (\fBSSL\fP * s, unsigned long f, int i)"

.PP
Definition at line 638 of file s2_pkt\&.c\&.
.SS "int ssl2_peek (\fBSSL\fP * s, \fBvoid\fP * buf, int len)"

.PP
Definition at line 305 of file s2_pkt\&.c\&.
.SS "int ssl2_read (\fBSSL\fP * s, \fBvoid\fP * buf, int len)"

.PP
Definition at line 300 of file s2_pkt\&.c\&.
.SS "int ssl2_write (\fBSSL\fP * s, const \fBvoid\fP * _buf, int len)"

.PP
Definition at line 398 of file s2_pkt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
