.TH "s2n/tls/s2n_server_hello.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/tls/s2n_server_hello.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <s2n\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'error/s2n_errno\&.h'\fP
.br
\fC#include 'tls/s2n_cipher_suites\&.h'\fP
.br
\fC#include 'tls/s2n_connection\&.h'\fP
.br
\fC#include 'tls/s2n_alerts\&.h'\fP
.br
\fC#include 'tls/s2n_tls\&.h'\fP
.br
\fC#include 'stuffer/s2n_stuffer\&.h'\fP
.br
\fC#include 'utils/s2n_safety\&.h'\fP
.br
\fC#include 'utils/s2n_random\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBS2N_TLS_COMPRESSION_METHOD_NULL\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBs2n_server_hello_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_hello_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define S2N_TLS_COMPRESSION_METHOD_NULL   0"

.PP
Definition at line 32 of file s2n_server_hello\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int s2n_server_hello_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 34 of file s2n_server_hello\&.c\&.
.SS "int s2n_server_hello_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 104 of file s2n_server_hello\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
