.TH "s2n/stuffer/s2n_stuffer.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/stuffer/s2n_stuffer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'utils/s2n_blob\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs2n_stuffer\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBs2n_stuffer_data_available\fP(s)     ((s)\->write_cursor \- (s)\->read_cursor)"
.br
.ti -1c
.RI "#define \fBs2n_stuffer_space_remaining\fP(s)   ((s)\->blob\&.size \- (s)\->write_cursor)"
.br
.ti -1c
.RI "#define \fBs2n_stuffer_write_char\fP(stuffer,  \fBc\fP)   \fBs2n_stuffer_write_uint8\fP( (stuffer), (uint8_t) (\fBc\fP) )"
.br
.ti -1c
.RI "#define \fBs2n_stuffer_read_char\fP(stuffer,  \fBc\fP)   \fBs2n_stuffer_read_uint8\fP( (stuffer), (uint8_t *) (\fBc\fP) )"
.br
.ti -1c
.RI "#define \fBs2n_stuffer_write_str\fP(stuffer,  \fBc\fP)   \fBs2n_stuffer_write_bytes\fP( (stuffer), (const uint8_t *) (\fBc\fP), strlen((\fBc\fP)) )"
.br
.ti -1c
.RI "#define \fBs2n_stuffer_write_text\fP(stuffer,  \fBc\fP,  n)   \fBs2n_stuffer_write_bytes\fP( (stuffer), (const uint8_t *) (\fBc\fP), (n) )"
.br
.ti -1c
.RI "#define \fBs2n_stuffer_read_text\fP(stuffer,  \fBc\fP,  n)   \fBs2n_stuffer_read_bytes\fP( (stuffer), (uint8_t *) (\fBc\fP), (n) )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBs2n_stuffer_init\fP (struct \fBs2n_stuffer\fP *stuffer, struct \fBs2n_blob\fP *\fBin\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_alloc\fP (struct \fBs2n_stuffer\fP *stuffer, const uint32_t size)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_growable_alloc\fP (struct \fBs2n_stuffer\fP *stuffer, const uint32_t size)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_free\fP (struct \fBs2n_stuffer\fP *stuffer)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_resize\fP (struct \fBs2n_stuffer\fP *stuffer, const uint32_t size)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_reread\fP (struct \fBs2n_stuffer\fP *stuffer)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_rewrite\fP (struct \fBs2n_stuffer\fP *stuffer)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_wipe\fP (struct \fBs2n_stuffer\fP *stuffer)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_wipe_n\fP (struct \fBs2n_stuffer\fP *stuffer, const uint32_t n)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_read\fP (struct \fBs2n_stuffer\fP *stuffer, struct \fBs2n_blob\fP *\fBout\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_erase_and_read\fP (struct \fBs2n_stuffer\fP *stuffer, struct \fBs2n_blob\fP *\fBout\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_write\fP (struct \fBs2n_stuffer\fP *stuffer, const struct \fBs2n_blob\fP *\fBin\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_read_bytes\fP (struct \fBs2n_stuffer\fP *stuffer, uint8_t *\fBout\fP, uint32_t n)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_write_bytes\fP (struct \fBs2n_stuffer\fP *stuffer, const uint8_t *\fBin\fP, const uint32_t n)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_skip_read\fP (struct \fBs2n_stuffer\fP *stuffer, uint32_t n)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_skip_write\fP (struct \fBs2n_stuffer\fP *stuffer, const uint32_t n)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBs2n_stuffer_raw_write\fP (struct \fBs2n_stuffer\fP *stuffer, const uint32_t data_len)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBs2n_stuffer_raw_read\fP (struct \fBs2n_stuffer\fP *stuffer, uint32_t data_len)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_recv_from_fd\fP (struct \fBs2n_stuffer\fP *stuffer, int rfd, uint32_t \fBlen\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_send_to_fd\fP (struct \fBs2n_stuffer\fP *stuffer, int wfd, uint32_t \fBlen\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_read_uint8\fP (struct \fBs2n_stuffer\fP *stuffer, uint8_t *\fBu\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_read_uint16\fP (struct \fBs2n_stuffer\fP *stuffer, uint16_t *\fBu\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_read_uint24\fP (struct \fBs2n_stuffer\fP *stuffer, uint32_t *\fBu\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_read_uint32\fP (struct \fBs2n_stuffer\fP *stuffer, uint32_t *\fBu\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_read_uint64\fP (struct \fBs2n_stuffer\fP *stuffer, uint64_t *\fBu\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_write_uint8\fP (struct \fBs2n_stuffer\fP *stuffer, const uint8_t \fBu\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_write_uint16\fP (struct \fBs2n_stuffer\fP *stuffer, const uint16_t \fBu\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_write_uint24\fP (struct \fBs2n_stuffer\fP *stuffer, const uint32_t \fBu\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_write_uint32\fP (struct \fBs2n_stuffer\fP *stuffer, const uint32_t \fBu\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_write_uint64\fP (struct \fBs2n_stuffer\fP *stuffer, const uint64_t \fBu\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_copy\fP (struct \fBs2n_stuffer\fP *from, struct \fBs2n_stuffer\fP *to, uint32_t \fBlen\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_read_base64\fP (struct \fBs2n_stuffer\fP *stuffer, struct \fBs2n_stuffer\fP *\fBout\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_write_base64\fP (struct \fBs2n_stuffer\fP *stuffer, struct \fBs2n_stuffer\fP *\fBin\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_peek_char\fP (struct \fBs2n_stuffer\fP *stuffer, char *\fBc\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_read_token\fP (struct \fBs2n_stuffer\fP *stuffer, struct \fBs2n_stuffer\fP *token, char delim)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_skip_whitespace\fP (struct \fBs2n_stuffer\fP *stuffer)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_alloc_ro_from_string\fP (struct \fBs2n_stuffer\fP *stuffer, const char *str)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_rsa_private_key_from_pem\fP (struct \fBs2n_stuffer\fP *pem, struct \fBs2n_stuffer\fP *asn1)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_certificate_from_pem\fP (struct \fBs2n_stuffer\fP *pem, struct \fBs2n_stuffer\fP *asn1)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_dhparams_from_pem\fP (struct \fBs2n_stuffer\fP *pem, struct \fBs2n_stuffer\fP *pkcs3)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define s2n_stuffer_data_available(s)   ((s)\->write_cursor \- (s)\->read_cursor)"

.PP
Definition at line 45 of file s2n_stuffer\&.h\&.
.SS "#define s2n_stuffer_read_char(stuffer, \fBc\fP)   \fBs2n_stuffer_read_uint8\fP( (stuffer), (uint8_t *) (\fBc\fP) )"

.PP
Definition at line 100 of file s2n_stuffer\&.h\&.
.SS "#define s2n_stuffer_read_text(stuffer, \fBc\fP, n)   \fBs2n_stuffer_read_bytes\fP( (stuffer), (uint8_t *) (\fBc\fP), (n) )"

.PP
Definition at line 103 of file s2n_stuffer\&.h\&.
.SS "#define s2n_stuffer_space_remaining(s)   ((s)\->blob\&.size \- (s)\->write_cursor)"

.PP
Definition at line 46 of file s2n_stuffer\&.h\&.
.SS "#define s2n_stuffer_write_char(stuffer, \fBc\fP)   \fBs2n_stuffer_write_uint8\fP( (stuffer), (uint8_t) (\fBc\fP) )"

.PP
Definition at line 99 of file s2n_stuffer\&.h\&.
.SS "#define s2n_stuffer_write_str(stuffer, \fBc\fP)   \fBs2n_stuffer_write_bytes\fP( (stuffer), (const uint8_t *) (\fBc\fP), strlen((\fBc\fP)) )"

.PP
Definition at line 101 of file s2n_stuffer\&.h\&.
.SS "#define s2n_stuffer_write_text(stuffer, \fBc\fP, n)   \fBs2n_stuffer_write_bytes\fP( (stuffer), (const uint8_t *) (\fBc\fP), (n) )"

.PP
Definition at line 102 of file s2n_stuffer\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int s2n_stuffer_alloc (struct \fBs2n_stuffer\fP * stuffer, const uint32_t size)"

.PP
Definition at line 43 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_alloc_ro_from_string (struct \fBs2n_stuffer\fP * stuffer, const char * str)"

.PP
Definition at line 74 of file s2n_stuffer_text\&.c\&.
.SS "int s2n_stuffer_certificate_from_pem (struct \fBs2n_stuffer\fP * pem, struct \fBs2n_stuffer\fP * asn1)"

.PP
Definition at line 104 of file s2n_stuffer_pem\&.c\&.
.SS "int s2n_stuffer_copy (struct \fBs2n_stuffer\fP * from, struct \fBs2n_stuffer\fP * to, uint32_t len)"

.PP
Definition at line 329 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_dhparams_from_pem (struct \fBs2n_stuffer\fP * pem, struct \fBs2n_stuffer\fP * pkcs3)"

.PP
Definition at line 109 of file s2n_stuffer_pem\&.c\&.
.SS "int s2n_stuffer_erase_and_read (struct \fBs2n_stuffer\fP * stuffer, struct \fBs2n_blob\fP * out)"

.PP
Definition at line 170 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_free (struct \fBs2n_stuffer\fP * stuffer)"

.PP
Definition at line 63 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_growable_alloc (struct \fBs2n_stuffer\fP * stuffer, const uint32_t size)"

.PP
Definition at line 54 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_init (struct \fBs2n_stuffer\fP * stuffer, struct \fBs2n_blob\fP * in)"

.PP
Definition at line 28 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_peek_char (struct \fBs2n_stuffer\fP * stuffer, char * c)"

.PP
Definition at line 23 of file s2n_stuffer_text\&.c\&.
.SS "\fBvoid\fP* s2n_stuffer_raw_read (struct \fBs2n_stuffer\fP * stuffer, uint32_t data_len)"

.PP
Definition at line 154 of file s2n_stuffer\&.c\&.
.SS "\fBvoid\fP* s2n_stuffer_raw_write (struct \fBs2n_stuffer\fP * stuffer, const uint32_t data_len)"

.PP
Definition at line 217 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_read (struct \fBs2n_stuffer\fP * stuffer, struct \fBs2n_blob\fP * out)"

.PP
Definition at line 163 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_read_base64 (struct \fBs2n_stuffer\fP * stuffer, struct \fBs2n_stuffer\fP * out)"
NOTE: In general, shift before masking\&. This avoids needing to worry about how the signed bit may be handled\&. 
.PP
Definition at line 70 of file s2n_stuffer_base64\&.c\&.
.SS "int s2n_stuffer_read_bytes (struct \fBs2n_stuffer\fP * stuffer, uint8_t * out, uint32_t n)"

.PP
Definition at line 185 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_read_token (struct \fBs2n_stuffer\fP * stuffer, struct \fBs2n_stuffer\fP * token, char delim)"

.PP
Definition at line 52 of file s2n_stuffer_text\&.c\&.
.SS "int s2n_stuffer_read_uint16 (struct \fBs2n_stuffer\fP * stuffer, uint16_t * u)"

.PP
Definition at line 263 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_read_uint24 (struct \fBs2n_stuffer\fP * stuffer, uint32_t * u)"

.PP
Definition at line 284 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_read_uint32 (struct \fBs2n_stuffer\fP * stuffer, uint32_t * u)"

.PP
Definition at line 306 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_read_uint64 (struct \fBs2n_stuffer\fP * stuffer, uint64_t * u)"

.SS "int s2n_stuffer_read_uint8 (struct \fBs2n_stuffer\fP * stuffer, uint8_t * u)"

.PP
Definition at line 249 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_recv_from_fd (struct \fBs2n_stuffer\fP * stuffer, int rfd, uint32_t len)"

.PP
Definition at line 29 of file s2n_stuffer_file\&.c\&.
.SS "int s2n_stuffer_reread (struct \fBs2n_stuffer\fP * stuffer)"

.PP
Definition at line 111 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_resize (struct \fBs2n_stuffer\fP * stuffer, const uint32_t size)"

.PP
Definition at line 80 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_rewrite (struct \fBs2n_stuffer\fP * stuffer)"

.PP
Definition at line 102 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_rsa_private_key_from_pem (struct \fBs2n_stuffer\fP * pem, struct \fBs2n_stuffer\fP * asn1)"

.PP
Definition at line 99 of file s2n_stuffer_pem\&.c\&.
.SS "int s2n_stuffer_send_to_fd (struct \fBs2n_stuffer\fP * stuffer, int wfd, uint32_t len)"

.PP
Definition at line 55 of file s2n_stuffer_file\&.c\&.
.SS "int s2n_stuffer_skip_read (struct \fBs2n_stuffer\fP * stuffer, uint32_t n)"

.PP
Definition at line 144 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_skip_whitespace (struct \fBs2n_stuffer\fP * stuffer)"

.PP
Definition at line 32 of file s2n_stuffer_text\&.c\&.
.SS "int s2n_stuffer_skip_write (struct \fBs2n_stuffer\fP * stuffer, const uint32_t n)"

.PP
Definition at line 197 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_wipe (struct \fBs2n_stuffer\fP * stuffer)"

.PP
Definition at line 138 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_wipe_n (struct \fBs2n_stuffer\fP * stuffer, const uint32_t n)"

.PP
Definition at line 117 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_write (struct \fBs2n_stuffer\fP * stuffer, const struct \fBs2n_blob\fP * in)"

.PP
Definition at line 226 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_write_base64 (struct \fBs2n_stuffer\fP * stuffer, struct \fBs2n_stuffer\fP * in)"

.PP
Definition at line 146 of file s2n_stuffer_base64\&.c\&.
.SS "int s2n_stuffer_write_bytes (struct \fBs2n_stuffer\fP * stuffer, const uint8_t * in, const uint32_t n)"

.PP
Definition at line 231 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_write_uint16 (struct \fBs2n_stuffer\fP * stuffer, const uint16_t u)"

.PP
Definition at line 275 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_write_uint24 (struct \fBs2n_stuffer\fP * stuffer, const uint32_t u)"

.PP
Definition at line 297 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_write_uint32 (struct \fBs2n_stuffer\fP * stuffer, const uint32_t u)"

.PP
Definition at line 320 of file s2n_stuffer\&.c\&.
.SS "int s2n_stuffer_write_uint64 (struct \fBs2n_stuffer\fP * stuffer, const uint64_t u)"

.SS "int s2n_stuffer_write_uint8 (struct \fBs2n_stuffer\fP * stuffer, const uint8_t u)"

.PP
Definition at line 256 of file s2n_stuffer\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
