.TH "s2n/tls/s2n_client_key_exchange.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/tls/s2n_client_key_exchange.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <s2n\&.h>\fP
.br
\fC#include 'error/s2n_errno\&.h'\fP
.br
\fC#include 'tls/s2n_cipher_suites\&.h'\fP
.br
\fC#include 'tls/s2n_connection\&.h'\fP
.br
\fC#include 'stuffer/s2n_stuffer\&.h'\fP
.br
\fC#include 'crypto/s2n_dhe\&.h'\fP
.br
\fC#include 'crypto/s2n_rsa\&.h'\fP
.br
\fC#include 'utils/s2n_safety\&.h'\fP
.br
\fC#include 'utils/s2n_random\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBs2n_client_key_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_client_key_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int s2n_client_key_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 115 of file s2n_client_key_exchange\&.c\&.
.SS "int s2n_client_key_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 203 of file s2n_client_key_exchange\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
