.TH "s2n/bin/s2nc.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/bin/s2nc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <sys/poll\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <s2n\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBusage\fP ()"
.br
.ti -1c
.RI "int \fBecho\fP (struct \fBs2n_connection\fP *conn, int sockfd)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *const *argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int echo (struct \fBs2n_connection\fP * conn, int sockfd)"

.PP
Definition at line 31 of file echo\&.c\&.
.SS "int main (int argc, char *const * argv)"

.PP
Definition at line 55 of file s2nc\&.c\&.
.SS "\fBvoid\fP usage (\fBvoid\fP)"

.PP
Definition at line 33 of file s2nc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
