.TH "s2n/libcrypto-build/openssl/ssl/s3_enc.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ssl/s3_enc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'ssl_locl\&.h'\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/md5\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBssl3_change_cipher_state\fP (\fBSSL\fP *s, int which)"
.br
.ti -1c
.RI "int \fBssl3_setup_key_block\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "\fBvoid\fP \fBssl3_cleanup_key_block\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "int \fBssl3_enc\fP (\fBSSL\fP *s, int send)"
.br
.ti -1c
.RI "\fBvoid\fP \fBssl3_init_finished_mac\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "\fBvoid\fP \fBssl3_free_digest_list\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "\fBvoid\fP \fBssl3_finish_mac\fP (\fBSSL\fP *s, const unsigned char *buf, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBssl3_digest_cached_records\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "int \fBssl3_cert_verify_mac\fP (\fBSSL\fP *s, int md_nid, unsigned char *\fBp\fP)"
.br
.ti -1c
.RI "int \fBssl3_final_finish_mac\fP (\fBSSL\fP *s, const char *sender, int \fBlen\fP, unsigned char *\fBp\fP)"
.br
.ti -1c
.RI "int \fBn_ssl3_mac\fP (\fBSSL\fP *\fBssl\fP, unsigned char *md, int send)"
.br
.ti -1c
.RI "\fBvoid\fP \fBssl3_record_sequence_update\fP (unsigned char *seq)"
.br
.ti -1c
.RI "int \fBssl3_generate_master_secret\fP (\fBSSL\fP *s, unsigned char *\fBout\fP, unsigned char *\fBp\fP, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBssl3_alert_code\fP (int \fBcode\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int n_ssl3_mac (\fBSSL\fP * ssl, unsigned char * md, int send)"

.PP
Definition at line 725 of file s3_enc\&.c\&.
.SS "int ssl3_alert_code (int code)"

.PP
Definition at line 906 of file s3_enc\&.c\&.
.SS "int ssl3_cert_verify_mac (\fBSSL\fP * s, int md_nid, unsigned char * p)"

.PP
Definition at line 646 of file s3_enc\&.c\&.
.SS "int ssl3_change_cipher_state (\fBSSL\fP * s, int which)"

.PP
Definition at line 215 of file s3_enc\&.c\&.
.SS "\fBvoid\fP ssl3_cleanup_key_block (\fBSSL\fP * s)"

.PP
Definition at line 477 of file s3_enc\&.c\&.
.SS "int ssl3_digest_cached_records (\fBSSL\fP * s)"

.PP
Definition at line 598 of file s3_enc\&.c\&.
.SS "int ssl3_enc (\fBSSL\fP * s, int send)"

.PP
Definition at line 497 of file s3_enc\&.c\&.
.SS "int ssl3_final_finish_mac (\fBSSL\fP * s, const char * sender, int len, unsigned char * p)"

.PP
Definition at line 651 of file s3_enc\&.c\&.
.SS "\fBvoid\fP ssl3_finish_mac (\fBSSL\fP * s, const unsigned char * buf, int len)"

.PP
Definition at line 584 of file s3_enc\&.c\&.
.SS "\fBvoid\fP ssl3_free_digest_list (\fBSSL\fP * s)"

.PP
Definition at line 571 of file s3_enc\&.c\&.
.SS "int ssl3_generate_master_secret (\fBSSL\fP * s, unsigned char * out, unsigned char * p, int len)"

.PP
Definition at line 840 of file s3_enc\&.c\&.
.SS "\fBvoid\fP ssl3_init_finished_mac (\fBSSL\fP * s)"

.PP
Definition at line 561 of file s3_enc\&.c\&.
.SS "\fBvoid\fP ssl3_record_sequence_update (unsigned char * seq)"

.PP
Definition at line 829 of file s3_enc\&.c\&.
.SS "int ssl3_setup_key_block (\fBSSL\fP * s)"

.PP
Definition at line 410 of file s3_enc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
