.TH "s2n/libcrypto-build/openssl/apps/s_socket.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/apps/s_socket.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include '\&.\&./e_os2\&.h'\fP
.br
\fC#include 'apps\&.h'\fP
.br
\fC#include 's_apps\&.h'\fP
.br
\fC#include <openssl/ssl\&.h>\fP
.br
\fC#include '\&.\&./e_os\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBghbn_cache_st\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSE_SOCKETS\fP"
.br
.ti -1c
.RI "#define \fBNON_MAIN\fP"
.br
.ti -1c
.RI "#define \fBSOCKET_PROTOCOL\fP   IPPROTO_TCP"
.br
.ti -1c
.RI "#define \fBGHBN_NUM\fP   4"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBinit_client\fP (int *sock, char *host, int port, int \fBtype\fP)"
.br
.ti -1c
.RI "int \fBdo_server\fP (int port, int \fBtype\fP, int *ret, int(*\fBcb\fP)(char *hostname, int s, int stype,                                                                                           unsigned char *context), unsigned char *context, int naccept)"
.br
.ti -1c
.RI "int \fBextract_host_port\fP (char *str, char **host_ptr, unsigned char *ip, short *port_ptr)"
.br
.ti -1c
.RI "int \fBextract_port\fP (char *str, short *port_ptr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define GHBN_NUM   4"

.PP
Definition at line 566 of file s_socket\&.c\&.
.SS "#define NON_MAIN"

.PP
Definition at line 85 of file s_socket\&.c\&.
.SS "#define SOCKET_PROTOCOL   IPPROTO_TCP"

.PP
Definition at line 118 of file s_socket\&.c\&.
.SS "#define USE_SOCKETS"

.PP
Definition at line 84 of file s_socket\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int do_server (int port, int type, int * ret, int(*)(char *hostname, int s, int stype,                                                                                           unsigned char *context) cb, unsigned char * context, int naccept)"

.PP
Definition at line 292 of file s_socket\&.c\&.
.SS "int extract_host_port (char * str, char ** host_ptr, unsigned char * ip, short * port_ptr)"

.PP
Definition at line 480 of file s_socket\&.c\&.
.SS "int extract_port (char * str, short * port_ptr)"

.PP
Definition at line 547 of file s_socket\&.c\&.
.SS "int init_client (int * sock, char * host, int port, int type)"

.PP
Definition at line 234 of file s_socket\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
