.TH "SCT_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SCT_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBsct\fP"
.br
.ti -1c
.RI "unsigned short \fBsctlen\fP"
.br
.ti -1c
.RI "unsigned char \fBversion\fP"
.br
.ti -1c
.RI "unsigned char * \fBlogid\fP"
.br
.ti -1c
.RI "unsigned short \fBlogidlen\fP"
.br
.ti -1c
.RI "\fBSCT_TIMESTAMP\fP \fBtimestamp\fP"
.br
.ti -1c
.RI "unsigned char * \fBext\fP"
.br
.ti -1c
.RI "unsigned short \fBextlen\fP"
.br
.ti -1c
.RI "unsigned char \fBhash_alg\fP"
.br
.ti -1c
.RI "unsigned char \fBsig_alg\fP"
.br
.ti -1c
.RI "unsigned char * \fBsig\fP"
.br
.ti -1c
.RI "unsigned short \fBsiglen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 91 of file v3_scts\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char* \fBext\fP"

.PP
Definition at line 103 of file v3_scts\&.c\&.
.SS "unsigned short extlen"

.PP
Definition at line 104 of file v3_scts\&.c\&.
.SS "unsigned char hash_alg"

.PP
Definition at line 105 of file v3_scts\&.c\&.
.SS "unsigned char* logid"

.PP
Definition at line 100 of file v3_scts\&.c\&.
.SS "unsigned short logidlen"

.PP
Definition at line 101 of file v3_scts\&.c\&.
.SS "unsigned char* sct"

.PP
Definition at line 93 of file v3_scts\&.c\&.
.SS "unsigned short sctlen"

.PP
Definition at line 94 of file v3_scts\&.c\&.
.SS "unsigned char* sig"

.PP
Definition at line 107 of file v3_scts\&.c\&.
.SS "unsigned char sig_alg"

.PP
Definition at line 106 of file v3_scts\&.c\&.
.SS "unsigned short siglen"

.PP
Definition at line 108 of file v3_scts\&.c\&.
.SS "\fBSCT_TIMESTAMP\fP timestamp"

.PP
Definition at line 102 of file v3_scts\&.c\&.
.SS "unsigned char version"

.PP
Definition at line 99 of file v3_scts\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
