.TH "set_name_fn" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
set_name_fn \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBfn\fP )(\fBX509\fP *, const char *)"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int \fBhost\fP"
.br
.ti -1c
.RI "int \fBemail\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 214 of file v3nametest\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int email"

.PP
Definition at line 218 of file v3nametest\&.c\&.
.SS "int(* fn)(\fBX509\fP *, const char *)"

.PP
Definition at line 215 of file v3nametest\&.c\&.
.SS "int host"

.PP
Definition at line 217 of file v3nametest\&.c\&.
.SS "const char * name"

.PP
Definition at line 216 of file v3nametest\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
