.TH "s2n/libcrypto-build/openssl/bugs/sgiccbug.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/bugs/sgiccbug.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.ti -1c
.RI "int \fBsub\fP (unsigned long *r, unsigned long *\fBa\fP, unsigned long *\fBb\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "main (\fBvoid\fP)"

.PP
Definition at line 28 of file sgiccbug\&.c\&.
.SS "int sub (unsigned long * r, unsigned long * a, unsigned long * b)"

.PP
Definition at line 38 of file sgiccbug\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
