.TH "Signature" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Signature \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBX509_ALGOR\fP * \fBsignatureAlgorithm\fP"
.br
.ti -1c
.RI "\fBASN1_BIT_STRING\fP * \fBsignature\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 182 of file ocsp\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBASN1_BIT_STRING\fP* signature"

.PP
Definition at line 184 of file ocsp\&.c\&.
.SS "\fBX509_ALGOR\fP* signatureAlgorithm"

.PP
Definition at line 183 of file ocsp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
