.TH "simple_ssl_session_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simple_ssl_session_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBid\fP"
.br
.ti -1c
.RI "unsigned int \fBidlen\fP"
.br
.ti -1c
.RI "unsigned char * \fBder\fP"
.br
.ti -1c
.RI "int \fBderlen\fP"
.br
.ti -1c
.RI "struct \fBsimple_ssl_session_st\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3394 of file s_server\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char* der"

.PP
Definition at line 3397 of file s_server\&.c\&.
.SS "int derlen"

.PP
Definition at line 3398 of file s_server\&.c\&.
.SS "unsigned char* id"

.PP
Definition at line 3395 of file s_server\&.c\&.
.SS "unsigned int idlen"

.PP
Definition at line 3396 of file s_server\&.c\&.
.SS "struct \fBsimple_ssl_session_st\fP* next"

.PP
Definition at line 3399 of file s_server\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
