.TH "s2n/libcrypto-build/openssl/apps/srp.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/apps/srp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/opensslconf\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/conf\&.h>\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <openssl/txt_db\&.h>\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/srp\&.h>\fP
.br
\fC#include 'apps\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPROG\fP   \fBsrp_main\fP"
.br
.ti -1c
.RI "#define \fBBASE_SECTION\fP   'srp'"
.br
.ti -1c
.RI "#define \fBCONFIG_FILE\fP   'openssl\&.cnf'"
.br
.ti -1c
.RI "#define \fBENV_RANDFILE\fP   'RANDFILE'"
.br
.ti -1c
.RI "#define \fBENV_DATABASE\fP   'srpvfile'"
.br
.ti -1c
.RI "#define \fBENV_DEFAULT_SRP\fP   'default_srp'"
.br
.ti -1c
.RI "#define \fBVERBOSE\fP   \fBif\fP (\fBverbose\fP)"
.br
.ti -1c
.RI "#define \fBVVERBOSE\fP   \fBif\fP (\fBverbose\fP>1)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBMAIN\fP (int, char **)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BASE_SECTION   'srp'"

.PP
Definition at line 77 of file srp\&.c\&.
.SS "#define CONFIG_FILE   'openssl\&.cnf'"

.PP
Definition at line 78 of file srp\&.c\&.
.SS "#define ENV_DATABASE   'srpvfile'"

.PP
Definition at line 82 of file srp\&.c\&.
.SS "#define ENV_DEFAULT_SRP   'default_srp'"

.PP
Definition at line 83 of file srp\&.c\&.
.SS "#define ENV_RANDFILE   'RANDFILE'"

.PP
Definition at line 80 of file srp\&.c\&.
.SS "#define PROG   \fBsrp_main\fP"

.PP
Definition at line 75 of file srp\&.c\&.
.SS "#define VERBOSE   \fBif\fP (\fBverbose\fP)"

.PP
Definition at line 115 of file srp\&.c\&.
.SS "#define VVERBOSE   \fBif\fP (\fBverbose\fP>1)"

.PP
Definition at line 116 of file srp\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int MAIN (int argc, char ** argv)"

.PP
Definition at line 267 of file srp\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
