.TH "SRP_gN_cache_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRP_gN_cache_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <srp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBb64_bn\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBbn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file srp\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char * b64_bn"

.PP
Definition at line 77 of file srp\&.h\&.
.SS "\fBBIGNUM\fP * bn"

.PP
Definition at line 78 of file srp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
