.TH "s2n/libcrypto-build/openssl/crypto/srp/srp_vfy.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/srp/srp_vfy.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include 'srp_lcl\&.h'\fP
.br
\fC#include <openssl/srp\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include <openssl/txt_db\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSRP_RANDOM_SALT_LEN\fP   20"
.br
.ti -1c
.RI "#define \fBMAX_LEN\fP   2500"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBSRP_user_pwd_free\fP (\fBSRP_user_pwd\fP *user_pwd)"
.br
.ti -1c
.RI "\fBSRP_VBASE\fP * \fBSRP_VBASE_new\fP (char *seed_key)"
.br
.ti -1c
.RI "int \fBSRP_VBASE_free\fP (\fBSRP_VBASE\fP *vb)"
.br
.ti -1c
.RI "int \fBSRP_VBASE_init\fP (\fBSRP_VBASE\fP *vb, char *verifier_file)"
.br
.ti -1c
.RI "\fBSRP_user_pwd\fP * \fBSRP_VBASE_get_by_user\fP (\fBSRP_VBASE\fP *vb, char *username)"
.br
.ti -1c
.RI "\fBSRP_user_pwd\fP * \fBSRP_VBASE_get1_by_user\fP (\fBSRP_VBASE\fP *vb, char *username)"
.br
.ti -1c
.RI "char * \fBSRP_create_verifier\fP (const char *user, const char *\fBpass\fP, char **salt, char **verifier, const char *\fBN\fP, const char *g)"
.br
.ti -1c
.RI "int \fBSRP_create_verifier_BN\fP (const char *user, const char *\fBpass\fP, \fBBIGNUM\fP **salt, \fBBIGNUM\fP **verifier, \fBBIGNUM\fP *\fBN\fP, \fBBIGNUM\fP *g)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX_LEN   2500"

.PP
Definition at line 70 of file srp_vfy\&.c\&.
.SS "#define SRP_RANDOM_SALT_LEN   20"

.PP
Definition at line 69 of file srp_vfy\&.c\&.
.SH "Function Documentation"
.PP 
.SS "char* SRP_create_verifier (const char * user, const char * pass, char ** salt, char ** verifier, const char * N, const char * g)"

.PP
Definition at line 567 of file srp_vfy\&.c\&.
.SS "int SRP_create_verifier_BN (const char * user, const char * pass, \fBBIGNUM\fP ** salt, \fBBIGNUM\fP ** verifier, \fBBIGNUM\fP * N, \fBBIGNUM\fP * g)"

.PP
Definition at line 654 of file srp_vfy\&.c\&.
.SS "\fBvoid\fP SRP_user_pwd_free (\fBSRP_user_pwd\fP * user_pwd)"

.PP
Definition at line 188 of file srp_vfy\&.c\&.
.SS "int SRP_VBASE_free (\fBSRP_VBASE\fP * vb)"

.PP
Definition at line 291 of file srp_vfy\&.c\&.
.SS "\fBSRP_user_pwd\fP* SRP_VBASE_get1_by_user (\fBSRP_VBASE\fP * vb, char * username)"

.PP
Definition at line 520 of file srp_vfy\&.c\&.
.SS "\fBSRP_user_pwd\fP* SRP_VBASE_get_by_user (\fBSRP_VBASE\fP * vb, char * username)"

.PP
Definition at line 511 of file srp_vfy\&.c\&.
.SS "int SRP_VBASE_init (\fBSRP_VBASE\fP * vb, char * verifier_file)"

.PP
Definition at line 376 of file srp_vfy\&.c\&.
.SS "\fBSRP_VBASE\fP* SRP_VBASE_new (char * seed_key)"

.PP
Definition at line 268 of file srp_vfy\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
