.TH "srp_arg_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srp_arg_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBsrppassin\fP"
.br
.ti -1c
.RI "char * \fBsrplogin\fP"
.br
.ti -1c
.RI "int \fBmsg\fP"
.br
.ti -1c
.RI "int \fBdebug\fP"
.br
.ti -1c
.RI "int \fBamp\fP"
.br
.ti -1c
.RI "int \fBstrength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 472 of file s_client\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int amp"

.PP
Definition at line 477 of file s_client\&.c\&.
.SS "int debug"

.PP
Definition at line 476 of file s_client\&.c\&.
.SS "int msg"

.PP
Definition at line 475 of file s_client\&.c\&.
.SS "char* srplogin"

.PP
Definition at line 474 of file s_client\&.c\&.
.SS "char* srppassin"

.PP
Definition at line 473 of file s_client\&.c\&.
.SS "int strength"

.PP
Definition at line 478 of file s_client\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
