.TH "s2n/libcrypto-build/openssl/crypto/srp/srp_grps.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/srp/srp_grps.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKNOWN_GN_NUMBER\fP   sizeof(knowngN) / sizeof(\fBSRP_gN\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define KNOWN_GN_NUMBER   sizeof(knowngN) / sizeof(\fBSRP_gN\fP)"

.PP
Definition at line 526 of file srp_grps\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
