.TH "srpsrvparm_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srpsrvparm_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBlogin\fP"
.br
.ti -1c
.RI "\fBSRP_VBASE\fP * \fBvb\fP"
.br
.ti -1c
.RI "\fBSRP_user_pwd\fP * \fBuser\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 408 of file s_server\&.c\&.
.SH "Field Documentation"
.PP 
.SS "char* login"

.PP
Definition at line 409 of file s_server\&.c\&.
.SS "\fBSRP_user_pwd\fP* user"

.PP
Definition at line 411 of file s_server\&.c\&.
.SS "\fBSRP_VBASE\fP* vb"

.PP
Definition at line 410 of file s_server\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
