.TH "ssl3_comp_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssl3_comp_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ssl_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcomp_id\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBCOMP_METHOD\fP * \fBmethod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 829 of file ssl_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int comp_id"

.PP
Definition at line 830 of file ssl_locl\&.h\&.
.SS "\fBCOMP_METHOD\fP* method"

.PP
Definition at line 833 of file ssl_locl\&.h\&.
.SS "char* name"

.PP
Definition at line 832 of file ssl_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
