.TH "s2n/libcrypto-build/openssl/ssl/ssl_asn1.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ssl/ssl_asn1.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'ssl_locl\&.h'\fP
.br
\fC#include <openssl/asn1_mac\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBssl_session_asn1_st\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLSIZE2\fP   (sizeof(long)*2)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBssl_session_asn1_st\fP \fBSSL_SESSION_ASN1\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBi2d_SSL_SESSION\fP (\fBSSL_SESSION\fP *\fBin\fP, unsigned char **\fBpp\fP)"
.br
.ti -1c
.RI "\fBSSL_SESSION\fP * \fBd2i_SSL_SESSION\fP (\fBSSL_SESSION\fP **\fBa\fP, const unsigned char **\fBpp\fP, long \fBlength\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define LSIZE2   (sizeof(long)*2)"

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBssl_session_asn1_st\fP  \fBSSL_SESSION_ASN1\fP"

.SH "Function Documentation"
.PP 
.SS "\fBSSL_SESSION\fP* d2i_SSL_SESSION (\fBSSL_SESSION\fP ** a, const unsigned char ** pp, long length)"

.PP
Definition at line 381 of file ssl_asn1\&.c\&.
.SS "int i2d_SSL_SESSION (\fBSSL_SESSION\fP * in, unsigned char ** pp)"

.PP
Definition at line 121 of file ssl_asn1\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
