.TH "ssl_comp_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssl_comp_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ssl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBCOMP_METHOD\fP * \fBmethod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 912 of file ssl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int id"

.PP
Definition at line 913 of file ssl\&.h\&.
.SS "\fBCOMP_METHOD\fP * method"

.PP
Definition at line 916 of file ssl\&.h\&.
.SS "const char * name"

.PP
Definition at line 914 of file ssl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
