.TH "s2n/libcrypto-build/openssl/test/sslv2conftest.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/test/sslv2conftest.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/ssl\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTOTAL_NUM_TESTS\fP   2"
.br
.ti -1c
.RI "#define \fBTEST_SSL_CTX\fP   0"
.br
.ti -1c
.RI "#define \fBSSLV2ON\fP   1"
.br
.ti -1c
.RI "#define \fBSSLV2OFF\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSSL_CONF_CTX\fP * \fBconfctx\fP"
.br
.ti -1c
.RI "\fBSSL_CTX\fP * \fBctx\fP"
.br
.ti -1c
.RI "\fBSSL\fP * \fBssl\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SSLV2OFF   0"

.PP
Definition at line 66 of file sslv2conftest\&.c\&.
.SS "#define SSLV2ON   1"

.PP
Definition at line 65 of file sslv2conftest\&.c\&.
.SS "#define TEST_SSL_CTX   0"

.PP
Definition at line 63 of file sslv2conftest\&.c\&.
.SS "#define TOTAL_NUM_TESTS   2"

.PP
Definition at line 62 of file sslv2conftest\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 83 of file sslv2conftest\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBSSL_CONF_CTX\fP* confctx"

.PP
Definition at line 68 of file sslv2conftest\&.c\&.
.SS "\fBSSL_CTX\fP* ctx"

.PP
Definition at line 69 of file sslv2conftest\&.c\&.
.SS "\fBSSL\fP* ssl"

.PP
Definition at line 70 of file sslv2conftest\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
