.TH "s2n/libcrypto-build/openssl/ssl/t1_enc.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ssl/t1_enc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'ssl_locl\&.h'\fP
.br
\fC#include <openssl/comp\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/hmac\&.h>\fP
.br
\fC#include <openssl/md5\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtls1_change_cipher_state\fP (\fBSSL\fP *s, int which)"
.br
.ti -1c
.RI "int \fBtls1_setup_key_block\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "int \fBtls1_enc\fP (\fBSSL\fP *s, int send)"
.br
.ti -1c
.RI "int \fBtls1_cert_verify_mac\fP (\fBSSL\fP *s, int md_nid, unsigned char *\fBout\fP)"
.br
.ti -1c
.RI "int \fBtls1_final_finish_mac\fP (\fBSSL\fP *s, const char *str, int slen, unsigned char *\fBout\fP)"
.br
.ti -1c
.RI "int \fBtls1_mac\fP (\fBSSL\fP *\fBssl\fP, unsigned char *md, int send)"
.br
.ti -1c
.RI "int \fBtls1_generate_master_secret\fP (\fBSSL\fP *s, unsigned char *\fBout\fP, unsigned char *\fBp\fP, int \fBlen\fP)"
.br
.ti -1c
.RI "int \fBtls1_export_keying_material\fP (\fBSSL\fP *s, unsigned char *\fBout\fP, size_t olen, const char *label, size_t llen, const unsigned char *context, size_t contextlen, int use_context)"
.br
.ti -1c
.RI "int \fBtls1_alert_code\fP (int \fBcode\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int tls1_alert_code (int code)"

.PP
Definition at line 1303 of file t1_enc\&.c\&.
.SS "int tls1_cert_verify_mac (\fBSSL\fP * s, int md_nid, unsigned char * out)"

.PP
Definition at line 920 of file t1_enc\&.c\&.
.SS "int tls1_change_cipher_state (\fBSSL\fP * s, int which)"

.PP
Definition at line 319 of file t1_enc\&.c\&.
.SS "int tls1_enc (\fBSSL\fP * s, int send)"

.PP
Definition at line 750 of file t1_enc\&.c\&.
.SS "int tls1_export_keying_material (\fBSSL\fP * s, unsigned char * out, size_t olen, const char * label, size_t llen, const unsigned char * context, size_t contextlen, int use_context)"

.PP
Definition at line 1204 of file t1_enc\&.c\&.
.SS "int tls1_final_finish_mac (\fBSSL\fP * s, const char * str, int slen, unsigned char * out)"

.PP
Definition at line 950 of file t1_enc\&.c\&.
.SS "int tls1_generate_master_secret (\fBSSL\fP * s, unsigned char * out, unsigned char * p, int len)"

.PP
Definition at line 1134 of file t1_enc\&.c\&.
.SS "int tls1_mac (\fBSSL\fP * ssl, unsigned char * md, int send)"

.PP
Definition at line 1005 of file t1_enc\&.c\&.
.SS "int tls1_setup_key_block (\fBSSL\fP * s)"

.PP
Definition at line 633 of file t1_enc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
