.TH "s2n/libcrypto-build/openssl/ssl/t1_reneg.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ssl/t1_reneg.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include 'ssl_locl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBssl_add_clienthello_renegotiate_ext\fP (\fBSSL\fP *s, unsigned char *\fBp\fP, int *\fBlen\fP, int maxlen)"
.br
.ti -1c
.RI "int \fBssl_parse_clienthello_renegotiate_ext\fP (\fBSSL\fP *s, unsigned char *d, int \fBlen\fP, int *al)"
.br
.ti -1c
.RI "int \fBssl_add_serverhello_renegotiate_ext\fP (\fBSSL\fP *s, unsigned char *\fBp\fP, int *\fBlen\fP, int maxlen)"
.br
.ti -1c
.RI "int \fBssl_parse_serverhello_renegotiate_ext\fP (\fBSSL\fP *s, unsigned char *d, int \fBlen\fP, int *al)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ssl_add_clienthello_renegotiate_ext (\fBSSL\fP * s, unsigned char * p, int * len, int maxlen)"

.PP
Definition at line 116 of file t1_reneg\&.c\&.
.SS "int ssl_add_serverhello_renegotiate_ext (\fBSSL\fP * s, unsigned char * p, int * len, int maxlen)"

.PP
Definition at line 195 of file t1_reneg\&.c\&.
.SS "int ssl_parse_clienthello_renegotiate_ext (\fBSSL\fP * s, unsigned char * d, int len, int * al)"

.PP
Definition at line 146 of file t1_reneg\&.c\&.
.SS "int ssl_parse_serverhello_renegotiate_ext (\fBSSL\fP * s, unsigned char * d, int len, int * al)"

.PP
Definition at line 232 of file t1_reneg\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
