.TH "tagMODULEENTRY32" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagMODULEENTRY32 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tlhelp32\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "DWORD \fBdwSize\fP"
.br
.ti -1c
.RI "DWORD \fBth32ModuleID\fP"
.br
.ti -1c
.RI "DWORD \fBth32ProcessID\fP"
.br
.ti -1c
.RI "DWORD \fBGlblcntUsage\fP"
.br
.ti -1c
.RI "DWORD \fBProccntUsage\fP"
.br
.ti -1c
.RI "BYTE * \fBmodBaseAddr\fP"
.br
.ti -1c
.RI "DWORD \fBmodBaseSize\fP"
.br
.ti -1c
.RI "HMODULE \fBhModule\fP"
.br
.ti -1c
.RI "char \fBszModule\fP [\fBMAX_MODULE_NAME32\fP+1]"
.br
.ti -1c
.RI "char \fBszExePath\fP [MAX_PATH]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file tlhelp32\&.h\&.
.SH "Field Documentation"
.PP 
.SS "DWORD dwSize"

.PP
Definition at line 93 of file tlhelp32\&.h\&.
.SS "DWORD GlblcntUsage"

.PP
Definition at line 96 of file tlhelp32\&.h\&.
.SS "HMODULE hModule"

.PP
Definition at line 100 of file tlhelp32\&.h\&.
.SS "BYTE* modBaseAddr"

.PP
Definition at line 98 of file tlhelp32\&.h\&.
.SS "DWORD modBaseSize"

.PP
Definition at line 99 of file tlhelp32\&.h\&.
.SS "DWORD ProccntUsage"

.PP
Definition at line 97 of file tlhelp32\&.h\&.
.SS "char szExePath[MAX_PATH]"

.PP
Definition at line 102 of file tlhelp32\&.h\&.
.SS "char szModule[\fBMAX_MODULE_NAME32\fP+1]"

.PP
Definition at line 101 of file tlhelp32\&.h\&.
.SS "DWORD th32ModuleID"

.PP
Definition at line 94 of file tlhelp32\&.h\&.
.SS "DWORD th32ProcessID"

.PP
Definition at line 95 of file tlhelp32\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
