.TH "tls_create_ctx_args" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tls_create_ctx_args \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <easy\-tls\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBclient_p\fP"
.br
.ti -1c
.RI "const char * \fBcertificate_file\fP"
.br
.ti -1c
.RI "const char * \fBkey_file\fP"
.br
.ti -1c
.RI "const char * \fBca_file\fP"
.br
.ti -1c
.RI "int \fBverify_depth\fP"
.br
.ti -1c
.RI "int \fBfail_unless_verified\fP"
.br
.ti -1c
.RI "int \fBexport_p\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file easy\-tls\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const char* ca_file"

.PP
Definition at line 34 of file easy\-tls\&.h\&.
.SS "const char* certificate_file"

.PP
Definition at line 32 of file easy\-tls\&.h\&.
.SS "int client_p"

.PP
Definition at line 31 of file easy\-tls\&.h\&.
.SS "int export_p"

.PP
Definition at line 37 of file easy\-tls\&.h\&.
.SS "int fail_unless_verified"

.PP
Definition at line 36 of file easy\-tls\&.h\&.
.SS "const char* key_file"

.PP
Definition at line 33 of file easy\-tls\&.h\&.
.SS "int verify_depth"

.PP
Definition at line 35 of file easy\-tls\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
