.TH "tlsextnextprotoctx_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlsextnextprotoctx_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "unsigned short \fBlen\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "unsigned int \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 592 of file s_client\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char * data"

.PP
Definition at line 593 of file s_client\&.c\&.
.SS "unsigned short len"

.PP
Definition at line 594 of file s_client\&.c\&.
.SS "unsigned int len"

.PP
Definition at line 1015 of file s_server\&.c\&.
.SS "int status"

.PP
Definition at line 595 of file s_client\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
