.TH "s2n/libcrypto-build/openssl/crypto/ts/ts_conf.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ts/ts_conf.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br
\fC#include <openssl/ts\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBASE_SECTION\fP   'tsa'"
.br
.ti -1c
.RI "#define \fBENV_DEFAULT_TSA\fP   'default_tsa'"
.br
.ti -1c
.RI "#define \fBENV_SERIAL\fP   'serial'"
.br
.ti -1c
.RI "#define \fBENV_CRYPTO_DEVICE\fP   'crypto_device'"
.br
.ti -1c
.RI "#define \fBENV_SIGNER_CERT\fP   'signer_cert'"
.br
.ti -1c
.RI "#define \fBENV_CERTS\fP   'certs'"
.br
.ti -1c
.RI "#define \fBENV_SIGNER_KEY\fP   'signer_key'"
.br
.ti -1c
.RI "#define \fBENV_DEFAULT_POLICY\fP   'default_policy'"
.br
.ti -1c
.RI "#define \fBENV_OTHER_POLICIES\fP   'other_policies'"
.br
.ti -1c
.RI "#define \fBENV_DIGESTS\fP   'digests'"
.br
.ti -1c
.RI "#define \fBENV_ACCURACY\fP   'accuracy'"
.br
.ti -1c
.RI "#define \fBENV_ORDERING\fP   'ordering'"
.br
.ti -1c
.RI "#define \fBENV_TSA_NAME\fP   'tsa_name'"
.br
.ti -1c
.RI "#define \fBENV_ESS_CERT_ID_CHAIN\fP   'ess_cert_id_chain'"
.br
.ti -1c
.RI "#define \fBENV_VALUE_SECS\fP   'secs'"
.br
.ti -1c
.RI "#define \fBENV_VALUE_MILLISECS\fP   'millisecs'"
.br
.ti -1c
.RI "#define \fBENV_VALUE_MICROSECS\fP   'microsecs'"
.br
.ti -1c
.RI "#define \fBENV_CLOCK_PRECISION_DIGITS\fP   'clock_precision_digits'"
.br
.ti -1c
.RI "#define \fBENV_VALUE_YES\fP   'yes'"
.br
.ti -1c
.RI "#define \fBENV_VALUE_NO\fP   'no'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBX509\fP * \fBTS_CONF_load_cert\fP (const char *\fBfile\fP)"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509\fP)"
.br
.ti -1c
.RI "\fBEVP_PKEY\fP * \fBTS_CONF_load_key\fP (const char *\fBfile\fP, const char *\fBpass\fP)"
.br
.ti -1c
.RI "const char * \fBTS_CONF_get_tsa_section\fP (\fBCONF\fP *conf, const char *\fBsection\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_serial\fP (\fBCONF\fP *conf, const char *\fBsection\fP, \fBTS_serial_cb\fP \fBcb\fP, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_crypto_device\fP (\fBCONF\fP *conf, const char *\fBsection\fP, const char *device)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_default_engine\fP (const char *name)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_signer_cert\fP (\fBCONF\fP *conf, const char *\fBsection\fP, const char *cert, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_certs\fP (\fBCONF\fP *conf, const char *\fBsection\fP, const char *certs, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_signer_key\fP (\fBCONF\fP *conf, const char *\fBsection\fP, const char *\fBkey\fP, const char *\fBpass\fP, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_def_policy\fP (\fBCONF\fP *conf, const char *\fBsection\fP, const char *policy, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_policies\fP (\fBCONF\fP *conf, const char *\fBsection\fP, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_digests\fP (\fBCONF\fP *conf, const char *\fBsection\fP, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_accuracy\fP (\fBCONF\fP *conf, const char *\fBsection\fP, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_clock_precision_digits\fP (\fBCONF\fP *conf, const char *\fBsection\fP, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_ordering\fP (\fBCONF\fP *conf, const char *\fBsection\fP, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_tsa_name\fP (\fBCONF\fP *conf, const char *\fBsection\fP, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBTS_CONF_set_ess_cert_id_chain\fP (\fBCONF\fP *conf, const char *\fBsection\fP, \fBTS_RESP_CTX\fP *\fBctx\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BASE_SECTION   'tsa'"

.PP
Definition at line 72 of file ts_conf\&.c\&.
.SS "#define ENV_ACCURACY   'accuracy'"

.PP
Definition at line 82 of file ts_conf\&.c\&.
.SS "#define ENV_CERTS   'certs'"

.PP
Definition at line 77 of file ts_conf\&.c\&.
.SS "#define ENV_CLOCK_PRECISION_DIGITS   'clock_precision_digits'"

.PP
Definition at line 89 of file ts_conf\&.c\&.
.SS "#define ENV_CRYPTO_DEVICE   'crypto_device'"

.PP
Definition at line 75 of file ts_conf\&.c\&.
.SS "#define ENV_DEFAULT_POLICY   'default_policy'"

.PP
Definition at line 79 of file ts_conf\&.c\&.
.SS "#define ENV_DEFAULT_TSA   'default_tsa'"

.PP
Definition at line 73 of file ts_conf\&.c\&.
.SS "#define ENV_DIGESTS   'digests'"

.PP
Definition at line 81 of file ts_conf\&.c\&.
.SS "#define ENV_ESS_CERT_ID_CHAIN   'ess_cert_id_chain'"

.PP
Definition at line 85 of file ts_conf\&.c\&.
.SS "#define ENV_ORDERING   'ordering'"

.PP
Definition at line 83 of file ts_conf\&.c\&.
.SS "#define ENV_OTHER_POLICIES   'other_policies'"

.PP
Definition at line 80 of file ts_conf\&.c\&.
.SS "#define ENV_SERIAL   'serial'"

.PP
Definition at line 74 of file ts_conf\&.c\&.
.SS "#define ENV_SIGNER_CERT   'signer_cert'"

.PP
Definition at line 76 of file ts_conf\&.c\&.
.SS "#define ENV_SIGNER_KEY   'signer_key'"

.PP
Definition at line 78 of file ts_conf\&.c\&.
.SS "#define ENV_TSA_NAME   'tsa_name'"

.PP
Definition at line 84 of file ts_conf\&.c\&.
.SS "#define ENV_VALUE_MICROSECS   'microsecs'"

.PP
Definition at line 88 of file ts_conf\&.c\&.
.SS "#define ENV_VALUE_MILLISECS   'millisecs'"

.PP
Definition at line 87 of file ts_conf\&.c\&.
.SS "#define ENV_VALUE_NO   'no'"

.PP
Definition at line 91 of file ts_conf\&.c\&.
.SS "#define ENV_VALUE_SECS   'secs'"

.PP
Definition at line 86 of file ts_conf\&.c\&.
.SS "#define ENV_VALUE_YES   'yes'"

.PP
Definition at line 90 of file ts_conf\&.c\&.
.SH "Function Documentation"
.PP 
.SS "STACK_OF (\fBX509\fP)"

.PP
Definition at line 110 of file ts_conf\&.c\&.
.SS "const char* TS_CONF_get_tsa_section (\fBCONF\fP * conf, const char * section)"

.PP
Definition at line 165 of file ts_conf\&.c\&.
.SS "\fBX509\fP* TS_CONF_load_cert (const char * file)"

.PP
Definition at line 95 of file ts_conf\&.c\&.
.SS "\fBEVP_PKEY\fP* TS_CONF_load_key (const char * file, const char * pass)"

.PP
Definition at line 138 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_accuracy (\fBCONF\fP * conf, const char * section, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 397 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_certs (\fBCONF\fP * conf, const char * section, const char * certs, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 262 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_clock_precision_digits (\fBCONF\fP * conf, const char * section, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 434 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_crypto_device (\fBCONF\fP * conf, const char * section, const char * device)"

.PP
Definition at line 193 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_def_policy (\fBCONF\fP * conf, const char * section, const char * policy, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 306 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_default_engine (const char * name)"

.PP
Definition at line 210 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_digests (\fBCONF\fP * conf, const char * section, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 361 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_ess_cert_id_chain (\fBCONF\fP * conf, const char * section, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 486 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_ordering (\fBCONF\fP * conf, const char * section, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 476 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_policies (\fBCONF\fP * conf, const char * section, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 330 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_serial (\fBCONF\fP * conf, const char * section, \fBTS_serial_cb\fP cb, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 175 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_signer_cert (\fBCONF\fP * conf, const char * section, const char * cert, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 240 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_signer_key (\fBCONF\fP * conf, const char * section, const char * key, const char * pass, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 283 of file ts_conf\&.c\&.
.SS "int TS_CONF_set_tsa_name (\fBCONF\fP * conf, const char * section, \fBTS_RESP_CTX\fP * ctx)"

.PP
Definition at line 481 of file ts_conf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
