.TH "u128" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
u128 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <modes_lcl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu64\fP \fBhi\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBlo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file modes_lcl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBu64\fP hi"

.PP
Definition at line 93 of file modes_lcl\&.h\&.
.SS "\fBu64\fP lo"

.PP
Definition at line 93 of file modes_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
