.TH "s2n/libcrypto-build/openssl/crypto/ui/ui_openssl.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ui/ui_openssl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/e_os2\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'ui_locl\&.h'\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <termios\&.h>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTERMIOS\fP"
.br
.ti -1c
.RI "#define \fBTTY_STRUCT\fP   struct termios"
.br
.ti -1c
.RI "#define \fBTTY_FLAGS\fP   c_lflag"
.br
.ti -1c
.RI "#define \fBTTY_get\fP(tty,  \fBdata\fP)           tcgetattr(tty,\fBdata\fP)"
.br
.ti -1c
.RI "#define \fBTTY_set\fP(tty,  \fBdata\fP)           tcsetattr(tty,TCSANOW,\fBdata\fP)"
.br
.ti -1c
.RI "#define \fBNX509_SIG\fP   32"
.br
.ti -1c
.RI "#define \fBSIZE\fP   4"
.br
.ti -1c
.RI "#define \fBDEV_TTY\fP   '/dev/tty'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUI_METHOD\fP * \fBUI_OpenSSL\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEV_TTY   '/dev/tty'"

.SS "#define NX509_SIG   32"

.PP
Definition at line 279 of file ui_openssl\&.c\&.
.SS "#define SIZE   4"

.SS "#define TERMIOS"

.PP
Definition at line 214 of file ui_openssl\&.c\&.
.SS "#define TTY_FLAGS   c_lflag"

.PP
Definition at line 224 of file ui_openssl\&.c\&.
.SS "#define TTY_get(tty, \fBdata\fP)   tcgetattr(tty,\fBdata\fP)"

.PP
Definition at line 225 of file ui_openssl\&.c\&.
.SS "#define TTY_set(tty, \fBdata\fP)   tcsetattr(tty,TCSANOW,\fBdata\fP)"

.PP
Definition at line 226 of file ui_openssl\&.c\&.
.SS "#define TTY_STRUCT   struct termios"

.PP
Definition at line 223 of file ui_openssl\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBUI_METHOD\fP* UI_OpenSSL (\fBvoid\fP)"

.PP
Definition at line 336 of file ui_openssl\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
