.TH "ui_string_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui_string_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBUI_string_types\fP \fBtype\fP"
.br
.ti -1c
.RI "const char * \fBout_string\fP"
.br
.ti -1c
.RI "int \fBinput_flags\fP"
.br
.ti -1c
.RI "char * \fBresult_buf\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      int \fBresult_minsize\fP"
.br
.ti -1c
.RI "      int \fBresult_maxsize\fP"
.br
.ti -1c
.RI "      const char * \fBtest_buf\fP"
.br
.ti -1c
.RI "   } \fBstring_data\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      const char * \fBaction_desc\fP"
.br
.ti -1c
.RI "      const char * \fBok_chars\fP"
.br
.ti -1c
.RI "      const char * \fBcancel_chars\fP"
.br
.ti -1c
.RI "   } \fBboolean_data\fP"
.br
.ti -1c
.RI "} \fB_\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 101 of file ui_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "union { \&.\&.\&. }   _"

.SS "const char* action_desc"

.PP
Definition at line 123 of file ui_locl\&.h\&.
.SS "struct { \&.\&.\&. }   boolean_data"

.SS "const char* cancel_chars"

.PP
Definition at line 125 of file ui_locl\&.h\&.
.SS "int flags"

.PP
Definition at line 130 of file ui_locl\&.h\&.
.SS "int input_flags"

.PP
Definition at line 104 of file ui_locl\&.h\&.
.SS "const char* ok_chars"

.PP
Definition at line 124 of file ui_locl\&.h\&.
.SS "const char* out_string"

.PP
Definition at line 103 of file ui_locl\&.h\&.
.SS "char* result_buf"

.PP
Definition at line 109 of file ui_locl\&.h\&.
.SS "int result_maxsize"

.PP
Definition at line 118 of file ui_locl\&.h\&.
.SS "int result_minsize"

.PP
Definition at line 116 of file ui_locl\&.h\&.
.SS "struct { \&.\&.\&. }   string_data"

.SS "const char* test_buf"

.PP
Definition at line 120 of file ui_locl\&.h\&.
.SS "enum \fBUI_string_types\fP type"

.PP
Definition at line 102 of file ui_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
