.TH "s2n/libcrypto-build/openssl/bugs/ultrixcc.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/bugs/ultrixcc.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.ti -1c
.RI "int \fBf\fP (int \fBa\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int f (int a)"

.PP
Definition at line 21 of file ultrixcc\&.c\&.
.SS "main (\fBvoid\fP)"

.PP
Definition at line 15 of file ultrixcc\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
