.TH "s2n/libcrypto-build/openssl/crypto/des/times/usparc.cc" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/des/times/usparc.cc \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "solaris usparc SC4 cc fast Xa \fBxO5\fP For the ultra \fBsparc\fP"
.br
.ti -1c
.RI "solaris usparc SC4 cc fast Xa xO5 For the ultra SunC cc fast Xa \fBxO5\fP"
.br
.ti -1c
.RI "solaris usparc SC4 cc fast Xa \fBxO5\fP For the ultra SunC cc fast Xa running des_opts \fBgives\fP \fBa\fP \fBspeed\fP \fBof\fP"
.br
.ti -1c
.RI "solaris usparc SC4 cc fast Xa \fBxO5\fP For the ultra SunC cc fast Xa running des_opts gives \fBa\fP \fBspeed\fP \fBdes\fP s while \fBspeed\fP \fBgives\fP"
.br
.ti -1c
.RI "solaris usparc SC4 cc fast Xa \fBxO5\fP For the ultra SunC cc fast Xa running des_opts \fBgives\fP \fBa\fP speed \fBdes\fP s while speed \fBdes\fP s \fBI\fP believe the difference is tied up \fBin\fP optimisation that the compiler is able to perform when the \fBcode\fP is inlined For \fBspeed\fP"
.br
.ti -1c
.RI "solaris usparc SC4 cc fast Xa \fBxO5\fP For the ultra SunC cc fast Xa running des_opts \fBgives\fP \fBa\fP \fBspeed\fP \fBdes\fP s while \fBspeed\fP \fBdes\fP s \fBI\fP believe the difference is tied up \fBin\fP optimisation that the compiler is able to perform when the \fBcode\fP is inlined For the DES routines are being linked from \fBa\fP library \fBI\fP ll record the higher \fBspeed\fP since \fBif\fP performance is \fBeverything\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "solaris usparc SC4 cc fast Xa \fBxO5\fP For the ultra SunC cc fast Xa running des_opts \fBgives\fP \fBa\fP \fBspeed\fP \fBdes\fP s while \fBspeed\fP \fBdes\fP s \fBI\fP believe the difference is tied up \fBin\fP optimisation that the compiler is able to perform when the \fBcode\fP is inlined For the DES routines are being linked from \fBa\fP library \fBI\fP ll record the higher \fBspeed\fP since \fBif\fP performance is everything"

.PP
Definition at line 3 of file usparc\&.cc\&.
.SS "solaris usparc SC4 cc fast Xa \fBxO5\fP For the ultra SunC cc fast Xa running des_opts gives \fBa\fP \fBspeed\fP \fBdes\fP s while \fBspeed\fP gives"

.PP
Definition at line 3 of file usparc\&.cc\&.
.SS "solaris usparc SC4 cc fast Xa \fBxO5\fP For the ultra SunC cc fast Xa running des_opts \fBgives\fP \fBa\fP \fBspeed\fP of"

.PP
Definition at line 3 of file usparc\&.cc\&.
.SS "solaris usparc SC4 cc fast Xa \fBxO5\fP For the ultra sparc"

.PP
Definition at line 3 of file usparc\&.cc\&.
.SS "solaris usparc SC4 cc fast Xa \fBxO5\fP For the ultra SunC cc fast Xa running des_opts \fBgives\fP \fBa\fP speed \fBdes\fP s while speed \fBdes\fP s \fBI\fP believe the difference is tied up \fBin\fP optimisation that the compiler is able to perform when the \fBcode\fP is inlined For speed"

.PP
Definition at line 3 of file usparc\&.cc\&.
.SS "solaris usparc SC4 cc fast Xa xO5 For the ultra SunC cc fast Xa xO5"

.PP
Definition at line 3 of file usparc\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
