.TH "s2n/libcrypto-build/openssl/crypto/x509v3/v3_alt.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/x509v3/v3_alt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/conf\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCONF_VALUE\fP)"
.br
.ti -1c
.RI "int \fBGENERAL_NAME_print\fP (\fBBIO\fP *\fBout\fP, \fBGENERAL_NAME\fP *\fBgen\fP)"
.br
.ti -1c
.RI "GENERAL_NAMES * \fBv2i_GENERAL_NAMES\fP (const \fBX509V3_EXT_METHOD\fP *method, \fBX509V3_CTX\fP *\fBctx\fP, \fBSTACK_OF\fP(\fBCONF_VALUE\fP)*nval)"
.br
.ti -1c
.RI "\fBGENERAL_NAME\fP * \fBv2i_GENERAL_NAME\fP (const \fBX509V3_EXT_METHOD\fP *method, \fBX509V3_CTX\fP *\fBctx\fP, \fBCONF_VALUE\fP *cnf)"
.br
.ti -1c
.RI "\fBGENERAL_NAME\fP * \fBa2i_GENERAL_NAME\fP (\fBGENERAL_NAME\fP *\fBout\fP, const \fBX509V3_EXT_METHOD\fP *method, \fBX509V3_CTX\fP *\fBctx\fP, int gen_type, char *value, int is_nc)"
.br
.ti -1c
.RI "\fBGENERAL_NAME\fP * \fBv2i_GENERAL_NAME_ex\fP (\fBGENERAL_NAME\fP *\fBout\fP, const \fBX509V3_EXT_METHOD\fP *method, \fBX509V3_CTX\fP *\fBctx\fP, \fBCONF_VALUE\fP *cnf, int is_nc)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBX509V3_EXT_METHOD\fP \fBv3_alt\fP []"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBGENERAL_NAME\fP* a2i_GENERAL_NAME (\fBGENERAL_NAME\fP * out, const \fBX509V3_EXT_METHOD\fP * method, \fBX509V3_CTX\fP * ctx, int gen_type, char * value, int is_nc)"

.PP
Definition at line 428 of file v3_alt\&.c\&.
.SS "int GENERAL_NAME_print (\fBBIO\fP * out, \fBGENERAL_NAME\fP * gen)"

.PP
Definition at line 179 of file v3_alt\&.c\&.
.SS "STACK_OF (\fBCONF_VALUE\fP)"

.PP
Definition at line 98 of file v3_alt\&.c\&.
.SS "\fBGENERAL_NAME\fP* v2i_GENERAL_NAME (const \fBX509V3_EXT_METHOD\fP * method, \fBX509V3_CTX\fP * ctx, \fBCONF_VALUE\fP * cnf)"

.PP
Definition at line 422 of file v3_alt\&.c\&.
.SS "\fBGENERAL_NAME\fP* v2i_GENERAL_NAME_ex (\fBGENERAL_NAME\fP * out, const \fBX509V3_EXT_METHOD\fP * method, \fBX509V3_CTX\fP * ctx, \fBCONF_VALUE\fP * cnf, int is_nc)"

.PP
Definition at line 519 of file v3_alt\&.c\&.
.SS "GENERAL_NAMES* v2i_GENERAL_NAMES (const \fBX509V3_EXT_METHOD\fP * method, \fBX509V3_CTX\fP * ctx, \fBSTACK_OF\fP(\fBCONF_VALUE\fP)* nval)"

.PP
Definition at line 399 of file v3_alt\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBX509V3_EXT_METHOD\fP v3_alt[]"
\fBInitial value:\fP
.PP
.nf
= {
    {NID_subject_alt_name, 0, ASN1_ITEM_ref(GENERAL_NAMES),
     0, 0, 0, 0,
     0, 0,
     (X509V3_EXT_I2V) i2v_GENERAL_NAMES,
     (X509V3_EXT_V2I)v2i_subject_alt,
     NULL, NULL, NULL},

    {NID_issuer_alt_name, 0, ASN1_ITEM_ref(GENERAL_NAMES),
     0, 0, 0, 0,
     0, 0,
     (X509V3_EXT_I2V) i2v_GENERAL_NAMES,
     (X509V3_EXT_V2I)v2i_issuer_alt,
     NULL, NULL, NULL},

    {NID_certificate_issuer, 0, ASN1_ITEM_ref(GENERAL_NAMES),
     0, 0, 0, 0,
     0, 0,
     (X509V3_EXT_I2V) i2v_GENERAL_NAMES,
     NULL, NULL, NULL, NULL},
}
.fi
.PP
Definition at line 76 of file v3_alt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
