.TH "s2n/libcrypto-build/openssl/crypto/x509v3/v3_bitst.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/x509v3/v3_bitst.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/conf\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCONF_VALUE\fP)"
.br
.ti -1c
.RI "\fBASN1_BIT_STRING\fP * \fBv2i_ASN1_BIT_STRING\fP (\fBX509V3_EXT_METHOD\fP *method, \fBX509V3_CTX\fP *\fBctx\fP, \fBSTACK_OF\fP(\fBCONF_VALUE\fP)*nval)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBX509V3_EXT_METHOD\fP \fBv3_nscert\fP"
.br
.ti -1c
.RI "const \fBX509V3_EXT_METHOD\fP \fBv3_key_usage\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "STACK_OF (\fBCONF_VALUE\fP)"

.PP
Definition at line 95 of file v3_bitst\&.c\&.
.SS "\fBASN1_BIT_STRING\fP* v2i_ASN1_BIT_STRING (\fBX509V3_EXT_METHOD\fP * method, \fBX509V3_CTX\fP * ctx, \fBSTACK_OF\fP(\fBCONF_VALUE\fP)* nval)"

.PP
Definition at line 107 of file v3_bitst\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBX509V3_EXT_METHOD\fP v3_key_usage"
\fBInitial value:\fP
.PP
.nf
=
EXT_BITSTRING(NID_key_usage, key_usage_type_table)
.fi
.PP
Definition at line 92 of file v3_bitst\&.c\&.
.SS "const \fBX509V3_EXT_METHOD\fP v3_nscert"
\fBInitial value:\fP
.PP
.nf
=
EXT_BITSTRING(NID_netscape_cert_type, ns_cert_type_table)
.fi
.PP
Definition at line 90 of file v3_bitst\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
