.TH "s2n/libcrypto-build/openssl/crypto/x509v3/v3_crld.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/x509v3/v3_crld.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/conf\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBASN1_CHOICE_cb\fP (\fBDIST_POINT_NAME\fP, dpn_cb)"
.br
.ti -1c
.RI "int \fBDIST_POINT_set_dpname\fP (\fBDIST_POINT_NAME\fP *dpn, \fBX509_NAME\fP *iname)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBX509V3_EXT_METHOD\fP \fBv3_crld\fP"
.br
.ti -1c
.RI "const \fBX509V3_EXT_METHOD\fP \fBv3_freshest_crl\fP"
.br
.ti -1c
.RI "const \fBX509V3_EXT_METHOD\fP \fBv3_idp\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "ASN1_CHOICE_cb (\fBDIST_POINT_NAME\fP, dpn_cb)"

.SS "int DIST_POINT_set_dpname (\fBDIST_POINT_NAME\fP * dpn, \fBX509_NAME\fP * iname)"

.PP
Definition at line 536 of file v3_crld\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBX509V3_EXT_METHOD\fP v3_crld"
\fBInitial value:\fP
.PP
.nf
= {
    NID_crl_distribution_points, 0, ASN1_ITEM_ref(CRL_DIST_POINTS),
    0, 0, 0, 0,
    0, 0,
    0,
    v2i_crld,
    i2r_crldp, 0,
    NULL
}
.fi
.PP
Definition at line 72 of file v3_crld\&.c\&.
.SS "const \fBX509V3_EXT_METHOD\fP v3_freshest_crl"
\fBInitial value:\fP
.PP
.nf
= {
    NID_freshest_crl, 0, ASN1_ITEM_ref(CRL_DIST_POINTS),
    0, 0, 0, 0,
    0, 0,
    0,
    v2i_crld,
    i2r_crldp, 0,
    NULL
}
.fi
.PP
Definition at line 82 of file v3_crld\&.c\&.
.SS "const \fBX509V3_EXT_METHOD\fP v3_idp"
\fBInitial value:\fP
.PP
.nf
= {
    NID_issuing_distribution_point, X509V3_EXT_MULTILINE,
    ASN1_ITEM_ref(ISSUING_DIST_POINT),
    0, 0, 0, 0,
    0, 0,
    0,
    v2i_idp,
    i2r_idp, 0,
    NULL
}
.fi
.PP
Definition at line 405 of file v3_crld\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
