.TH "s2n/libcrypto-build/openssl/crypto/x509v3/v3_ncons.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/x509v3/v3_ncons.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/conf\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBX509V3_EXT_METHOD\fP \fBv3_name_constraints\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBX509V3_EXT_METHOD\fP v3_name_constraints"
\fBInitial value:\fP
.PP
.nf
= {
    NID_name_constraints, 0,
    ASN1_ITEM_ref(NAME_CONSTRAINTS),
    0, 0, 0, 0,
    0, 0,
    0, v2i_NAME_CONSTRAINTS,
    i2r_NAME_CONSTRAINTS, 0,
    NULL
}
.fi
.PP
Definition at line 83 of file v3_ncons\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
