.TH "s2n/libcrypto-build/openssl/crypto/x509v3/v3_sxnet.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/x509v3/v3_sxnet.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/conf\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSXNET_TEST\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBX509V3_EXT_METHOD\fP \fBv3_sxnet\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SXNET_TEST"

.PP
Definition at line 69 of file v3_sxnet\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBX509V3_EXT_METHOD\fP v3_sxnet"
\fBInitial value:\fP
.PP
.nf
= {
    NID_sxnet, X509V3_EXT_MULTILINE, ASN1_ITEM_ref(SXNET),
    0, 0, 0, 0,
    0, 0,
    0,

    (X509V3_EXT_V2I)sxnet_v2i,



    (X509V3_EXT_I2R)sxnet_i2r,
    0,
    NULL
}
.fi
.PP
Definition at line 77 of file v3_sxnet\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
