.TH "X509_POLICY_LEVEL_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
X509_POLICY_LEVEL_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pcy_int\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_POLICY_NODE\fP)*nodes"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBX509\fP * \fBcert\fP"
.br
.ti -1c
.RI "\fBX509_POLICY_NODE\fP * \fBanyPolicy\fP"
.br
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 149 of file pcy_int\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBX509_POLICY_NODE\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBX509_POLICY_NODE\fP* anyPolicy"

.PP
Definition at line 155 of file pcy_int\&.h\&.
.SS "\fBX509\fP* cert"

.PP
Definition at line 151 of file pcy_int\&.h\&.
.SS "unsigned int flags"

.PP
Definition at line 160 of file pcy_int\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
