.TH "s2n/libcrypto-build/openssl/crypto/x509/x509_d2.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/x509/x509_d2.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBX509_STORE_set_default_paths\fP (\fBX509_STORE\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBX509_STORE_load_locations\fP (\fBX509_STORE\fP *\fBctx\fP, const char *\fBfile\fP, const char *path)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int X509_STORE_load_locations (\fBX509_STORE\fP * ctx, const char * file, const char * path)"

.PP
Definition at line 85 of file x509_d2\&.c\&.
.SS "int X509_STORE_set_default_paths (\fBX509_STORE\fP * ctx)"

.PP
Definition at line 65 of file x509_d2\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
