.TH "x509_cert_pair_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
x509_cert_pair_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <x509\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBX509\fP * \fBforward\fP"
.br
.ti -1c
.RI "\fBX509\fP * \fBreverse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 317 of file x509\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBX509\fP * forward"

.PP
Definition at line 318 of file x509\&.h\&.
.SS "\fBX509\fP * reverse"

.PP
Definition at line 319 of file x509\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
