.TH "s2n/libcrypto-build/openssl/crypto/asn1/x_name.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/x_name.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include 'asn1_locl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBX509_NAME_MAX\fP   (1024 * 1024)"
.br
.ti -1c
.RI "#define \fBASN1_MASK_CANON\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "typedef \fBSTACK_OF\fP (\fBX509_NAME_ENTRY\fP)"
.br
.ti -1c
.RI "\fBASN1_SEQUENCE_END\fP (\fBX509_NAME_ENTRY\fP)"
.br
.ti -1c
.RI "int \fBX509_NAME_set\fP (\fBX509_NAME\fP **xn, \fBX509_NAME\fP *name)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASN1_MASK_CANON"
\fBValue:\fP
.PP
.nf
(B_ASN1_UTF8STRING | B_ASN1_BMPSTRING | B_ASN1_UNIVERSALSTRING \
        | B_ASN1_PRINTABLESTRING | B_ASN1_T61STRING | B_ASN1_IA5STRING \
        | B_ASN1_VISIBLESTRING)
.fi
.PP
Definition at line 415 of file x_name\&.c\&.
.SS "#define X509_NAME_MAX   (1024 * 1024)"

.SH "Function Documentation"
.PP 
.SS "ASN1_SEQUENCE_END (\fBX509_NAME_ENTRY\fP)"

.PP
Definition at line 99 of file x_name\&.c\&.
.SS "typedef STACK_OF (\fBX509_NAME_ENTRY\fP)"

.PP
Definition at line 66 of file x_name\&.c\&.
.SS "int X509_NAME_set (\fBX509_NAME\fP ** xn, \fBX509_NAME\fP * name)"

.PP
Definition at line 517 of file x_name\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
