.TH "ZEN_DES_KEY" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZEN_DES_KEY \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBdes_key\fP [24]"
.br
.ti -1c
.RI "unsigned char \fBdes_iv\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1371 of file hw_zencod\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char des_iv[8]"

.PP
Definition at line 1373 of file hw_zencod\&.c\&.
.SS "unsigned char des_key[24]"

.PP
Definition at line 1372 of file hw_zencod\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
