.TH "_SW_LARGENUMBER" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_SW_LARGENUMBER \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cswift\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBSW_U32\fP \fBnbytes\fP"
.br
.ti -1c
.RI "\fBSW_BYTE\fP * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 152 of file cswift\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBSW_U32\fP nbytes"

.PP
Definition at line 153 of file cswift\&.h\&.
.SS "\fBSW_BYTE\fP* value"

.PP
Definition at line 154 of file cswift\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
