.TH "asn1_pctx_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asn1_pctx_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <asn1_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBflags\fP"
.br
.ti -1c
.RI "unsigned long \fBnm_flags\fP"
.br
.ti -1c
.RI "unsigned long \fBcert_flags\fP"
.br
.ti -1c
.RI "unsigned long \fBoid_flags\fP"
.br
.ti -1c
.RI "unsigned long \fBstr_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 67 of file asn1_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned long flags"

.PP
Definition at line 68 of file asn1_locl\&.h\&.
.SS "unsigned long nm_flags"

.PP
Definition at line 69 of file asn1_locl\&.h\&.
.SS "unsigned long cert_flags"

.PP
Definition at line 70 of file asn1_locl\&.h\&.
.SS "unsigned long oid_flags"

.PP
Definition at line 71 of file asn1_locl\&.h\&.
.SS "unsigned long str_flags"

.PP
Definition at line 72 of file asn1_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
