.TH "asn1_object_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asn1_object_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <asn1\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBsn\fP"
.br
.ti -1c
.RI "const char * \fBln\fP"
.br
.ti -1c
.RI "int \fBnid\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "const unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 210 of file asn1\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const char * sn"

.PP
Definition at line 211 of file asn1\&.h\&.
.SS "const char * ln"

.PP
Definition at line 211 of file asn1\&.h\&.
.SS "int nid"

.PP
Definition at line 212 of file asn1\&.h\&.
.SS "int length"

.PP
Definition at line 213 of file asn1\&.h\&.
.SS "const unsigned char * data"

.PP
Definition at line 214 of file asn1\&.h\&.
.SS "int flags"

.PP
Definition at line 215 of file asn1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
