.TH "s2n-master/libcrypto-build/openssl/crypto/bio/bio_lcl.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/crypto/bio/bio_lcl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/bio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUP_stdin\fP   stdin"
.br
.ti -1c
.RI "#define \fBUP_stdout\fP   stdout"
.br
.ti -1c
.RI "#define \fBUP_stderr\fP   stderr"
.br
.ti -1c
.RI "#define \fBUP_fprintf\fP   fprintf"
.br
.ti -1c
.RI "#define \fBUP_fgets\fP   fgets"
.br
.ti -1c
.RI "#define \fBUP_fread\fP   fread"
.br
.ti -1c
.RI "#define \fBUP_fwrite\fP   fwrite"
.br
.ti -1c
.RI "#define \fBUP_feof\fP   feof"
.br
.ti -1c
.RI "#define \fBUP_fclose\fP   fclose"
.br
.ti -1c
.RI "#define \fBUP_fopen\fP   fopen"
.br
.ti -1c
.RI "#define \fBUP_fseek\fP   fseek"
.br
.ti -1c
.RI "#define \fBUP_ftell\fP   ftell"
.br
.ti -1c
.RI "#define \fBUP_fflush\fP   fflush"
.br
.ti -1c
.RI "#define \fBUP_ferror\fP   ferror"
.br
.ti -1c
.RI "#define \fBUP_fileno\fP   fileno"
.br
.ti -1c
.RI "#define \fBUP_open\fP   open"
.br
.ti -1c
.RI "#define \fBUP_read\fP   read"
.br
.ti -1c
.RI "#define \fBUP_write\fP   write"
.br
.ti -1c
.RI "#define \fBUP_lseek\fP   lseek"
.br
.ti -1c
.RI "#define \fBUP_close\fP   close"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define UP_stdin   stdin"

.PP
Definition at line 5 of file bio_lcl\&.h\&.
.SS "#define UP_stdout   stdout"

.PP
Definition at line 6 of file bio_lcl\&.h\&.
.SS "#define UP_stderr   stderr"

.PP
Definition at line 7 of file bio_lcl\&.h\&.
.SS "#define UP_fprintf   fprintf"

.PP
Definition at line 8 of file bio_lcl\&.h\&.
.SS "#define UP_fgets   fgets"

.PP
Definition at line 9 of file bio_lcl\&.h\&.
.SS "#define UP_fread   fread"

.PP
Definition at line 10 of file bio_lcl\&.h\&.
.SS "#define UP_fwrite   fwrite"

.PP
Definition at line 11 of file bio_lcl\&.h\&.
.SS "#define UP_feof   feof"

.PP
Definition at line 13 of file bio_lcl\&.h\&.
.SS "#define UP_fclose   fclose"

.PP
Definition at line 14 of file bio_lcl\&.h\&.
.SS "#define UP_fopen   fopen"

.PP
Definition at line 16 of file bio_lcl\&.h\&.
.SS "#define UP_fseek   fseek"

.PP
Definition at line 17 of file bio_lcl\&.h\&.
.SS "#define UP_ftell   ftell"

.PP
Definition at line 18 of file bio_lcl\&.h\&.
.SS "#define UP_fflush   fflush"

.PP
Definition at line 19 of file bio_lcl\&.h\&.
.SS "#define UP_ferror   ferror"

.PP
Definition at line 20 of file bio_lcl\&.h\&.
.SS "#define UP_fileno   fileno"

.PP
Definition at line 29 of file bio_lcl\&.h\&.
.SS "#define UP_open   open"

.PP
Definition at line 30 of file bio_lcl\&.h\&.
.SS "#define UP_read   read"

.PP
Definition at line 31 of file bio_lcl\&.h\&.
.SS "#define UP_write   write"

.PP
Definition at line 32 of file bio_lcl\&.h\&.
.SS "#define UP_lseek   lseek"

.PP
Definition at line 33 of file bio_lcl\&.h\&.
.SS "#define UP_close   close"

.PP
Definition at line 34 of file bio_lcl\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
