.TH "ccm128_context" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccm128_context \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <modes_lcl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBu64\fP \fBu\fP [2]"
.br
.ti -1c
.RI "   \fBu8\fP \fBc\fP [16]"
.br
.ti -1c
.RI "} \fBnonce\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBu64\fP \fBu\fP [2]"
.br
.ti -1c
.RI "   \fBu8\fP \fBc\fP [16]"
.br
.ti -1c
.RI "} \fBcmac\fP"
.br
.ti -1c
.RI "\fBu64\fP \fBblocks\fP"
.br
.ti -1c
.RI "\fBblock128_f\fP \fBblock\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBkey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 135 of file modes_lcl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBu64\fP u[2]"

.PP
Definition at line 137 of file modes_lcl\&.h\&.
.SS "\fBu8\fP c[16]"

.PP
Definition at line 138 of file modes_lcl\&.h\&.
.SS "union { \&.\&.\&. }   nonce"

.SS "union { \&.\&.\&. }   cmac"

.SS "\fBu64\fP blocks"

.PP
Definition at line 140 of file modes_lcl\&.h\&.
.SS "\fBblock128_f\fP block"

.PP
Definition at line 141 of file modes_lcl\&.h\&.
.SS "\fBvoid\fP* key"

.PP
Definition at line 142 of file modes_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
