.TH "s2n-master/libcrypto-build/openssl/crypto/camellia/cmll_locl.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/crypto/camellia/cmll_locl.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBu32\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBu8\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBCamellia_Ekeygen\fP (int keyBitLength, const \fBu8\fP *rawKey, \fBKEY_TABLE_TYPE\fP keyTable)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCamellia_EncryptBlock_Rounds\fP (int grandRounds, const \fBu8\fP plaintext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP ciphertext[])"
.br
.ti -1c
.RI "\fBvoid\fP \fBCamellia_DecryptBlock_Rounds\fP (int grandRounds, const \fBu8\fP ciphertext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP plaintext[])"
.br
.ti -1c
.RI "\fBvoid\fP \fBCamellia_EncryptBlock\fP (int keyBitLength, const \fBu8\fP plaintext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP ciphertext[])"
.br
.ti -1c
.RI "\fBvoid\fP \fBCamellia_DecryptBlock\fP (int keyBitLength, const \fBu8\fP ciphertext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP plaintext[])"
.br
.ti -1c
.RI "int \fBprivate_Camellia_set_key\fP (const unsigned char *userKey, const int \fBbits\fP, \fBCAMELLIA_KEY\fP *key)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned int \fBu32\fP"

.PP
Definition at line 71 of file cmll_locl\&.h\&.
.SS "typedef unsigned char \fBu8\fP"

.PP
Definition at line 72 of file cmll_locl\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int Camellia_Ekeygen (int keyBitLength, const \fBu8\fP * rawKey, \fBKEY_TABLE_TYPE\fP keyTable)"

.SS "\fBvoid\fP Camellia_EncryptBlock_Rounds (int grandRounds, const \fBu8\fP plaintext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP ciphertext[])"

.SS "\fBvoid\fP Camellia_DecryptBlock_Rounds (int grandRounds, const \fBu8\fP ciphertext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP plaintext[])"

.SS "\fBvoid\fP Camellia_EncryptBlock (int keyBitLength, const \fBu8\fP plaintext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP ciphertext[])"

.SS "\fBvoid\fP Camellia_DecryptBlock (int keyBitLength, const \fBu8\fP ciphertext[], const \fBKEY_TABLE_TYPE\fP keyTable, \fBu8\fP plaintext[])"

.SS "int private_Camellia_set_key (const unsigned char * userKey, const int bits, \fBCAMELLIA_KEY\fP * key)"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
