.TH "CMS_KeyAgreeRecipientInfo_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMS_KeyAgreeRecipientInfo_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cms_lcl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCMS_RecipientEncryptedKey\fP)*recipientEncryptedKeys"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBversion\fP"
.br
.ti -1c
.RI "\fBCMS_OriginatorIdentifierOrKey\fP * \fBoriginator\fP"
.br
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBukm\fP"
.br
.ti -1c
.RI "\fBX509_ALGOR\fP * \fBkeyEncryptionAlgorithm\fP"
.br
.ti -1c
.RI "\fBEVP_PKEY_CTX\fP * \fBpctx\fP"
.br
.ti -1c
.RI "\fBEVP_CIPHER_CTX\fP \fBctx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 202 of file cms_lcl\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBCMS_RecipientEncryptedKey\fP)"

.SH "Field Documentation"
.PP 
.SS "long version"

.PP
Definition at line 203 of file cms_lcl\&.h\&.
.SS "\fBCMS_OriginatorIdentifierOrKey\fP* originator"

.PP
Definition at line 204 of file cms_lcl\&.h\&.
.SS "\fBASN1_OCTET_STRING\fP* ukm"

.PP
Definition at line 205 of file cms_lcl\&.h\&.
.SS "\fBX509_ALGOR\fP* keyEncryptionAlgorithm"

.PP
Definition at line 206 of file cms_lcl\&.h\&.
.SS "\fBEVP_PKEY_CTX\fP* pctx"

.PP
Definition at line 209 of file cms_lcl\&.h\&.
.SS "\fBEVP_CIPHER_CTX\fP ctx"

.PP
Definition at line 211 of file cms_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
