.TH "CMS_DigestedData_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMS_DigestedData_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cms_lcl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBversion\fP"
.br
.ti -1c
.RI "\fBX509_ALGOR\fP * \fBdigestAlgorithm\fP"
.br
.ti -1c
.RI "\fBCMS_EncapsulatedContentInfo\fP * \fBencapContentInfo\fP"
.br
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBdigest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 280 of file cms_lcl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "long version"

.PP
Definition at line 281 of file cms_lcl\&.h\&.
.SS "\fBX509_ALGOR\fP* digestAlgorithm"

.PP
Definition at line 282 of file cms_lcl\&.h\&.
.SS "\fBCMS_EncapsulatedContentInfo\fP* encapContentInfo"

.PP
Definition at line 283 of file cms_lcl\&.h\&.
.SS "\fBASN1_OCTET_STRING\fP* digest"

.PP
Definition at line 284 of file cms_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
