.TH "CMS_SignedData_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMS_SignedData_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cms_lcl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ALGOR\fP)*digestAlgorithms"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCMS_CertificateChoices\fP)*certificates"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCMS_RevocationInfoChoice\fP)*crls"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCMS_SignerInfo\fP)*signerInfos"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBversion\fP"
.br
.ti -1c
.RI "\fBCMS_EncapsulatedContentInfo\fP * \fBencapContentInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file cms_lcl\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBX509_ALGOR\fP)"

.SS "STACK_OF (\fBCMS_CertificateChoices\fP)"

.SS "STACK_OF (\fBCMS_RevocationInfoChoice\fP)"

.SS "STACK_OF (\fBCMS_SignerInfo\fP)"

.SH "Field Documentation"
.PP 
.SS "long version"

.PP
Definition at line 113 of file cms_lcl\&.h\&.
.SS "\fBCMS_EncapsulatedContentInfo\fP* encapContentInfo"

.PP
Definition at line 115 of file cms_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
