.TH "s2n-master/libcrypto-build/openssl/include/openssl/conf_api.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/include/openssl/conf_api.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/lhash\&.h>\fP
.br
\fC#include <openssl/conf\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCONF_VALUE\fP * \fB_CONF_new_section\fP (\fBCONF\fP *conf, const char *\fBsection\fP)"
.br
.ti -1c
.RI "\fBCONF_VALUE\fP * \fB_CONF_get_section\fP (const \fBCONF\fP *conf, const char *\fBsection\fP)"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCONF_VALUE\fP)*_CONF_get_section_values(const \fBCONF\fP *conf"
.br
.ti -1c
.RI "int \fB_CONF_add_string\fP (\fBCONF\fP *conf, \fBCONF_VALUE\fP *\fBsection\fP, \fBCONF_VALUE\fP *value)"
.br
.ti -1c
.RI "char * \fB_CONF_get_string\fP (const \fBCONF\fP *conf, const char *\fBsection\fP, const char *name)"
.br
.ti -1c
.RI "long \fB_CONF_get_number\fP (const \fBCONF\fP *conf, const char *\fBsection\fP, const char *name)"
.br
.ti -1c
.RI "int \fB_CONF_new_data\fP (\fBCONF\fP *conf)"
.br
.ti -1c
.RI "\fBvoid\fP \fB_CONF_free_data\fP (\fBCONF\fP *conf)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBsection\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBCONF_VALUE\fP* _CONF_new_section (\fBCONF\fP * conf, const char * section)"

.SS "\fBCONF_VALUE\fP* _CONF_get_section (const \fBCONF\fP * conf, const char * section)"

.SS "STACK_OF (\fBCONF_VALUE\fP) const"

.SS "int _CONF_add_string (\fBCONF\fP * conf, \fBCONF_VALUE\fP * section, \fBCONF_VALUE\fP * value)"

.SS "char* _CONF_get_string (const \fBCONF\fP * conf, const char * section, const char * name)"

.SS "long _CONF_get_number (const \fBCONF\fP * conf, const char * section, const char * name)"

.SS "int _CONF_new_data (\fBCONF\fP * conf)"

.SS "\fBvoid\fP _CONF_free_data (\fBCONF\fP * conf)"

.SH "Variable Documentation"
.PP 
.SS "const char* section"

.PP
Definition at line 75 of file conf_api\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
