.TH "CONF_VALUE" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CONF_VALUE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <conf\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBsection\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file conf\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char * section"

.PP
Definition at line 75 of file conf\&.h\&.
.SS "char * name"

.PP
Definition at line 76 of file conf\&.h\&.
.SS "char * value"

.PP
Definition at line 77 of file conf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
