.TH "s2n-master/libcrypto-build/openssl/crypto/cryptlib.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/crypto/cryptlib.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'e_os\&.h'\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <openssl/opensslconf\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBX509_CERT_AREA\fP   OPENSSLDIR"
.br
.ti -1c
.RI "#define \fBX509_CERT_DIR\fP   OPENSSLDIR '/certs'"
.br
.ti -1c
.RI "#define \fBX509_CERT_FILE\fP   OPENSSLDIR '/cert\&.pem'"
.br
.ti -1c
.RI "#define \fBX509_PRIVATE_DIR\fP   OPENSSLDIR '/private'"
.br
.ti -1c
.RI "#define \fBX509_CERT_DIR_EVP\fP   'SSL_CERT_DIR'"
.br
.ti -1c
.RI "#define \fBX509_CERT_FILE_EVP\fP   'SSL_CERT_FILE'"
.br
.ti -1c
.RI "#define \fBDECIMAL_SIZE\fP(\fBtype\fP)           ((sizeof(\fBtype\fP)*8+2)/3+1)"
.br
.ti -1c
.RI "#define \fBHEX_SIZE\fP(\fBtype\fP)                   (sizeof(\fBtype\fP)*2)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBOPENSSL_cpuid_setup\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOPENSSL_showfatal\fP (const char *fmta,\&.\&.\&.)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBOPENSSL_stderr\fP (\fBvoid\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned int \fBOPENSSL_ia32cap_P\fP []"
.br
.ti -1c
.RI "int \fBOPENSSL_NONPIC_relocated\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define X509_CERT_AREA   OPENSSLDIR"

.PP
Definition at line 83 of file cryptlib\&.h\&.
.SS "#define X509_CERT_DIR   OPENSSLDIR '/certs'"

.PP
Definition at line 84 of file cryptlib\&.h\&.
.SS "#define X509_CERT_FILE   OPENSSLDIR '/cert\&.pem'"

.PP
Definition at line 85 of file cryptlib\&.h\&.
.SS "#define X509_PRIVATE_DIR   OPENSSLDIR '/private'"

.PP
Definition at line 86 of file cryptlib\&.h\&.
.SS "#define X509_CERT_DIR_EVP   'SSL_CERT_DIR'"

.PP
Definition at line 94 of file cryptlib\&.h\&.
.SS "#define X509_CERT_FILE_EVP   'SSL_CERT_FILE'"

.PP
Definition at line 95 of file cryptlib\&.h\&.
.SS "#define DECIMAL_SIZE(\fBtype\fP)   ((sizeof(\fBtype\fP)*8+2)/3+1)"

.PP
Definition at line 98 of file cryptlib\&.h\&.
.SS "#define HEX_SIZE(\fBtype\fP)   (sizeof(\fBtype\fP)*2)"

.PP
Definition at line 99 of file cryptlib\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP OPENSSL_cpuid_setup (\fBvoid\fP)"

.SS "\fBvoid\fP OPENSSL_showfatal (const char * fmta,  \&.\&.\&.)"

.SS "\fBvoid\fP* OPENSSL_stderr (\fBvoid\fP)"

.SH "Variable Documentation"
.PP 
.SS "unsigned int OPENSSL_ia32cap_P[]"

.SS "int OPENSSL_NONPIC_relocated"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
