.TH "custom_ext_methods" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
custom_ext_methods \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ssl_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBcustom_ext_method\fP * \fBmeths\fP"
.br
.ti -1c
.RI "size_t \fBmeths_count\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 594 of file ssl_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBcustom_ext_method\fP* meths"

.PP
Definition at line 595 of file ssl_locl\&.h\&.
.SS "size_t meths_count"

.PP
Definition at line 596 of file ssl_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
