.TH "dso_meth_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dso_meth_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dso\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int(* \fBdso_load\fP )(\fBDSO\fP *dso)"
.br
.ti -1c
.RI "int(* \fBdso_unload\fP )(\fBDSO\fP *dso)"
.br
.ti -1c
.RI "\fBvoid\fP *(* \fBdso_bind_var\fP )(\fBDSO\fP *dso, const char *symname)"
.br
.ti -1c
.RI "\fBDSO_FUNC_TYPE\fP(* \fBdso_bind_func\fP )(\fBDSO\fP *dso, const char *symname)"
.br
.ti -1c
.RI "long(* \fBdso_ctrl\fP )(\fBDSO\fP *dso, int cmd, long larg, \fBvoid\fP *parg)"
.br
.ti -1c
.RI "\fBDSO_NAME_CONVERTER_FUNC\fP \fBdso_name_converter\fP"
.br
.ti -1c
.RI "\fBDSO_MERGER_FUNC\fP \fBdso_merger\fP"
.br
.ti -1c
.RI "int(* \fBinit\fP )(\fBDSO\fP *dso)"
.br
.ti -1c
.RI "int(* \fBfinish\fP )(\fBDSO\fP *dso)"
.br
.ti -1c
.RI "int(* \fBpathbyaddr\fP )(\fBvoid\fP *addr, char *path, int sz)"
.br
.ti -1c
.RI "\fBvoid\fP *(* \fBgloballookup\fP )(const char *symname)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 140 of file dso\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const char * name"

.PP
Definition at line 141 of file dso\&.h\&.
.SS "int(* dso_load)(\fBDSO\fP *dso)"

.PP
Definition at line 147 of file dso\&.h\&.
.SS "int(* dso_unload)(\fBDSO\fP *dso)"

.PP
Definition at line 149 of file dso\&.h\&.
.SS "\fBvoid\fP *(* dso_bind_var)(\fBDSO\fP *dso, const char *symname)"

.PP
Definition at line 151 of file dso\&.h\&.
.SS "\fBDSO_FUNC_TYPE\fP(* dso_bind_func)(\fBDSO\fP *dso, const char *symname)"

.PP
Definition at line 159 of file dso\&.h\&.
.SS "long(* dso_ctrl)(\fBDSO\fP *dso, int cmd, long larg, \fBvoid\fP *parg)"

.PP
Definition at line 171 of file dso\&.h\&.
.SS "\fBDSO_NAME_CONVERTER_FUNC\fP dso_name_converter"

.PP
Definition at line 176 of file dso\&.h\&.
.SS "\fBDSO_MERGER_FUNC\fP dso_merger"

.PP
Definition at line 181 of file dso\&.h\&.
.SS "int(* init)(\fBDSO\fP *dso)"

.PP
Definition at line 183 of file dso\&.h\&.
.SS "int(* finish)(\fBDSO\fP *dso)"

.PP
Definition at line 184 of file dso\&.h\&.
.SS "int(* pathbyaddr)(\fBvoid\fP *addr, char *path, int sz)"

.PP
Definition at line 186 of file dso\&.h\&.
.SS "\fBvoid\fP *(* globallookup)(const char *symname)"

.PP
Definition at line 188 of file dso\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
