.TH "s2n-master/libcrypto-build/openssl/engines/e_atalla_err.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/engines/e_atalla_err.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBATALLAerr\fP(f,  r)   ERR_ATALLA_error((f),(r),__FILE__,__LINE__)"
.br
.ti -1c
.RI "#define \fBATALLA_F_ATALLA_CTRL\fP   100"
.br
.ti -1c
.RI "#define \fBATALLA_F_ATALLA_FINISH\fP   101"
.br
.ti -1c
.RI "#define \fBATALLA_F_ATALLA_INIT\fP   102"
.br
.ti -1c
.RI "#define \fBATALLA_F_ATALLA_MOD_EXP\fP   103"
.br
.ti -1c
.RI "#define \fBATALLA_F_ATALLA_RSA_MOD_EXP\fP   104"
.br
.ti -1c
.RI "#define \fBATALLA_R_ALREADY_LOADED\fP   100"
.br
.ti -1c
.RI "#define \fBATALLA_R_BN_CTX_FULL\fP   101"
.br
.ti -1c
.RI "#define \fBATALLA_R_BN_EXPAND_FAIL\fP   102"
.br
.ti -1c
.RI "#define \fBATALLA_R_CTRL_COMMAND_NOT_IMPLEMENTED\fP   103"
.br
.ti -1c
.RI "#define \fBATALLA_R_MISSING_KEY_COMPONENTS\fP   104"
.br
.ti -1c
.RI "#define \fBATALLA_R_NOT_LOADED\fP   105"
.br
.ti -1c
.RI "#define \fBATALLA_R_REQUEST_FAILED\fP   106"
.br
.ti -1c
.RI "#define \fBATALLA_R_UNIT_FAILURE\fP   107"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ATALLAerr(f, r)   ERR_ATALLA_error((f),(r),__FILE__,__LINE__)"

.PP
Definition at line 70 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_F_ATALLA_CTRL   100"

.PP
Definition at line 75 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_F_ATALLA_FINISH   101"

.PP
Definition at line 76 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_F_ATALLA_INIT   102"

.PP
Definition at line 77 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_F_ATALLA_MOD_EXP   103"

.PP
Definition at line 78 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_F_ATALLA_RSA_MOD_EXP   104"

.PP
Definition at line 79 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_R_ALREADY_LOADED   100"

.PP
Definition at line 82 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_R_BN_CTX_FULL   101"

.PP
Definition at line 83 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_R_BN_EXPAND_FAIL   102"

.PP
Definition at line 84 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_R_CTRL_COMMAND_NOT_IMPLEMENTED   103"

.PP
Definition at line 85 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_R_MISSING_KEY_COMPONENTS   104"

.PP
Definition at line 86 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_R_NOT_LOADED   105"

.PP
Definition at line 87 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_R_REQUEST_FAILED   106"

.PP
Definition at line 88 of file e_atalla_err\&.h\&.
.SS "#define ATALLA_R_UNIT_FAILURE   107"

.PP
Definition at line 89 of file e_atalla_err\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
