.TH "s2n-master/libcrypto-build/openssl/engines/e_capi_err.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/engines/e_capi_err.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAPIerr\fP(f,  r)   ERR_CAPI_error((f),(r),__FILE__,__LINE__)"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_CERT_GET_FNAME\fP   99"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_CTRL\fP   100"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_CTX_NEW\fP   101"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_CTX_SET_PROVNAME\fP   102"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_DSA_DO_SIGN\fP   114"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_GET_KEY\fP   103"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_GET_PKEY\fP   115"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_GET_PROVNAME\fP   104"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_GET_PROV_INFO\fP   105"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_INIT\fP   106"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_LIST_CONTAINERS\fP   107"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_LOAD_PRIVKEY\fP   108"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_OPEN_STORE\fP   109"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_RSA_PRIV_DEC\fP   110"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_RSA_PRIV_ENC\fP   111"
.br
.ti -1c
.RI "#define \fBCAPI_F_CAPI_RSA_SIGN\fP   112"
.br
.ti -1c
.RI "#define \fBCAPI_F_CERT_SELECT_DIALOG\fP   117"
.br
.ti -1c
.RI "#define \fBCAPI_F_CLIENT_CERT_SELECT\fP   116"
.br
.ti -1c
.RI "#define \fBCAPI_F_WIDE_TO_ASC\fP   113"
.br
.ti -1c
.RI "#define \fBCAPI_R_CANT_CREATE_HASH_OBJECT\fP   99"
.br
.ti -1c
.RI "#define \fBCAPI_R_CANT_FIND_CAPI_CONTEXT\fP   100"
.br
.ti -1c
.RI "#define \fBCAPI_R_CANT_GET_KEY\fP   101"
.br
.ti -1c
.RI "#define \fBCAPI_R_CANT_SET_HASH_VALUE\fP   102"
.br
.ti -1c
.RI "#define \fBCAPI_R_CRYPTACQUIRECONTEXT_ERROR\fP   103"
.br
.ti -1c
.RI "#define \fBCAPI_R_CRYPTENUMPROVIDERS_ERROR\fP   104"
.br
.ti -1c
.RI "#define \fBCAPI_R_DECRYPT_ERROR\fP   105"
.br
.ti -1c
.RI "#define \fBCAPI_R_ENGINE_NOT_INITIALIZED\fP   106"
.br
.ti -1c
.RI "#define \fBCAPI_R_ENUMCONTAINERS_ERROR\fP   107"
.br
.ti -1c
.RI "#define \fBCAPI_R_ERROR_ADDING_CERT\fP   125"
.br
.ti -1c
.RI "#define \fBCAPI_R_ERROR_CREATING_STORE\fP   126"
.br
.ti -1c
.RI "#define \fBCAPI_R_ERROR_GETTING_FRIENDLY_NAME\fP   108"
.br
.ti -1c
.RI "#define \fBCAPI_R_ERROR_GETTING_KEY_PROVIDER_INFO\fP   109"
.br
.ti -1c
.RI "#define \fBCAPI_R_ERROR_OPENING_STORE\fP   110"
.br
.ti -1c
.RI "#define \fBCAPI_R_ERROR_SIGNING_HASH\fP   111"
.br
.ti -1c
.RI "#define \fBCAPI_R_FUNCTION_NOT_SUPPORTED\fP   112"
.br
.ti -1c
.RI "#define \fBCAPI_R_GETUSERKEY_ERROR\fP   113"
.br
.ti -1c
.RI "#define \fBCAPI_R_INVALID_DIGEST_LENGTH\fP   124"
.br
.ti -1c
.RI "#define \fBCAPI_R_INVALID_DSA_PUBLIC_KEY_BLOB_MAGIC_NUMBER\fP   122"
.br
.ti -1c
.RI "#define \fBCAPI_R_INVALID_LOOKUP_METHOD\fP   114"
.br
.ti -1c
.RI "#define \fBCAPI_R_INVALID_PUBLIC_KEY_BLOB\fP   115"
.br
.ti -1c
.RI "#define \fBCAPI_R_INVALID_RSA_PUBLIC_KEY_BLOB_MAGIC_NUMBER\fP   123"
.br
.ti -1c
.RI "#define \fBCAPI_R_PUBKEY_EXPORT_ERROR\fP   116"
.br
.ti -1c
.RI "#define \fBCAPI_R_PUBKEY_EXPORT_LENGTH_ERROR\fP   117"
.br
.ti -1c
.RI "#define \fBCAPI_R_UNKNOWN_COMMAND\fP   118"
.br
.ti -1c
.RI "#define \fBCAPI_R_UNSUPPORTED_ALGORITHM_NID\fP   119"
.br
.ti -1c
.RI "#define \fBCAPI_R_UNSUPPORTED_PADDING\fP   120"
.br
.ti -1c
.RI "#define \fBCAPI_R_UNSUPPORTED_PUBLIC_KEY_ALGORITHM\fP   121"
.br
.ti -1c
.RI "#define \fBCAPI_R_WIN32_ERROR\fP   127"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAPIerr(f, r)   ERR_CAPI_error((f),(r),__FILE__,__LINE__)"

.PP
Definition at line 70 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_CERT_GET_FNAME   99"

.PP
Definition at line 75 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_CTRL   100"

.PP
Definition at line 76 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_CTX_NEW   101"

.PP
Definition at line 77 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_CTX_SET_PROVNAME   102"

.PP
Definition at line 78 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_DSA_DO_SIGN   114"

.PP
Definition at line 79 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_GET_KEY   103"

.PP
Definition at line 80 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_GET_PKEY   115"

.PP
Definition at line 81 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_GET_PROVNAME   104"

.PP
Definition at line 82 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_GET_PROV_INFO   105"

.PP
Definition at line 83 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_INIT   106"

.PP
Definition at line 84 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_LIST_CONTAINERS   107"

.PP
Definition at line 85 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_LOAD_PRIVKEY   108"

.PP
Definition at line 86 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_OPEN_STORE   109"

.PP
Definition at line 87 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_RSA_PRIV_DEC   110"

.PP
Definition at line 88 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_RSA_PRIV_ENC   111"

.PP
Definition at line 89 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CAPI_RSA_SIGN   112"

.PP
Definition at line 90 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CERT_SELECT_DIALOG   117"

.PP
Definition at line 91 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_CLIENT_CERT_SELECT   116"

.PP
Definition at line 92 of file e_capi_err\&.h\&.
.SS "#define CAPI_F_WIDE_TO_ASC   113"

.PP
Definition at line 93 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_CANT_CREATE_HASH_OBJECT   99"

.PP
Definition at line 96 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_CANT_FIND_CAPI_CONTEXT   100"

.PP
Definition at line 97 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_CANT_GET_KEY   101"

.PP
Definition at line 98 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_CANT_SET_HASH_VALUE   102"

.PP
Definition at line 99 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_CRYPTACQUIRECONTEXT_ERROR   103"

.PP
Definition at line 100 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_CRYPTENUMPROVIDERS_ERROR   104"

.PP
Definition at line 101 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_DECRYPT_ERROR   105"

.PP
Definition at line 102 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_ENGINE_NOT_INITIALIZED   106"

.PP
Definition at line 103 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_ENUMCONTAINERS_ERROR   107"

.PP
Definition at line 104 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_ERROR_ADDING_CERT   125"

.PP
Definition at line 105 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_ERROR_CREATING_STORE   126"

.PP
Definition at line 106 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_ERROR_GETTING_FRIENDLY_NAME   108"

.PP
Definition at line 107 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_ERROR_GETTING_KEY_PROVIDER_INFO   109"

.PP
Definition at line 108 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_ERROR_OPENING_STORE   110"

.PP
Definition at line 109 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_ERROR_SIGNING_HASH   111"

.PP
Definition at line 110 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_FUNCTION_NOT_SUPPORTED   112"

.PP
Definition at line 111 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_GETUSERKEY_ERROR   113"

.PP
Definition at line 112 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_INVALID_DIGEST_LENGTH   124"

.PP
Definition at line 113 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_INVALID_DSA_PUBLIC_KEY_BLOB_MAGIC_NUMBER   122"

.PP
Definition at line 114 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_INVALID_LOOKUP_METHOD   114"

.PP
Definition at line 115 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_INVALID_PUBLIC_KEY_BLOB   115"

.PP
Definition at line 116 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_INVALID_RSA_PUBLIC_KEY_BLOB_MAGIC_NUMBER   123"

.PP
Definition at line 117 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_PUBKEY_EXPORT_ERROR   116"

.PP
Definition at line 118 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_PUBKEY_EXPORT_LENGTH_ERROR   117"

.PP
Definition at line 119 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_UNKNOWN_COMMAND   118"

.PP
Definition at line 120 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_UNSUPPORTED_ALGORITHM_NID   119"

.PP
Definition at line 121 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_UNSUPPORTED_PADDING   120"

.PP
Definition at line 122 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_UNSUPPORTED_PUBLIC_KEY_ALGORITHM   121"

.PP
Definition at line 123 of file e_capi_err\&.h\&.
.SS "#define CAPI_R_WIN32_ERROR   127"

.PP
Definition at line 124 of file e_capi_err\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
