.TH "s2n-master/libcrypto-build/openssl/demos/easy_tls/easy-tls.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/demos/easy_tls/easy-tls.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtls_create_ctx_args\fP"
.br
.ti -1c
.RI "struct \fBtls_start_proxy_args\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTLS_INFO_SIZE\fP   512      /* max\&. # \fBof\fP \fBbytes\fP written to infofd */"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBssl_ctx_st\fP \fBSSL_CTX\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBtls_set_dhe1024\fP (int i, \fBvoid\fP *apparg)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtls_rand_seed\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBtls_rand_seed_from_file\fP (const char *filename, size_t n, \fBvoid\fP *apparg)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtls_rand_seed_from_memory\fP (const \fBvoid\fP *buf, size_t n)"
.br
.ti -1c
.RI "struct \fBtls_create_ctx_args\fP \fBtls_create_ctx_defaultargs\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBSSL_CTX\fP * \fBtls_create_ctx\fP (struct \fBtls_create_ctx_args\fP, \fBvoid\fP *apparg)"
.br
.ti -1c
.RI "struct \fBtls_start_proxy_args\fP \fBtls_start_proxy_defaultargs\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBtls_start_proxy\fP (struct \fBtls_start_proxy_args\fP, \fBvoid\fP *apparg)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TLS_INFO_SIZE   512      /* max\&. # \fBof\fP \fBbytes\fP written to infofd */"

.PP
Definition at line 17 of file easy\-tls\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBssl_ctx_st\fP \fBSSL_CTX\fP"

.PP
Definition at line 14 of file easy\-tls\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP tls_set_dhe1024 (int i, \fBvoid\fP * apparg)"

.SS "\fBvoid\fP tls_rand_seed (\fBvoid\fP)"

.SS "int tls_rand_seed_from_file (const char * filename, size_t n, \fBvoid\fP * apparg)"

.SS "\fBvoid\fP tls_rand_seed_from_memory (const \fBvoid\fP * buf, size_t n)"

.SS "struct \fBtls_create_ctx_args\fP tls_create_ctx_defaultargs (\fBvoid\fP)"

.SS "\fBSSL_CTX\fP* tls_create_ctx (struct \fBtls_create_ctx_args\fP, \fBvoid\fP * apparg)"

.SS "struct \fBtls_start_proxy_args\fP tls_start_proxy_defaultargs (\fBvoid\fP)"

.SS "int tls_start_proxy (struct \fBtls_start_proxy_args\fP, \fBvoid\fP * apparg)"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
