.TH "ecdh_method" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecdh_method \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ech_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "int(* \fBcompute_key\fP )(\fBvoid\fP *key, size_t outlen, const \fBEC_POINT\fP *pub_key, \fBEC_KEY\fP *ecdh, \fBvoid\fP *(*KDF)(const \fBvoid\fP *in,                                                                                                                                                                                                       size_t inlen, \fBvoid\fP *out,                                                                                                                                                                                                       size_t *outlen))"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "char * \fBapp_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file ech_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const char* name"

.PP
Definition at line 66 of file ech_locl\&.h\&.
.SS "int(* compute_key) (\fBvoid\fP *key, size_t outlen, const \fBEC_POINT\fP *pub_key, \fBEC_KEY\fP *ecdh, \fBvoid\fP *(*KDF)(const \fBvoid\fP *in,                                                                                                     size_t inlen, \fBvoid\fP *out,                                                                                                     size_t *outlen))"

.PP
Definition at line 67 of file ech_locl\&.h\&.
.SS "int flags"

.PP
Definition at line 75 of file ech_locl\&.h\&.
.SS "char* app_data"

.PP
Definition at line 76 of file ech_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
