.TH "ecdsa_method" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecdsa_method \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ecs_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBECDSA_SIG\fP *(* \fBecdsa_do_sign\fP )(const unsigned char *dgst, int dgst_len, const \fBBIGNUM\fP *inv, const \fBBIGNUM\fP *rp, \fBEC_KEY\fP *eckey)"
.br
.ti -1c
.RI "int(* \fBecdsa_sign_setup\fP )(\fBEC_KEY\fP *eckey, \fBBN_CTX\fP *ctx, \fBBIGNUM\fP **kinv, \fBBIGNUM\fP **r)"
.br
.ti -1c
.RI "int(* \fBecdsa_do_verify\fP )(const unsigned char *dgst, int dgst_len, const \fBECDSA_SIG\fP *sig, \fBEC_KEY\fP *eckey)"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBapp_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file ecs_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const char* name"

.PP
Definition at line 69 of file ecs_locl\&.h\&.
.SS "\fBECDSA_SIG\fP*(* ecdsa_do_sign) (const unsigned char *dgst, int dgst_len, const \fBBIGNUM\fP *inv, const \fBBIGNUM\fP *rp, \fBEC_KEY\fP *eckey)"

.PP
Definition at line 70 of file ecs_locl\&.h\&.
.SS "int(* ecdsa_sign_setup) (\fBEC_KEY\fP *eckey, \fBBN_CTX\fP *ctx, \fBBIGNUM\fP **kinv, \fBBIGNUM\fP **r)"

.PP
Definition at line 73 of file ecs_locl\&.h\&.
.SS "int(* ecdsa_do_verify) (const unsigned char *dgst, int dgst_len, const \fBECDSA_SIG\fP *sig, \fBEC_KEY\fP *eckey)"

.PP
Definition at line 75 of file ecs_locl\&.h\&.
.SS "int flags"

.PP
Definition at line 81 of file ecs_locl\&.h\&.
.SS "\fBvoid\fP* app_data"

.PP
Definition at line 82 of file ecs_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
