.TH "ecdsa_data_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ecdsa_data_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ecs_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBinit\fP )(\fBEC_KEY\fP *)"
.br
.ti -1c
.RI "\fBENGINE\fP * \fBengine\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "const \fBECDSA_METHOD\fP * \fBmeth\fP"
.br
.ti -1c
.RI "\fBCRYPTO_EX_DATA\fP \fBex_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 98 of file ecs_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int(* init) (\fBEC_KEY\fP *)"

.PP
Definition at line 100 of file ecs_locl\&.h\&.
.SS "\fBENGINE\fP* engine"

.PP
Definition at line 102 of file ecs_locl\&.h\&.
.SS "int flags"

.PP
Definition at line 103 of file ecs_locl\&.h\&.
.SS "const \fBECDSA_METHOD\fP* meth"

.PP
Definition at line 104 of file ecs_locl\&.h\&.
.SS "\fBCRYPTO_EX_DATA\fP ex_data"

.PP
Definition at line 105 of file ecs_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
