.TH "s2n-master/libcrypto-build/openssl/crypto/ecdh/ech_locl.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/crypto/ecdh/ech_locl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/ecdh\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBecdh_method\fP"
.br
.ti -1c
.RI "struct \fBecdh_data_st\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBECDH_FLAG_FIPS_METHOD\fP   0x1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBecdh_data_st\fP \fBECDH_DATA\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBECDH_DATA\fP * \fBecdh_check\fP (\fBEC_KEY\fP *)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ECDH_FLAG_FIPS_METHOD   0x1"

.PP
Definition at line 86 of file ech_locl\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBecdh_data_st\fP  \fBECDH_DATA\fP"

.SH "Function Documentation"
.PP 
.SS "\fBECDH_DATA\fP* ecdh_check (\fBEC_KEY\fP *)"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
