.TH "s2n-master/libcrypto-build/openssl/crypto/x509v3/ext_dat.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/crypto/x509v3/ext_dat.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTANDARD_EXTENSION_COUNT\fP   (sizeof(standard_exts)/sizeof(\fBX509V3_EXT_METHOD\fP *))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_bcons\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_nscert\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_key_usage\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_ext_ku\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_pkey_usage_period\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_sxnet\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_info\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_sinfo\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_ns_ia5_list\fP []"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_alt\fP []"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_skey_id\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_akey_id\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_crl_num\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_crl_reason\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_crl_invdate\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_delta_crl\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_cpols\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_crld\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_freshest_crl\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_ocsp_nonce\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_ocsp_accresp\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_ocsp_acutoff\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_ocsp_crlid\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_ocsp_nocheck\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_ocsp_serviceloc\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_crl_hold\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_pci\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_policy_mappings\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_policy_constraints\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_name_constraints\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_inhibit_anyp\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_idp\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_addr\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_asid\fP"
.br
.ti -1c
.RI "\fBX509V3_EXT_METHOD\fP \fBv3_ct_scts\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STANDARD_EXTENSION_COUNT   (sizeof(standard_exts)/sizeof(\fBX509V3_EXT_METHOD\fP *))"

.PP
Definition at line 136 of file ext_dat\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "\fBX509V3_EXT_METHOD\fP v3_bcons"

.SS "\fBX509V3_EXT_METHOD\fP v3_nscert"

.SS "\fBX509V3_EXT_METHOD\fP v3_key_usage"

.SS "\fBX509V3_EXT_METHOD\fP v3_ext_ku"

.SS "\fBX509V3_EXT_METHOD\fP v3_pkey_usage_period"

.SS "\fBX509V3_EXT_METHOD\fP v3_sxnet"

.SS "\fBX509V3_EXT_METHOD\fP v3_info"

.SS "\fBX509V3_EXT_METHOD\fP v3_sinfo"

.SS "\fBX509V3_EXT_METHOD\fP v3_ns_ia5_list[]"

.SS "\fBX509V3_EXT_METHOD\fP v3_alt[]"

.SS "\fBX509V3_EXT_METHOD\fP v3_skey_id"

.SS "\fBX509V3_EXT_METHOD\fP v3_akey_id"

.SS "\fBX509V3_EXT_METHOD\fP v3_crl_num"

.SS "\fBX509V3_EXT_METHOD\fP v3_crl_reason"

.SS "\fBX509V3_EXT_METHOD\fP v3_crl_invdate"

.SS "\fBX509V3_EXT_METHOD\fP v3_delta_crl"

.SS "\fBX509V3_EXT_METHOD\fP v3_cpols"

.SS "\fBX509V3_EXT_METHOD\fP v3_crld"

.SS "\fBX509V3_EXT_METHOD\fP v3_freshest_crl"

.SS "\fBX509V3_EXT_METHOD\fP v3_ocsp_nonce"

.SS "\fBX509V3_EXT_METHOD\fP v3_ocsp_accresp"

.SS "\fBX509V3_EXT_METHOD\fP v3_ocsp_acutoff"

.SS "\fBX509V3_EXT_METHOD\fP v3_ocsp_crlid"

.SS "\fBX509V3_EXT_METHOD\fP v3_ocsp_nocheck"

.SS "\fBX509V3_EXT_METHOD\fP v3_ocsp_serviceloc"

.SS "\fBX509V3_EXT_METHOD\fP v3_crl_hold"

.SS "\fBX509V3_EXT_METHOD\fP v3_pci"

.SS "\fBX509V3_EXT_METHOD\fP v3_policy_mappings"

.SS "\fBX509V3_EXT_METHOD\fP v3_policy_constraints"

.SS "\fBX509V3_EXT_METHOD\fP v3_name_constraints"

.SS "\fBX509V3_EXT_METHOD\fP v3_inhibit_anyp"

.SS "\fBX509V3_EXT_METHOD\fP v3_idp"

.SS "\fBX509V3_EXT_METHOD\fP v3_addr"

.SS "\fBX509V3_EXT_METHOD\fP v3_asid"

.SS "\fBX509V3_EXT_METHOD\fP v3_ct_scts[]"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
