.TH "gost_pmeth_data" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gost_pmeth_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gost_lcl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsign_param_nid\fP"
.br
.ti -1c
.RI "\fBEVP_MD\fP * \fBmd\fP"
.br
.ti -1c
.RI "unsigned char * \fBshared_ukm\fP"
.br
.ti -1c
.RI "int \fBpeer_key_used\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file gost_lcl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int sign_param_nid"

.PP
Definition at line 48 of file gost_lcl\&.h\&.
.SS "\fBEVP_MD\fP* md"

.PP
Definition at line 50 of file gost_lcl\&.h\&.
.SS "unsigned char* shared_ukm"

.PP
Definition at line 51 of file gost_lcl\&.h\&.
.SS "int peer_key_used"

.PP
Definition at line 52 of file gost_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
