.TH "srtp.h" 3 "Fri Aug 12 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srtp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/ssl\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSRTP_AES128_CM_SHA1_80\fP   0x0001"
.br
.ti -1c
.RI "#define \fBSRTP_AES128_CM_SHA1_32\fP   0x0002"
.br
.ti -1c
.RI "#define \fBSRTP_AES128_F8_SHA1_80\fP   0x0003"
.br
.ti -1c
.RI "#define \fBSRTP_AES128_F8_SHA1_32\fP   0x0004"
.br
.ti -1c
.RI "#define \fBSRTP_NULL_SHA1_80\fP   0x0005"
.br
.ti -1c
.RI "#define \fBSRTP_NULL_SHA1_32\fP   0x0006"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBSSL_CTX_set_tlsext_use_srtp\fP (\fBSSL_CTX\fP *ctx, const char *profiles)"
.br
.ti -1c
.RI "int \fBSSL_set_tlsext_use_srtp\fP (\fBSSL\fP *ctx, const char *profiles)"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBSRTP_PROTECTION_PROFILE\fP)*SSL_get_srtp_profiles(\fBSSL\fP *ssl)"
.br
.ti -1c
.RI "\fBSRTP_PROTECTION_PROFILE\fP * \fBSSL_get_selected_srtp_profile\fP (\fBSSL\fP *s)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SRTP_AES128_CM_SHA1_32   0x0002"

.PP
Definition at line 127 of file include/openssl/srtp\&.h\&.
.SS "#define SRTP_AES128_CM_SHA1_80   0x0001"

.PP
Definition at line 126 of file include/openssl/srtp\&.h\&.
.SS "#define SRTP_AES128_F8_SHA1_32   0x0004"

.PP
Definition at line 129 of file include/openssl/srtp\&.h\&.
.SS "#define SRTP_AES128_F8_SHA1_80   0x0003"

.PP
Definition at line 128 of file include/openssl/srtp\&.h\&.
.SS "#define SRTP_NULL_SHA1_32   0x0006"

.PP
Definition at line 131 of file include/openssl/srtp\&.h\&.
.SS "#define SRTP_NULL_SHA1_80   0x0005"

.PP
Definition at line 130 of file include/openssl/srtp\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int SSL_CTX_set_tlsext_use_srtp (\fBSSL_CTX\fP * ctx, const char * profiles)"

.SS "\fBSRTP_PROTECTION_PROFILE\fP* SSL_get_selected_srtp_profile (\fBSSL\fP * s)"

.SS "int SSL_set_tlsext_use_srtp (\fBSSL\fP * ctx, const char * profiles)"

.SS "STACK_OF (\fBSRTP_PROTECTION_PROFILE\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
