.TH "rc2.h" 3 "Fri Aug 12 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rc2.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/opensslconf\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBrc2_key_st\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRC2_ENCRYPT\fP   1"
.br
.ti -1c
.RI "#define \fBRC2_DECRYPT\fP   0"
.br
.ti -1c
.RI "#define \fBRC2_BLOCK\fP   8"
.br
.ti -1c
.RI "#define \fBRC2_KEY_LENGTH\fP   16"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBrc2_key_st\fP \fBRC2_KEY\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBRC2_set_key\fP (\fBRC2_KEY\fP *key, int \fBlen\fP, const unsigned char *data, int \fBbits\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRC2_ecb_encrypt\fP (const unsigned char *in, unsigned char *out, \fBRC2_KEY\fP *key, int enc)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRC2_encrypt\fP (unsigned long *data, \fBRC2_KEY\fP *key)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRC2_decrypt\fP (unsigned long *data, \fBRC2_KEY\fP *key)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRC2_cbc_encrypt\fP (const unsigned char *in, unsigned char *out, long \fBlength\fP, \fBRC2_KEY\fP *ks, unsigned char *iv, int enc)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRC2_cfb64_encrypt\fP (const unsigned char *in, unsigned char *out, long \fBlength\fP, \fBRC2_KEY\fP *schedule, unsigned char *ivec, int *\fBnum\fP, int enc)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRC2_ofb64_encrypt\fP (const unsigned char *in, unsigned char *out, long \fBlength\fP, \fBRC2_KEY\fP *schedule, unsigned char *ivec, int *\fBnum\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define RC2_BLOCK   8"

.PP
Definition at line 70 of file include/openssl/rc2\&.h\&.
.SS "#define RC2_DECRYPT   0"

.PP
Definition at line 68 of file include/openssl/rc2\&.h\&.
.SS "#define RC2_ENCRYPT   1"

.PP
Definition at line 67 of file include/openssl/rc2\&.h\&.
.SS "#define RC2_KEY_LENGTH   16"

.PP
Definition at line 71 of file include/openssl/rc2\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBrc2_key_st\fP  \fBRC2_KEY\fP"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP RC2_cbc_encrypt (const unsigned char * in, unsigned char * out, long length, \fBRC2_KEY\fP * ks, unsigned char * iv, int enc)"

.SS "\fBvoid\fP RC2_cfb64_encrypt (const unsigned char * in, unsigned char * out, long length, \fBRC2_KEY\fP * schedule, unsigned char * ivec, int * num, int enc)"

.SS "\fBvoid\fP RC2_decrypt (unsigned long * data, \fBRC2_KEY\fP * key)"

.SS "\fBvoid\fP RC2_ecb_encrypt (const unsigned char * in, unsigned char * out, \fBRC2_KEY\fP * key, int enc)"

.SS "\fBvoid\fP RC2_encrypt (unsigned long * data, \fBRC2_KEY\fP * key)"

.SS "\fBvoid\fP RC2_ofb64_encrypt (const unsigned char * in, unsigned char * out, long length, \fBRC2_KEY\fP * schedule, unsigned char * ivec, int * num)"

.SS "\fBvoid\fP RC2_set_key (\fBRC2_KEY\fP * key, int len, const unsigned char * data, int bits)"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
