.TH "ItemStr" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemStr \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <atalla\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "int \fBlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13 of file atalla\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char* data"

.PP
Definition at line 14 of file atalla\&.h\&.
.SS "int len"

.PP
Definition at line 15 of file atalla\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
