.TH "krb5_tktbody_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
krb5_tktbody_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <krb5_asn\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBtktvno\fP"
.br
.ti -1c
.RI "\fBASN1_GENERALSTRING\fP * \fBrealm\fP"
.br
.ti -1c
.RI "\fBKRB5_PRINCNAME\fP * \fBsname\fP"
.br
.ti -1c
.RI "\fBKRB5_ENCDATA\fP * \fBencdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 110 of file krb5_asn\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBASN1_INTEGER\fP * tktvno"

.PP
Definition at line 111 of file krb5_asn\&.h\&.
.SS "\fBASN1_GENERALSTRING\fP * realm"

.PP
Definition at line 112 of file krb5_asn\&.h\&.
.SS "\fBKRB5_PRINCNAME\fP * sname"

.PP
Definition at line 113 of file krb5_asn\&.h\&.
.SS "\fBKRB5_ENCDATA\fP * encdata"

.PP
Definition at line 114 of file krb5_asn\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
