.TH "s2n-master/libcrypto-build/openssl/include/openssl/krb5_asn.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/include/openssl/krb5_asn.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/safestack\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBkrb5_encdata_st\fP"
.br
.ti -1c
.RI "struct \fBkrb5_princname_st\fP"
.br
.ti -1c
.RI "struct \fBkrb5_tktbody_st\fP"
.br
.ti -1c
.RI "struct \fBkrb5_ap_req_st\fP"
.br
.ti -1c
.RI "struct \fBkrb5_checksum_st\fP"
.br
.ti -1c
.RI "struct \fBkrb5_encryptionkey_st\fP"
.br
.ti -1c
.RI "struct \fBkrb5_authorization_st\fP"
.br
.ti -1c
.RI "struct \fBkrb5_authenticator_st\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBkrb5_encdata_st\fP \fBKRB5_ENCDATA\fP"
.br
.ti -1c
.RI "typedef struct \fBkrb5_princname_st\fP \fBKRB5_PRINCNAME\fP"
.br
.ti -1c
.RI "typedef struct \fBkrb5_tktbody_st\fP \fBKRB5_TKTBODY\fP"
.br
.ti -1c
.RI "typedef struct \fBkrb5_ap_req_st\fP \fBKRB5_APREQBODY\fP"
.br
.ti -1c
.RI "typedef struct \fBkrb5_checksum_st\fP \fBKRB5_CHECKSUM\fP"
.br
.ti -1c
.RI "typedef struct \fBkrb5_encryptionkey_st\fP \fBKRB5_ENCKEY\fP"
.br
.ti -1c
.RI "typedef struct \fBkrb5_authorization_st\fP \fBKRB5_AUTHDATA\fP"
.br
.ti -1c
.RI "typedef struct \fBkrb5_authenticator_st\fP \fBKRB5_AUTHENTBODY\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "typedef \fBSTACK_OF\fP (\fBKRB5_TKTBODY\fP) KRB5_TICKET"
.br
.ti -1c
.RI "typedef \fBSTACK_OF\fP (\fBKRB5_APREQBODY\fP) KRB5_APREQ"
.br
.ti -1c
.RI "typedef \fBSTACK_OF\fP (\fBKRB5_AUTHENTBODY\fP) KRB5_AUTHENT"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBkrb5_encdata_st\fP  \fBKRB5_ENCDATA\fP"

.SS "typedef struct \fBkrb5_princname_st\fP  \fBKRB5_PRINCNAME\fP"

.SS "typedef struct \fBkrb5_tktbody_st\fP  \fBKRB5_TKTBODY\fP"

.SS "typedef struct \fBkrb5_ap_req_st\fP  \fBKRB5_APREQBODY\fP"

.SS "typedef struct \fBkrb5_checksum_st\fP  \fBKRB5_CHECKSUM\fP"

.SS "typedef struct \fBkrb5_encryptionkey_st\fP  \fBKRB5_ENCKEY\fP"

.SS "typedef struct \fBkrb5_authorization_st\fP  \fBKRB5_AUTHDATA\fP"

.SS "typedef struct \fBkrb5_authenticator_st\fP  \fBKRB5_AUTHENTBODY\fP"

.SH "Function Documentation"
.PP 
.SS "typedef STACK_OF (\fBKRB5_TKTBODY\fP)"

.SS "typedef STACK_OF (\fBKRB5_APREQBODY\fP)"

.SS "typedef STACK_OF (\fBKRB5_AUTHENTBODY\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
