.TH "s2n-master/libcrypto-build/openssl/ssl/kssl_lcl.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/ssl/kssl_lcl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/kssl\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBprint_krb5_data\fP (char *label, krb5_data *kdata)"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint_krb5_authdata\fP (char *label, krb5_authdata **adata)"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint_krb5_keyblock\fP (char *label, krb5_keyblock *keyblk)"
.br
.ti -1c
.RI "char * \fBkstring\fP (char *string)"
.br
.ti -1c
.RI "char * \fBknumber\fP (int \fBlen\fP, krb5_octet *contents)"
.br
.ti -1c
.RI "const \fBEVP_CIPHER\fP * \fBkssl_map_enc\fP (krb5_enctype enctype)"
.br
.ti -1c
.RI "int \fBkssl_keytab_is_available\fP (\fBKSSL_CTX\fP *kssl_ctx)"
.br
.ti -1c
.RI "int \fBkssl_tgt_is_available\fP (\fBKSSL_CTX\fP *kssl_ctx)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP print_krb5_data (char * label, krb5_data * kdata)"

.SS "\fBvoid\fP print_krb5_authdata (char * label, krb5_authdata ** adata)"

.SS "\fBvoid\fP print_krb5_keyblock (char * label, krb5_keyblock * keyblk)"

.SS "char* kstring (char * string)"

.SS "char* knumber (int len, krb5_octet * contents)"

.SS "const \fBEVP_CIPHER\fP* kssl_map_enc (krb5_enctype enctype)"

.SS "int kssl_keytab_is_available (\fBKSSL_CTX\fP * kssl_ctx)"

.SS "int kssl_tgt_is_available (\fBKSSL_CTX\fP * kssl_ctx)"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
