.TH "md___users__issac_lam__downloads_s2n-master_docs__r_e_a_d_i_n_g-_l_i_s_t" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___users__issac_lam__downloads_s2n-master_docs__r_e_a_d_i_n_g-_l_i_s_t \- Useful Reading list for s2n 

.SS "Books"
.PP
.IP "\(bu" 2
\fCBulletproof SSL and TLS\fP - great book by Ivan Ristic\&.
.IP "\(bu" 2
\fCImplementing SSL / TLS using Cryptography and PKI\fP - by Joshua Davies\&.
.IP "\(bu" 2
\fCIntroduction to Modern Cryptography, 2nd ed\fP - Katz and Lindell
.PP
.PP
.SS "RFCs and specifications relating to TLS/SSL"
.PP
.IP "\(bu" 2
\fCSSLv2\fP
.IP "\(bu" 2
\fCSSLv3\fP
.IP "\(bu" 2
\fCTLS 1\&.0\fP
.IP "\(bu" 2
\fCTLS 1\&.1\fP
.IP "\(bu" 2
\fCTLS 1\&.2\fP
.IP "\(bu" 2
\fCAES GCM for TLS\fP
.IP "\(bu" 2
\fCECC cipher suites for TLS\fP
.IP "\(bu" 2
\fCTLS extensions\fP
.IP "\(bu" 2
\fCApplication-Layer Protocol Negotiation Extension\fP
.IP "\(bu" 2
\fCTLS 1\&.3 draft specification\fP
.IP "\(bu" 2
\fCSSLv3 is deprecated\fP
.PP
.PP
.SS "ASN\&.1 and X509"
.PP
.IP "\(bu" 2
\fCX\&.509 PKI\fP
.IP "\(bu" 2
\fCX\&.509 PKI and CRLs\fP
.IP "\(bu" 2
\fCLayman's Guide to ASN\&.1\fP
.PP
.PP
.SS "Interesting implementations"
.PP
.IP "\(bu" 2
\fCMiTLS\fP , and \fCTLS Attacks\fP in particular\&.
.IP "\(bu" 2
\fCGoTLS\fP - TLS as implemented in the Go programming language
.IP "\(bu" 2
\fCOpenSSL\fP - ubiquitous and reference implementation
.IP "\(bu" 2
\fCLibreSSL\fP - fork of OpenSSL maintained by a team from OpenBSD
.IP "\(bu" 2
\fCBoringSSL\fP - fork of OpenSSL maintained by Google Security team
.IP "\(bu" 2
\fCNSS\fP - maintained by Mozilla, used by several browsers
.PP
.PP
.SS "Mailing lists and forums"
.PP
.IP "\(bu" 2
\fCIETF TLS Working Group\fP
.IP "\(bu" 2
\fCIETF CRFG\fP
.PP
.PP
.SS "Videos and tutorials"
.PP
.IP "\(bu" 2
\fCSSL with Amazon Web Services\fP - nuts and bolts overview of SSL/TLS
.PP
.PP
.SS "Miscellaneous"
.PP
.IP "\(bu" 2
\fCNIST SP 800-90A\fP
.IP "\(bu" 2
\fCDJBs crypto page\fP
.IP "\(bu" 2
\fCDJBs entropy attacks\fP
.IP "\(bu" 2
\fCNaCL\fP and \fClibsodium\fP
.IP "\(bu" 2
\fCspiped\fP 
.PP

