.TH "mdc2_ctx_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mdc2_ctx_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mdc2\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBnum\fP"
.br
.ti -1c
.RI "unsigned char \fBdata\fP [\fBMDC2_BLOCK\fP]"
.br
.ti -1c
.RI "\fBDES_cblock\fP \fBh\fP"
.br
.ti -1c
.RI "\fBDES_cblock\fP \fBhh\fP"
.br
.ti -1c
.RI "int \fBpad_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file mdc2\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned int num"

.PP
Definition at line 76 of file mdc2\&.h\&.
.SS "unsigned char data[\fBMDC2_BLOCK\fP]"

.PP
Definition at line 77 of file mdc2\&.h\&.
.SS "\fBDES_cblock\fP h"

.PP
Definition at line 78 of file mdc2\&.h\&.
.SS "\fBDES_cblock\fP hh"

.PP
Definition at line 78 of file mdc2\&.h\&.
.SS "int pad_type"

.PP
Definition at line 79 of file mdc2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
