.TH "nid_triple" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nid_triple \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <obj_xref\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsign_id\fP"
.br
.ti -1c
.RI "int \fBhash_id\fP"
.br
.ti -1c
.RI "int \fBpkey_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file obj_xref\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int sign_id"

.PP
Definition at line 4 of file obj_xref\&.h\&.
.SS "int hash_id"

.PP
Definition at line 5 of file obj_xref\&.h\&.
.SS "int pkey_id"

.PP
Definition at line 6 of file obj_xref\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
