.TH "ocsp_response_data_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ocsp_response_data_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ocsp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBOCSP_SINGLERESP\fP)*responses"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_EXTENSION\fP)*responseExtensions"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBOCSP_SINGLERESP\fP)*responses"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_EXTENSION\fP)*responseExtensions"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBversion\fP"
.br
.ti -1c
.RI "\fBOCSP_RESPID\fP * \fBresponderId\fP"
.br
.ti -1c
.RI "\fBASN1_GENERALIZEDTIME\fP * \fBproducedAt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 263 of file ocsp\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBOCSP_SINGLERESP\fP)"

.SS "STACK_OF (\fBX509_EXTENSION\fP)"

.SS "STACK_OF (\fBOCSP_SINGLERESP\fP)"

.SS "STACK_OF (\fBX509_EXTENSION\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBASN1_INTEGER\fP * version"

.PP
Definition at line 264 of file ocsp\&.h\&.
.SS "\fBOCSP_RESPID\fP * responderId"

.PP
Definition at line 265 of file ocsp\&.h\&.
.SS "\fBASN1_GENERALIZEDTIME\fP * producedAt"

.PP
Definition at line 266 of file ocsp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
