.TH "openssl_item_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
openssl_item_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crypto\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBvalue\fP"
.br
.ti -1c
.RI "size_t \fBvalue_size\fP"
.br
.ti -1c
.RI "size_t * \fBvalue_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 175 of file crypto\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int code"

.PP
Definition at line 176 of file crypto\&.h\&.
.SS "\fBvoid\fP * value"

.PP
Definition at line 177 of file crypto\&.h\&.
.SS "size_t value_size"

.PP
Definition at line 178 of file crypto\&.h\&.
.SS "size_t * value_length"

.PP
Definition at line 180 of file crypto\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
