.TH "ossl_gost_digest_ctx" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ossl_gost_digest_ctx \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gost_lcl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBgost_hash_ctx\fP \fBdctx\fP"
.br
.ti -1c
.RI "\fBgost_ctx\fP \fBcctx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 129 of file gost_lcl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBgost_hash_ctx\fP dctx"

.PP
Definition at line 130 of file gost_lcl\&.h\&.
.SS "\fBgost_ctx\fP cctx"

.PP
Definition at line 131 of file gost_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
