.TH "otherName_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
otherName_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <x509v3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBtype_id\fP"
.br
.ti -1c
.RI "\fBASN1_TYPE\fP * \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 167 of file x509v3\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBASN1_OBJECT\fP * type_id"

.PP
Definition at line 168 of file x509v3\&.h\&.
.SS "\fBASN1_TYPE\fP * value"

.PP
Definition at line 169 of file x509v3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
