.TH "PKCS12_SAFEBAG" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PKCS12_SAFEBAG \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pkcs12\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ATTRIBUTE\fP)*attrib"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ATTRIBUTE\fP)*attrib"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct \fBpkcs12_bag_st\fP * \fBbag\fP"
.br
.ti -1c
.RI "   struct \fBpkcs8_priv_key_info_st\fP * \fBkeybag\fP"
.br
.ti -1c
.RI "   \fBX509_SIG\fP * \fBshkeybag\fP"
.br
.ti -1c
.RI "   \fBASN1_TYPE\fP * \fBother\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct \fBpkcs12_bag_st\fP * \fBbag\fP"
.br
.ti -1c
.RI "   struct \fBpkcs8_priv_key_info_st\fP * \fBkeybag\fP"
.br
.ti -1c
.RI "   \fBX509_SIG\fP * \fBshkeybag\fP"
.br
.ti -1c
.RI "   \fBASN1_TYPE\fP * \fBother\fP"
.br
.ti -1c
.RI "} \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 114 of file pkcs12\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBX509_ATTRIBUTE\fP)"

.SS "STACK_OF (\fBX509_ATTRIBUTE\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBASN1_OBJECT\fP * type"

.PP
Definition at line 115 of file pkcs12\&.h\&.
.SS "struct \fBpkcs12_bag_st\fP* bag"

.PP
Definition at line 117 of file pkcs12\&.h\&.
.SS "struct \fBpkcs8_priv_key_info_st\fP* keybag"

.PP
Definition at line 118 of file pkcs12\&.h\&.
.SS "\fBX509_SIG\fP* shkeybag"

.PP
Definition at line 119 of file pkcs12\&.h\&.
.SS "\fBASN1_TYPE\fP* other"

.PP
Definition at line 121 of file pkcs12\&.h\&.
.SS "union { \&.\&.\&. }   value"

.SS "union { \&.\&.\&. }   value"


.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
