.TH "pkcs7_recip_info_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pkcs7_recip_info_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pkcs7\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBversion\fP"
.br
.ti -1c
.RI "\fBPKCS7_ISSUER_AND_SERIAL\fP * \fBissuer_and_serial\fP"
.br
.ti -1c
.RI "\fBX509_ALGOR\fP * \fBkey_enc_algor\fP"
.br
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBenc_key\fP"
.br
.ti -1c
.RI "\fBX509\fP * \fBcert\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 106 of file pkcs7\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBASN1_INTEGER\fP * version"

.PP
Definition at line 107 of file pkcs7\&.h\&.
.SS "\fBPKCS7_ISSUER_AND_SERIAL\fP * issuer_and_serial"

.PP
Definition at line 108 of file pkcs7\&.h\&.
.SS "\fBX509_ALGOR\fP * key_enc_algor"

.PP
Definition at line 109 of file pkcs7\&.h\&.
.SS "\fBASN1_OCTET_STRING\fP * enc_key"

.PP
Definition at line 110 of file pkcs7\&.h\&.
.SS "\fBX509\fP * cert"

.PP
Definition at line 111 of file pkcs7\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
