.TH "s2n_session_key" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n_session_key \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <s2n_cipher\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBRC4_KEY\fP \fBrc4\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBDES_key_schedule\fP \fBdks1\fP"
.br
.ti -1c
.RI "      \fBDES_key_schedule\fP \fBdks2\fP"
.br
.ti -1c
.RI "      \fBDES_key_schedule\fP \fBdks3\fP"
.br
.ti -1c
.RI "   } \fBdes\fP"
.br
.ti -1c
.RI "   \fBEVP_CIPHER_CTX\fP \fBevp_cipher_ctx\fP"
.br
.ti -1c
.RI "} \fBnative_format\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file s2n_cipher\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBRC4_KEY\fP rc4"

.PP
Definition at line 31 of file s2n_cipher\&.h\&.
.SS "\fBDES_key_schedule\fP dks1"

.PP
Definition at line 33 of file s2n_cipher\&.h\&.
.SS "\fBDES_key_schedule\fP dks2"

.PP
Definition at line 34 of file s2n_cipher\&.h\&.
.SS "\fBDES_key_schedule\fP dks3"

.PP
Definition at line 35 of file s2n_cipher\&.h\&.
.SS "struct { \&.\&.\&. }   des"

.SS "\fBEVP_CIPHER_CTX\fP evp_cipher_ctx"

.PP
Definition at line 37 of file s2n_cipher\&.h\&.
.SS "union { \&.\&.\&. }   native_format"


.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
