.TH "s2n-master/tls/s2n_alerts.c" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/tls/s2n_alerts.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <sys/param\&.h>\fP
.br
\fC#include 'error/s2n_errno\&.h'\fP
.br
\fC#include 'tls/s2n_tls_parameters\&.h'\fP
.br
\fC#include 'tls/s2n_connection\&.h'\fP
.br
\fC#include 'tls/s2n_record\&.h'\fP
.br
\fC#include 'tls/s2n_resume\&.h'\fP
.br
\fC#include 'tls/s2n_alerts\&.h'\fP
.br
\fC#include 'utils/s2n_safety\&.h'\fP
.br
\fC#include 'utils/s2n_blob\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_CLOSE_NOTIFY\fP   0"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_UNEXPECTED_MSG\fP   10"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_BAD_RECORD_MAC\fP   20"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_DECRIPT_FAILED\fP   21"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_RECORD_OVERFLOW\fP   22"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_DECOMP_FAILED\fP   30"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_HANDSHAKE_FAILED\fP   40"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_NO_CERTIFICATE\fP   41"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_BAD_CERTIFICATE\fP   42"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_UNSUPPORTED_CERT\fP   43"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_CERT_REVOKED\fP   44"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_CERT_EXPIRED\fP   45"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_CERT_UNKNOWN\fP   46"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_ILLEGAL_PARAMETER\fP   47"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_UNKNOWN_CA\fP   48"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_ACCESS_DENIED\fP   49"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_DECODE_ERROR\fP   50"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_DECRYPT_ERROR\fP   51"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_EXPORT_RESTRICTED\fP   60"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_PROTOCOL_VERSION\fP   70"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_INSUFFICIENT_SECURITY\fP   71"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_INTERNAL_ERROR\fP   80"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_USER_CANCELED\fP   90"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_NO_RENEGOTIATION\fP   100"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_UNSUPPORTED_EXTENSION\fP   110"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_LEVEL_WARNING\fP   1"
.br
.ti -1c
.RI "#define \fBS2N_TLS_ALERT_LEVEL_FATAL\fP   2"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBs2n_process_alert_fragment\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_queue_writer_close_alert_warning\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_queue_reader_unsupported_protocol_version_alert\fP (struct \fBs2n_connection\fP *conn)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define S2N_TLS_ALERT_CLOSE_NOTIFY   0"

.PP
Definition at line 30 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_UNEXPECTED_MSG   10"

.PP
Definition at line 31 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_BAD_RECORD_MAC   20"

.PP
Definition at line 32 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_DECRIPT_FAILED   21"

.PP
Definition at line 33 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_RECORD_OVERFLOW   22"

.PP
Definition at line 34 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_DECOMP_FAILED   30"

.PP
Definition at line 35 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_HANDSHAKE_FAILED   40"

.PP
Definition at line 36 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_NO_CERTIFICATE   41"

.PP
Definition at line 37 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_BAD_CERTIFICATE   42"

.PP
Definition at line 38 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_UNSUPPORTED_CERT   43"

.PP
Definition at line 39 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_CERT_REVOKED   44"

.PP
Definition at line 40 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_CERT_EXPIRED   45"

.PP
Definition at line 41 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_CERT_UNKNOWN   46"

.PP
Definition at line 42 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_ILLEGAL_PARAMETER   47"

.PP
Definition at line 43 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_UNKNOWN_CA   48"

.PP
Definition at line 44 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_ACCESS_DENIED   49"

.PP
Definition at line 45 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_DECODE_ERROR   50"

.PP
Definition at line 46 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_DECRYPT_ERROR   51"

.PP
Definition at line 47 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_EXPORT_RESTRICTED   60"

.PP
Definition at line 48 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_PROTOCOL_VERSION   70"

.PP
Definition at line 49 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_INSUFFICIENT_SECURITY   71"

.PP
Definition at line 50 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_INTERNAL_ERROR   80"

.PP
Definition at line 51 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_USER_CANCELED   90"

.PP
Definition at line 52 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_NO_RENEGOTIATION   100"

.PP
Definition at line 53 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_UNSUPPORTED_EXTENSION   110"

.PP
Definition at line 54 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_LEVEL_WARNING   1"

.PP
Definition at line 56 of file s2n_alerts\&.c\&.
.SS "#define S2N_TLS_ALERT_LEVEL_FATAL   2"

.PP
Definition at line 57 of file s2n_alerts\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int s2n_process_alert_fragment (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 59 of file s2n_alerts\&.c\&.
.PP
.nf
60 {
61     if (s2n_stuffer_data_available(&conn->alert_in) == 2) {
62         S2N_ERROR(S2N_ERR_ALERT_PRESENT);
63     }
64 
65     while (s2n_stuffer_data_available(&conn->in)) {
66         uint8_t bytes_required = 2;
67 
68         /* Alerts are two bytes long, but can still be fragmented or coalesced */
69         if (s2n_stuffer_data_available(&conn->alert_in) == 1) {
70             bytes_required = 1;
71         }
72 
73         int bytes_to_read = MIN(bytes_required, s2n_stuffer_data_available(&conn->in));
74 
75         GUARD(s2n_stuffer_copy(&conn->in, &conn->alert_in, bytes_to_read));
76 
77         if (s2n_stuffer_data_available(&conn->alert_in) == 2) {
78             conn->closed = 1;
79 
80             /* Close notifications are handled as shutdowns */
81             if (conn->alert_in_data[1] == S2N_TLS_ALERT_CLOSE_NOTIFY) {
82                 return 0;
83             }
84 
85             /* Expire any cached session on an error alert */
86             if (s2n_is_caching_enabled(conn->config) && conn->session_id_len) {
87                 conn->config->cache_delete(conn->config->cache_delete_data, conn->session_id, conn->session_id_len);
88             }
89 
90             /* All other alerts are treated as fatal errors (even warnings) */
91             S2N_ERROR(S2N_ERR_ALERT);
92         }
93     }
94 
95     return 0;
96 }
.fi
.SS "int s2n_queue_writer_close_alert_warning (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 98 of file s2n_alerts\&.c\&.
.PP
.nf
99 {
100     uint8_t alert[2];
101     struct s2n_blob out = {\&.data = alert,\&.size = sizeof(alert) };
102 
103     /* If there is an alert pending or we've already sent a close_notify, do nothing */
104     if (s2n_stuffer_data_available(&conn->writer_alert_out) || conn->close_notify_queued) {
105         return 0;
106     }
107 
108     alert[0] = S2N_TLS_ALERT_LEVEL_WARNING;
109     alert[1] = S2N_TLS_ALERT_CLOSE_NOTIFY;
110 
111     GUARD(s2n_stuffer_write(&conn->writer_alert_out, &out));
112     conn->close_notify_queued = 1;
113 
114     return 0;
115 }
.fi
.SS "int s2n_queue_reader_unsupported_protocol_version_alert (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 117 of file s2n_alerts\&.c\&.
.PP
.nf
118 {
119     uint8_t alert[2];
120     struct s2n_blob out = {\&.data = alert,\&.size = sizeof(alert) };
121 
122     /* If there is an alert pending, do nothing */
123     if (s2n_stuffer_data_available(&conn->reader_alert_out)) {
124         return 0;
125     }
126 
127     alert[0] = S2N_TLS_ALERT_LEVEL_FATAL;
128     alert[1] = S2N_TLS_ALERT_PROTOCOL_VERSION;
129 
130     GUARD(s2n_stuffer_write(&conn->reader_alert_out, &out));
131 
132     return 0;
133 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
