.TH "s2n-master/libcrypto-build/openssl/apps/s_apps.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/apps/s_apps.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <openssl/opensslconf\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPORT\fP   4433"
.br
.ti -1c
.RI "#define \fBPORT_STR\fP   '4433'"
.br
.ti -1c
.RI "#define \fBPROTOCOL\fP   'tcp'"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct ssl_excert_st \fBSSL_EXCERT\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBdo_server\fP (int port, int \fBtype\fP, int *ret, int(*\fBcb\fP)(char *hostname, int s, int stype,                                                                                           unsigned char *context), unsigned char *context, int naccept)"
.br
.ti -1c
.RI "int \fBssl_print_tmp_key\fP (\fBBIO\fP *out, \fBSSL\fP *s)"
.br
.ti -1c
.RI "int \fBinit_client\fP (int *sock, char *server, int port, int \fBtype\fP)"
.br
.ti -1c
.RI "int \fBshould_retry\fP (int i)"
.br
.ti -1c
.RI "int \fBextract_port\fP (char *str, short *port_ptr)"
.br
.ti -1c
.RI "int \fBextract_host_port\fP (char *str, char **host_ptr, unsigned char *ip, short *\fBp\fP)"
.br
.ti -1c
.RI "long \fBMS_CALLBACK\fP \fBbio_dump_callback\fP (\fBBIO\fP *bio, int cmd, const char *argp, int argi, long argl, long ret)"
.br
.ti -1c
.RI "int \fBMS_CALLBACK\fP \fBgenerate_cookie_callback\fP (\fBSSL\fP *ssl, unsigned char *cookie, unsigned int *cookie_len)"
.br
.ti -1c
.RI "int \fBMS_CALLBACK\fP \fBverify_cookie_callback\fP (\fBSSL\fP *ssl, unsigned char *cookie, unsigned int cookie_len)"
.br
.ti -1c
.RI "\fBvoid\fP \fBssl_ctx_set_excert\fP (\fBSSL_CTX\fP *ctx, \fBSSL_EXCERT\fP *exc)"
.br
.ti -1c
.RI "\fBvoid\fP \fBssl_excert_free\fP (\fBSSL_EXCERT\fP *exc)"
.br
.ti -1c
.RI "int \fBargs_excert\fP (char ***pargs, int *pargc, int *badarg, \fBBIO\fP *err, \fBSSL_EXCERT\fP **pexc)"
.br
.ti -1c
.RI "int \fBload_excert\fP (\fBSSL_EXCERT\fP **pexc, \fBBIO\fP *err)"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint_ssl_summary\fP (\fBBIO\fP *bio, \fBSSL\fP *s)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PORT   4433"

.PP
Definition at line 150 of file s_apps\&.h\&.
.SS "#define PORT_STR   '4433'"

.PP
Definition at line 151 of file s_apps\&.h\&.
.SS "#define PROTOCOL   'tcp'"

.PP
Definition at line 152 of file s_apps\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct ssl_excert_st \fBSSL_EXCERT\fP"

.PP
Definition at line 192 of file s_apps\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int do_server (int port, int type, int * ret, int(*)(char *hostname, int s, int stype,                                                                                                                                                                                                                                                                                                                                                                   unsigned char *context) cb, unsigned char * context, int naccept)"

.SS "int ssl_print_tmp_key (\fBBIO\fP * out, \fBSSL\fP * s)"

.SS "int init_client (int * sock, char * server, int port, int type)"

.SS "int should_retry (int i)"

.SS "int extract_port (char * str, short * port_ptr)"

.SS "int extract_host_port (char * str, char ** host_ptr, unsigned char * ip, short * p)"

.SS "long \fBMS_CALLBACK\fP bio_dump_callback (\fBBIO\fP * bio, int cmd, const char * argp, int argi, long argl, long ret)"

.SS "int \fBMS_CALLBACK\fP generate_cookie_callback (\fBSSL\fP * ssl, unsigned char * cookie, unsigned int * cookie_len)"

.SS "int \fBMS_CALLBACK\fP verify_cookie_callback (\fBSSL\fP * ssl, unsigned char * cookie, unsigned int cookie_len)"

.SS "\fBvoid\fP ssl_ctx_set_excert (\fBSSL_CTX\fP * ctx, \fBSSL_EXCERT\fP * exc)"

.SS "\fBvoid\fP ssl_excert_free (\fBSSL_EXCERT\fP * exc)"

.SS "int args_excert (char *** pargs, int * pargc, int * badarg, \fBBIO\fP * err, \fBSSL_EXCERT\fP ** pexc)"

.SS "int load_excert (\fBSSL_EXCERT\fP ** pexc, \fBBIO\fP * err)"

.SS "\fBvoid\fP print_ssl_summary (\fBBIO\fP * bio, \fBSSL\fP * s)"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
