.TH "session_cache_entry" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
session_cache_entry \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBkey\fP [\fBMAX_KEY_LEN\fP]"
.br
.ti -1c
.RI "uint8_t \fBkey_len\fP"
.br
.ti -1c
.RI "uint8_t \fBvalue\fP [\fBMAX_VAL_LEN\fP]"
.br
.ti -1c
.RI "uint8_t \fBvalue_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 93 of file s2nd\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t key[\fBMAX_KEY_LEN\fP]"

.PP
Definition at line 94 of file s2nd\&.c\&.
.SS "uint8_t key_len"

.PP
Definition at line 95 of file s2nd\&.c\&.
.SS "uint8_t value[\fBMAX_VAL_LEN\fP]"

.PP
Definition at line 96 of file s2nd\&.c\&.
.SS "uint8_t value_len"

.PP
Definition at line 97 of file s2nd\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
