.TH "SRP_gN_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRP_gN_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <srp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBid\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBg\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file srp\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char * id"

.PP
Definition at line 113 of file srp\&.h\&.
.SS "\fBBIGNUM\fP * g"

.PP
Definition at line 114 of file srp\&.h\&.
.SS "\fBBIGNUM\fP * N"

.PP
Definition at line 115 of file srp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
