.TH "s2n-master/libcrypto-build/openssl/ssl/ssl23.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/ssl/ssl23.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSSL23_ST_CW_CLNT_HELLO_A\fP   (0x210|SSL_ST_CONNECT)"
.br
.ti -1c
.RI "#define \fBSSL23_ST_CW_CLNT_HELLO_B\fP   (0x211|SSL_ST_CONNECT)"
.br
.ti -1c
.RI "#define \fBSSL23_ST_CR_SRVR_HELLO_A\fP   (0x220|SSL_ST_CONNECT)"
.br
.ti -1c
.RI "#define \fBSSL23_ST_CR_SRVR_HELLO_B\fP   (0x221|SSL_ST_CONNECT)"
.br
.ti -1c
.RI "#define \fBSSL23_ST_SR_CLNT_HELLO_A\fP   (0x210|SSL_ST_ACCEPT)"
.br
.ti -1c
.RI "#define \fBSSL23_ST_SR_CLNT_HELLO_B\fP   (0x211|SSL_ST_ACCEPT)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SSL23_ST_CW_CLNT_HELLO_A   (0x210|SSL_ST_CONNECT)"

.PP
Definition at line 70 of file ssl23\&.h\&.
.SS "#define SSL23_ST_CW_CLNT_HELLO_B   (0x211|SSL_ST_CONNECT)"

.PP
Definition at line 71 of file ssl23\&.h\&.
.SS "#define SSL23_ST_CR_SRVR_HELLO_A   (0x220|SSL_ST_CONNECT)"

.PP
Definition at line 73 of file ssl23\&.h\&.
.SS "#define SSL23_ST_CR_SRVR_HELLO_B   (0x221|SSL_ST_CONNECT)"

.PP
Definition at line 74 of file ssl23\&.h\&.
.SS "#define SSL23_ST_SR_CLNT_HELLO_A   (0x210|SSL_ST_ACCEPT)"

.PP
Definition at line 78 of file ssl23\&.h\&.
.SS "#define SSL23_ST_SR_CLNT_HELLO_B   (0x211|SSL_ST_ACCEPT)"

.PP
Definition at line 79 of file ssl23\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
