.TH "ssl_session_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ssl_session_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ssl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBSSL_CIPHER\fP)*ciphers"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBSSL_CIPHER\fP)*ciphers"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBssl_version\fP"
.br
.ti -1c
.RI "unsigned int \fBkey_arg_length\fP"
.br
.ti -1c
.RI "unsigned char \fBkey_arg\fP [\fBSSL_MAX_KEY_ARG_LENGTH\fP]"
.br
.ti -1c
.RI "int \fBmaster_key_length\fP"
.br
.ti -1c
.RI "unsigned char \fBmaster_key\fP [\fBSSL_MAX_MASTER_KEY_LENGTH\fP]"
.br
.ti -1c
.RI "unsigned int \fBsession_id_length\fP"
.br
.ti -1c
.RI "unsigned char \fBsession_id\fP [\fBSSL_MAX_SSL_SESSION_ID_LENGTH\fP]"
.br
.ti -1c
.RI "unsigned int \fBsid_ctx_length\fP"
.br
.ti -1c
.RI "unsigned char \fBsid_ctx\fP [\fBSSL_MAX_SID_CTX_LENGTH\fP]"
.br
.ti -1c
.RI "unsigned int \fBkrb5_client_princ_len\fP"
.br
.ti -1c
.RI "unsigned char \fBkrb5_client_princ\fP [\fBSSL_MAX_KRB5_PRINCIPAL_LENGTH\fP]"
.br
.ti -1c
.RI "char * \fBpsk_identity_hint\fP"
.br
.ti -1c
.RI "char * \fBpsk_identity\fP"
.br
.ti -1c
.RI "int \fBnot_resumable\fP"
.br
.ti -1c
.RI "struct \fBsess_cert_st\fP * \fBsess_cert\fP"
.br
.ti -1c
.RI "\fBX509\fP * \fBpeer\fP"
.br
.ti -1c
.RI "long \fBverify_result\fP"
.br
.ti -1c
.RI "int \fBreferences\fP"
.br
.ti -1c
.RI "long \fBtimeout\fP"
.br
.ti -1c
.RI "long \fBtime\fP"
.br
.ti -1c
.RI "unsigned int \fBcompress_meth\fP"
.br
.ti -1c
.RI "const \fBSSL_CIPHER\fP * \fBcipher\fP"
.br
.ti -1c
.RI "unsigned long \fBcipher_id\fP"
.br
.ti -1c
.RI "\fBCRYPTO_EX_DATA\fP \fBex_data\fP"
.br
.ti -1c
.RI "struct \fBssl_session_st\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBssl_session_st\fP * \fBnext\fP"
.br
.ti -1c
.RI "char * \fBtlsext_hostname\fP"
.br
.ti -1c
.RI "size_t \fBtlsext_ecpointformatlist_length\fP"
.br
.ti -1c
.RI "unsigned char * \fBtlsext_ecpointformatlist\fP"
.br
.ti -1c
.RI "size_t \fBtlsext_ellipticcurvelist_length\fP"
.br
.ti -1c
.RI "unsigned char * \fBtlsext_ellipticcurvelist\fP"
.br
.ti -1c
.RI "unsigned char * \fBtlsext_tick\fP"
.br
.ti -1c
.RI "size_t \fBtlsext_ticklen\fP"
.br
.ti -1c
.RI "long \fBtlsext_tick_lifetime_hint\fP"
.br
.ti -1c
.RI "char * \fBsrp_username\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 498 of file ssl\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBSSL_CIPHER\fP)"

.SS "STACK_OF (\fBSSL_CIPHER\fP)"

.SH "Field Documentation"
.PP 
.SS "int ssl_version"

.PP
Definition at line 499 of file ssl\&.h\&.
.SS "unsigned int key_arg_length"

.PP
Definition at line 502 of file ssl\&.h\&.
.SS "unsigned char key_arg"

.PP
Definition at line 503 of file ssl\&.h\&.
.SS "int master_key_length"

.PP
Definition at line 504 of file ssl\&.h\&.
.SS "unsigned char master_key"

.PP
Definition at line 505 of file ssl\&.h\&.
.SS "unsigned int session_id_length"

.PP
Definition at line 507 of file ssl\&.h\&.
.SS "unsigned char session_id"

.PP
Definition at line 508 of file ssl\&.h\&.
.SS "unsigned int sid_ctx_length"

.PP
Definition at line 514 of file ssl\&.h\&.
.SS "unsigned char sid_ctx"

.PP
Definition at line 515 of file ssl\&.h\&.
.SS "unsigned int krb5_client_princ_len"

.PP
Definition at line 517 of file ssl\&.h\&.
.SS "unsigned char krb5_client_princ"

.PP
Definition at line 518 of file ssl\&.h\&.
.SS "char * psk_identity_hint"

.PP
Definition at line 521 of file ssl\&.h\&.
.SS "char * psk_identity"

.PP
Definition at line 522 of file ssl\&.h\&.
.SS "int not_resumable"

.PP
Definition at line 529 of file ssl\&.h\&.
.SS "struct \fBsess_cert_st\fP * sess_cert"

.PP
Definition at line 531 of file ssl\&.h\&.
.SS "\fBX509\fP * peer"

.PP
Definition at line 538 of file ssl\&.h\&.
.SS "long verify_result"

.PP
Definition at line 543 of file ssl\&.h\&.
.SS "int references"

.PP
Definition at line 544 of file ssl\&.h\&.
.SS "long timeout"

.PP
Definition at line 545 of file ssl\&.h\&.
.SS "long time"

.PP
Definition at line 546 of file ssl\&.h\&.
.SS "unsigned int compress_meth"

.PP
Definition at line 547 of file ssl\&.h\&.
.SS "const \fBSSL_CIPHER\fP * cipher"

.PP
Definition at line 548 of file ssl\&.h\&.
.SS "unsigned long cipher_id"

.PP
Definition at line 549 of file ssl\&.h\&.
.SS "\fBCRYPTO_EX_DATA\fP ex_data"

.PP
Definition at line 552 of file ssl\&.h\&.
.SS "struct \fBssl_session_st\fP * prev"

.PP
Definition at line 557 of file ssl\&.h\&.
.SS "struct \fBssl_session_st\fP * next"

.PP
Definition at line 557 of file ssl\&.h\&.
.SS "char * tlsext_hostname"

.PP
Definition at line 559 of file ssl\&.h\&.
.SS "size_t tlsext_ecpointformatlist_length"

.PP
Definition at line 561 of file ssl\&.h\&.
.SS "unsigned char * tlsext_ecpointformatlist"

.PP
Definition at line 562 of file ssl\&.h\&.
.SS "size_t tlsext_ellipticcurvelist_length"

.PP
Definition at line 563 of file ssl\&.h\&.
.SS "unsigned char * tlsext_ellipticcurvelist"

.PP
Definition at line 564 of file ssl\&.h\&.
.SS "unsigned char * tlsext_tick"

.PP
Definition at line 567 of file ssl\&.h\&.
.SS "size_t tlsext_ticklen"

.PP
Definition at line 568 of file ssl\&.h\&.
.SS "long tlsext_tick_lifetime_hint"

.PP
Definition at line 569 of file ssl\&.h\&.
.SS "char * srp_username"

.PP
Definition at line 572 of file ssl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
