.TH "tagTHREADENTRY32" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tagTHREADENTRY32 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tlhelp32\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "DWORD \fBdwSize\fP"
.br
.ti -1c
.RI "DWORD \fBcntUsage\fP"
.br
.ti -1c
.RI "DWORD \fBth32ThreadID\fP"
.br
.ti -1c
.RI "DWORD \fBth32OwnerProcessID\fP"
.br
.ti -1c
.RI "LONG \fBtpBasePri\fP"
.br
.ti -1c
.RI "LONG \fBtpDeltaPri\fP"
.br
.ti -1c
.RI "DWORD \fBdwFlags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 71 of file tlhelp32\&.h\&.
.SH "Field Documentation"
.PP 
.SS "DWORD dwSize"

.PP
Definition at line 72 of file tlhelp32\&.h\&.
.SS "DWORD cntUsage"

.PP
Definition at line 73 of file tlhelp32\&.h\&.
.SS "DWORD th32ThreadID"

.PP
Definition at line 74 of file tlhelp32\&.h\&.
.SS "DWORD th32OwnerProcessID"

.PP
Definition at line 75 of file tlhelp32\&.h\&.
.SS "LONG tpBasePri"

.PP
Definition at line 76 of file tlhelp32\&.h\&.
.SS "LONG tpDeltaPri"

.PP
Definition at line 77 of file tlhelp32\&.h\&.
.SS "DWORD dwFlags"

.PP
Definition at line 78 of file tlhelp32\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
