.TH "s2n-master/libcrypto-build/openssl/ms/tlhelp32.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/ms/tlhelp32.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtagHEAPLIST32\fP"
.br
.ti -1c
.RI "struct \fBtagHEAPENTRY32\fP"
.br
.ti -1c
.RI "struct \fBtagPROCESSENTRY32W\fP"
.br
.ti -1c
.RI "struct \fBtagPROCESSENTRY32\fP"
.br
.ti -1c
.RI "struct \fBtagTHREADENTRY32\fP"
.br
.ti -1c
.RI "struct \fBtagMODULEENTRY32W\fP"
.br
.ti -1c
.RI "struct \fBtagMODULEENTRY32\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHF32_DEFAULT\fP   1"
.br
.ti -1c
.RI "#define \fBHF32_SHARED\fP   2"
.br
.ti -1c
.RI "#define \fBLF32_FIXED\fP   0x1"
.br
.ti -1c
.RI "#define \fBLF32_FREE\fP   0x2"
.br
.ti -1c
.RI "#define \fBLF32_MOVEABLE\fP   0x4"
.br
.ti -1c
.RI "#define \fBMAX_MODULE_NAME32\fP   255"
.br
.ti -1c
.RI "#define \fBTH32CS_SNAPHEAPLIST\fP   0x1"
.br
.ti -1c
.RI "#define \fBTH32CS_SNAPPROCESS\fP   0x2"
.br
.ti -1c
.RI "#define \fBTH32CS_SNAPTHREAD\fP   0x4"
.br
.ti -1c
.RI "#define \fBTH32CS_SNAPMODULE\fP   0x8"
.br
.ti -1c
.RI "#define \fBTH32CS_SNAPALL\fP   (\fBTH32CS_SNAPHEAPLIST\fP|\fBTH32CS_SNAPPROCESS\fP|\fBTH32CS_SNAPTHREAD\fP|\fBTH32CS_SNAPMODULE\fP)"
.br
.ti -1c
.RI "#define \fBTH32CS_INHERIT\fP   0x80000000"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBtagHEAPLIST32\fP \fBHEAPLIST32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagHEAPLIST32\fP * \fBPHEAPLIST32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagHEAPLIST32\fP * \fBLPHEAPLIST32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagHEAPENTRY32\fP \fBHEAPENTRY32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagHEAPENTRY32\fP * \fBPHEAPENTRY32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagHEAPENTRY32\fP * \fBLPHEAPENTRY32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagPROCESSENTRY32W\fP \fBPROCESSENTRY32W\fP"
.br
.ti -1c
.RI "typedef struct \fBtagPROCESSENTRY32W\fP * \fBPPROCESSENTRY32W\fP"
.br
.ti -1c
.RI "typedef struct \fBtagPROCESSENTRY32W\fP * \fBLPPROCESSENTRY32W\fP"
.br
.ti -1c
.RI "typedef struct \fBtagPROCESSENTRY32\fP \fBPROCESSENTRY32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagPROCESSENTRY32\fP * \fBPPROCESSENTRY32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagPROCESSENTRY32\fP * \fBLPPROCESSENTRY32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagTHREADENTRY32\fP \fBTHREADENTRY32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagTHREADENTRY32\fP * \fBPTHREADENTRY32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagTHREADENTRY32\fP * \fBLPTHREADENTRY32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagMODULEENTRY32W\fP \fBMODULEENTRY32W\fP"
.br
.ti -1c
.RI "typedef struct \fBtagMODULEENTRY32W\fP * \fBPMODULEENTRY32W\fP"
.br
.ti -1c
.RI "typedef struct \fBtagMODULEENTRY32W\fP * \fBLPMODULEENTRY32W\fP"
.br
.ti -1c
.RI "typedef struct \fBtagMODULEENTRY32\fP \fBMODULEENTRY32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagMODULEENTRY32\fP * \fBPMODULEENTRY32\fP"
.br
.ti -1c
.RI "typedef struct \fBtagMODULEENTRY32\fP * \fBLPMODULEENTRY32\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "BOOL WINAPI \fBHeap32First\fP (\fBLPHEAPENTRY32\fP, DWORD, DWORD)"
.br
.ti -1c
.RI "BOOL WINAPI \fBHeap32ListFirst\fP (HANDLE, \fBLPHEAPLIST32\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBHeap32ListNext\fP (HANDLE, \fBLPHEAPLIST32\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBHeap32Next\fP (\fBLPHEAPENTRY32\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBModule32First\fP (HANDLE, \fBLPMODULEENTRY32\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBModule32FirstW\fP (HANDLE, \fBLPMODULEENTRY32W\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBModule32Next\fP (HANDLE, \fBLPMODULEENTRY32\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBModule32NextW\fP (HANDLE, \fBLPMODULEENTRY32W\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBProcess32First\fP (HANDLE, \fBLPPROCESSENTRY32\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBProcess32FirstW\fP (HANDLE, \fBLPPROCESSENTRY32W\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBProcess32Next\fP (HANDLE, \fBLPPROCESSENTRY32\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBProcess32NextW\fP (HANDLE, \fBLPPROCESSENTRY32W\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBThread32First\fP (HANDLE, \fBLPTHREADENTRY32\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBThread32Next\fP (HANDLE, \fBLPTHREADENTRY32\fP)"
.br
.ti -1c
.RI "BOOL WINAPI \fBToolhelp32ReadProcessMemory\fP (DWORD, LPCVOID, LPVOID, DWORD, LPDWORD)"
.br
.ti -1c
.RI "HANDLE WINAPI \fBCreateToolhelp32Snapshot\fP (DWORD, DWORD)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HF32_DEFAULT   1"

.PP
Definition at line 18 of file tlhelp32\&.h\&.
.SS "#define HF32_SHARED   2"

.PP
Definition at line 19 of file tlhelp32\&.h\&.
.SS "#define LF32_FIXED   0x1"

.PP
Definition at line 20 of file tlhelp32\&.h\&.
.SS "#define LF32_FREE   0x2"

.PP
Definition at line 21 of file tlhelp32\&.h\&.
.SS "#define LF32_MOVEABLE   0x4"

.PP
Definition at line 22 of file tlhelp32\&.h\&.
.SS "#define MAX_MODULE_NAME32   255"

.PP
Definition at line 23 of file tlhelp32\&.h\&.
.SS "#define TH32CS_SNAPHEAPLIST   0x1"

.PP
Definition at line 24 of file tlhelp32\&.h\&.
.SS "#define TH32CS_SNAPPROCESS   0x2"

.PP
Definition at line 25 of file tlhelp32\&.h\&.
.SS "#define TH32CS_SNAPTHREAD   0x4"

.PP
Definition at line 26 of file tlhelp32\&.h\&.
.SS "#define TH32CS_SNAPMODULE   0x8"

.PP
Definition at line 27 of file tlhelp32\&.h\&.
.SS "#define TH32CS_SNAPALL   (\fBTH32CS_SNAPHEAPLIST\fP|\fBTH32CS_SNAPPROCESS\fP|\fBTH32CS_SNAPTHREAD\fP|\fBTH32CS_SNAPMODULE\fP)"

.PP
Definition at line 28 of file tlhelp32\&.h\&.
.SS "#define TH32CS_INHERIT   0x80000000"

.PP
Definition at line 29 of file tlhelp32\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBtagHEAPLIST32\fP  \fBHEAPLIST32\fP"

.SS "typedef struct \fBtagHEAPLIST32\fP * \fBPHEAPLIST32\fP"

.SS "typedef struct \fBtagHEAPLIST32\fP * \fBLPHEAPLIST32\fP"

.SS "typedef struct \fBtagHEAPENTRY32\fP  \fBHEAPENTRY32\fP"

.SS "typedef struct \fBtagHEAPENTRY32\fP * \fBPHEAPENTRY32\fP"

.SS "typedef struct \fBtagHEAPENTRY32\fP * \fBLPHEAPENTRY32\fP"

.SS "typedef struct \fBtagPROCESSENTRY32W\fP  \fBPROCESSENTRY32W\fP"

.SS "typedef struct \fBtagPROCESSENTRY32W\fP * \fBPPROCESSENTRY32W\fP"

.SS "typedef struct \fBtagPROCESSENTRY32W\fP * \fBLPPROCESSENTRY32W\fP"

.SS "typedef struct \fBtagPROCESSENTRY32\fP  \fBPROCESSENTRY32\fP"

.SS "typedef struct \fBtagPROCESSENTRY32\fP * \fBPPROCESSENTRY32\fP"

.SS "typedef struct \fBtagPROCESSENTRY32\fP * \fBLPPROCESSENTRY32\fP"

.SS "typedef struct \fBtagTHREADENTRY32\fP  \fBTHREADENTRY32\fP"

.SS "typedef struct \fBtagTHREADENTRY32\fP * \fBPTHREADENTRY32\fP"

.SS "typedef struct \fBtagTHREADENTRY32\fP * \fBLPTHREADENTRY32\fP"

.SS "typedef struct \fBtagMODULEENTRY32W\fP  \fBMODULEENTRY32W\fP"

.SS "typedef struct \fBtagMODULEENTRY32W\fP * \fBPMODULEENTRY32W\fP"

.SS "typedef struct \fBtagMODULEENTRY32W\fP * \fBLPMODULEENTRY32W\fP"

.SS "typedef struct \fBtagMODULEENTRY32\fP  \fBMODULEENTRY32\fP"

.SS "typedef struct \fBtagMODULEENTRY32\fP * \fBPMODULEENTRY32\fP"

.SS "typedef struct \fBtagMODULEENTRY32\fP * \fBLPMODULEENTRY32\fP"

.SH "Function Documentation"
.PP 
.SS "BOOL WINAPI Heap32First (\fBLPHEAPENTRY32\fP, DWORD, DWORD)"

.SS "BOOL WINAPI Heap32ListFirst (HANDLE, \fBLPHEAPLIST32\fP)"

.SS "BOOL WINAPI Heap32ListNext (HANDLE, \fBLPHEAPLIST32\fP)"

.SS "BOOL WINAPI Heap32Next (\fBLPHEAPENTRY32\fP)"

.SS "BOOL WINAPI Module32First (HANDLE, \fBLPMODULEENTRY32\fP)"

.SS "BOOL WINAPI Module32FirstW (HANDLE, \fBLPMODULEENTRY32W\fP)"

.SS "BOOL WINAPI Module32Next (HANDLE, \fBLPMODULEENTRY32\fP)"

.SS "BOOL WINAPI Module32NextW (HANDLE, \fBLPMODULEENTRY32W\fP)"

.SS "BOOL WINAPI Process32First (HANDLE, \fBLPPROCESSENTRY32\fP)"

.SS "BOOL WINAPI Process32FirstW (HANDLE, \fBLPPROCESSENTRY32W\fP)"

.SS "BOOL WINAPI Process32Next (HANDLE, \fBLPPROCESSENTRY32\fP)"

.SS "BOOL WINAPI Process32NextW (HANDLE, \fBLPPROCESSENTRY32W\fP)"

.SS "BOOL WINAPI Thread32First (HANDLE, \fBLPTHREADENTRY32\fP)"

.SS "BOOL WINAPI Thread32Next (HANDLE, \fBLPTHREADENTRY32\fP)"

.SS "BOOL WINAPI Toolhelp32ReadProcessMemory (DWORD, LPCVOID, LPVOID, DWORD, LPDWORD)"

.SS "HANDLE WINAPI CreateToolhelp32Snapshot (DWORD, DWORD)"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
