.TH "TS_req_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TS_req_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ts\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_EXTENSION\fP)*extensions"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_EXTENSION\fP)*extensions"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBversion\fP"
.br
.ti -1c
.RI "\fBTS_MSG_IMPRINT\fP * \fBmsg_imprint\fP"
.br
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBpolicy_id\fP"
.br
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBnonce\fP"
.br
.ti -1c
.RI "\fBASN1_BOOLEAN\fP \fBcert_req\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 125 of file ts\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBX509_EXTENSION\fP)"

.SS "STACK_OF (\fBX509_EXTENSION\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBASN1_INTEGER\fP * version"

.PP
Definition at line 126 of file ts\&.h\&.
.SS "\fBTS_MSG_IMPRINT\fP * msg_imprint"

.PP
Definition at line 127 of file ts\&.h\&.
.SS "\fBASN1_OBJECT\fP * policy_id"

.PP
Definition at line 128 of file ts\&.h\&.
.SS "\fBASN1_INTEGER\fP * nonce"

.PP
Definition at line 129 of file ts\&.h\&.
.SS "\fBASN1_BOOLEAN\fP cert_req"

.PP
Definition at line 130 of file ts\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
