.TH "s2n-master/libcrypto-build/openssl/crypto/ui/ui_locl.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/crypto/ui/ui_locl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/ui\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBui_method_st\fP"
.br
.ti -1c
.RI "struct \fBui_string_st\fP"
.br
.ti -1c
.RI "struct \fBui_st\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOUT_STRING_FREEABLE\fP   0x01"
.br
.ti -1c
.RI "#define \fBUI_FLAG_REDOABLE\fP   0x0001"
.br
.ti -1c
.RI "#define \fBUI_FLAG_PRINT_ERRORS\fP   0x0100"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OUT_STRING_FREEABLE   0x01"

.PP
Definition at line 129 of file ui_locl\&.h\&.
.SS "#define UI_FLAG_REDOABLE   0x0001"

.PP
Definition at line 140 of file ui_locl\&.h\&.
.SS "#define UI_FLAG_PRINT_ERRORS   0x0100"

.PP
Definition at line 141 of file ui_locl\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
