.TH "ui_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_locl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBUI_STRING\fP)*strings"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBUI_METHOD\fP * \fBmeth\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBuser_data\fP"
.br
.ti -1c
.RI "\fBCRYPTO_EX_DATA\fP \fBex_data\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 133 of file ui_locl\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBUI_STRING\fP)"

.SH "Field Documentation"
.PP 
.SS "const \fBUI_METHOD\fP* meth"

.PP
Definition at line 134 of file ui_locl\&.h\&.
.SS "\fBvoid\fP* user_data"

.PP
Definition at line 138 of file ui_locl\&.h\&.
.SS "\fBCRYPTO_EX_DATA\fP ex_data"

.PP
Definition at line 139 of file ui_locl\&.h\&.
.SS "int flags"

.PP
Definition at line 142 of file ui_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
