.TH "s2n-master/libcrypto-build/openssl/include/openssl/whrlpool.h" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n-master/libcrypto-build/openssl/include/openssl/whrlpool.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/e_os2\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBWHIRLPOOL_CTX\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWHIRLPOOL_DIGEST_LENGTH\fP   (512/8)"
.br
.ti -1c
.RI "#define \fBWHIRLPOOL_BBLOCK\fP   512"
.br
.ti -1c
.RI "#define \fBWHIRLPOOL_COUNTER\fP   (256/8)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBWHIRLPOOL_Init\fP (\fBWHIRLPOOL_CTX\fP *\fBc\fP)"
.br
.ti -1c
.RI "int \fBWHIRLPOOL_Update\fP (\fBWHIRLPOOL_CTX\fP *\fBc\fP, const \fBvoid\fP *inp, size_t \fBbytes\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBWHIRLPOOL_BitUpdate\fP (\fBWHIRLPOOL_CTX\fP *\fBc\fP, const \fBvoid\fP *inp, size_t \fBbits\fP)"
.br
.ti -1c
.RI "int \fBWHIRLPOOL_Final\fP (unsigned char *md, \fBWHIRLPOOL_CTX\fP *\fBc\fP)"
.br
.ti -1c
.RI "unsigned char * \fBWHIRLPOOL\fP (const \fBvoid\fP *inp, size_t \fBbytes\fP, unsigned char *md)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define WHIRLPOOL_DIGEST_LENGTH   (512/8)"

.PP
Definition at line 11 of file whrlpool\&.h\&.
.SS "#define WHIRLPOOL_BBLOCK   512"

.PP
Definition at line 12 of file whrlpool\&.h\&.
.SS "#define WHIRLPOOL_COUNTER   (256/8)"

.PP
Definition at line 13 of file whrlpool\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int WHIRLPOOL_Init (\fBWHIRLPOOL_CTX\fP * c)"

.SS "int WHIRLPOOL_Update (\fBWHIRLPOOL_CTX\fP * c, const \fBvoid\fP * inp, size_t bytes)"

.SS "\fBvoid\fP WHIRLPOOL_BitUpdate (\fBWHIRLPOOL_CTX\fP * c, const \fBvoid\fP * inp, size_t bits)"

.SS "int WHIRLPOOL_Final (unsigned char * md, \fBWHIRLPOOL_CTX\fP * c)"

.SS "unsigned char* WHIRLPOOL (const \fBvoid\fP * inp, size_t bytes, unsigned char * md)"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
