.TH "X509_info_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
X509_info_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <x509\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBX509\fP * \fBx509\fP"
.br
.ti -1c
.RI "\fBX509_CRL\fP * \fBcrl\fP"
.br
.ti -1c
.RI "\fBX509_PKEY\fP * \fBx_pkey\fP"
.br
.ti -1c
.RI "\fBEVP_CIPHER_INFO\fP \fBenc_cipher\fP"
.br
.ti -1c
.RI "int \fBenc_len\fP"
.br
.ti -1c
.RI "char * \fBenc_data\fP"
.br
.ti -1c
.RI "int \fBreferences\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 496 of file x509\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBX509\fP * x509"

.PP
Definition at line 497 of file x509\&.h\&.
.SS "\fBX509_CRL\fP * crl"

.PP
Definition at line 498 of file x509\&.h\&.
.SS "\fBX509_PKEY\fP * x_pkey"

.PP
Definition at line 499 of file x509\&.h\&.
.SS "\fBEVP_CIPHER_INFO\fP enc_cipher"

.PP
Definition at line 500 of file x509\&.h\&.
.SS "int enc_len"

.PP
Definition at line 501 of file x509\&.h\&.
.SS "char * enc_data"

.PP
Definition at line 502 of file x509\&.h\&.
.SS "int references"

.PP
Definition at line 503 of file x509\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
