.TH "X509V3_CONF_METHOD_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
X509V3_CONF_METHOD_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <x509v3\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCONF_VALUE\fP)*(*get_section)(\fBvoid\fP *db"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBCONF_VALUE\fP)*(*get_section)(\fBvoid\fP *db"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char *(* \fBget_string\fP )(\fBvoid\fP *db, char *\fBsection\fP, char *value)"
.br
.ti -1c
.RI "char * \fBsection\fP"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBfree_string\fP )(\fBvoid\fP *db, char *string)"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBfree_section\fP )(\fBvoid\fP *db, \fBSTACK_OF\fP(\fBCONF_VALUE\fP)*\fBsection\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 126 of file x509v3\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBCONF_VALUE\fP)"

.SS "STACK_OF (\fBCONF_VALUE\fP)"

.SH "Field Documentation"
.PP 
.SS "char *(* get_string)(\fBvoid\fP *db, char *\fBsection\fP, char *value)"

.PP
Definition at line 127 of file x509v3\&.h\&.
.SS "char * section"

.PP
Definition at line 128 of file x509v3\&.h\&.
.SS "\fBvoid\fP(* free_string)(\fBvoid\fP *db, char *string)"

.PP
Definition at line 129 of file x509v3\&.h\&.
.SS "\fBvoid\fP(* free_section)(\fBvoid\fP *db, \fBSTACK_OF\fP(\fBCONF_VALUE\fP)*\fBsection\fP)"

.PP
Definition at line 130 of file x509v3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
