.TH "X509_POLICY_DATA_st" 3 "Fri Aug 19 2016" "s2n-doxygen-full" \" -*- nroff -*-
.ad l
.nh
.SH NAME
X509_POLICY_DATA_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pcy_int\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBPOLICYQUALINFO\fP)*qualifier_set"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBASN1_OBJECT\fP)*expected_policy_set"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBflags\fP"
.br
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBvalid_policy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file pcy_int\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBPOLICYQUALINFO\fP)"

.SS "STACK_OF (\fBASN1_OBJECT\fP)"

.SH "Field Documentation"
.PP 
.SS "unsigned int flags"

.PP
Definition at line 74 of file pcy_int\&.h\&.
.SS "\fBASN1_OBJECT\fP* valid_policy"

.PP
Definition at line 76 of file pcy_int\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen-full from the source code\&.
