.TH "s2n_ecc_named_curve" 3 "Tue Jun 28 2016" "s2n-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n_ecc_named_curve \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <s2n_ecc\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBiana_id\fP"
.br
.ti -1c
.RI "int \fBlibcrypto_nid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file s2n_ecc\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint16_t iana_id"

.PP
Definition at line 25 of file s2n_ecc\&.h\&.
.SS "int libcrypto_nid"

.PP
Definition at line 27 of file s2n_ecc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen from the source code\&.
