.TH "s2n_handshake_action" 3 "Tue Jun 28 2016" "s2n-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n_handshake_action \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBrecord_type\fP"
.br
.ti -1c
.RI "uint8_t \fBmessage_type\fP"
.br
.ti -1c
.RI "char \fBwriter\fP"
.br
.ti -1c
.RI "int(* \fBhandler\fP [2])(struct \fBs2n_connection\fP *conn)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file s2n_handshake_io\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int(* handler[2])(struct \fBs2n_connection\fP *conn)"

.PP
Definition at line 49 of file s2n_handshake_io\&.c\&.
.SS "uint8_t message_type"

.PP
Definition at line 47 of file s2n_handshake_io\&.c\&.
.SS "uint8_t record_type"

.PP
Definition at line 46 of file s2n_handshake_io\&.c\&.
.SS "char writer"

.PP
Definition at line 48 of file s2n_handshake_io\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen from the source code\&.
