.TH "s2n/tls/s2n_handshake.c" 3 "Tue Jun 28 2016" "s2n-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/tls/s2n_handshake.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'error/s2n_errno\&.h'\fP
.br
\fC#include 'tls/s2n_connection\&.h'\fP
.br
\fC#include 'tls/s2n_record\&.h'\fP
.br
\fC#include 'stuffer/s2n_stuffer\&.h'\fP
.br
\fC#include 'utils/s2n_safety\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBs2n_handshake_write_header\fP (struct \fBs2n_connection\fP *conn, uint8_t message_type)"
.br
.ti -1c
.RI "int \fBs2n_handshake_finish_header\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_handshake_parse_header\fP (struct \fBs2n_connection\fP *conn, uint8_t *message_type, uint32_t *length)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int s2n_handshake_finish_header (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 43 of file s2n_handshake\&.c\&.
.SS "int s2n_handshake_parse_header (struct \fBs2n_connection\fP * conn, uint8_t * message_type, uint32_t * length)"

.PP
Definition at line 61 of file s2n_handshake\&.c\&.
.SS "int s2n_handshake_write_header (struct \fBs2n_connection\fP * conn, uint8_t message_type)"

.PP
Definition at line 27 of file s2n_handshake\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen from the source code\&.
