.TH "s2n/utils/s2n_mem.c" 3 "Tue Jun 28 2016" "s2n-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/utils/s2n_mem.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <sys/mman\&.h>\fP
.br
\fC#include 'error/s2n_errno\&.h'\fP
.br
\fC#include 'utils/s2n_blob\&.h'\fP
.br
\fC#include 'utils/s2n_mem\&.h'\fP
.br
\fC#include 'utils/s2n_safety\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBs2n_mem_init\fP (void)"
.br
.ti -1c
.RI "int \fBs2n_alloc\fP (struct \fBs2n_blob\fP *b, uint32_t size)"
.br
.ti -1c
.RI "int \fBs2n_realloc\fP (struct \fBs2n_blob\fP *b, uint32_t size)"
.br
.ti -1c
.RI "int \fBs2n_free\fP (struct \fBs2n_blob\fP *b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int s2n_alloc (struct \fBs2n_blob\fP * b, uint32_t size)"

.PP
Definition at line 40 of file s2n_mem\&.c\&.
.SS "int s2n_free (struct \fBs2n_blob\fP * b)"

.PP
Definition at line 96 of file s2n_mem\&.c\&.
.SS "int s2n_mem_init (void)"

.PP
Definition at line 30 of file s2n_mem\&.c\&.
.SS "int s2n_realloc (struct \fBs2n_blob\fP * b, uint32_t size)"

.PP
Definition at line 50 of file s2n_mem\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen from the source code\&.
