.TH "s2n_session_key" 3 "Tue Jun 28 2016" "s2n-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n_session_key \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <s2n_cipher\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   RC4_KEY \fBrc4\fP"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      DES_key_schedule \fBdks1\fP"
.br
.ti -1c
.RI "      DES_key_schedule \fBdks2\fP"
.br
.ti -1c
.RI "      DES_key_schedule \fBdks3\fP"
.br
.ti -1c
.RI "   } \fBdes\fP"
.br
.ti -1c
.RI "   EVP_CIPHER_CTX \fBevp_cipher_ctx\fP"
.br
.ti -1c
.RI "} \fBnative_format\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file s2n_cipher\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. }   des"

.SS "DES_key_schedule dks1"

.PP
Definition at line 33 of file s2n_cipher\&.h\&.
.SS "DES_key_schedule dks2"

.PP
Definition at line 34 of file s2n_cipher\&.h\&.
.SS "DES_key_schedule dks3"

.PP
Definition at line 35 of file s2n_cipher\&.h\&.
.SS "EVP_CIPHER_CTX evp_cipher_ctx"

.PP
Definition at line 37 of file s2n_cipher\&.h\&.
.SS "union { \&.\&.\&. }   native_format"

.SS "RC4_KEY rc4"

.PP
Definition at line 31 of file s2n_cipher\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen from the source code\&.
