.TH "s2n_stream_cipher" 3 "Tue Jun 28 2016" "s2n-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n_stream_cipher \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <s2n_cipher\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBdecrypt\fP )(struct \fBs2n_session_key\fP *key, struct \fBs2n_blob\fP *in, struct \fBs2n_blob\fP *out)"
.br
.ti -1c
.RI "int(* \fBencrypt\fP )(struct \fBs2n_session_key\fP *key, struct \fBs2n_blob\fP *in, struct \fBs2n_blob\fP *out)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file s2n_cipher\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int(* decrypt) (struct \fBs2n_session_key\fP *key, struct \fBs2n_blob\fP *in, struct \fBs2n_blob\fP *out)"

.PP
Definition at line 42 of file s2n_cipher\&.h\&.
.SS "int(* encrypt) (struct \fBs2n_session_key\fP *key, struct \fBs2n_blob\fP *in, struct \fBs2n_blob\fP *out)"

.PP
Definition at line 43 of file s2n_cipher\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen from the source code\&.
