.TH "s2n/tls/s2n_tls.h" 3 "Tue Jun 28 2016" "s2n-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/tls/s2n_tls.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include 'tls/s2n_connection\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs2n_tls_session_id\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBs2n_server_can_send_ocsp\fP(conn)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBs2n_flush\fP (struct \fBs2n_connection\fP *conn, \fBs2n_blocked_status\fP *more)"
.br
.ti -1c
.RI "int \fBs2n_client_hello_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_client_hello_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_sslv2_client_hello_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_hello_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_hello_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_cert_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_cert_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_status_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_status_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_key_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_key_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_done_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_done_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_client_key_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_client_key_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_client_ccs_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_client_ccs_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_ccs_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_ccs_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_client_finished_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_client_finished_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_finished_send\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_server_finished_recv\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_handshake_write_header\fP (struct \fBs2n_connection\fP *conn, uint8_t message_type)"
.br
.ti -1c
.RI "int \fBs2n_handshake_finish_header\fP (struct \fBs2n_connection\fP *conn)"
.br
.ti -1c
.RI "int \fBs2n_handshake_parse_header\fP (struct \fBs2n_connection\fP *conn, uint8_t *message_type, uint32_t *length)"
.br
.ti -1c
.RI "int \fBs2n_read_full_record\fP (struct \fBs2n_connection\fP *conn, uint8_t *record_type, int *isSSLv2)"
.br
.ti -1c
.RI "int \fBs2n_client_extensions_send\fP (struct \fBs2n_connection\fP *conn, struct \fBs2n_stuffer\fP *out)"
.br
.ti -1c
.RI "int \fBs2n_client_extensions_recv\fP (struct \fBs2n_connection\fP *conn, struct \fBs2n_blob\fP *extensions)"
.br
.ti -1c
.RI "int \fBs2n_server_extensions_send\fP (struct \fBs2n_connection\fP *conn, struct \fBs2n_stuffer\fP *out)"
.br
.ti -1c
.RI "int \fBs2n_server_extensions_recv\fP (struct \fBs2n_connection\fP *conn, struct \fBs2n_blob\fP *extensions)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint8_t \fBs2n_highest_protocol_version\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define s2n_server_can_send_ocsp(conn)"
\fBValue:\fP
.PP
.nf
((conn)->status_type == S2N_STATUS_REQUEST_OCSP && \
        (conn)->config->cert_and_key_pairs && \
        (conn)->config->cert_and_key_pairs->ocsp_status\&.size > 0)
.fi
.PP
Definition at line 65 of file s2n_tls\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int s2n_client_ccs_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 31 of file s2n_client_ccs\&.c\&.
.SS "int s2n_client_ccs_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 57 of file s2n_client_ccs\&.c\&.
.SS "int s2n_client_extensions_recv (struct \fBs2n_connection\fP * conn, struct \fBs2n_blob\fP * extensions)"

.PP
Definition at line 136 of file s2n_client_extensions\&.c\&.
.SS "int s2n_client_extensions_send (struct \fBs2n_connection\fP * conn, struct \fBs2n_stuffer\fP * out)"

.PP
Definition at line 36 of file s2n_client_extensions\&.c\&.
.SS "int s2n_client_finished_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 27 of file s2n_client_finished\&.c\&.
.SS "int s2n_client_finished_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 44 of file s2n_client_finished\&.c\&.
.SS "int s2n_client_hello_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 38 of file s2n_client_hello\&.c\&.
.SS "int s2n_client_hello_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 104 of file s2n_client_hello\&.c\&.
.SS "int s2n_client_key_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 115 of file s2n_client_key_exchange\&.c\&.
.SS "int s2n_client_key_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 203 of file s2n_client_key_exchange\&.c\&.
.SS "int s2n_flush (struct \fBs2n_connection\fP * conn, \fBs2n_blocked_status\fP * more)"

.PP
Definition at line 33 of file s2n_send\&.c\&.
.SS "int s2n_handshake_finish_header (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 43 of file s2n_handshake\&.c\&.
.SS "int s2n_handshake_parse_header (struct \fBs2n_connection\fP * conn, uint8_t * message_type, uint32_t * length)"

.PP
Definition at line 61 of file s2n_handshake\&.c\&.
.SS "int s2n_handshake_write_header (struct \fBs2n_connection\fP * conn, uint8_t message_type)"

.PP
Definition at line 27 of file s2n_handshake\&.c\&.
.SS "int s2n_read_full_record (struct \fBs2n_connection\fP * conn, uint8_t * record_type, int * isSSLv2)"

.PP
Definition at line 36 of file s2n_recv\&.c\&.
.SS "int s2n_server_ccs_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 30 of file s2n_server_ccs\&.c\&.
.SS "int s2n_server_ccs_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 58 of file s2n_server_ccs\&.c\&.
.SS "int s2n_server_cert_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 29 of file s2n_server_cert\&.c\&.
.SS "int s2n_server_cert_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 78 of file s2n_server_cert\&.c\&.
.SS "int s2n_server_done_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 25 of file s2n_server_done\&.c\&.
.SS "int s2n_server_done_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 36 of file s2n_server_done\&.c\&.
.SS "int s2n_server_extensions_recv (struct \fBs2n_connection\fP * conn, struct \fBs2n_blob\fP * extensions)"

.PP
Definition at line 70 of file s2n_server_extensions\&.c\&.
.SS "int s2n_server_extensions_send (struct \fBs2n_connection\fP * conn, struct \fBs2n_stuffer\fP * out)"

.PP
Definition at line 33 of file s2n_server_extensions\&.c\&.
.SS "int s2n_server_finished_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 27 of file s2n_server_finished\&.c\&.
.SS "int s2n_server_finished_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 49 of file s2n_server_finished\&.c\&.
.SS "int s2n_server_hello_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 34 of file s2n_server_hello\&.c\&.
.SS "int s2n_server_hello_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 104 of file s2n_server_hello\&.c\&.
.SS "int s2n_server_key_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 35 of file s2n_server_key_exchange\&.c\&.
.SS "int s2n_server_key_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 213 of file s2n_server_key_exchange\&.c\&.
.SS "int s2n_server_status_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 44 of file s2n_ocsp_stapling\&.c\&.
.SS "int s2n_server_status_send (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 27 of file s2n_ocsp_stapling\&.c\&.
.SS "int s2n_sslv2_client_hello_recv (struct \fBs2n_connection\fP * conn)"

.PP
Definition at line 148 of file s2n_client_hello\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "uint8_t s2n_highest_protocol_version"

.PP
Definition at line 21 of file s2n_tls\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen from the source code\&.
