.TH "s2n/crypto/s2n_dhe.c" 3 "Tue Jun 28 2016" "s2n-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/crypto/s2n_dhe.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/dh\&.h>\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'error/s2n_errno\&.h'\fP
.br
\fC#include 'stuffer/s2n_stuffer\&.h'\fP
.br
\fC#include 'crypto/s2n_dhe\&.h'\fP
.br
\fC#include 'utils/s2n_safety\&.h'\fP
.br
\fC#include 'utils/s2n_blob\&.h'\fP
.br
\fC#include 'utils/s2n_mem\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBs2n_check_all_dh_params\fP (struct \fBs2n_dh_params\fP *dh_params)"
.br
.ti -1c
.RI "int \fBs2n_pkcs3_to_dh_params\fP (struct \fBs2n_dh_params\fP *dh_params, struct \fBs2n_blob\fP *pkcs3)"
.br
.ti -1c
.RI "int \fBs2n_dh_p_g_Ys_to_dh_params\fP (struct \fBs2n_dh_params\fP *server_dh_params, struct \fBs2n_blob\fP *p, struct \fBs2n_blob\fP *g, struct \fBs2n_blob\fP *Ys)"
.br
.ti -1c
.RI "int \fBs2n_dh_params_to_p_g_Ys\fP (struct \fBs2n_dh_params\fP *server_dh_params, struct \fBs2n_stuffer\fP *out, struct \fBs2n_blob\fP *output)"
.br
.ti -1c
.RI "int \fBs2n_dh_compute_shared_secret_as_client\fP (struct \fBs2n_dh_params\fP *server_dh_params, struct \fBs2n_stuffer\fP *Yc_out, struct \fBs2n_blob\fP *shared_key)"
.br
.ti -1c
.RI "int \fBs2n_dh_compute_shared_secret_as_server\fP (struct \fBs2n_dh_params\fP *server_dh_params, struct \fBs2n_stuffer\fP *Yc_in, struct \fBs2n_blob\fP *shared_key)"
.br
.ti -1c
.RI "int \fBs2n_dh_params_check\fP (struct \fBs2n_dh_params\fP *params)"
.br
.ti -1c
.RI "int \fBs2n_dh_params_copy\fP (struct \fBs2n_dh_params\fP *from, struct \fBs2n_dh_params\fP *to)"
.br
.ti -1c
.RI "int \fBs2n_dh_generate_ephemeral_key\fP (struct \fBs2n_dh_params\fP *dh_params)"
.br
.ti -1c
.RI "int \fBs2n_dh_params_free\fP (struct \fBs2n_dh_params\fP *dh_params)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int s2n_check_all_dh_params (struct \fBs2n_dh_params\fP * dh_params)"

.PP
Definition at line 53 of file s2n_dhe\&.c\&.
.SS "int s2n_dh_compute_shared_secret_as_client (struct \fBs2n_dh_params\fP * server_dh_params, struct \fBs2n_stuffer\fP * Yc_out, struct \fBs2n_blob\fP * shared_key)"

.PP
Definition at line 144 of file s2n_dhe\&.c\&.
.SS "int s2n_dh_compute_shared_secret_as_server (struct \fBs2n_dh_params\fP * server_dh_params, struct \fBs2n_stuffer\fP * Yc_in, struct \fBs2n_blob\fP * shared_key)"

.PP
Definition at line 185 of file s2n_dhe\&.c\&.
.SS "int s2n_dh_generate_ephemeral_key (struct \fBs2n_dh_params\fP * dh_params)"

.PP
Definition at line 242 of file s2n_dhe\&.c\&.
.SS "int s2n_dh_p_g_Ys_to_dh_params (struct \fBs2n_dh_params\fP * server_dh_params, struct \fBs2n_blob\fP * p, struct \fBs2n_blob\fP * g, struct \fBs2n_blob\fP * Ys)"

.PP
Definition at line 88 of file s2n_dhe\&.c\&.
.SS "int s2n_dh_params_check (struct \fBs2n_dh_params\fP * params)"

.PP
Definition at line 216 of file s2n_dhe\&.c\&.
.SS "int s2n_dh_params_copy (struct \fBs2n_dh_params\fP * from, struct \fBs2n_dh_params\fP * to)"

.PP
Definition at line 230 of file s2n_dhe\&.c\&.
.SS "int s2n_dh_params_free (struct \fBs2n_dh_params\fP * dh_params)"

.PP
Definition at line 253 of file s2n_dhe\&.c\&.
.SS "int s2n_dh_params_to_p_g_Ys (struct \fBs2n_dh_params\fP * server_dh_params, struct \fBs2n_stuffer\fP * out, struct \fBs2n_blob\fP * output)"

.PP
Definition at line 104 of file s2n_dhe\&.c\&.
.SS "int s2n_pkcs3_to_dh_params (struct \fBs2n_dh_params\fP * dh_params, struct \fBs2n_blob\fP * pkcs3)"

.PP
Definition at line 65 of file s2n_dhe\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen from the source code\&.
