.TH "s2n/tls/s2n_aead.c" 3 "Tue Jun 28 2016" "s2n-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/tls/s2n_aead.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'error/s2n_errno\&.h'\fP
.br
\fC#include 'utils/s2n_safety\&.h'\fP
.br
\fC#include 'utils/s2n_mem\&.h'\fP
.br
\fC#include 'tls/s2n_record\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBs2n_aead_aad_init\fP (const struct \fBs2n_connection\fP *conn, uint8_t *sequence_number, uint8_t content_type, uint16_t record_length, struct \fBs2n_stuffer\fP *ad)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int s2n_aead_aad_init (const struct \fBs2n_connection\fP * conn, uint8_t * sequence_number, uint8_t content_type, uint16_t record_length, struct \fBs2n_stuffer\fP * ad)"

.PP
Definition at line 25 of file s2n_aead\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen from the source code\&.
