.TH "s2n/tls/s2n_config.c" 3 "Tue Jun 28 2016" "s2n-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/tls/s2n_config.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <strings\&.h>\fP
.br
\fC#include 'error/s2n_errno\&.h'\fP
.br
\fC#include 'tls/s2n_cipher_suites\&.h'\fP
.br
\fC#include 'tls/s2n_config\&.h'\fP
.br
\fC#include 'utils/s2n_random\&.h'\fP
.br
\fC#include 'utils/s2n_safety\&.h'\fP
.br
\fC#include 'utils/s2n_mem\&.h'\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBS2N_CLOCK\fP   CLOCK_MONOTONIC"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBget_nanoseconds_since_epoch\fP (void *data, uint64_t *nanoseconds)"
.br
.ti -1c
.RI "struct \fBs2n_config\fP * \fBs2n_config_new\fP (void)"
.br
.ti -1c
.RI "int \fBs2n_config_free_cert_chain_and_key\fP (struct \fBs2n_config\fP *config)"
.br
.ti -1c
.RI "int \fBs2n_config_free_dhparams\fP (struct \fBs2n_config\fP *config)"
.br
.ti -1c
.RI "int \fBs2n_config_free\fP (struct \fBs2n_config\fP *config)"
.br
.ti -1c
.RI "int \fBs2n_config_set_cipher_preferences\fP (struct \fBs2n_config\fP *config, const char *\fBversion\fP)"
.br
.ti -1c
.RI "int \fBs2n_config_set_protocol_preferences\fP (struct \fBs2n_config\fP *config, const char *const *protocols, int protocol_count)"
.br
.ti -1c
.RI "int \fBs2n_config_set_status_request_type\fP (struct \fBs2n_config\fP *config, \fBs2n_status_request_type\fP type)"
.br
.ti -1c
.RI "int \fBs2n_config_add_cert_chain_and_key_with_status\fP (struct \fBs2n_config\fP *config, char *cert_chain_pem, char *private_key_pem, const uint8_t *status, uint32_t length)"
.br
.ti -1c
.RI "int \fBs2n_config_add_cert_chain_and_key\fP (struct \fBs2n_config\fP *config, char *cert_chain_pem, char *private_key_pem)"
.br
.ti -1c
.RI "int \fBs2n_config_add_dhparams\fP (struct \fBs2n_config\fP *config, char *dhparams_pem)"
.br
.ti -1c
.RI "int \fBs2n_config_set_nanoseconds_since_epoch_callback\fP (struct \fBs2n_config\fP *config, int(*nanoseconds_since_epoch)(void *, uint64_t *), void *data)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint8_t \fBwire_format_20140601\fP []"
.br
.ti -1c
.RI "struct \fBs2n_cipher_preferences\fP \fBcipher_preferences_20140601\fP"
.br
.ti -1c
.RI "struct \fBs2n_cipher_preferences\fP \fBcipher_preferences_20141001\fP"
.br
.ti -1c
.RI "uint8_t \fBwire_format_20150202\fP []"
.br
.ti -1c
.RI "struct \fBs2n_cipher_preferences\fP \fBcipher_preferences_20150202\fP"
.br
.ti -1c
.RI "uint8_t \fBwire_format_20150214\fP []"
.br
.ti -1c
.RI "struct \fBs2n_cipher_preferences\fP \fBcipher_preferences_20150214\fP"
.br
.ti -1c
.RI "uint8_t \fBwire_format_20150306\fP []"
.br
.ti -1c
.RI "struct \fBs2n_cipher_preferences\fP \fBcipher_preferences_20150306\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   const char * \fBversion\fP"
.br
.ti -1c
.RI "   struct \fBs2n_cipher_preferences\fP * \fBpreferences\fP"
.br
.ti -1c
.RI "} \fBselection\fP []"
.br
.ti -1c
.RI "struct \fBs2n_config\fP \fBs2n_default_config\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define S2N_CLOCK   CLOCK_MONOTONIC"

.PP
Definition at line 53 of file s2n_config\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int get_nanoseconds_since_epoch (void * data, uint64_t * nanoseconds)"

.PP
Definition at line 56 of file s2n_config\&.c\&.
.SS "int s2n_config_add_cert_chain_and_key (struct \fBs2n_config\fP * config, char * cert_chain_pem, char * private_key_pem)"

.PP
Definition at line 342 of file s2n_config\&.c\&.
.SS "int s2n_config_add_cert_chain_and_key_with_status (struct \fBs2n_config\fP * config, char * cert_chain_pem, char * private_key_pem, const uint8_t * status, uint32_t length)"

.PP
Definition at line 274 of file s2n_config\&.c\&.
.SS "int s2n_config_add_dhparams (struct \fBs2n_config\fP * config, char * dhparams_pem)"

.PP
Definition at line 349 of file s2n_config\&.c\&.
.SS "int s2n_config_free (struct \fBs2n_config\fP * config)"

.PP
Definition at line 210 of file s2n_config\&.c\&.
.SS "int s2n_config_free_cert_chain_and_key (struct \fBs2n_config\fP * config)"

.PP
Definition at line 165 of file s2n_config\&.c\&.
.SS "int s2n_config_free_dhparams (struct \fBs2n_config\fP * config)"

.PP
Definition at line 195 of file s2n_config\&.c\&.
.SS "struct \fBs2n_config\fP* s2n_config_new (void)"

.PP
Definition at line 145 of file s2n_config\&.c\&.
.SS "int s2n_config_set_cipher_preferences (struct \fBs2n_config\fP * config, const char * version)"

.PP
Definition at line 222 of file s2n_config\&.c\&.
.SS "int s2n_config_set_nanoseconds_since_epoch_callback (struct \fBs2n_config\fP * config, int(*)(void *, uint64_t *) nanoseconds_since_epoch, void * data)"

.PP
Definition at line 378 of file s2n_config\&.c\&.
.SS "int s2n_config_set_protocol_preferences (struct \fBs2n_config\fP * config, const char *const * protocols, int protocol_count)"

.PP
Definition at line 234 of file s2n_config\&.c\&.
.SS "int s2n_config_set_status_request_type (struct \fBs2n_config\fP * config, \fBs2n_status_request_type\fP type)"

.PP
Definition at line 267 of file s2n_config\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "struct \fBs2n_cipher_preferences\fP cipher_preferences_20140601"
\fBInitial value:\fP
.PP
.nf
= {
    \&.count = sizeof(wire_format_20140601) / S2N_TLS_CIPHER_SUITE_LEN,
    \&.wire_format = wire_format_20140601,
    \&.minimum_protocol_version = S2N_SSLv3
}
.fi
.PP
Definition at line 75 of file s2n_config\&.c\&.
.SS "struct \fBs2n_cipher_preferences\fP cipher_preferences_20141001"
\fBInitial value:\fP
.PP
.nf
= {
    \&.count = sizeof(wire_format_20140601) / S2N_TLS_CIPHER_SUITE_LEN,
    \&.wire_format = wire_format_20140601,
    \&.minimum_protocol_version = S2N_TLS10
}
.fi
.PP
Definition at line 82 of file s2n_config\&.c\&.
.SS "struct \fBs2n_cipher_preferences\fP cipher_preferences_20150202"
\fBInitial value:\fP
.PP
.nf
= {
    \&.count = sizeof(wire_format_20150202) / S2N_TLS_CIPHER_SUITE_LEN,
    \&.wire_format = wire_format_20150202,
    \&.minimum_protocol_version = S2N_TLS10
}
.fi
.PP
Definition at line 93 of file s2n_config\&.c\&.
.SS "struct \fBs2n_cipher_preferences\fP cipher_preferences_20150214"
\fBInitial value:\fP
.PP
.nf
= {
    \&.count = sizeof(wire_format_20150214) / S2N_TLS_CIPHER_SUITE_LEN,
    \&.wire_format = wire_format_20150214,
    \&.minimum_protocol_version = S2N_TLS10
}
.fi
.PP
Definition at line 104 of file s2n_config\&.c\&.
.SS "struct \fBs2n_cipher_preferences\fP cipher_preferences_20150306"
\fBInitial value:\fP
.PP
.nf
= {
    \&.count = sizeof(wire_format_20150306) / S2N_TLS_CIPHER_SUITE_LEN,
    \&.wire_format = wire_format_20150306,
    \&.minimum_protocol_version = S2N_TLS10
}
.fi
.PP
Definition at line 120 of file s2n_config\&.c\&.
.SS "struct \fBs2n_cipher_preferences\fP* preferences"

.PP
Definition at line 128 of file s2n_config\&.c\&.
.SS "struct \fBs2n_config\fP s2n_default_config"
\fBInitial value:\fP
.PP
.nf
= {
    \&.cert_and_key_pairs = NULL,
    \&.cipher_preferences = &cipher_preferences_20150306,
    \&.nanoseconds_since_epoch = get_nanoseconds_since_epoch,
}
.fi
.PP
Definition at line 139 of file s2n_config\&.c\&.
.SS "struct { \&.\&.\&. }   selection[]"
\fBInitial value:\fP
.PP
.nf
= {
    { "default", &cipher_preferences_20150306 },
    { "20140601", &cipher_preferences_20140601 },
    { "20141001", &cipher_preferences_20141001 },
    { "20150202", &cipher_preferences_20150202 },
    { "20150214", &cipher_preferences_20150214 },
    { "20150306", &cipher_preferences_20150306 },
    { NULL, NULL }
}
.fi
.SS "const char* version"

.PP
Definition at line 127 of file s2n_config\&.c\&.
.SS "uint8_t wire_format_20140601[]"
\fBInitial value:\fP
.PP
.nf
=
    { TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA,
    TLS_RSA_WITH_3DES_EDE_CBC_SHA, TLS_RSA_WITH_RC4_128_SHA, TLS_RSA_WITH_RC4_128_MD5
}
.fi
.PP
Definition at line 71 of file s2n_config\&.c\&.
.SS "uint8_t wire_format_20150202[]"
\fBInitial value:\fP
.PP
.nf
=
    { TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA,
    TLS_RSA_WITH_3DES_EDE_CBC_SHA
}
.fi
.PP
Definition at line 89 of file s2n_config\&.c\&.
.SS "uint8_t wire_format_20150214[]"
\fBInitial value:\fP
.PP
.nf
=
    { TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA,
    TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA
}
.fi
.PP
Definition at line 100 of file s2n_config\&.c\&.
.SS "uint8_t wire_format_20150306[]"
\fBInitial value:\fP
.PP
.nf
= {
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,
    TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
    TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_3DES_EDE_CBC_SHA
}
.fi
.PP
Definition at line 111 of file s2n_config\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen from the source code\&.
