.TH "s2n/stuffer/s2n_stuffer_file.c" 3 "Tue Jun 28 2016" "s2n-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/stuffer/s2n_stuffer_file.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/mman\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include 'error/s2n_errno\&.h'\fP
.br
\fC#include 'stuffer/s2n_stuffer\&.h'\fP
.br
\fC#include 'utils/s2n_safety\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBs2n_stuffer_recv_from_fd\fP (struct \fBs2n_stuffer\fP *stuffer, int rfd, uint32_t len)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_send_to_fd\fP (struct \fBs2n_stuffer\fP *stuffer, int wfd, uint32_t len)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_alloc_ro_from_fd\fP (struct \fBs2n_stuffer\fP *stuffer, int rfd)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_alloc_ro_from_file\fP (struct \fBs2n_stuffer\fP *stuffer, const char *file)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int s2n_stuffer_alloc_ro_from_fd (struct \fBs2n_stuffer\fP * stuffer, int rfd)"

.PP
Definition at line 78 of file s2n_stuffer_file\&.c\&.
.SS "int s2n_stuffer_alloc_ro_from_file (struct \fBs2n_stuffer\fP * stuffer, const char * file)"

.PP
Definition at line 96 of file s2n_stuffer_file\&.c\&.
.SS "int s2n_stuffer_recv_from_fd (struct \fBs2n_stuffer\fP * stuffer, int rfd, uint32_t len)"

.PP
Definition at line 29 of file s2n_stuffer_file\&.c\&.
.SS "int s2n_stuffer_send_to_fd (struct \fBs2n_stuffer\fP * stuffer, int wfd, uint32_t len)"

.PP
Definition at line 55 of file s2n_stuffer_file\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-doxygen from the source code\&.
