.TH "_ossl_old_des_ks_struct" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ossl_old_des_ks_struct \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <des_old\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB_ossl_old_des_cblock\fP \fB_\fP"
.br
.ti -1c
.RI "   DES_LONG \fBpad\fP [2]"
.br
.ti -1c
.RI "} \fBks\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB_ossl_old_des_cblock\fP \fB_\fP"
.br
.ti -1c
.RI "   DES_LONG \fBpad\fP [2]"
.br
.ti -1c
.RI "} \fBks\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fB_ossl_old_des_cblock\fP \fB_\fP"
.br
.ti -1c
.RI "   DES_LONG \fBpad\fP [2]"
.br
.ti -1c
.RI "} \fBks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 126 of file des_old\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fB_ossl_old_des_cblock\fP _"

.PP
Definition at line 128 of file des_old\&.h\&.
.SS "union { \&.\&.\&. }   ks"

.SS "union { \&.\&.\&. }   ks"

.SS "union { \&.\&.\&. }   ks"

.SS "DES_LONG pad[2]"

.PP
Definition at line 132 of file des_old\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
