.TH "_tunala_item_t" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_tunala_item_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBstate_machine_t\fP \fBsm\fP"
.br
.ti -1c
.RI "int \fBdirty_read\fP"
.br
.ti -1c
.RI "int \fBdirty_send\fP"
.br
.ti -1c
.RI "int \fBclean_read\fP"
.br
.ti -1c
.RI "int \fBclean_send\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file tunala\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int clean_read"

.PP
Definition at line 35 of file tunala\&.c\&.
.SS "int clean_send"

.PP
Definition at line 35 of file tunala\&.c\&.
.SS "int dirty_read"

.PP
Definition at line 29 of file tunala\&.c\&.
.SS "int dirty_send"

.PP
Definition at line 29 of file tunala\&.c\&.
.SS "\fBstate_machine_t\fP sm"

.PP
Definition at line 23 of file tunala\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
