.TH "s2n/libcrypto-build/openssl/crypto/asn1/a_type.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/a_type.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBASN1_TYPE_get\fP (\fBASN1_TYPE\fP *\fBa\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBASN1_TYPE_set\fP (\fBASN1_TYPE\fP *\fBa\fP, int \fBtype\fP, \fBvoid\fP *value)"
.br
.ti -1c
.RI "int \fBASN1_TYPE_set1\fP (\fBASN1_TYPE\fP *\fBa\fP, int \fBtype\fP, const \fBvoid\fP *value)"
.br
.ti -1c
.RI "int \fBASN1_TYPE_cmp\fP (const \fBASN1_TYPE\fP *\fBa\fP, const \fBASN1_TYPE\fP *\fBb\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ASN1_TYPE_cmp (const \fBASN1_TYPE\fP * a, const \fBASN1_TYPE\fP * b)"

.PP
Definition at line 111 of file a_type\&.c\&.
.SS "int ASN1_TYPE_get (\fBASN1_TYPE\fP * a)"

.PP
Definition at line 64 of file a_type\&.c\&.
.SS "\fBvoid\fP ASN1_TYPE_set (\fBASN1_TYPE\fP * a, int type, \fBvoid\fP * value)"

.PP
Definition at line 72 of file a_type\&.c\&.
.SS "int ASN1_TYPE_set1 (\fBASN1_TYPE\fP * a, int type, const \fBvoid\fP * value)"

.PP
Definition at line 85 of file a_type\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
