.TH "AEP_CONNECTION_ENTRY" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AEP_CONNECTION_ENTRY \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aep\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBAEP_CONNECTION_STATE\fP \fBconn_state\fP"
.br
.ti -1c
.RI "\fBAEP_CONNECTION_HNDL\fP \fBconn_hndl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 188 of file aep\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBAEP_CONNECTION_HNDL\fP conn_hndl"

.PP
Definition at line 190 of file aep\&.h\&.
.SS "\fBAEP_CONNECTION_STATE\fP conn_state"

.PP
Definition at line 189 of file aep\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
