.TH "s2n/libcrypto-build/openssl/crypto/aes/aes_ige.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/aes/aes_ige.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/aes\&.h>\fP
.br
\fC#include 'aes_locl\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBaes_block_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBN_WORDS\fP   (\fBAES_BLOCK_SIZE\fP / sizeof(unsigned long))"
.br
.ti -1c
.RI "#define \fBUNALIGNED_MEMOPS_ARE_FAST\fP   0"
.br
.ti -1c
.RI "#define \fBload_block\fP(d,  s)               memcpy((d)\&.\fBdata\fP, (s), \fBAES_BLOCK_SIZE\fP)"
.br
.ti -1c
.RI "#define \fBstore_block\fP(d,  s)             memcpy((d), (s)\&.\fBdata\fP, \fBAES_BLOCK_SIZE\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBAES_ige_encrypt\fP (const unsigned char *\fBin\fP, unsigned char *\fBout\fP, size_t \fBlength\fP, const \fBAES_KEY\fP *\fBkey\fP, unsigned char *ivec, const int \fBenc\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBAES_bi_ige_encrypt\fP (const unsigned char *\fBin\fP, unsigned char *\fBout\fP, size_t \fBlength\fP, const \fBAES_KEY\fP *\fBkey\fP, const \fBAES_KEY\fP *key2, const unsigned char *ivec, const int \fBenc\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define load_block(d, s)   memcpy((d)\&.\fBdata\fP, (s), \fBAES_BLOCK_SIZE\fP)"

.PP
Definition at line 73 of file aes_ige\&.c\&.
.SS "#define N_WORDS   (\fBAES_BLOCK_SIZE\fP / sizeof(unsigned long))"

.PP
Definition at line 57 of file aes_ige\&.c\&.
.SS "#define store_block(d, s)   memcpy((d), (s)\&.\fBdata\fP, \fBAES_BLOCK_SIZE\fP)"

.PP
Definition at line 74 of file aes_ige\&.c\&.
.SS "#define UNALIGNED_MEMOPS_ARE_FAST   0"

.PP
Definition at line 66 of file aes_ige\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP AES_bi_ige_encrypt (const unsigned char * in, unsigned char * out, size_t length, const \fBAES_KEY\fP * key, const \fBAES_KEY\fP * key2, const unsigned char * ivec, const int enc)"

.PP
Definition at line 208 of file aes_ige\&.c\&.
.SS "\fBvoid\fP AES_ige_encrypt (const unsigned char * in, unsigned char * out, size_t length, const \fBAES_KEY\fP * key, unsigned char * ivec, const int enc)"

.PP
Definition at line 79 of file aes_ige\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
