.TH "ASN1_TLC_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ASN1_TLC_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <asn1t\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBvalid\fP"
.br
.ti -1c
.RI "int \fBret\fP"
.br
.ti -1c
.RI "long \fBplen\fP"
.br
.ti -1c
.RI "int \fBptag\fP"
.br
.ti -1c
.RI "int \fBpclass\fP"
.br
.ti -1c
.RI "int \fBhdrlen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 641 of file asn1t\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int hdrlen"

.PP
Definition at line 647 of file asn1t\&.h\&.
.SS "int pclass"

.PP
Definition at line 646 of file asn1t\&.h\&.
.SS "long plen"

.PP
Definition at line 644 of file asn1t\&.h\&.
.SS "int ptag"

.PP
Definition at line 645 of file asn1t\&.h\&.
.SS "int ret"

.PP
Definition at line 643 of file asn1t\&.h\&.
.SS "char valid"

.PP
Definition at line 642 of file asn1t\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
