.TH "bf_key_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bf_key_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <blowfish\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBF_LONG\fP \fBP\fP [\fBBF_ROUNDS\fP+2]"
.br
.ti -1c
.RI "\fBBF_LONG\fP \fBS\fP [4 *256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 101 of file blowfish\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBBF_LONG\fP P[\fBBF_ROUNDS\fP+2]"

.PP
Definition at line 102 of file blowfish\&.h\&.
.SS "\fBBF_LONG\fP S[4 *256]"

.PP
Definition at line 103 of file blowfish\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
