.TH "bignum_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bignum_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bn\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "BN_ULONG * \fBd\fP"
.br
.ti -1c
.RI "int \fBtop\fP"
.br
.ti -1c
.RI "int \fBdmax\fP"
.br
.ti -1c
.RI "int \fBneg\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 313 of file bn\&.h\&.
.SH "Field Documentation"
.PP 
.SS "BN_ULONG * d"

.PP
Definition at line 314 of file bn\&.h\&.
.SS "int dmax"

.PP
Definition at line 318 of file bn\&.h\&.
.SS "int flags"

.PP
Definition at line 320 of file bn\&.h\&.
.SS "int neg"

.PP
Definition at line 319 of file bn\&.h\&.
.SS "int top"

.PP
Definition at line 316 of file bn\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
