.TH "bignum_pool_item" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bignum_pool_item \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBIGNUM\fP \fBvals\fP [\fBBN_CTX_POOL_SIZE\fP]"
.br
.ti -1c
.RI "struct \fBbignum_pool_item\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fBbignum_pool_item\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file bn_ctx\&.c\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBbignum_pool_item\fP * next"

.PP
Definition at line 96 of file bn_ctx\&.c\&.
.SS "struct \fBbignum_pool_item\fP* prev"

.PP
Definition at line 96 of file bn_ctx\&.c\&.
.SS "\fBBIGNUM\fP vals[\fBBN_CTX_POOL_SIZE\fP]"

.PP
Definition at line 94 of file bn_ctx\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
