.TH "BIO_ASN1_BUF_CTX_t" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BIO_ASN1_BUF_CTX_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBasn1_bio_state_t\fP \fBstate\fP"
.br
.ti -1c
.RI "unsigned char * \fBbuf\fP"
.br
.ti -1c
.RI "int \fBbufsize\fP"
.br
.ti -1c
.RI "int \fBbufpos\fP"
.br
.ti -1c
.RI "int \fBbuflen\fP"
.br
.ti -1c
.RI "int \fBcopylen\fP"
.br
.ti -1c
.RI "int \fBasn1_class\fP"
.br
.ti -1c
.RI "int \fBasn1_tag\fP"
.br
.ti -1c
.RI "\fBasn1_ps_func\fP * \fBprefix\fP"
.br
.ti -1c
.RI "\fBasn1_ps_func\fP * \fBprefix_free\fP"
.br
.ti -1c
.RI "\fBasn1_ps_func\fP * \fBsuffix\fP"
.br
.ti -1c
.RI "\fBasn1_ps_func\fP * \fBsuffix_free\fP"
.br
.ti -1c
.RI "unsigned char * \fBex_buf\fP"
.br
.ti -1c
.RI "int \fBex_len\fP"
.br
.ti -1c
.RI "int \fBex_pos\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBex_arg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file bio_asn1\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int asn1_class"

.PP
Definition at line 102 of file bio_asn1\&.c\&.
.SS "int asn1_tag"

.PP
Definition at line 102 of file bio_asn1\&.c\&.
.SS "unsigned char* buf"

.PP
Definition at line 92 of file bio_asn1\&.c\&.
.SS "int buflen"

.PP
Definition at line 98 of file bio_asn1\&.c\&.
.SS "int bufpos"

.PP
Definition at line 96 of file bio_asn1\&.c\&.
.SS "int bufsize"

.PP
Definition at line 94 of file bio_asn1\&.c\&.
.SS "int copylen"

.PP
Definition at line 100 of file bio_asn1\&.c\&.
.SS "\fBvoid\fP* ex_arg"

.PP
Definition at line 108 of file bio_asn1\&.c\&.
.SS "unsigned char* ex_buf"

.PP
Definition at line 105 of file bio_asn1\&.c\&.
.SS "int ex_len"

.PP
Definition at line 106 of file bio_asn1\&.c\&.
.SS "int ex_pos"

.PP
Definition at line 107 of file bio_asn1\&.c\&.
.SS "\fBasn1_ps_func\fP* prefix"

.PP
Definition at line 103 of file bio_asn1\&.c\&.
.SS "\fBasn1_ps_func\fP * prefix_free"

.PP
Definition at line 103 of file bio_asn1\&.c\&.
.SS "\fBasn1_bio_state_t\fP state"

.PP
Definition at line 90 of file bio_asn1\&.c\&.
.SS "\fBasn1_ps_func\fP * suffix"

.PP
Definition at line 103 of file bio_asn1\&.c\&.
.SS "\fBasn1_ps_func\fP * suffix_free"

.PP
Definition at line 103 of file bio_asn1\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
