.TH "bio_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bio_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBIO_METHOD\fP * \fBmethod\fP"
.br
.ti -1c
.RI "long(* \fBcallback\fP )(struct \fBbio_st\fP *, int, const char *, int, long, long)"
.br
.ti -1c
.RI "char * \fBcb_arg\fP"
.br
.ti -1c
.RI "int \fBinit\fP"
.br
.ti -1c
.RI "int \fBshutdown\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBretry_reason\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBptr\fP"
.br
.ti -1c
.RI "struct \fBbio_st\fP * \fBnext_bio\fP"
.br
.ti -1c
.RI "struct \fBbio_st\fP * \fBprev_bio\fP"
.br
.ti -1c
.RI "int \fBreferences\fP"
.br
.ti -1c
.RI "unsigned long \fBnum_read\fP"
.br
.ti -1c
.RI "unsigned long \fBnum_write\fP"
.br
.ti -1c
.RI "\fBCRYPTO_EX_DATA\fP \fBex_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 325 of file bio\&.h\&.
.SH "Field Documentation"
.PP 
.SS "long(* callback)(struct \fBbio_st\fP *, int, const char *, int, long, long)"

.PP
Definition at line 328 of file bio\&.h\&.
.SS "char * cb_arg"

.PP
Definition at line 329 of file bio\&.h\&.
.SS "\fBCRYPTO_EX_DATA\fP ex_data"

.PP
Definition at line 341 of file bio\&.h\&.
.SS "int flags"

.PP
Definition at line 332 of file bio\&.h\&.
.SS "int init"

.PP
Definition at line 330 of file bio\&.h\&.
.SS "\fBBIO_METHOD\fP * method"

.PP
Definition at line 326 of file bio\&.h\&.
.SS "struct \fBbio_st\fP * next_bio"

.PP
Definition at line 336 of file bio\&.h\&.
.SS "int num"

.PP
Definition at line 334 of file bio\&.h\&.
.SS "unsigned long num_read"

.PP
Definition at line 339 of file bio\&.h\&.
.SS "unsigned long num_write"

.PP
Definition at line 340 of file bio\&.h\&.
.SS "struct \fBbio_st\fP * prev_bio"

.PP
Definition at line 337 of file bio\&.h\&.
.SS "\fBvoid\fP * ptr"

.PP
Definition at line 335 of file bio\&.h\&.
.SS "int references"

.PP
Definition at line 338 of file bio\&.h\&.
.SS "int retry_reason"

.PP
Definition at line 333 of file bio\&.h\&.
.SS "int shutdown"

.PP
Definition at line 331 of file bio\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
