.TH "s2n/libcrypto-build/openssl/crypto/bn/bn_const.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/bn/bn_const.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'bn\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBIGNUM\fP * \fBget_rfc2409_prime_768\fP (\fBBIGNUM\fP *bn)"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBget_rfc2409_prime_1024\fP (\fBBIGNUM\fP *bn)"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBget_rfc3526_prime_1536\fP (\fBBIGNUM\fP *bn)"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBget_rfc3526_prime_2048\fP (\fBBIGNUM\fP *bn)"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBget_rfc3526_prime_3072\fP (\fBBIGNUM\fP *bn)"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBget_rfc3526_prime_4096\fP (\fBBIGNUM\fP *bn)"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBget_rfc3526_prime_6144\fP (\fBBIGNUM\fP *bn)"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBget_rfc3526_prime_8192\fP (\fBBIGNUM\fP *bn)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBBIGNUM\fP* get_rfc2409_prime_1024 (\fBBIGNUM\fP * bn)"

.PP
Definition at line 43 of file bn_const\&.c\&.
.SS "\fBBIGNUM\fP* get_rfc2409_prime_768 (\fBBIGNUM\fP * bn)"

.PP
Definition at line 15 of file bn_const\&.c\&.
.SS "\fBBIGNUM\fP* get_rfc3526_prime_1536 (\fBBIGNUM\fP * bn)"

.PP
Definition at line 75 of file bn_const\&.c\&.
.SS "\fBBIGNUM\fP* get_rfc3526_prime_2048 (\fBBIGNUM\fP * bn)"

.PP
Definition at line 114 of file bn_const\&.c\&.
.SS "\fBBIGNUM\fP* get_rfc3526_prime_3072 (\fBBIGNUM\fP * bn)"

.PP
Definition at line 161 of file bn_const\&.c\&.
.SS "\fBBIGNUM\fP* get_rfc3526_prime_4096 (\fBBIGNUM\fP * bn)"

.PP
Definition at line 224 of file bn_const\&.c\&.
.SS "\fBBIGNUM\fP* get_rfc3526_prime_6144 (\fBBIGNUM\fP * bn)"

.PP
Definition at line 303 of file bn_const\&.c\&.
.SS "\fBBIGNUM\fP* get_rfc3526_prime_8192 (\fBBIGNUM\fP * bn)"

.PP
Definition at line 414 of file bn_const\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
