.TH "s2n/libcrypto-build/openssl/crypto/bn/bn_mod.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/bn/bn_mod.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include 'bn_lcl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBBN_nnmod\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *m, const \fBBIGNUM\fP *d, \fBBN_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBBN_mod_add\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *\fBb\fP, const \fBBIGNUM\fP *m, \fBBN_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBBN_mod_add_quick\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *\fBb\fP, const \fBBIGNUM\fP *m)"
.br
.ti -1c
.RI "int \fBBN_mod_sub\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *\fBb\fP, const \fBBIGNUM\fP *m, \fBBN_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBBN_mod_sub_quick\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *\fBb\fP, const \fBBIGNUM\fP *m)"
.br
.ti -1c
.RI "int \fBBN_mod_mul\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *\fBb\fP, const \fBBIGNUM\fP *m, \fBBN_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBBN_mod_sqr\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *m, \fBBN_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBBN_mod_lshift1\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *m, \fBBN_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBBN_mod_lshift1_quick\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, const \fBBIGNUM\fP *m)"
.br
.ti -1c
.RI "int \fBBN_mod_lshift\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, int n, const \fBBIGNUM\fP *m, \fBBN_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBBN_mod_lshift_quick\fP (\fBBIGNUM\fP *r, const \fBBIGNUM\fP *\fBa\fP, int n, const \fBBIGNUM\fP *m)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int BN_mod_add (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * a, const \fBBIGNUM\fP * b, const \fBBIGNUM\fP * m, \fBBN_CTX\fP * ctx)"

.PP
Definition at line 142 of file bn_mod\&.c\&.
.SS "int BN_mod_add_quick (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * a, const \fBBIGNUM\fP * b, const \fBBIGNUM\fP * m)"

.PP
Definition at line 154 of file bn_mod\&.c\&.
.SS "int BN_mod_lshift (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * a, int n, const \fBBIGNUM\fP * m, \fBBN_CTX\fP * ctx)"

.PP
Definition at line 246 of file bn_mod\&.c\&.
.SS "int BN_mod_lshift1 (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * a, const \fBBIGNUM\fP * m, \fBBN_CTX\fP * ctx)"

.PP
Definition at line 224 of file bn_mod\&.c\&.
.SS "int BN_mod_lshift1_quick (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * a, const \fBBIGNUM\fP * m)"

.PP
Definition at line 236 of file bn_mod\&.c\&.
.SS "int BN_mod_lshift_quick (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * a, int n, const \fBBIGNUM\fP * m)"

.PP
Definition at line 274 of file bn_mod\&.c\&.
.SS "int BN_mod_mul (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * a, const \fBBIGNUM\fP * b, const \fBBIGNUM\fP * m, \fBBN_CTX\fP * ctx)"

.PP
Definition at line 187 of file bn_mod\&.c\&.
.SS "int BN_mod_sqr (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * a, const \fBBIGNUM\fP * m, \fBBN_CTX\fP * ctx)"

.PP
Definition at line 216 of file bn_mod\&.c\&.
.SS "int BN_mod_sub (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * a, const \fBBIGNUM\fP * b, const \fBBIGNUM\fP * m, \fBBN_CTX\fP * ctx)"

.PP
Definition at line 164 of file bn_mod\&.c\&.
.SS "int BN_mod_sub_quick (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * a, const \fBBIGNUM\fP * b, const \fBBIGNUM\fP * m)"

.PP
Definition at line 176 of file bn_mod\&.c\&.
.SS "int BN_nnmod (\fBBIGNUM\fP * r, const \fBBIGNUM\fP * m, const \fBBIGNUM\fP * d, \fBBN_CTX\fP * ctx)"

.PP
Definition at line 127 of file bn_mod\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
