.TH "s2n/libcrypto-build/openssl/crypto/bio/bss_sock.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/bio/bss_sock.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSE_SOCKETS\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBBIO_sock_should_retry\fP (int s)"
.br
.ti -1c
.RI "\fBBIO_METHOD\fP * \fBBIO_s_socket\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBBIO\fP * \fBBIO_new_socket\fP (int fd, int close_flag)"
.br
.ti -1c
.RI "int \fBBIO_sock_non_fatal_error\fP (int err)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define USE_SOCKETS"

.PP
Definition at line 61 of file bss_sock\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBBIO\fP* BIO_new_socket (int fd, int close_flag)"

.PP
Definition at line 100 of file bss_sock\&.c\&.
.SS "\fBBIO_METHOD\fP* BIO_s_socket (\fBvoid\fP)"

.PP
Definition at line 95 of file bss_sock\&.c\&.
.SS "int BIO_sock_non_fatal_error (int err)"

.PP
Definition at line 229 of file bss_sock\&.c\&.
.SS "int BIO_sock_should_retry (int s)"

.PP
Definition at line 211 of file bss_sock\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
