.TH "s2n/libcrypto-build/openssl/apps/ca.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/apps/ca.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <openssl/conf\&.h>\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <openssl/txt_db\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/ocsp\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <sys/file\&.h>\fP
.br
\fC#include 'apps\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_OK\fP   0"
.br
.ti -1c
.RI "#define \fBX_OK\fP   1"
.br
.ti -1c
.RI "#define \fBW_OK\fP   2"
.br
.ti -1c
.RI "#define \fBR_OK\fP   4"
.br
.ti -1c
.RI "#define \fBPROG\fP   \fBca_main\fP"
.br
.ti -1c
.RI "#define \fBBASE_SECTION\fP   'ca'"
.br
.ti -1c
.RI "#define \fBCONFIG_FILE\fP   'openssl\&.cnf'"
.br
.ti -1c
.RI "#define \fBENV_DEFAULT_CA\fP   'default_ca'"
.br
.ti -1c
.RI "#define \fBSTRING_MASK\fP   'string_mask'"
.br
.ti -1c
.RI "#define \fBUTF8_IN\fP   'utf8'"
.br
.ti -1c
.RI "#define \fBENV_NEW_CERTS_DIR\fP   'new_certs_dir'"
.br
.ti -1c
.RI "#define \fBENV_CERTIFICATE\fP   'certificate'"
.br
.ti -1c
.RI "#define \fBENV_SERIAL\fP   'serial'"
.br
.ti -1c
.RI "#define \fBENV_CRLNUMBER\fP   'crlnumber'"
.br
.ti -1c
.RI "#define \fBENV_PRIVATE_KEY\fP   'private_key'"
.br
.ti -1c
.RI "#define \fBENV_DEFAULT_DAYS\fP   'default_days'"
.br
.ti -1c
.RI "#define \fBENV_DEFAULT_STARTDATE\fP   'default_startdate'"
.br
.ti -1c
.RI "#define \fBENV_DEFAULT_ENDDATE\fP   'default_enddate'"
.br
.ti -1c
.RI "#define \fBENV_DEFAULT_CRL_DAYS\fP   'default_crl_days'"
.br
.ti -1c
.RI "#define \fBENV_DEFAULT_CRL_HOURS\fP   'default_crl_hours'"
.br
.ti -1c
.RI "#define \fBENV_DEFAULT_MD\fP   'default_md'"
.br
.ti -1c
.RI "#define \fBENV_DEFAULT_EMAIL_DN\fP   'email_in_dn'"
.br
.ti -1c
.RI "#define \fBENV_PRESERVE\fP   'preserve'"
.br
.ti -1c
.RI "#define \fBENV_POLICY\fP   'policy'"
.br
.ti -1c
.RI "#define \fBENV_EXTENSIONS\fP   'x509_extensions'"
.br
.ti -1c
.RI "#define \fBENV_CRLEXT\fP   'crl_extensions'"
.br
.ti -1c
.RI "#define \fBENV_MSIE_HACK\fP   'msie_hack'"
.br
.ti -1c
.RI "#define \fBENV_NAMEOPT\fP   'name_opt'"
.br
.ti -1c
.RI "#define \fBENV_CERTOPT\fP   'cert_opt'"
.br
.ti -1c
.RI "#define \fBENV_EXTCOPY\fP   'copy_extensions'"
.br
.ti -1c
.RI "#define \fBENV_UNIQUE_SUBJECT\fP   'unique_subject'"
.br
.ti -1c
.RI "#define \fBENV_DATABASE\fP   'database'"
.br
.ti -1c
.RI "#define \fBREV_NONE\fP   0 /* No addditional information */"
.br
.ti -1c
.RI "#define \fBREV_CRL_REASON\fP   1 /* Value is CRL reason \fBcode\fP */"
.br
.ti -1c
.RI "#define \fBREV_HOLD\fP   2 /* Value is hold instruction */"
.br
.ti -1c
.RI "#define \fBREV_KEY_COMPROMISE\fP   3 /* Value is cert \fBkey\fP compromise time */"
.br
.ti -1c
.RI "#define \fBREV_CA_COMPROMISE\fP   4 /* Value is CA \fBkey\fP compromise time */"
.br
.ti -1c
.RI "#define \fBBSIZE\fP   256"
.br
.ti -1c
.RI "#define \fBNUM_REASONS\fP   (sizeof(crl_reasons) / sizeof(char *))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmake_revocation_str\fP (int rev_type, char *rev_arg)"
.br
.ti -1c
.RI "int \fBmake_revoked\fP (\fBX509_REVOKED\fP *rev, const char *str)"
.br
.ti -1c
.RI "int \fBold_entry_print\fP (\fBBIO\fP *\fBbp\fP, \fBASN1_OBJECT\fP *\fBobj\fP, \fBASN1_STRING\fP *str)"
.br
.ti -1c
.RI "int \fBMAIN\fP (int, char **)"
.br
.ti -1c
.RI "int \fBunpack_revinfo\fP (\fBASN1_TIME\fP **prevtm, int *preason, \fBASN1_OBJECT\fP **phold, \fBASN1_GENERALIZEDTIME\fP **pinvtm, const char *str)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BASE_SECTION   'ca'"

.PP
Definition at line 102 of file ca\&.c\&.
.SS "#define BSIZE   256"

.SS "#define CONFIG_FILE   'openssl\&.cnf'"

.PP
Definition at line 103 of file ca\&.c\&.
.SS "#define ENV_CERTIFICATE   'certificate'"

.PP
Definition at line 111 of file ca\&.c\&.
.SS "#define ENV_CERTOPT   'cert_opt'"

.PP
Definition at line 128 of file ca\&.c\&.
.SS "#define ENV_CRLEXT   'crl_extensions'"

.PP
Definition at line 125 of file ca\&.c\&.
.SS "#define ENV_CRLNUMBER   'crlnumber'"

.PP
Definition at line 113 of file ca\&.c\&.
.SS "#define ENV_DATABASE   'database'"

.PP
Definition at line 132 of file ca\&.c\&.
.SS "#define ENV_DEFAULT_CA   'default_ca'"

.PP
Definition at line 105 of file ca\&.c\&.
.SS "#define ENV_DEFAULT_CRL_DAYS   'default_crl_days'"

.PP
Definition at line 118 of file ca\&.c\&.
.SS "#define ENV_DEFAULT_CRL_HOURS   'default_crl_hours'"

.PP
Definition at line 119 of file ca\&.c\&.
.SS "#define ENV_DEFAULT_DAYS   'default_days'"

.PP
Definition at line 115 of file ca\&.c\&.
.SS "#define ENV_DEFAULT_EMAIL_DN   'email_in_dn'"

.PP
Definition at line 121 of file ca\&.c\&.
.SS "#define ENV_DEFAULT_ENDDATE   'default_enddate'"

.PP
Definition at line 117 of file ca\&.c\&.
.SS "#define ENV_DEFAULT_MD   'default_md'"

.PP
Definition at line 120 of file ca\&.c\&.
.SS "#define ENV_DEFAULT_STARTDATE   'default_startdate'"

.PP
Definition at line 116 of file ca\&.c\&.
.SS "#define ENV_EXTCOPY   'copy_extensions'"

.PP
Definition at line 129 of file ca\&.c\&.
.SS "#define ENV_EXTENSIONS   'x509_extensions'"

.PP
Definition at line 124 of file ca\&.c\&.
.SS "#define ENV_MSIE_HACK   'msie_hack'"

.PP
Definition at line 126 of file ca\&.c\&.
.SS "#define ENV_NAMEOPT   'name_opt'"

.PP
Definition at line 127 of file ca\&.c\&.
.SS "#define ENV_NEW_CERTS_DIR   'new_certs_dir'"

.PP
Definition at line 110 of file ca\&.c\&.
.SS "#define ENV_POLICY   'policy'"

.PP
Definition at line 123 of file ca\&.c\&.
.SS "#define ENV_PRESERVE   'preserve'"

.PP
Definition at line 122 of file ca\&.c\&.
.SS "#define ENV_PRIVATE_KEY   'private_key'"

.PP
Definition at line 114 of file ca\&.c\&.
.SS "#define ENV_SERIAL   'serial'"

.PP
Definition at line 112 of file ca\&.c\&.
.SS "#define ENV_UNIQUE_SUBJECT   'unique_subject'"

.PP
Definition at line 130 of file ca\&.c\&.
.SS "#define F_OK   0"

.PP
Definition at line 93 of file ca\&.c\&.
.SS "#define NUM_REASONS   (sizeof(crl_reasons) / sizeof(char *))"

.PP
Definition at line 2608 of file ca\&.c\&.
.SS "#define PROG   \fBca_main\fP"

.PP
Definition at line 100 of file ca\&.c\&.
.SS "#define R_OK   4"

.PP
Definition at line 96 of file ca\&.c\&.
.SS "#define REV_CA_COMPROMISE   4 /* Value is CA \fBkey\fP compromise time */"

.PP
Definition at line 140 of file ca\&.c\&.
.SS "#define REV_CRL_REASON   1 /* Value is CRL reason \fBcode\fP */"

.PP
Definition at line 137 of file ca\&.c\&.
.SS "#define REV_HOLD   2 /* Value is hold instruction */"

.PP
Definition at line 138 of file ca\&.c\&.
.SS "#define REV_KEY_COMPROMISE   3 /* Value is cert \fBkey\fP compromise time */"

.PP
Definition at line 139 of file ca\&.c\&.
.SS "#define REV_NONE   0 /* No addditional information */"

.PP
Definition at line 136 of file ca\&.c\&.
.SS "#define STRING_MASK   'string_mask'"

.PP
Definition at line 107 of file ca\&.c\&.
.SS "#define UTF8_IN   'utf8'"

.PP
Definition at line 108 of file ca\&.c\&.
.SS "#define W_OK   2"

.PP
Definition at line 95 of file ca\&.c\&.
.SS "#define X_OK   1"

.PP
Definition at line 94 of file ca\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int MAIN (int argc, char ** argv)"

.PP
Definition at line 245 of file ca\&.c\&.
.SS "char * make_revocation_str (int rev_type, char * rev_arg)"

.PP
Definition at line 2617 of file ca\&.c\&.
.SS "int make_revoked (\fBX509_REVOKED\fP * rev, const char * str)"

.PP
Definition at line 2714 of file ca\&.c\&.
.SS "int old_entry_print (\fBBIO\fP * bp, \fBASN1_OBJECT\fP * obj, \fBASN1_STRING\fP * str)"

.PP
Definition at line 2769 of file ca\&.c\&.
.SS "int unpack_revinfo (\fBASN1_TIME\fP ** prevtm, int * preason, \fBASN1_OBJECT\fP ** phold, \fBASN1_GENERALIZEDTIME\fP ** pinvtm, const char * str)"

.PP
Definition at line 2808 of file ca\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
