.TH "s2n/libcrypto-build/openssl/demos/tunala/cb.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/demos/tunala/cb.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tunala\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBcb_ssl_info\fP (const \fBSSL\fP *s, int where, int ret)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcb_ssl_info_set_output\fP (FILE *\fBfp\fP)"
.br
.ti -1c
.RI "int \fBcb_ssl_verify\fP (int ok, \fBX509_STORE_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcb_ssl_verify_set_output\fP (FILE *\fBfp\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcb_ssl_verify_set_depth\fP (unsigned int \fBverify_depth\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcb_ssl_verify_set_level\fP (unsigned int level)"
.br
.ti -1c
.RI "\fBRSA\fP * \fBcb_generate_tmp_rsa\fP (\fBSSL\fP *s, int is_export, int keylength)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBRSA\fP* cb_generate_tmp_rsa (\fBSSL\fP * s, int is_export, int keylength)"

.PP
Definition at line 142 of file cb\&.c\&.
.SS "\fBvoid\fP cb_ssl_info (const \fBSSL\fP * s, int where, int ret)"

.PP
Definition at line 23 of file cb\&.c\&.
.SS "\fBvoid\fP cb_ssl_info_set_output (FILE * fp)"

.PP
Definition at line 56 of file cb\&.c\&.
.SS "int cb_ssl_verify (int ok, \fBX509_STORE_CTX\fP * ctx)"

.PP
Definition at line 71 of file cb\&.c\&.
.SS "\fBvoid\fP cb_ssl_verify_set_depth (unsigned int verify_depth)"

.PP
Definition at line 131 of file cb\&.c\&.
.SS "\fBvoid\fP cb_ssl_verify_set_level (unsigned int level)"

.PP
Definition at line 136 of file cb\&.c\&.
.SS "\fBvoid\fP cb_ssl_verify_set_output (FILE * fp)"

.PP
Definition at line 126 of file cb\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
