.TH "s2n/libcrypto-build/openssl/crypto/cmac/cmac.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/cmac/cmac.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/cmac\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBCMAC_CTX_st\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCMAC_CTX\fP * \fBCMAC_CTX_new\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCMAC_CTX_cleanup\fP (\fBCMAC_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "\fBEVP_CIPHER_CTX\fP * \fBCMAC_CTX_get0_cipher_ctx\fP (\fBCMAC_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCMAC_CTX_free\fP (\fBCMAC_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBCMAC_CTX_copy\fP (\fBCMAC_CTX\fP *\fBout\fP, const \fBCMAC_CTX\fP *\fBin\fP)"
.br
.ti -1c
.RI "int \fBCMAC_Init\fP (\fBCMAC_CTX\fP *\fBctx\fP, const \fBvoid\fP *\fBkey\fP, size_t keylen, const \fBEVP_CIPHER\fP *cipher, \fBENGINE\fP *impl)"
.br
.ti -1c
.RI "int \fBCMAC_Update\fP (\fBCMAC_CTX\fP *\fBctx\fP, const \fBvoid\fP *\fBin\fP, size_t dlen)"
.br
.ti -1c
.RI "int \fBCMAC_Final\fP (\fBCMAC_CTX\fP *\fBctx\fP, unsigned char *\fBout\fP, size_t *poutlen)"
.br
.ti -1c
.RI "int \fBCMAC_resume\fP (\fBCMAC_CTX\fP *\fBctx\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP CMAC_CTX_cleanup (\fBCMAC_CTX\fP * ctx)"

.PP
Definition at line 106 of file cmac\&.c\&.
.SS "int CMAC_CTX_copy (\fBCMAC_CTX\fP * out, const \fBCMAC_CTX\fP * in)"

.PP
Definition at line 135 of file cmac\&.c\&.
.SS "\fBvoid\fP CMAC_CTX_free (\fBCMAC_CTX\fP * ctx)"

.PP
Definition at line 127 of file cmac\&.c\&.
.SS "\fBEVP_CIPHER_CTX\fP* CMAC_CTX_get0_cipher_ctx (\fBCMAC_CTX\fP * ctx)"

.PP
Definition at line 122 of file cmac\&.c\&.
.SS "\fBCMAC_CTX\fP* CMAC_CTX_new (\fBvoid\fP)"

.PP
Definition at line 95 of file cmac\&.c\&.
.SS "int CMAC_Final (\fBCMAC_CTX\fP * ctx, unsigned char * out, size_t * poutlen)"

.PP
Definition at line 262 of file cmac\&.c\&.
.SS "int CMAC_Init (\fBCMAC_CTX\fP * ctx, const \fBvoid\fP * key, size_t keylen, const \fBEVP_CIPHER\fP * cipher, \fBENGINE\fP * impl)"

.PP
Definition at line 151 of file cmac\&.c\&.
.SS "int CMAC_resume (\fBCMAC_CTX\fP * ctx)"

.PP
Definition at line 294 of file cmac\&.c\&.
.SS "int CMAC_Update (\fBCMAC_CTX\fP * ctx, const \fBvoid\fP * in, size_t dlen)"

.PP
Definition at line 218 of file cmac\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
