.TH "s2n/libcrypto-build/openssl/apps/cms.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/apps/cms.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'apps\&.h'\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <openssl/x509_vfy\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br
\fC#include <openssl/cms\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcms_key_param_st\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPROG\fP   \fBcms_main\fP"
.br
.ti -1c
.RI "#define \fBSMIME_OP\fP   0x10"
.br
.ti -1c
.RI "#define \fBSMIME_IP\fP   0x20"
.br
.ti -1c
.RI "#define \fBSMIME_SIGNERS\fP   0x40"
.br
.ti -1c
.RI "#define \fBSMIME_ENCRYPT\fP   (1 | \fBSMIME_OP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_DECRYPT\fP   (2 | \fBSMIME_IP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_SIGN\fP   (3 | \fBSMIME_OP\fP | \fBSMIME_SIGNERS\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_VERIFY\fP   (4 | \fBSMIME_IP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_CMSOUT\fP   (5 | \fBSMIME_IP\fP | \fBSMIME_OP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_RESIGN\fP   (6 | \fBSMIME_IP\fP | \fBSMIME_OP\fP | \fBSMIME_SIGNERS\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_DATAOUT\fP   (7 | \fBSMIME_IP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_DATA_CREATE\fP   (8 | \fBSMIME_OP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_DIGEST_VERIFY\fP   (9 | \fBSMIME_IP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_DIGEST_CREATE\fP   (10 | \fBSMIME_OP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_UNCOMPRESS\fP   (11 | \fBSMIME_IP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_COMPRESS\fP   (12 | \fBSMIME_OP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_ENCRYPTED_DECRYPT\fP   (13 | \fBSMIME_IP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_ENCRYPTED_ENCRYPT\fP   (14 | \fBSMIME_OP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_SIGN_RECEIPT\fP   (15 | \fBSMIME_IP\fP | \fBSMIME_OP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_VERIFY_RECEIPT\fP   (16 | \fBSMIME_IP\fP)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBcms_key_param_st\fP \fBcms_key_param\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBMAIN\fP (int, char **)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverify_err\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PROG   \fBcms_main\fP"

.PP
Definition at line 71 of file cms\&.c\&.
.SS "#define SMIME_CMSOUT   (5 | \fBSMIME_IP\fP | \fBSMIME_OP\fP)"

.PP
Definition at line 88 of file cms\&.c\&.
.SS "#define SMIME_COMPRESS   (12 | \fBSMIME_OP\fP)"

.PP
Definition at line 95 of file cms\&.c\&.
.SS "#define SMIME_DATA_CREATE   (8 | \fBSMIME_OP\fP)"

.PP
Definition at line 91 of file cms\&.c\&.
.SS "#define SMIME_DATAOUT   (7 | \fBSMIME_IP\fP)"

.PP
Definition at line 90 of file cms\&.c\&.
.SS "#define SMIME_DECRYPT   (2 | \fBSMIME_IP\fP)"

.PP
Definition at line 85 of file cms\&.c\&.
.SS "#define SMIME_DIGEST_CREATE   (10 | \fBSMIME_OP\fP)"

.PP
Definition at line 93 of file cms\&.c\&.
.SS "#define SMIME_DIGEST_VERIFY   (9 | \fBSMIME_IP\fP)"

.PP
Definition at line 92 of file cms\&.c\&.
.SS "#define SMIME_ENCRYPT   (1 | \fBSMIME_OP\fP)"

.PP
Definition at line 84 of file cms\&.c\&.
.SS "#define SMIME_ENCRYPTED_DECRYPT   (13 | \fBSMIME_IP\fP)"

.PP
Definition at line 96 of file cms\&.c\&.
.SS "#define SMIME_ENCRYPTED_ENCRYPT   (14 | \fBSMIME_OP\fP)"

.PP
Definition at line 97 of file cms\&.c\&.
.SS "#define SMIME_IP   0x20"

.PP
Definition at line 82 of file cms\&.c\&.
.SS "#define SMIME_OP   0x10"

.PP
Definition at line 81 of file cms\&.c\&.
.SS "#define SMIME_RESIGN   (6 | \fBSMIME_IP\fP | \fBSMIME_OP\fP | \fBSMIME_SIGNERS\fP)"

.PP
Definition at line 89 of file cms\&.c\&.
.SS "#define SMIME_SIGN   (3 | \fBSMIME_OP\fP | \fBSMIME_SIGNERS\fP)"

.PP
Definition at line 86 of file cms\&.c\&.
.SS "#define SMIME_SIGN_RECEIPT   (15 | \fBSMIME_IP\fP | \fBSMIME_OP\fP)"

.PP
Definition at line 98 of file cms\&.c\&.
.SS "#define SMIME_SIGNERS   0x40"

.PP
Definition at line 83 of file cms\&.c\&.
.SS "#define SMIME_UNCOMPRESS   (11 | \fBSMIME_IP\fP)"

.PP
Definition at line 94 of file cms\&.c\&.
.SS "#define SMIME_VERIFY   (4 | \fBSMIME_IP\fP)"

.PP
Definition at line 87 of file cms\&.c\&.
.SS "#define SMIME_VERIFY_RECEIPT   (16 | \fBSMIME_IP\fP)"

.PP
Definition at line 99 of file cms\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBcms_key_param_st\fP \fBcms_key_param\fP"

.PP
Definition at line 103 of file cms\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int MAIN (int argc, char ** argv)"

.PP
Definition at line 113 of file cms\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "int verify_err = 0"

.PP
Definition at line 101 of file cms\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
