.TH "CMS_RecipientInfo_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMS_RecipientInfo_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cms_lcl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBCMS_KeyTransRecipientInfo\fP * \fBktri\fP"
.br
.ti -1c
.RI "   \fBCMS_KeyAgreeRecipientInfo\fP * \fBkari\fP"
.br
.ti -1c
.RI "   \fBCMS_KEKRecipientInfo\fP * \fBkekri\fP"
.br
.ti -1c
.RI "   \fBCMS_PasswordRecipientInfo\fP * \fBpwri\fP"
.br
.ti -1c
.RI "   \fBCMS_OtherRecipientInfo\fP * \fBori\fP"
.br
.ti -1c
.RI "} \fBd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 177 of file cms_lcl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "union { \&.\&.\&. }   d"

.SS "\fBCMS_KeyAgreeRecipientInfo\fP* kari"

.PP
Definition at line 181 of file cms_lcl\&.h\&.
.SS "\fBCMS_KEKRecipientInfo\fP* kekri"

.PP
Definition at line 182 of file cms_lcl\&.h\&.
.SS "\fBCMS_KeyTransRecipientInfo\fP* ktri"

.PP
Definition at line 180 of file cms_lcl\&.h\&.
.SS "\fBCMS_OtherRecipientInfo\fP* ori"

.PP
Definition at line 184 of file cms_lcl\&.h\&.
.SS "\fBCMS_PasswordRecipientInfo\fP* pwri"

.PP
Definition at line 183 of file cms_lcl\&.h\&.
.SS "int type"

.PP
Definition at line 178 of file cms_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
