.TH "CMS_RevocationInfoChoice_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMS_RevocationInfoChoice_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cms_lcl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBX509_CRL\fP * \fBcrl\fP"
.br
.ti -1c
.RI "   \fBCMS_OtherRevocationInfoFormat\fP * \fBother\fP"
.br
.ti -1c
.RI "} \fBd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 312 of file cms_lcl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBX509_CRL\fP* crl"

.PP
Definition at line 315 of file cms_lcl\&.h\&.
.SS "union { \&.\&.\&. }   d"

.SS "\fBCMS_OtherRevocationInfoFormat\fP* other"

.PP
Definition at line 316 of file cms_lcl\&.h\&.
.SS "int type"

.PP
Definition at line 313 of file cms_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
