.TH "CMS_SignerInfo_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMS_SignerInfo_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cms_lcl\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ATTRIBUTE\fP)*signedAttrs"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ATTRIBUTE\fP)*unsignedAttrs"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBversion\fP"
.br
.ti -1c
.RI "\fBCMS_SignerIdentifier\fP * \fBsid\fP"
.br
.ti -1c
.RI "\fBX509_ALGOR\fP * \fBdigestAlgorithm\fP"
.br
.ti -1c
.RI "\fBX509_ALGOR\fP * \fBsignatureAlgorithm\fP"
.br
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBsignature\fP"
.br
.ti -1c
.RI "\fBX509\fP * \fBsigner\fP"
.br
.ti -1c
.RI "\fBEVP_PKEY\fP * \fBpkey\fP"
.br
.ti -1c
.RI "\fBEVP_MD_CTX\fP \fBmctx\fP"
.br
.ti -1c
.RI "\fBEVP_PKEY_CTX\fP * \fBpctx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file cms_lcl\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBX509_ATTRIBUTE\fP)"

.SS "STACK_OF (\fBX509_ATTRIBUTE\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBX509_ALGOR\fP* digestAlgorithm"

.PP
Definition at line 131 of file cms_lcl\&.h\&.
.SS "\fBEVP_MD_CTX\fP mctx"

.PP
Definition at line 140 of file cms_lcl\&.h\&.
.SS "\fBEVP_PKEY_CTX\fP* pctx"

.PP
Definition at line 141 of file cms_lcl\&.h\&.
.SS "\fBEVP_PKEY\fP* pkey"

.PP
Definition at line 138 of file cms_lcl\&.h\&.
.SS "\fBCMS_SignerIdentifier\fP* sid"

.PP
Definition at line 130 of file cms_lcl\&.h\&.
.SS "\fBASN1_OCTET_STRING\fP* signature"

.PP
Definition at line 134 of file cms_lcl\&.h\&.
.SS "\fBX509_ALGOR\fP* signatureAlgorithm"

.PP
Definition at line 133 of file cms_lcl\&.h\&.
.SS "\fBX509\fP* signer"

.PP
Definition at line 137 of file cms_lcl\&.h\&.
.SS "long version"

.PP
Definition at line 129 of file cms_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
