.TH "custom_ext_method" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
custom_ext_method \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ssl_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned short \fBext_type\fP"
.br
.ti -1c
.RI "unsigned short \fBext_flags\fP"
.br
.ti -1c
.RI "\fBcustom_ext_add_cb\fP \fBadd_cb\fP"
.br
.ti -1c
.RI "\fBcustom_ext_free_cb\fP \fBfree_cb\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBadd_arg\fP"
.br
.ti -1c
.RI "\fBcustom_ext_parse_cb\fP \fBparse_cb\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBparse_arg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 567 of file ssl_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBvoid\fP* add_arg"

.PP
Definition at line 576 of file ssl_locl\&.h\&.
.SS "\fBcustom_ext_add_cb\fP add_cb"

.PP
Definition at line 574 of file ssl_locl\&.h\&.
.SS "unsigned short ext_flags"

.PP
Definition at line 573 of file ssl_locl\&.h\&.
.SS "unsigned short ext_type"

.PP
Definition at line 568 of file ssl_locl\&.h\&.
.SS "\fBcustom_ext_free_cb\fP free_cb"

.PP
Definition at line 575 of file ssl_locl\&.h\&.
.SS "\fBvoid\fP* parse_arg"

.PP
Definition at line 578 of file ssl_locl\&.h\&.
.SS "\fBcustom_ext_parse_cb\fP parse_cb"

.PP
Definition at line 577 of file ssl_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
