.TH "s2n/libcrypto-build/openssl/crypto/asn1/d2i_pu.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/d2i_pu.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/rsa\&.h>\fP
.br
\fC#include <openssl/dsa\&.h>\fP
.br
\fC#include <openssl/ec\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBEVP_PKEY\fP * \fBd2i_PublicKey\fP (int \fBtype\fP, \fBEVP_PKEY\fP **\fBa\fP, const unsigned char **\fBpp\fP, long \fBlength\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBEVP_PKEY\fP* d2i_PublicKey (int type, \fBEVP_PKEY\fP ** a, const unsigned char ** pp, long length)"

.PP
Definition at line 75 of file d2i_pu\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
