.TH "s2n/libcrypto-build/openssl/test/destest.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/test/destest.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <openssl/e_os2\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/des\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBcrypt\fP(\fBc\fP,  s)   (\fBDES_crypt\fP((\fBc\fP),(s)))"
.br
.ti -1c
.RI "#define \fBNUM_TESTS\fP   34"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define crypt(\fBc\fP, s)   (\fBDES_crypt\fP((\fBc\fP),(s)))"

.PP
Definition at line 87 of file destest\&.c\&.
.SS "#define NUM_TESTS   34"

.PP
Definition at line 91 of file destest\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 361 of file destest\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
