.TH "s2n/libcrypto-build/openssl/crypto/dh/dh_ameth.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/dh/dh_ameth.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/dh\&.h>\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include 'asn1_locl\&.h'\fP
.br
\fC#include <openssl/cms\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDH\fP * \fBDHparams_dup\fP (\fBDH\fP *dh)"
.br
.ti -1c
.RI "int \fBDHparams_print\fP (\fBBIO\fP *\fBbp\fP, const \fBDH\fP *\fBx\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBEVP_PKEY_ASN1_METHOD\fP \fBdhx_asn1_meth\fP"
.br
.ti -1c
.RI "const \fBEVP_PKEY_ASN1_METHOD\fP \fBdh_asn1_meth\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBDH\fP* DHparams_dup (\fBDH\fP * dh)"

.PP
Definition at line 501 of file dh_ameth\&.c\&.
.SS "int DHparams_print (\fBBIO\fP * bp, const \fBDH\fP * x)"

.PP
Definition at line 555 of file dh_ameth\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBEVP_PKEY_ASN1_METHOD\fP dh_asn1_meth"

.PP
Definition at line 587 of file dh_ameth\&.c\&.
.SS "const \fBEVP_PKEY_ASN1_METHOD\fP dhx_asn1_meth"

.PP
Definition at line 619 of file dh_ameth\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
