.TH "s2n/libcrypto-build/openssl/crypto/dh/dh_lib.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/dh/dh_lib.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <openssl/dh\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBDH_set_default_method\fP (const \fBDH_METHOD\fP *meth)"
.br
.ti -1c
.RI "const \fBDH_METHOD\fP * \fBDH_get_default_method\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBDH_set_method\fP (\fBDH\fP *dh, const \fBDH_METHOD\fP *meth)"
.br
.ti -1c
.RI "\fBDH\fP * \fBDH_new\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBDH\fP * \fBDH_new_method\fP (\fBENGINE\fP *engine)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDH_free\fP (\fBDH\fP *r)"
.br
.ti -1c
.RI "int \fBDH_up_ref\fP (\fBDH\fP *r)"
.br
.ti -1c
.RI "int \fBDH_get_ex_new_index\fP (long argl, \fBvoid\fP *argp, \fBCRYPTO_EX_new\fP *new_func, \fBCRYPTO_EX_dup\fP *dup_func, \fBCRYPTO_EX_free\fP *\fBfree_func\fP)"
.br
.ti -1c
.RI "int \fBDH_set_ex_data\fP (\fBDH\fP *d, int idx, \fBvoid\fP *\fBarg\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBDH_get_ex_data\fP (\fBDH\fP *d, int idx)"
.br
.ti -1c
.RI "int \fBDH_size\fP (const \fBDH\fP *dh)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBDH_version\fP [] = 'Diffie\-Hellman' OPENSSL_VERSION_PTEXT"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP DH_free (\fBDH\fP * r)"

.PP
Definition at line 182 of file dh_lib\&.c\&.
.SS "const \fBDH_METHOD\fP* DH_get_default_method (\fBvoid\fP)"

.PP
Definition at line 80 of file dh_lib\&.c\&.
.SS "\fBvoid\fP* DH_get_ex_data (\fBDH\fP * d, int idx)"

.PP
Definition at line 255 of file dh_lib\&.c\&.
.SS "int DH_get_ex_new_index (long argl, \fBvoid\fP * argp, \fBCRYPTO_EX_new\fP * new_func, \fBCRYPTO_EX_dup\fP * dup_func, \fBCRYPTO_EX_free\fP * free_func)"

.PP
Definition at line 243 of file dh_lib\&.c\&.
.SS "\fBDH\fP* DH_new (\fBvoid\fP)"

.PP
Definition at line 117 of file dh_lib\&.c\&.
.SS "\fBDH\fP* DH_new_method (\fBENGINE\fP * engine)"

.PP
Definition at line 122 of file dh_lib\&.c\&.
.SS "\fBvoid\fP DH_set_default_method (const \fBDH_METHOD\fP * meth)"

.PP
Definition at line 75 of file dh_lib\&.c\&.
.SS "int DH_set_ex_data (\fBDH\fP * d, int idx, \fBvoid\fP * arg)"

.PP
Definition at line 250 of file dh_lib\&.c\&.
.SS "int DH_set_method (\fBDH\fP * dh, const \fBDH_METHOD\fP * meth)"

.PP
Definition at line 95 of file dh_lib\&.c\&.
.SS "int DH_size (const \fBDH\fP * dh)"

.PP
Definition at line 260 of file dh_lib\&.c\&.
.SS "int DH_up_ref (\fBDH\fP * r)"

.PP
Definition at line 228 of file dh_lib\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const char DH_version[] = 'Diffie\-Hellman' OPENSSL_VERSION_PTEXT"

.PP
Definition at line 71 of file dh_lib\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
