.TH "s2n/libcrypto-build/openssl/crypto/evp/digest.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/evp/digest.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBEVP_MD_CTX_init\fP (\fBEVP_MD_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "\fBEVP_MD_CTX\fP * \fBEVP_MD_CTX_create\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBEVP_DigestInit\fP (\fBEVP_MD_CTX\fP *\fBctx\fP, const \fBEVP_MD\fP *\fBtype\fP)"
.br
.ti -1c
.RI "int \fBEVP_DigestInit_ex\fP (\fBEVP_MD_CTX\fP *\fBctx\fP, const \fBEVP_MD\fP *\fBtype\fP, \fBENGINE\fP *impl)"
.br
.ti -1c
.RI "int \fBEVP_DigestUpdate\fP (\fBEVP_MD_CTX\fP *\fBctx\fP, const \fBvoid\fP *\fBdata\fP, size_t count)"
.br
.ti -1c
.RI "int \fBEVP_DigestFinal\fP (\fBEVP_MD_CTX\fP *\fBctx\fP, unsigned char *md, unsigned int *size)"
.br
.ti -1c
.RI "int \fBEVP_DigestFinal_ex\fP (\fBEVP_MD_CTX\fP *\fBctx\fP, unsigned char *md, unsigned int *size)"
.br
.ti -1c
.RI "int \fBEVP_MD_CTX_copy\fP (\fBEVP_MD_CTX\fP *\fBout\fP, const \fBEVP_MD_CTX\fP *\fBin\fP)"
.br
.ti -1c
.RI "int \fBEVP_MD_CTX_copy_ex\fP (\fBEVP_MD_CTX\fP *\fBout\fP, const \fBEVP_MD_CTX\fP *\fBin\fP)"
.br
.ti -1c
.RI "int \fBEVP_Digest\fP (const \fBvoid\fP *\fBdata\fP, size_t count, unsigned char *md, unsigned int *size, const \fBEVP_MD\fP *\fBtype\fP, \fBENGINE\fP *impl)"
.br
.ti -1c
.RI "\fBvoid\fP \fBEVP_MD_CTX_destroy\fP (\fBEVP_MD_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBEVP_MD_CTX_cleanup\fP (\fBEVP_MD_CTX\fP *\fBctx\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int EVP_Digest (const \fBvoid\fP * data, size_t count, unsigned char * md, unsigned int * size, const \fBEVP_MD\fP * type, \fBENGINE\fP * impl)"

.PP
Definition at line 350 of file digest\&.c\&.
.SS "int EVP_DigestFinal (\fBEVP_MD_CTX\fP * ctx, unsigned char * md, unsigned int * size)"

.PP
Definition at line 263 of file digest\&.c\&.
.SS "int EVP_DigestFinal_ex (\fBEVP_MD_CTX\fP * ctx, unsigned char * md, unsigned int * size)"

.PP
Definition at line 272 of file digest\&.c\&.
.SS "int EVP_DigestInit (\fBEVP_MD_CTX\fP * ctx, const \fBEVP_MD\fP * type)"

.PP
Definition at line 140 of file digest\&.c\&.
.SS "int EVP_DigestInit_ex (\fBEVP_MD_CTX\fP * ctx, const \fBEVP_MD\fP * type, \fBENGINE\fP * impl)"

.PP
Definition at line 146 of file digest\&.c\&.
.SS "int EVP_DigestUpdate (\fBEVP_MD_CTX\fP * ctx, const \fBvoid\fP * data, size_t count)"

.PP
Definition at line 253 of file digest\&.c\&.
.SS "int EVP_MD_CTX_cleanup (\fBEVP_MD_CTX\fP * ctx)"

.PP
Definition at line 376 of file digest\&.c\&.
.SS "int EVP_MD_CTX_copy (\fBEVP_MD_CTX\fP * out, const \fBEVP_MD_CTX\fP * in)"

.PP
Definition at line 292 of file digest\&.c\&.
.SS "int EVP_MD_CTX_copy_ex (\fBEVP_MD_CTX\fP * out, const \fBEVP_MD_CTX\fP * in)"

.PP
Definition at line 298 of file digest\&.c\&.
.SS "\fBEVP_MD_CTX\fP* EVP_MD_CTX_create (\fBvoid\fP)"

.PP
Definition at line 130 of file digest\&.c\&.
.SS "\fBvoid\fP EVP_MD_CTX_destroy (\fBEVP_MD_CTX\fP * ctx)"

.PP
Definition at line 367 of file digest\&.c\&.
.SS "\fBvoid\fP EVP_MD_CTX_init (\fBEVP_MD_CTX\fP * ctx)"

.PP
Definition at line 125 of file digest\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
