.TH "s2n/libcrypto-build/openssl/crypto/dso/dso_vms.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/dso/dso_vms.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/dso\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDSO_METHOD\fP * \fBDSO_METHOD_vms\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBDSO_METHOD\fP* DSO_METHOD_vms (\fBvoid\fP)"

.PP
Definition at line 67 of file dso_vms\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
