.TH "s2n/libcrypto-build/openssl/crypto/evp/e_aes_cbc_hmac_sha1.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/evp/e_aes_cbc_hmac_sha1.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/opensslconf\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/aes\&.h>\fP
.br
\fC#include <openssl/sha\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include 'modes_lcl\&.h'\fP
.br
\fC#include 'constant_time_locl\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBEVP_AES_HMAC_SHA1\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEVP_CIPH_FLAG_AEAD_CIPHER\fP   0x200000"
.br
.ti -1c
.RI "#define \fBEVP_CTRL_AEAD_TLS1_AAD\fP   0x16"
.br
.ti -1c
.RI "#define \fBEVP_CTRL_AEAD_SET_MAC_KEY\fP   0x17"
.br
.ti -1c
.RI "#define \fBEVP_CIPH_FLAG_DEFAULT_ASN1\fP   0"
.br
.ti -1c
.RI "#define \fBEVP_CIPH_FLAG_TLS1_1_MULTIBLOCK\fP   0"
.br
.ti -1c
.RI "#define \fBTLS1_1_VERSION\fP   0x0302"
.br
.ti -1c
.RI "#define \fBNO_PAYLOAD_LENGTH\fP   ((size_t)\-1)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBEVP_CIPHER\fP * \fBEVP_aes_128_cbc_hmac_sha1\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "const \fBEVP_CIPHER\fP * \fBEVP_aes_256_cbc_hmac_sha1\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EVP_CIPH_FLAG_AEAD_CIPHER   0x200000"

.PP
Definition at line 66 of file e_aes_cbc_hmac_sha1\&.c\&.
.SS "\fBEVP_CIPH_RAND_KEY\fP \fBEVP_CIPH_FLAG_FIPS\fP des3_ctrl \fBEVP_CIPH_RAND_KEY\fP \fBEVP_CIPH_FLAG_FIPS\fP EVP_CIPH_FLAG_DEFAULT_ASN1   0"

.PP
Definition at line 72 of file e_aes_cbc_hmac_sha1\&.c\&.
.SS "#define EVP_CIPH_FLAG_TLS1_1_MULTIBLOCK   0"

.PP
Definition at line 76 of file e_aes_cbc_hmac_sha1\&.c\&.
.SS "#define EVP_CTRL_AEAD_SET_MAC_KEY   0x17"

.PP
Definition at line 68 of file e_aes_cbc_hmac_sha1\&.c\&.
.SS "#define EVP_CTRL_AEAD_TLS1_AAD   0x16"

.PP
Definition at line 67 of file e_aes_cbc_hmac_sha1\&.c\&.
.SS "#define NO_PAYLOAD_LENGTH   ((size_t)\-1)"

.PP
Definition at line 91 of file e_aes_cbc_hmac_sha1\&.c\&.
.SS "#define TLS1_1_VERSION   0x0302"

.PP
Definition at line 79 of file e_aes_cbc_hmac_sha1\&.c\&.
.SH "Function Documentation"
.PP 
.SS "const \fBEVP_CIPHER\fP* EVP_aes_128_cbc_hmac_sha1 (\fBvoid\fP)"

.PP
Definition at line 998 of file e_aes_cbc_hmac_sha1\&.c\&.
.SS "const \fBEVP_CIPHER\fP* EVP_aes_256_cbc_hmac_sha1 (\fBvoid\fP)"

.PP
Definition at line 1003 of file e_aes_cbc_hmac_sha1\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
