.TH "ec_key_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ec_key_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ec_lcl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "\fBEC_GROUP\fP * \fBgroup\fP"
.br
.ti -1c
.RI "\fBEC_POINT\fP * \fBpub_key\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBpriv_key\fP"
.br
.ti -1c
.RI "unsigned int \fBenc_flag\fP"
.br
.ti -1c
.RI "\fBpoint_conversion_form_t\fP \fBconv_form\fP"
.br
.ti -1c
.RI "int \fBreferences\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "\fBEC_EXTRA_DATA\fP * \fBmethod_data\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 265 of file ec_lcl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBpoint_conversion_form_t\fP conv_form"

.PP
Definition at line 271 of file ec_lcl\&.h\&.
.SS "unsigned int enc_flag"

.PP
Definition at line 270 of file ec_lcl\&.h\&.
.SS "int flags"

.PP
Definition at line 273 of file ec_lcl\&.h\&.
.SS "\fBEC_GROUP\fP* group"

.PP
Definition at line 267 of file ec_lcl\&.h\&.
.SS "\fBEC_EXTRA_DATA\fP* method_data"

.PP
Definition at line 274 of file ec_lcl\&.h\&.
.SS "\fBBIGNUM\fP* priv_key"

.PP
Definition at line 269 of file ec_lcl\&.h\&.
.SS "\fBEC_POINT\fP* pub_key"

.PP
Definition at line 268 of file ec_lcl\&.h\&.
.SS "int references"

.PP
Definition at line 272 of file ec_lcl\&.h\&.
.SS "int version"

.PP
Definition at line 266 of file ec_lcl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
