.TH "EVP_AES_XTS_CTX" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EVP_AES_XTS_CTX \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   double \fBalign\fP"
.br
.ti -1c
.RI "   \fBAES_KEY\fP \fBks\fP"
.br
.ti -1c
.RI "} \fBks1\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   double \fBalign\fP"
.br
.ti -1c
.RI "   \fBAES_KEY\fP \fBks\fP"
.br
.ti -1c
.RI "} \fBks2\fP"
.br
.ti -1c
.RI "\fBXTS128_CONTEXT\fP \fBxts\fP"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBstream\fP )(const unsigned char *\fBin\fP, unsigned char *\fBout\fP, size_t \fBlength\fP, const \fBAES_KEY\fP *key1, const \fBAES_KEY\fP *key2, const unsigned char iv[16])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 94 of file e_aes\&.c\&.
.SH "Field Documentation"
.PP 
.SS "double align"

.PP
Definition at line 96 of file e_aes\&.c\&.
.SS "\fBAES_KEY\fP ks"

.PP
Definition at line 97 of file e_aes\&.c\&.
.SS "union { \&.\&.\&. }   ks1"

.SS "union { \&.\&.\&. }   ks2"

.SS "\fBvoid\fP(* stream) (const unsigned char *\fBin\fP, unsigned char *\fBout\fP, size_t \fBlength\fP, const \fBAES_KEY\fP *key1, const \fBAES_KEY\fP *key2, const unsigned char iv[16])"

.PP
Definition at line 100 of file e_aes\&.c\&.
.SS "\fBXTS128_CONTEXT\fP xts"

.PP
Definition at line 99 of file e_aes\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
