.TH "EVP_AES_CCM_CTX" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EVP_AES_CCM_CTX \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   double \fBalign\fP"
.br
.ti -1c
.RI "   \fBAES_KEY\fP \fBks\fP"
.br
.ti -1c
.RI "} \fBks\fP"
.br
.ti -1c
.RI "int \fBkey_set\fP"
.br
.ti -1c
.RI "int \fBiv_set\fP"
.br
.ti -1c
.RI "int \fBtag_set\fP"
.br
.ti -1c
.RI "int \fBlen_set\fP"
.br
.ti -1c
.RI "int \fBL\fP"
.br
.ti -1c
.RI "int \fBM\fP"
.br
.ti -1c
.RI "\fBCCM128_CONTEXT\fP \fBccm\fP"
.br
.ti -1c
.RI "\fBccm128_f\fP \fBstr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 106 of file e_aes\&.c\&.
.SH "Field Documentation"
.PP 
.SS "double align"

.PP
Definition at line 108 of file e_aes\&.c\&.
.SS "\fBCCM128_CONTEXT\fP ccm"

.PP
Definition at line 116 of file e_aes\&.c\&.
.SS "int iv_set"

.PP
Definition at line 112 of file e_aes\&.c\&.
.SS "int key_set"

.PP
Definition at line 111 of file e_aes\&.c\&.
.SS "\fBAES_KEY\fP ks"

.PP
Definition at line 109 of file e_aes\&.c\&.
.SS "union { \&.\&.\&. }   ks"

.SS "int L"

.PP
Definition at line 115 of file e_aes\&.c\&.
.SS "int len_set"

.PP
Definition at line 114 of file e_aes\&.c\&.
.SS "int M"

.PP
Definition at line 115 of file e_aes\&.c\&.
.SS "\fBccm128_f\fP str"

.PP
Definition at line 117 of file e_aes\&.c\&.
.SS "int tag_set"

.PP
Definition at line 113 of file e_aes\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
