.TH "s2n/libcrypto-build/openssl/crypto/des/fcrypt_b.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/des/fcrypt_b.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'des_locl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDES_FCRYPT\fP"
.br
.ti -1c
.RI "#define \fBPERM_OP\fP(\fBa\fP,  \fBb\fP,  \fBt\fP,  n,  m)"
.br
.ti -1c
.RI "#define \fBHPERM_OP\fP(\fBa\fP,  \fBt\fP,  n,  m)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBfcrypt_body\fP (DES_LONG *\fBout\fP, \fBDES_key_schedule\fP *ks, DES_LONG Eswap0, DES_LONG Eswap1)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DES_FCRYPT"

.PP
Definition at line 67 of file fcrypt_b\&.c\&.
.SS "#define HPERM_OP(\fBa\fP, \fBt\fP, n, m)"
\fBValue:\fP
.PP
.nf
((t)=((((a)<<(16-(n)))^(a))&(m)),\
        (a)=(a)^(t)^(t>>(16-(n))))\
.fi
.PP
Definition at line 77 of file fcrypt_b\&.c\&.
.SS "#define PERM_OP(\fBa\fP, \fBb\fP, \fBt\fP, n, m)"
\fBValue:\fP
.PP
.nf
((t)=((((a)>>(n))^(b))&(m)),\
        (b)^=(t),\
        (a)^=((t)<<(n)))
.fi
.PP
Definition at line 72 of file fcrypt_b\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP fcrypt_body (DES_LONG * out, \fBDES_key_schedule\fP * ks, DES_LONG Eswap0, DES_LONG Eswap1)"

.PP
Definition at line 80 of file fcrypt_b\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
