.TH "s2n/libcrypto-build/openssl/engines/ccgost/gost_lcl.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/engines/ccgost/gost_lcl.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/dsa\&.h>\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br
\fC#include <openssl/ec\&.h>\fP
.br
\fC#include 'gost89\&.h'\fP
.br
\fC#include 'gosthash\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgost_pmeth_data\fP"
.br
.ti -1c
.RI "struct \fBgost_mac_pmeth_data\fP"
.br
.ti -1c
.RI "struct \fBGOST_KEY_INFO\fP"
.br
.ti -1c
.RI "struct \fBGOST_KEY_AGREEMENT_INFO\fP"
.br
.ti -1c
.RI "struct \fBGOST_KEY_TRANSPORT\fP"
.br
.ti -1c
.RI "struct \fBGOST_CLIENT_KEY_EXCHANGE_PARAMS\fP"
.br
.ti -1c
.RI "struct \fBGOST_KEY_PARAMS\fP"
.br
.ti -1c
.RI "struct \fBGOST_CIPHER_PARAMS\fP"
.br
.ti -1c
.RI "struct \fBossl_gost_digest_ctx\fP"
.br
.ti -1c
.RI "struct \fBossl_gost_cipher_ctx\fP"
.br
.ti -1c
.RI "struct \fBgost_cipher_info\fP"
.br
.ti -1c
.RI "struct \fBossl_gost_imit_ctx\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGOST_PARAM_CRYPT_PARAMS\fP   0"
.br
.ti -1c
.RI "#define \fBGOST_PARAM_MAX\fP   0"
.br
.ti -1c
.RI "#define \fBGOST_CTRL_CRYPT_PARAMS\fP   (\fBENGINE_CMD_BASE\fP+\fBGOST_PARAM_CRYPT_PARAMS\fP)"
.br
.ti -1c
.RI "#define \fBparam_ctrl_string\fP   'paramset'"
.br
.ti -1c
.RI "#define \fBEVP_PKEY_CTRL_GOST_PARAMSET\fP   (\fBEVP_PKEY_ALG_CTRL\fP+1)"
.br
.ti -1c
.RI "#define \fBkey_ctrl_string\fP   'key'"
.br
.ti -1c
.RI "#define \fBhexkey_ctrl_string\fP   'hexkey'"
.br
.ti -1c
.RI "#define \fBEVP_PKEY_CTRL_GOST_MAC_HEXKEY\fP   (\fBEVP_PKEY_ALG_CTRL\fP+3)"
.br
.ti -1c
.RI "#define \fBEVP_MD_CTRL_KEY_LEN\fP   (\fBEVP_MD_CTRL_ALG_CTRL\fP+3)"
.br
.ti -1c
.RI "#define \fBEVP_MD_CTRL_SET_KEY\fP   (\fBEVP_MD_CTRL_ALG_CTRL\fP+4)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgost_control_func\fP (\fBENGINE\fP *\fBe\fP, int cmd, long i, \fBvoid\fP *\fBp\fP, \fBvoid\fP(*\fBf\fP)(\fBvoid\fP))"
.br
.ti -1c
.RI "const char * \fBget_gost_engine_param\fP (int param)"
.br
.ti -1c
.RI "int \fBgost_set_default_param\fP (int param, const char *value)"
.br
.ti -1c
.RI "\fBvoid\fP \fBgost_param_free\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBregister_ameth_gost\fP (int \fBnid\fP, \fBEVP_PKEY_ASN1_METHOD\fP **ameth, const char *pemstr, const char *info)"
.br
.ti -1c
.RI "int \fBregister_pmeth_gost\fP (int id, \fBEVP_PKEY_METHOD\fP **pmeth, int \fBflags\fP)"
.br
.ti -1c
.RI "const struct \fBgost_cipher_info\fP * \fBget_encryption_params\fP (\fBASN1_OBJECT\fP *\fBobj\fP)"
.br
.ti -1c
.RI "int \fBpkey_GOST94cp_encrypt\fP (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBout\fP, size_t *outlen, const unsigned char *\fBkey\fP, size_t key_len)"
.br
.ti -1c
.RI "int \fBpkey_GOST94cp_decrypt\fP (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBout\fP, size_t *outlen, const unsigned char *\fBin\fP, size_t in_len)"
.br
.ti -1c
.RI "int \fBpkey_GOST01cp_encrypt\fP (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBout\fP, size_t *outlen, const unsigned char *\fBkey\fP, size_t key_len)"
.br
.ti -1c
.RI "int \fBpkey_GOST01cp_decrypt\fP (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBout\fP, size_t *outlen, const unsigned char *\fBin\fP, size_t in_len)"
.br
.ti -1c
.RI "int \fBpkey_gost2001_derive\fP (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBkey\fP, size_t *keylen)"
.br
.ti -1c
.RI "int \fBpkey_gost94_derive\fP (\fBEVP_PKEY_CTX\fP *\fBctx\fP, unsigned char *\fBkey\fP, size_t *keylen)"
.br
.ti -1c
.RI "int \fBfill_GOST94_params\fP (\fBDSA\fP *dsa, int \fBnid\fP)"
.br
.ti -1c
.RI "int \fBfill_GOST2001_params\fP (\fBEC_KEY\fP *eckey, int \fBnid\fP)"
.br
.ti -1c
.RI "int \fBgost_sign_keygen\fP (\fBDSA\fP *dsa)"
.br
.ti -1c
.RI "int \fBgost2001_keygen\fP (\fBEC_KEY\fP *ec)"
.br
.ti -1c
.RI "\fBDSA_SIG\fP * \fBgost_do_sign\fP (const unsigned char *dgst, int dlen, \fBDSA\fP *dsa)"
.br
.ti -1c
.RI "\fBDSA_SIG\fP * \fBgost2001_do_sign\fP (const unsigned char *dgst, int dlen, \fBEC_KEY\fP *eckey)"
.br
.ti -1c
.RI "int \fBgost_do_verify\fP (const unsigned char *dgst, int dgst_len, \fBDSA_SIG\fP *sig, \fBDSA\fP *dsa)"
.br
.ti -1c
.RI "int \fBgost2001_do_verify\fP (const unsigned char *dgst, int dgst_len, \fBDSA_SIG\fP *sig, \fBEC_KEY\fP *ec)"
.br
.ti -1c
.RI "int \fBgost2001_compute_public\fP (\fBEC_KEY\fP *ec)"
.br
.ti -1c
.RI "int \fBgost94_compute_public\fP (\fBDSA\fP *dsa)"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBhashsum2bn\fP (const unsigned char *dgst)"
.br
.ti -1c
.RI "int \fBstore_bignum\fP (\fBBIGNUM\fP *bn, unsigned char *buf, int \fBlen\fP)"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBgetbnfrombuf\fP (const unsigned char *buf, size_t \fBlen\fP)"
.br
.ti -1c
.RI "int \fBpack_sign_cp\fP (\fBDSA_SIG\fP *s, int order, unsigned char *sig, size_t *siglen)"
.br
.ti -1c
.RI "\fBDSA_SIG\fP * \fBunpack_cp_signature\fP (const unsigned char *sig, size_t siglen)"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBgost_get0_priv_key\fP (const \fBEVP_PKEY\fP *pkey)"
.br
.ti -1c
.RI "int \fBgost94_nid_by_params\fP (\fBDSA\fP *\fBp\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBENGINE_CMD_DEFN\fP \fBgost_cmds\fP []"
.br
.ti -1c
.RI "\fBEVP_MD\fP \fBdigest_gost\fP"
.br
.ti -1c
.RI "\fBEVP_MD\fP \fBimit_gost_cpa\fP"
.br
.ti -1c
.RI "struct \fBgost_cipher_info\fP \fBgost_cipher_list\fP []"
.br
.ti -1c
.RI "\fBEVP_CIPHER\fP \fBcipher_gost\fP"
.br
.ti -1c
.RI "\fBEVP_CIPHER\fP \fBcipher_gost_cpacnt\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define EVP_MD_CTRL_KEY_LEN   (\fBEVP_MD_CTRL_ALG_CTRL\fP+3)"

.PP
Definition at line 167 of file gost_lcl\&.h\&.
.SS "#define EVP_MD_CTRL_SET_KEY   (\fBEVP_MD_CTRL_ALG_CTRL\fP+4)"

.PP
Definition at line 168 of file gost_lcl\&.h\&.
.SS "#define EVP_PKEY_CTRL_GOST_MAC_HEXKEY   (\fBEVP_PKEY_ALG_CTRL\fP+3)"

.PP
Definition at line 45 of file gost_lcl\&.h\&.
.SS "#define EVP_PKEY_CTRL_GOST_PARAMSET   (\fBEVP_PKEY_ALG_CTRL\fP+1)"

.PP
Definition at line 41 of file gost_lcl\&.h\&.
.SS "#define GOST_CTRL_CRYPT_PARAMS   (\fBENGINE_CMD_BASE\fP+\fBGOST_PARAM_CRYPT_PARAMS\fP)"

.PP
Definition at line 24 of file gost_lcl\&.h\&.
.SS "#define GOST_PARAM_CRYPT_PARAMS   0"

.PP
Definition at line 22 of file gost_lcl\&.h\&.
.SS "#define GOST_PARAM_MAX   0"

.PP
Definition at line 23 of file gost_lcl\&.h\&.
.SS "#define hexkey_ctrl_string   'hexkey'"

.PP
Definition at line 44 of file gost_lcl\&.h\&.
.SS "#define key_ctrl_string   'key'"

.PP
Definition at line 43 of file gost_lcl\&.h\&.
.SS "#define param_ctrl_string   'paramset'"

.PP
Definition at line 40 of file gost_lcl\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int fill_GOST2001_params (\fBEC_KEY\fP * eckey, int nid)"

.PP
Definition at line 35 of file gost2001\&.c\&.
.SS "int fill_GOST94_params (\fBDSA\fP * dsa, int nid)"

.PP
Definition at line 259 of file gost_sign\&.c\&.
.SS "const struct \fBgost_cipher_info\fP* get_encryption_params (\fBASN1_OBJECT\fP * obj)"

.PP
Definition at line 139 of file gost_crypt\&.c\&.
.SS "const char* get_gost_engine_param (int param)"

.PP
Definition at line 59 of file gost_ctl\&.c\&.
.SS "\fBBIGNUM\fP* getbnfrombuf (const unsigned char * buf, size_t len)"

.PP
Definition at line 346 of file gost_sign\&.c\&.
.SS "int gost2001_compute_public (\fBEC_KEY\fP * ec)"

.PP
Definition at line 381 of file gost2001\&.c\&.
.SS "\fBDSA_SIG\fP* gost2001_do_sign (const unsigned char * dgst, int dlen, \fBEC_KEY\fP * eckey)"

.PP
Definition at line 126 of file gost2001\&.c\&.
.SS "int gost2001_do_verify (const unsigned char * dgst, int dgst_len, \fBDSA_SIG\fP * sig, \fBEC_KEY\fP * ec)"

.PP
Definition at line 260 of file gost2001\&.c\&.
.SS "int gost2001_keygen (\fBEC_KEY\fP * ec)"

.PP
Definition at line 434 of file gost2001\&.c\&.
.SS "int gost94_compute_public (\fBDSA\fP * dsa)"

.PP
Definition at line 228 of file gost_sign\&.c\&.
.SS "int gost94_nid_by_params (\fBDSA\fP * p)"

.PP
Definition at line 23 of file gost_ameth\&.c\&.
.SS "int gost_control_func (\fBENGINE\fP * e, int cmd, long i, \fBvoid\fP * p, \fBvoid\fP(*)(\fBvoid\fP) f)"

.PP
Definition at line 49 of file gost_ctl\&.c\&.
.SS "\fBDSA_SIG\fP* gost_do_sign (const unsigned char * dgst, int dlen, \fBDSA\fP * dsa)"

.PP
Definition at line 53 of file gost_sign\&.c\&.
.SS "int gost_do_verify (const unsigned char * dgst, int dgst_len, \fBDSA_SIG\fP * sig, \fBDSA\fP * dsa)"

.PP
Definition at line 162 of file gost_sign\&.c\&.
.SS "\fBBIGNUM\fP* gost_get0_priv_key (const \fBEVP_PKEY\fP * pkey)"

.PP
Definition at line 183 of file gost_ameth\&.c\&.
.SS "\fBvoid\fP gost_param_free (\fBvoid\fP)"

.PP
Definition at line 38 of file gost_ctl\&.c\&.
.SS "int gost_set_default_param (int param, const char * value)"

.PP
Definition at line 77 of file gost_ctl\&.c\&.
.SS "int gost_sign_keygen (\fBDSA\fP * dsa)"

.PP
Definition at line 292 of file gost_sign\&.c\&.
.SS "\fBBIGNUM\fP* hashsum2bn (const unsigned char * dgst)"

.PP
Definition at line 335 of file gost_sign\&.c\&.
.SS "int pack_sign_cp (\fBDSA_SIG\fP * s, int order, unsigned char * sig, size_t * siglen)"

.PP
Definition at line 146 of file gost_sign\&.c\&.
.SS "int pkey_GOST01cp_decrypt (\fBEVP_PKEY_CTX\fP * ctx, unsigned char * out, size_t * outlen, const unsigned char * in, size_t in_len)"

.PP
Definition at line 217 of file gost2001_keyx\&.c\&.
.SS "int pkey_GOST01cp_encrypt (\fBEVP_PKEY_CTX\fP * ctx, unsigned char * out, size_t * outlen, const unsigned char * key, size_t key_len)"

.PP
Definition at line 115 of file gost2001_keyx\&.c\&.
.SS "int pkey_gost2001_derive (\fBEVP_PKEY_CTX\fP * ctx, unsigned char * key, size_t * keylen)"

.PP
Definition at line 73 of file gost2001_keyx\&.c\&.
.SS "int pkey_gost94_derive (\fBEVP_PKEY_CTX\fP * ctx, unsigned char * key, size_t * keylen)"

.PP
Definition at line 80 of file gost94_keyx\&.c\&.
.SS "int pkey_GOST94cp_decrypt (\fBEVP_PKEY_CTX\fP * ctx, unsigned char * out, size_t * outlen, const unsigned char * in, size_t in_len)"

.PP
Definition at line 209 of file gost94_keyx\&.c\&.
.SS "int pkey_GOST94cp_encrypt (\fBEVP_PKEY_CTX\fP * ctx, unsigned char * out, size_t * outlen, const unsigned char * key, size_t key_len)"

.PP
Definition at line 96 of file gost94_keyx\&.c\&.
.SS "int register_ameth_gost (int nid, \fBEVP_PKEY_ASN1_METHOD\fP ** ameth, const char * pemstr, const char * info)"

.PP
Definition at line 896 of file gost_ameth\&.c\&.
.SS "int register_pmeth_gost (int id, \fBEVP_PKEY_METHOD\fP ** pmeth, int flags)"

.PP
Definition at line 562 of file gost_pmeth\&.c\&.
.SS "int store_bignum (\fBBIGNUM\fP * bn, unsigned char * buf, int len)"

.PP
Definition at line 365 of file gost_sign\&.c\&.
.SS "\fBDSA_SIG\fP* unpack_cp_signature (const unsigned char * sig, size_t siglen)"

.PP
Definition at line 320 of file gost_sign\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "\fBEVP_CIPHER\fP cipher_gost"

.PP
Definition at line 40 of file gost_crypt\&.c\&.
.SS "\fBEVP_CIPHER\fP cipher_gost_cpacnt"

.PP
Definition at line 57 of file gost_crypt\&.c\&.
.SS "\fBEVP_MD\fP digest_gost"

.PP
Definition at line 22 of file gost_md\&.c\&.
.SS "struct \fBgost_cipher_info\fP gost_cipher_list[]"

.PP
Definition at line 111 of file gost_crypt\&.c\&.
.SS "const \fBENGINE_CMD_DEFN\fP gost_cmds[]"

.PP
Definition at line 20 of file gost_ctl\&.c\&.
.SS "\fBEVP_MD\fP imit_gost_cpa"

.PP
Definition at line 87 of file gost_crypt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
