.TH "s2n/libcrypto-build/openssl/engines/ccgost/gost_ameth.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/engines/ccgost/gost_ameth.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <openssl/engine\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/cms\&.h>\fP
.br
\fC#include 'gost_params\&.h'\fP
.br
\fC#include 'gost_lcl\&.h'\fP
.br
\fC#include 'e_gost_err\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCOPYBIGNUM\fP(\fBa\fP,  \fBb\fP,  \fBx\fP)   \fBif\fP (\fBa\fP\->\fBx\fP) \fBBN_free\fP(\fBa\fP\->\fBx\fP); \fBa\fP\->\fBx\fP=\fBBN_dup\fP(\fBb\fP\->\fBx\fP);"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgost94_nid_by_params\fP (\fBDSA\fP *\fBp\fP)"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBgost_get0_priv_key\fP (const \fBEVP_PKEY\fP *pkey)"
.br
.ti -1c
.RI "int \fBregister_ameth_gost\fP (int \fBnid\fP, \fBEVP_PKEY_ASN1_METHOD\fP **ameth, const char *pemstr, const char *info)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define COPYBIGNUM(\fBa\fP, \fBb\fP, \fBx\fP)   \fBif\fP (\fBa\fP\->\fBx\fP) \fBBN_free\fP(\fBa\fP\->\fBx\fP); \fBa\fP\->\fBx\fP=\fBBN_dup\fP(\fBb\fP\->\fBx\fP);"

.SH "Function Documentation"
.PP 
.SS "int gost94_nid_by_params (\fBDSA\fP * p)"

.PP
Definition at line 23 of file gost_ameth\&.c\&.
.SS "\fBBIGNUM\fP* gost_get0_priv_key (const \fBEVP_PKEY\fP * pkey)"

.PP
Definition at line 183 of file gost_ameth\&.c\&.
.SS "int register_ameth_gost (int nid, \fBEVP_PKEY_ASN1_METHOD\fP ** ameth, const char * pemstr, const char * info)"

.PP
Definition at line 896 of file gost_ameth\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
