.TH "heartbeat_test_fixture" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
heartbeat_test_fixture \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBSSL_CTX\fP * \fBctx\fP"
.br
.ti -1c
.RI "\fBSSL\fP * \fBs\fP"
.br
.ti -1c
.RI "const char * \fBtest_case_name\fP"
.br
.ti -1c
.RI "int(* \fBprocess_heartbeat\fP )(\fBSSL\fP *\fBs\fP)"
.br
.ti -1c
.RI "unsigned char * \fBpayload\fP"
.br
.ti -1c
.RI "int \fBsent_payload_len\fP"
.br
.ti -1c
.RI "int \fBexpected_return_value\fP"
.br
.ti -1c
.RI "int \fBreturn_payload_offset\fP"
.br
.ti -1c
.RI "int \fBexpected_payload_len\fP"
.br
.ti -1c
.RI "const char * \fBexpected_return_payload\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file heartbeat_test\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBSSL_CTX\fP * ctx"

.PP
Definition at line 60 of file heartbeat_test\&.c\&.
.SS "int expected_payload_len"

.PP
Definition at line 68 of file heartbeat_test\&.c\&.
.SS "const char * expected_return_payload"

.PP
Definition at line 69 of file heartbeat_test\&.c\&.
.SS "int expected_return_value"

.PP
Definition at line 66 of file heartbeat_test\&.c\&.
.SS "unsigned char * payload"

.PP
Definition at line 64 of file heartbeat_test\&.c\&.
.SS "int(* process_heartbeat)(\fBSSL\fP *\fBs\fP)"

.PP
Definition at line 63 of file heartbeat_test\&.c\&.
.SS "int return_payload_offset"

.PP
Definition at line 67 of file heartbeat_test\&.c\&.
.SS "\fBSSL\fP * s"

.PP
Definition at line 61 of file heartbeat_test\&.c\&.
.SS "int sent_payload_len"

.PP
Definition at line 65 of file heartbeat_test\&.c\&.
.SS "const char * test_case_name"

.PP
Definition at line 62 of file heartbeat_test\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
