.TH "s2n/libcrypto-build/openssl/crypto/hmac/hm_ameth.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/hmac/hm_ameth.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include 'asn1_locl\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHMAC_TEST_PRIVATE_KEY_FORMAT\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBEVP_PKEY_ASN1_METHOD\fP \fBhmac_asn1_meth\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HMAC_TEST_PRIVATE_KEY_FORMAT"

.PP
Definition at line 64 of file hm_ameth\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBEVP_PKEY_ASN1_METHOD\fP hmac_asn1_meth"
\fBInitial value:\fP
.PP
.nf
= {
    EVP_PKEY_HMAC,
    EVP_PKEY_HMAC,
    0,

    "HMAC",
    "OpenSSL HMAC method",

    0, 0, 0, 0,

    0, 0, 0,

    hmac_size,
    0,
    0, 0, 0, 0, 0, 0, 0,

    hmac_key_free,
    hmac_pkey_ctrl,

    old_hmac_decode,
    old_hmac_encode



}
.fi
.PP
Definition at line 143 of file hm_ameth\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
