.TH "hmac_ctx_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hmac_ctx_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hmac\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBEVP_MD\fP * \fBmd\fP"
.br
.ti -1c
.RI "\fBEVP_MD_CTX\fP \fBmd_ctx\fP"
.br
.ti -1c
.RI "\fBEVP_MD_CTX\fP \fBi_ctx\fP"
.br
.ti -1c
.RI "\fBEVP_MD_CTX\fP \fBo_ctx\fP"
.br
.ti -1c
.RI "unsigned int \fBkey_length\fP"
.br
.ti -1c
.RI "unsigned char \fBkey\fP [\fBHMAC_MAX_MD_CBLOCK\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file hmac\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBEVP_MD_CTX\fP i_ctx"

.PP
Definition at line 78 of file hmac\&.h\&.
.SS "unsigned char key"

.PP
Definition at line 81 of file hmac\&.h\&.
.SS "unsigned int key_length"

.PP
Definition at line 80 of file hmac\&.h\&.
.SS "const \fBEVP_MD\fP * md"

.PP
Definition at line 76 of file hmac\&.h\&.
.SS "\fBEVP_MD_CTX\fP md_ctx"

.PP
Definition at line 77 of file hmac\&.h\&.
.SS "\fBEVP_MD_CTX\fP o_ctx"

.PP
Definition at line 79 of file hmac\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
