.TH "JPAKE_CTX_PUBLIC" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JPAKE_CTX_PUBLIC \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBpeer_name\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBp\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBg\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBq\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBgxc\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBgxd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file jpake\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBBIGNUM\fP* g"

.PP
Definition at line 18 of file jpake\&.c\&.
.SS "\fBBIGNUM\fP* gxc"

.PP
Definition at line 20 of file jpake\&.c\&.
.SS "\fBBIGNUM\fP* gxd"

.PP
Definition at line 21 of file jpake\&.c\&.
.SS "char* name"

.PP
Definition at line 15 of file jpake\&.c\&.
.SS "\fBBIGNUM\fP* p"

.PP
Definition at line 17 of file jpake\&.c\&.
.SS "char* peer_name"

.PP
Definition at line 16 of file jpake\&.c\&.
.SS "\fBBIGNUM\fP* q"

.PP
Definition at line 19 of file jpake\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
