.TH "s2n/libcrypto-build/openssl/crypto/jpake/jpake.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/jpake/jpake.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'jpake\&.h'\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/sha\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <memory\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBJPAKE_CTX_PUBLIC\fP"
.br
.ti -1c
.RI "struct \fBJPAKE_CTX\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBJPAKE_STEP_PART_init\fP   \fBJPAKE_STEP2_init\fP"
.br
.ti -1c
.RI "#define \fBJPAKE_STEP_PART_release\fP   \fBJPAKE_STEP2_release\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBJPAKE_STEP_PART_init\fP (\fBJPAKE_STEP_PART\fP *\fBp\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBJPAKE_STEP_PART_release\fP (\fBJPAKE_STEP_PART\fP *\fBp\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBJPAKE_STEP1_init\fP (\fBJPAKE_STEP1\fP *s1)"
.br
.ti -1c
.RI "\fBvoid\fP \fBJPAKE_STEP1_release\fP (\fBJPAKE_STEP1\fP *s1)"
.br
.ti -1c
.RI "\fBJPAKE_CTX\fP * \fBJPAKE_CTX_new\fP (const char *name, const char *peer_name, const \fBBIGNUM\fP *\fBp\fP, const \fBBIGNUM\fP *g, const \fBBIGNUM\fP *\fBq\fP, const \fBBIGNUM\fP *secret)"
.br
.ti -1c
.RI "\fBvoid\fP \fBJPAKE_CTX_free\fP (\fBJPAKE_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBJPAKE_STEP1_generate\fP (\fBJPAKE_STEP1\fP *send, \fBJPAKE_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBJPAKE_STEP1_process\fP (\fBJPAKE_CTX\fP *\fBctx\fP, const \fBJPAKE_STEP1\fP *received)"
.br
.ti -1c
.RI "int \fBJPAKE_STEP2_generate\fP (\fBJPAKE_STEP2\fP *send, \fBJPAKE_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBJPAKE_STEP2_process\fP (\fBJPAKE_CTX\fP *\fBctx\fP, const \fBJPAKE_STEP2\fP *received)"
.br
.ti -1c
.RI "\fBvoid\fP \fBJPAKE_STEP3A_init\fP (\fBJPAKE_STEP3A\fP *s3a)"
.br
.ti -1c
.RI "int \fBJPAKE_STEP3A_generate\fP (\fBJPAKE_STEP3A\fP *send, \fBJPAKE_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBJPAKE_STEP3A_process\fP (\fBJPAKE_CTX\fP *\fBctx\fP, const \fBJPAKE_STEP3A\fP *received)"
.br
.ti -1c
.RI "\fBvoid\fP \fBJPAKE_STEP3A_release\fP (\fBJPAKE_STEP3A\fP *s3a)"
.br
.ti -1c
.RI "\fBvoid\fP \fBJPAKE_STEP3B_init\fP (\fBJPAKE_STEP3B\fP *s3b)"
.br
.ti -1c
.RI "int \fBJPAKE_STEP3B_generate\fP (\fBJPAKE_STEP3B\fP *send, \fBJPAKE_CTX\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBJPAKE_STEP3B_process\fP (\fBJPAKE_CTX\fP *\fBctx\fP, const \fBJPAKE_STEP3B\fP *received)"
.br
.ti -1c
.RI "\fBvoid\fP \fBJPAKE_STEP3B_release\fP (\fBJPAKE_STEP3B\fP *s3b)"
.br
.ti -1c
.RI "const \fBBIGNUM\fP * \fBJPAKE_get_shared_key\fP (\fBJPAKE_CTX\fP *\fBctx\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define JPAKE_STEP_PART_init   \fBJPAKE_STEP2_init\fP"

.PP
Definition at line 46 of file jpake\&.c\&.
.SS "#define JPAKE_STEP_PART_release   \fBJPAKE_STEP2_release\fP"

.PP
Definition at line 47 of file jpake\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP JPAKE_CTX_free (\fBJPAKE_CTX\fP * ctx)"

.PP
Definition at line 125 of file jpake\&.c\&.
.SS "\fBJPAKE_CTX\fP* JPAKE_CTX_new (const char * name, const char * peer_name, const \fBBIGNUM\fP * p, const \fBBIGNUM\fP * g, const \fBBIGNUM\fP * q, const \fBBIGNUM\fP * secret)"

.PP
Definition at line 114 of file jpake\&.c\&.
.SS "const \fBBIGNUM\fP* JPAKE_get_shared_key (\fBJPAKE_CTX\fP * ctx)"

.PP
Definition at line 509 of file jpake\&.c\&.
.SS "int JPAKE_STEP1_generate (\fBJPAKE_STEP1\fP * send, \fBJPAKE_CTX\fP * ctx)"

.PP
Definition at line 279 of file jpake\&.c\&.
.SS "\fBvoid\fP JPAKE_STEP1_init (\fBJPAKE_STEP1\fP * s1)"

.PP
Definition at line 61 of file jpake\&.c\&.
.SS "int JPAKE_STEP1_process (\fBJPAKE_CTX\fP * ctx, const \fBJPAKE_STEP1\fP * received)"

.PP
Definition at line 305 of file jpake\&.c\&.
.SS "\fBvoid\fP JPAKE_STEP1_release (\fBJPAKE_STEP1\fP * s1)"

.PP
Definition at line 67 of file jpake\&.c\&.
.SS "int JPAKE_STEP2_generate (\fBJPAKE_STEP2\fP * send, \fBJPAKE_CTX\fP * ctx)"

.PP
Definition at line 344 of file jpake\&.c\&.
.SS "int JPAKE_STEP2_process (\fBJPAKE_CTX\fP * ctx, const \fBJPAKE_STEP2\fP * received)"

.PP
Definition at line 413 of file jpake\&.c\&.
.SS "int JPAKE_STEP3A_generate (\fBJPAKE_STEP3A\fP * send, \fBJPAKE_CTX\fP * ctx)"

.PP
Definition at line 456 of file jpake\&.c\&.
.SS "\fBvoid\fP JPAKE_STEP3A_init (\fBJPAKE_STEP3A\fP * s3a)"

.PP
Definition at line 452 of file jpake\&.c\&.
.SS "int JPAKE_STEP3A_process (\fBJPAKE_CTX\fP * ctx, const \fBJPAKE_STEP3A\fP * received)"

.PP
Definition at line 464 of file jpake\&.c\&.
.SS "\fBvoid\fP JPAKE_STEP3A_release (\fBJPAKE_STEP3A\fP * s3a)"

.PP
Definition at line 478 of file jpake\&.c\&.
.SS "int JPAKE_STEP3B_generate (\fBJPAKE_STEP3B\fP * send, \fBJPAKE_CTX\fP * ctx)"

.PP
Definition at line 486 of file jpake\&.c\&.
.SS "\fBvoid\fP JPAKE_STEP3B_init (\fBJPAKE_STEP3B\fP * s3b)"

.PP
Definition at line 482 of file jpake\&.c\&.
.SS "int JPAKE_STEP3B_process (\fBJPAKE_CTX\fP * ctx, const \fBJPAKE_STEP3B\fP * received)"

.PP
Definition at line 493 of file jpake\&.c\&.
.SS "\fBvoid\fP JPAKE_STEP3B_release (\fBJPAKE_STEP3B\fP * s3b)"

.PP
Definition at line 505 of file jpake\&.c\&.
.SS "\fBvoid\fP JPAKE_STEP_PART_init (\fBJPAKE_STEP_PART\fP * p)"

.PP
Definition at line 49 of file jpake\&.c\&.
.SS "\fBvoid\fP JPAKE_STEP_PART_release (\fBJPAKE_STEP_PART\fP * p)"

.PP
Definition at line 55 of file jpake\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
