.TH "s2n/libcrypto-build/openssl/crypto/asn1/n_pkey.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/n_pkey.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/rsa\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/asn1_mac\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBnetscape_pkey_st\fP"
.br
.ti -1c
.RI "struct \fBnetscape_encrypted_pkey_st\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBnetscape_pkey_st\fP \fBNETSCAPE_PKEY\fP"
.br
.ti -1c
.RI "typedef struct \fBnetscape_encrypted_pkey_st\fP \fBNETSCAPE_ENCRYPTED_PKEY\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBASN1_BROKEN_SEQUENCE\fP (\fBNETSCAPE_ENCRYPTED_PKEY\fP)"
.br
.ti -1c
.RI "int \fBi2d_Netscape_RSA\fP (const \fBRSA\fP *\fBa\fP, unsigned char **\fBpp\fP, int(*\fBcb\fP)(char *buf, int \fBlen\fP, const char *prompt,                                                                                                                       int verify))"
.br
.ti -1c
.RI "int \fBi2d_RSA_NET\fP (const \fBRSA\fP *\fBa\fP, unsigned char **\fBpp\fP, int(*\fBcb\fP)(char *buf, int \fBlen\fP, const char *prompt,                                                                                                   int verify), int sgckey)"
.br
.ti -1c
.RI "\fBRSA\fP * \fBd2i_Netscape_RSA\fP (\fBRSA\fP **\fBa\fP, const unsigned char **\fBpp\fP, long \fBlength\fP, int(*\fBcb\fP)(char *buf, int \fBlen\fP, const char *prompt,                                                                                                                           int verify))"
.br
.ti -1c
.RI "\fBRSA\fP * \fBd2i_RSA_NET\fP (\fBRSA\fP **\fBa\fP, const unsigned char **\fBpp\fP, long \fBlength\fP, int(*\fBcb\fP)(char *buf, int \fBlen\fP, const char *prompt,                                                                                                       int verify), int sgckey)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBnetscape_encrypted_pkey_st\fP  \fBNETSCAPE_ENCRYPTED_PKEY\fP"

.SS "typedef struct \fBnetscape_pkey_st\fP  \fBNETSCAPE_PKEY\fP"

.SH "Function Documentation"
.PP 
.SS "ASN1_BROKEN_SEQUENCE (\fBNETSCAPE_ENCRYPTED_PKEY\fP)"

.SS "\fBRSA\fP* d2i_Netscape_RSA (\fBRSA\fP ** a, const unsigned char ** pp, long length, int(*)(char *buf, int \fBlen\fP, const char *prompt,                                                                                                                           int verify) cb)"

.PP
Definition at line 232 of file n_pkey\&.c\&.
.SS "\fBRSA\fP* d2i_RSA_NET (\fBRSA\fP ** a, const unsigned char ** pp, long length, int(*)(char *buf, int \fBlen\fP, const char *prompt,                                                                                                       int verify) cb, int sgckey)"

.PP
Definition at line 239 of file n_pkey\&.c\&.
.SS "int i2d_Netscape_RSA (const \fBRSA\fP * a, unsigned char ** pp, int(*)(char *buf, int \fBlen\fP, const char *prompt,                                                                                                                       int verify) cb)"

.PP
Definition at line 110 of file n_pkey\&.c\&.
.SS "int i2d_RSA_NET (const \fBRSA\fP * a, unsigned char ** pp, int(*)(char *buf, int \fBlen\fP, const char *prompt,                                                                                                   int verify) cb, int sgckey)"

.PP
Definition at line 117 of file n_pkey\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
