.TH "NETSCAPE_X509_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NETSCAPE_X509_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <asn1\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBheader\fP"
.br
.ti -1c
.RI "\fBX509\fP * \fBcert\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 563 of file asn1\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBX509\fP * cert"

.PP
Definition at line 565 of file asn1\&.h\&.
.SS "\fBASN1_OCTET_STRING\fP * header"

.PP
Definition at line 564 of file asn1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
