.TH "s2n/libcrypto-build/openssl/crypto/ocsp/ocsp_srv.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ocsp/ocsp_srv.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <cryptlib\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br
\fC#include <openssl/ocsp\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBOCSP_request_onereq_count\fP (\fBOCSP_REQUEST\fP *req)"
.br
.ti -1c
.RI "\fBOCSP_ONEREQ\fP * \fBOCSP_request_onereq_get0\fP (\fBOCSP_REQUEST\fP *req, int i)"
.br
.ti -1c
.RI "\fBOCSP_CERTID\fP * \fBOCSP_onereq_get0_id\fP (\fBOCSP_ONEREQ\fP *one)"
.br
.ti -1c
.RI "int \fBOCSP_id_get0_info\fP (\fBASN1_OCTET_STRING\fP **piNameHash, \fBASN1_OBJECT\fP **pmd, \fBASN1_OCTET_STRING\fP **pikeyHash, \fBASN1_INTEGER\fP **pserial, \fBOCSP_CERTID\fP *cid)"
.br
.ti -1c
.RI "int \fBOCSP_request_is_signed\fP (\fBOCSP_REQUEST\fP *req)"
.br
.ti -1c
.RI "\fBOCSP_RESPONSE\fP * \fBOCSP_response_create\fP (int status, \fBOCSP_BASICRESP\fP *bs)"
.br
.ti -1c
.RI "\fBOCSP_SINGLERESP\fP * \fBOCSP_basic_add1_status\fP (\fBOCSP_BASICRESP\fP *rsp, \fBOCSP_CERTID\fP *cid, int status, int reason, \fBASN1_TIME\fP *revtime, \fBASN1_TIME\fP *thisupd, \fBASN1_TIME\fP *nextupd)"
.br
.ti -1c
.RI "int \fBOCSP_basic_add1_cert\fP (\fBOCSP_BASICRESP\fP *resp, \fBX509\fP *cert)"
.br
.ti -1c
.RI "int \fBOCSP_basic_sign\fP (\fBOCSP_BASICRESP\fP *brsp, \fBX509\fP *signer, \fBEVP_PKEY\fP *\fBkey\fP, const \fBEVP_MD\fP *dgst, \fBSTACK_OF\fP(\fBX509\fP)*certs, unsigned long \fBflags\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int OCSP_basic_add1_cert (\fBOCSP_BASICRESP\fP * resp, \fBX509\fP * cert)"

.PP
Definition at line 207 of file ocsp_srv\&.c\&.
.SS "\fBOCSP_SINGLERESP\fP* OCSP_basic_add1_status (\fBOCSP_BASICRESP\fP * rsp, \fBOCSP_CERTID\fP * cid, int status, int reason, \fBASN1_TIME\fP * revtime, \fBASN1_TIME\fP * thisupd, \fBASN1_TIME\fP * nextupd)"

.PP
Definition at line 137 of file ocsp_srv\&.c\&.
.SS "int OCSP_basic_sign (\fBOCSP_BASICRESP\fP * brsp, \fBX509\fP * signer, \fBEVP_PKEY\fP * key, const \fBEVP_MD\fP * dgst, \fBSTACK_OF\fP(\fBX509\fP)* certs, unsigned long flags)"

.PP
Definition at line 218 of file ocsp_srv\&.c\&.
.SS "int OCSP_id_get0_info (\fBASN1_OCTET_STRING\fP ** piNameHash, \fBASN1_OBJECT\fP ** pmd, \fBASN1_OCTET_STRING\fP ** pikeyHash, \fBASN1_INTEGER\fP ** pserial, \fBOCSP_CERTID\fP * cid)"

.PP
Definition at line 89 of file ocsp_srv\&.c\&.
.SS "\fBOCSP_CERTID\fP* OCSP_onereq_get0_id (\fBOCSP_ONEREQ\fP * one)"

.PP
Definition at line 84 of file ocsp_srv\&.c\&.
.SS "int OCSP_request_is_signed (\fBOCSP_REQUEST\fP * req)"

.PP
Definition at line 106 of file ocsp_srv\&.c\&.
.SS "int OCSP_request_onereq_count (\fBOCSP_REQUEST\fP * req)"

.PP
Definition at line 74 of file ocsp_srv\&.c\&.
.SS "\fBOCSP_ONEREQ\fP* OCSP_request_onereq_get0 (\fBOCSP_REQUEST\fP * req, int i)"

.PP
Definition at line 79 of file ocsp_srv\&.c\&.
.SS "\fBOCSP_RESPONSE\fP* OCSP_response_create (int status, \fBOCSP_BASICRESP\fP * bs)"

.PP
Definition at line 114 of file ocsp_srv\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
