.TH "ocsp_service_locator_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ocsp_service_locator_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ocsp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBACCESS_DESCRIPTION\fP)*locator"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBACCESS_DESCRIPTION\fP)*locator"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBACCESS_DESCRIPTION\fP)*locator"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBX509_NAME\fP * \fBissuer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 342 of file ocsp\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBACCESS_DESCRIPTION\fP)"

.SS "STACK_OF (\fBACCESS_DESCRIPTION\fP)"

.SS "STACK_OF (\fBACCESS_DESCRIPTION\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBX509_NAME\fP * issuer"

.PP
Definition at line 343 of file ocsp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
