.TH "OCSPRequest" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OCSPRequest \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTBSRequest\fP * \fBtbsRequest\fP"
.br
.ti -1c
.RI "\fBSignature\fP * \fBoptionalSignature\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 188 of file ocsp\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBSignature\fP* optionalSignature"

.PP
Definition at line 190 of file ocsp\&.c\&.
.SS "\fBTBSRequest\fP* tbsRequest"

.PP
Definition at line 189 of file ocsp\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
