.TH "ocsp_req_info_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ocsp_req_info_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ocsp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBOCSP_ONEREQ\fP)*requestList"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_EXTENSION\fP)*requestExtensions"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBOCSP_ONEREQ\fP)*requestList"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_EXTENSION\fP)*requestExtensions"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBOCSP_ONEREQ\fP)*requestList"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_EXTENSION\fP)*requestExtensions"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBASN1_INTEGER\fP * \fBversion\fP"
.br
.ti -1c
.RI "\fBGENERAL_NAME\fP * \fBrequestorName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 129 of file ocsp\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBOCSP_ONEREQ\fP)"

.SS "STACK_OF (\fBOCSP_ONEREQ\fP)"

.SS "STACK_OF (\fBOCSP_ONEREQ\fP)"

.SS "STACK_OF (\fBX509_EXTENSION\fP)"

.SS "STACK_OF (\fBX509_EXTENSION\fP)"

.SS "STACK_OF (\fBX509_EXTENSION\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBGENERAL_NAME\fP * requestorName"

.PP
Definition at line 131 of file ocsp\&.h\&.
.SS "\fBASN1_INTEGER\fP * version"

.PP
Definition at line 130 of file ocsp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
