.TH "ocsp_resp_bytes_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ocsp_resp_bytes_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ocsp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBASN1_OBJECT\fP * \fBresponseType\fP"
.br
.ti -1c
.RI "\fBASN1_OCTET_STRING\fP * \fBresponse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 177 of file ocsp\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBASN1_OCTET_STRING\fP * response"

.PP
Definition at line 179 of file ocsp\&.h\&.
.SS "\fBASN1_OBJECT\fP * responseType"

.PP
Definition at line 178 of file ocsp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
