.TH "s2n/libcrypto-root/include/openssl/opensslv.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-root/include/openssl/opensslv.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOPENSSL_VERSION_NUMBER\fP   0x10002090L"
.br
.ti -1c
.RI "#define \fBOPENSSL_VERSION_TEXT\fP   'OpenSSL 1\&.0\&.2i\-dev  xx XXX xxxx'"
.br
.ti -1c
.RI "#define \fBOPENSSL_VERSION_PTEXT\fP   ' part \fBof\fP ' OPENSSL_VERSION_TEXT"
.br
.ti -1c
.RI "#define \fBSHLIB_VERSION_HISTORY\fP   ''"
.br
.ti -1c
.RI "#define \fBSHLIB_VERSION_NUMBER\fP   '1\&.0\&.0'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define OPENSSL_VERSION_NUMBER   0x10002090L"

.PP
Definition at line 33 of file opensslv\&.h\&.
.SS "#define OPENSSL_VERSION_PTEXT   ' part \fBof\fP ' OPENSSL_VERSION_TEXT"

.PP
Definition at line 39 of file opensslv\&.h\&.
.SS "#define OPENSSL_VERSION_TEXT   'OpenSSL 1\&.0\&.2i\-dev  xx XXX xxxx'"

.PP
Definition at line 37 of file opensslv\&.h\&.
.SS "#define SHLIB_VERSION_HISTORY   ''"

.PP
Definition at line 90 of file opensslv\&.h\&.
.SS "#define SHLIB_VERSION_NUMBER   '1\&.0\&.0'"

.PP
Definition at line 91 of file opensslv\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
