.TH "s2n/libcrypto-build/openssl/crypto/pkcs12/p12_crt.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/pkcs12/p12_crt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/pkcs12\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPKCS12\fP * \fBPKCS12_create\fP (char *\fBpass\fP, char *name, \fBEVP_PKEY\fP *pkey, \fBX509\fP *cert, \fBSTACK_OF\fP(\fBX509\fP)*ca, int nid_key, int nid_cert, int iter, int mac_iter, int keytype)"
.br
.ti -1c
.RI "\fBPKCS12_SAFEBAG\fP * \fBPKCS12_add_cert\fP (\fBSTACK_OF\fP(\fBPKCS12_SAFEBAG\fP)**pbags, \fBX509\fP *cert)"
.br
.ti -1c
.RI "\fBPKCS12_SAFEBAG\fP * \fBPKCS12_add_key\fP (\fBSTACK_OF\fP(\fBPKCS12_SAFEBAG\fP)**pbags, \fBEVP_PKEY\fP *\fBkey\fP, int key_usage, int iter, int nid_key, char *\fBpass\fP)"
.br
.ti -1c
.RI "int \fBPKCS12_add_safe\fP (\fBSTACK_OF\fP(\fBPKCS7\fP)**psafes, \fBSTACK_OF\fP(\fBPKCS12_SAFEBAG\fP)*bags, int nid_safe, int iter, char *\fBpass\fP)"
.br
.ti -1c
.RI "\fBPKCS12\fP * \fBPKCS12_add_safes\fP (\fBSTACK_OF\fP(\fBPKCS7\fP)*safes, int nid_p7)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPKCS12_SAFEBAG\fP* PKCS12_add_cert (\fBSTACK_OF\fP(\fBPKCS12_SAFEBAG\fP)** pbags, \fBX509\fP * cert)"

.PP
Definition at line 193 of file p12_crt\&.c\&.
.SS "\fBPKCS12_SAFEBAG\fP* PKCS12_add_key (\fBSTACK_OF\fP(\fBPKCS12_SAFEBAG\fP)** pbags, \fBEVP_PKEY\fP * key, int key_usage, int iter, int nid_key, char * pass)"

.PP
Definition at line 233 of file p12_crt\&.c\&.
.SS "int PKCS12_add_safe (\fBSTACK_OF\fP(\fBPKCS7\fP)** psafes, \fBSTACK_OF\fP(\fBPKCS12_SAFEBAG\fP)* bags, int nid_safe, int iter, char * pass)"

.PP
Definition at line 269 of file p12_crt\&.c\&.
.SS "\fBPKCS12\fP* PKCS12_add_safes (\fBSTACK_OF\fP(\fBPKCS7\fP)* safes, int nid_p7)"

.PP
Definition at line 341 of file p12_crt\&.c\&.
.SS "\fBPKCS12\fP* PKCS12_create (char * pass, char * name, \fBEVP_PKEY\fP * pkey, \fBX509\fP * cert, \fBSTACK_OF\fP(\fBX509\fP)* ca, int nid_key, int nid_cert, int iter, int mac_iter, int keytype)"

.PP
Definition at line 80 of file p12_crt\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
