.TH "s2n/libcrypto-build/openssl/crypto/pkcs12/p12_utl.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/pkcs12/p12_utl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/pkcs12\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned char * \fBOPENSSL_asc2uni\fP (const char *asc, int asclen, unsigned char **uni, int *unilen)"
.br
.ti -1c
.RI "char * \fBOPENSSL_uni2asc\fP (unsigned char *uni, int unilen)"
.br
.ti -1c
.RI "int \fBi2d_PKCS12_bio\fP (\fBBIO\fP *\fBbp\fP, \fBPKCS12\fP *p12)"
.br
.ti -1c
.RI "int \fBi2d_PKCS12_fp\fP (FILE *\fBfp\fP, \fBPKCS12\fP *p12)"
.br
.ti -1c
.RI "\fBPKCS12\fP * \fBd2i_PKCS12_bio\fP (\fBBIO\fP *\fBbp\fP, \fBPKCS12\fP **p12)"
.br
.ti -1c
.RI "\fBPKCS12\fP * \fBd2i_PKCS12_fp\fP (FILE *\fBfp\fP, \fBPKCS12\fP **p12)"
.br
.ti -1c
.RI "\fBPKCS12_SAFEBAG\fP * \fBPKCS12_x5092certbag\fP (\fBX509\fP *x509)"
.br
.ti -1c
.RI "\fBPKCS12_SAFEBAG\fP * \fBPKCS12_x509crl2certbag\fP (\fBX509_CRL\fP *crl)"
.br
.ti -1c
.RI "\fBX509\fP * \fBPKCS12_certbag2x509\fP (\fBPKCS12_SAFEBAG\fP *bag)"
.br
.ti -1c
.RI "\fBX509_CRL\fP * \fBPKCS12_certbag2x509crl\fP (\fBPKCS12_SAFEBAG\fP *bag)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPKCS12\fP* d2i_PKCS12_bio (\fBBIO\fP * bp, \fBPKCS12\fP ** p12)"

.PP
Definition at line 119 of file p12_utl\&.c\&.
.SS "\fBPKCS12\fP* d2i_PKCS12_fp (FILE * fp, \fBPKCS12\fP ** p12)"

.PP
Definition at line 125 of file p12_utl\&.c\&.
.SS "int i2d_PKCS12_bio (\fBBIO\fP * bp, \fBPKCS12\fP * p12)"

.PP
Definition at line 107 of file p12_utl\&.c\&.
.SS "int i2d_PKCS12_fp (FILE * fp, \fBPKCS12\fP * p12)"

.PP
Definition at line 113 of file p12_utl\&.c\&.
.SS "unsigned char* OPENSSL_asc2uni (const char * asc, int asclen, unsigned char ** uni, int * unilen)"

.PP
Definition at line 66 of file p12_utl\&.c\&.
.SS "char* OPENSSL_uni2asc (unsigned char * uni, int unilen)"

.PP
Definition at line 90 of file p12_utl\&.c\&.
.SS "\fBX509\fP* PKCS12_certbag2x509 (\fBPKCS12_SAFEBAG\fP * bag)"

.PP
Definition at line 143 of file p12_utl\&.c\&.
.SS "\fBX509_CRL\fP* PKCS12_certbag2x509crl (\fBPKCS12_SAFEBAG\fP * bag)"

.PP
Definition at line 153 of file p12_utl\&.c\&.
.SS "\fBPKCS12_SAFEBAG\fP* PKCS12_x5092certbag (\fBX509\fP * x509)"

.PP
Definition at line 131 of file p12_utl\&.c\&.
.SS "\fBPKCS12_SAFEBAG\fP* PKCS12_x509crl2certbag (\fBX509_CRL\fP * crl)"

.PP
Definition at line 137 of file p12_utl\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
