.TH "s2n/libcrypto-build/openssl/crypto/pkcs12/p12_key.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/pkcs12/p12_key.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/pkcs12\&.h>\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBmin\fP(\fBa\fP,  \fBb\fP)   ((\fBa\fP) < (\fBb\fP) ? (\fBa\fP) : (\fBb\fP))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBPKCS12_key_gen_asc\fP (const char *\fBpass\fP, int \fBpasslen\fP, unsigned char *salt, int saltlen, int id, int iter, int n, unsigned char *\fBout\fP, const \fBEVP_MD\fP *md_type)"
.br
.ti -1c
.RI "int \fBPKCS12_key_gen_uni\fP (unsigned char *\fBpass\fP, int \fBpasslen\fP, unsigned char *salt, int saltlen, int id, int iter, int n, unsigned char *\fBout\fP, const \fBEVP_MD\fP *md_type)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define min(\fBa\fP, \fBb\fP)   ((\fBa\fP) < (\fBb\fP) ? (\fBa\fP) : (\fBb\fP))"

.PP
Definition at line 77 of file p12_key\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int PKCS12_key_gen_asc (const char * pass, int passlen, unsigned char * salt, int saltlen, int id, int iter, int n, unsigned char * out, const \fBEVP_MD\fP * md_type)"

.PP
Definition at line 80 of file p12_key\&.c\&.
.SS "int PKCS12_key_gen_uni (unsigned char * pass, int passlen, unsigned char * salt, int saltlen, int id, int iter, int n, unsigned char * out, const \fBEVP_MD\fP * md_type)"

.PP
Definition at line 106 of file p12_key\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
