.TH "s2n/libcrypto-build/openssl/crypto/x509v3/pcy_data.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/x509v3/pcy_data.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br
\fC#include 'pcy_int\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBpolicy_data_free\fP (\fBX509_POLICY_DATA\fP *\fBdata\fP)"
.br
.ti -1c
.RI "\fBX509_POLICY_DATA\fP * \fBpolicy_data_new\fP (\fBPOLICYINFO\fP *policy, const \fBASN1_OBJECT\fP *cid, int crit)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP policy_data_free (\fBX509_POLICY_DATA\fP * data)"

.PP
Definition at line 68 of file pcy_data\&.c\&.
.SS "\fBX509_POLICY_DATA\fP* policy_data_new (\fBPOLICYINFO\fP * policy, const \fBASN1_OBJECT\fP * cid, int crit)"

.PP
Definition at line 86 of file pcy_data\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
