.TH "s2n/libcrypto-build/openssl/crypto/pkcs7/pk7_attr.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/pkcs7/pk7_attr.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <openssl/bio\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <openssl/pkcs7\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBPKCS7_add_attrib_smimecap\fP (\fBPKCS7_SIGNER_INFO\fP *si, \fBSTACK_OF\fP(\fBX509_ALGOR\fP)*cap)"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBX509_ALGOR\fP)"
.br
.ti -1c
.RI "int \fBPKCS7_simple_smimecap\fP (\fBSTACK_OF\fP(\fBX509_ALGOR\fP)*sk, int \fBnid\fP, int \fBarg\fP)"
.br
.ti -1c
.RI "int \fBPKCS7_add_attrib_content_type\fP (\fBPKCS7_SIGNER_INFO\fP *si, \fBASN1_OBJECT\fP *coid)"
.br
.ti -1c
.RI "int \fBPKCS7_add0_attrib_signing_time\fP (\fBPKCS7_SIGNER_INFO\fP *si, \fBASN1_TIME\fP *\fBt\fP)"
.br
.ti -1c
.RI "int \fBPKCS7_add1_attrib_digest\fP (\fBPKCS7_SIGNER_INFO\fP *si, const unsigned char *md, int mdlen)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int PKCS7_add0_attrib_signing_time (\fBPKCS7_SIGNER_INFO\fP * si, \fBASN1_TIME\fP * t)"

.PP
Definition at line 140 of file pk7_attr\&.c\&.
.SS "int PKCS7_add1_attrib_digest (\fBPKCS7_SIGNER_INFO\fP * si, const unsigned char * md, int mdlen)"

.PP
Definition at line 151 of file pk7_attr\&.c\&.
.SS "int PKCS7_add_attrib_content_type (\fBPKCS7_SIGNER_INFO\fP * si, \fBASN1_OBJECT\fP * coid)"

.PP
Definition at line 130 of file pk7_attr\&.c\&.
.SS "int PKCS7_add_attrib_smimecap (\fBPKCS7_SIGNER_INFO\fP * si, \fBSTACK_OF\fP(\fBX509_ALGOR\fP)* cap)"

.PP
Definition at line 70 of file pk7_attr\&.c\&.
.SS "int PKCS7_simple_smimecap (\fBSTACK_OF\fP(\fBX509_ALGOR\fP)* sk, int nid, int arg)"

.PP
Definition at line 99 of file pk7_attr\&.c\&.
.SS "STACK_OF (\fBX509_ALGOR\fP)"

.PP
Definition at line 84 of file pk7_attr\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
