.TH "s2n/libcrypto-build/openssl/crypto/rand/rand_egd.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/rand/rand_egd.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/e_os2\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/opensslconf\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/un\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBoffsetof\fP(\fBTYPE\fP,  MEMBER)   ((size_t) &((\fBTYPE\fP *)0)\->MEMBER)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBRAND_query_egd_bytes\fP (const char *path, unsigned char *buf, int \fBbytes\fP)"
.br
.ti -1c
.RI "int \fBRAND_egd_bytes\fP (const char *path, int \fBbytes\fP)"
.br
.ti -1c
.RI "int \fBRAND_egd\fP (const char *path)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define offsetof(\fBTYPE\fP, MEMBER)   ((size_t) &((\fBTYPE\fP *)0)\->MEMBER)"

.PP
Definition at line 135 of file rand_egd\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int RAND_egd (const char * path)"

.PP
Definition at line 287 of file rand_egd\&.c\&.
.SS "int RAND_egd_bytes (const char * path, int bytes)"

.PP
Definition at line 274 of file rand_egd\&.c\&.
.SS "int RAND_query_egd_bytes (const char * path, unsigned char * buf, int bytes)"

.PP
Definition at line 138 of file rand_egd\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
