.TH "s2n/libcrypto-build/openssl/crypto/rand/rand_unix.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/rand/rand_unix.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'e_os\&.h'\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include 'rand_lcl\&.h'\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/times\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSE_SOCKETS\fP"
.br
.ti -1c
.RI "#define \fBFD_SETSIZE\fP   (8*sizeof(fd_set))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBRAND_poll\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FD_SETSIZE   (8*sizeof(fd_set))"

.PP
Definition at line 134 of file rand_unix\&.c\&.
.SS "#define USE_SOCKETS"

.PP
Definition at line 113 of file rand_unix\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int RAND_poll (\fBvoid\fP)"

.PP
Definition at line 243 of file rand_unix\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
