.TH "s2n/libcrypto-build/openssl/crypto/ripemd/rmdconst.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ripemd/rmdconst.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKL0\fP   0x00000000L"
.br
.ti -1c
.RI "#define \fBKL1\fP   0x5A827999L"
.br
.ti -1c
.RI "#define \fBKL2\fP   0x6ED9EBA1L"
.br
.ti -1c
.RI "#define \fBKL3\fP   0x8F1BBCDCL"
.br
.ti -1c
.RI "#define \fBKL4\fP   0xA953FD4EL"
.br
.ti -1c
.RI "#define \fBKR0\fP   0x50A28BE6L"
.br
.ti -1c
.RI "#define \fBKR1\fP   0x5C4DD124L"
.br
.ti -1c
.RI "#define \fBKR2\fP   0x6D703EF3L"
.br
.ti -1c
.RI "#define \fBKR3\fP   0x7A6D76E9L"
.br
.ti -1c
.RI "#define \fBKR4\fP   0x00000000L"
.br
.ti -1c
.RI "#define \fBWL00\fP   0"
.br
.ti -1c
.RI "#define \fBSL00\fP   11"
.br
.ti -1c
.RI "#define \fBWL01\fP   1"
.br
.ti -1c
.RI "#define \fBSL01\fP   14"
.br
.ti -1c
.RI "#define \fBWL02\fP   2"
.br
.ti -1c
.RI "#define \fBSL02\fP   15"
.br
.ti -1c
.RI "#define \fBWL03\fP   3"
.br
.ti -1c
.RI "#define \fBSL03\fP   12"
.br
.ti -1c
.RI "#define \fBWL04\fP   4"
.br
.ti -1c
.RI "#define \fBSL04\fP   5"
.br
.ti -1c
.RI "#define \fBWL05\fP   5"
.br
.ti -1c
.RI "#define \fBSL05\fP   8"
.br
.ti -1c
.RI "#define \fBWL06\fP   6"
.br
.ti -1c
.RI "#define \fBSL06\fP   7"
.br
.ti -1c
.RI "#define \fBWL07\fP   7"
.br
.ti -1c
.RI "#define \fBSL07\fP   9"
.br
.ti -1c
.RI "#define \fBWL08\fP   8"
.br
.ti -1c
.RI "#define \fBSL08\fP   11"
.br
.ti -1c
.RI "#define \fBWL09\fP   9"
.br
.ti -1c
.RI "#define \fBSL09\fP   13"
.br
.ti -1c
.RI "#define \fBWL10\fP   10"
.br
.ti -1c
.RI "#define \fBSL10\fP   14"
.br
.ti -1c
.RI "#define \fBWL11\fP   11"
.br
.ti -1c
.RI "#define \fBSL11\fP   15"
.br
.ti -1c
.RI "#define \fBWL12\fP   12"
.br
.ti -1c
.RI "#define \fBSL12\fP   6"
.br
.ti -1c
.RI "#define \fBWL13\fP   13"
.br
.ti -1c
.RI "#define \fBSL13\fP   7"
.br
.ti -1c
.RI "#define \fBWL14\fP   14"
.br
.ti -1c
.RI "#define \fBSL14\fP   9"
.br
.ti -1c
.RI "#define \fBWL15\fP   15"
.br
.ti -1c
.RI "#define \fBSL15\fP   8"
.br
.ti -1c
.RI "#define \fBWL16\fP   7"
.br
.ti -1c
.RI "#define \fBSL16\fP   7"
.br
.ti -1c
.RI "#define \fBWL17\fP   4"
.br
.ti -1c
.RI "#define \fBSL17\fP   6"
.br
.ti -1c
.RI "#define \fBWL18\fP   13"
.br
.ti -1c
.RI "#define \fBSL18\fP   8"
.br
.ti -1c
.RI "#define \fBWL19\fP   1"
.br
.ti -1c
.RI "#define \fBSL19\fP   13"
.br
.ti -1c
.RI "#define \fBWL20\fP   10"
.br
.ti -1c
.RI "#define \fBSL20\fP   11"
.br
.ti -1c
.RI "#define \fBWL21\fP   6"
.br
.ti -1c
.RI "#define \fBSL21\fP   9"
.br
.ti -1c
.RI "#define \fBWL22\fP   15"
.br
.ti -1c
.RI "#define \fBSL22\fP   7"
.br
.ti -1c
.RI "#define \fBWL23\fP   3"
.br
.ti -1c
.RI "#define \fBSL23\fP   15"
.br
.ti -1c
.RI "#define \fBWL24\fP   12"
.br
.ti -1c
.RI "#define \fBSL24\fP   7"
.br
.ti -1c
.RI "#define \fBWL25\fP   0"
.br
.ti -1c
.RI "#define \fBSL25\fP   12"
.br
.ti -1c
.RI "#define \fBWL26\fP   9"
.br
.ti -1c
.RI "#define \fBSL26\fP   15"
.br
.ti -1c
.RI "#define \fBWL27\fP   5"
.br
.ti -1c
.RI "#define \fBSL27\fP   9"
.br
.ti -1c
.RI "#define \fBWL28\fP   2"
.br
.ti -1c
.RI "#define \fBSL28\fP   11"
.br
.ti -1c
.RI "#define \fBWL29\fP   14"
.br
.ti -1c
.RI "#define \fBSL29\fP   7"
.br
.ti -1c
.RI "#define \fBWL30\fP   11"
.br
.ti -1c
.RI "#define \fBSL30\fP   13"
.br
.ti -1c
.RI "#define \fBWL31\fP   8"
.br
.ti -1c
.RI "#define \fBSL31\fP   12"
.br
.ti -1c
.RI "#define \fBWL32\fP   3"
.br
.ti -1c
.RI "#define \fBSL32\fP   11"
.br
.ti -1c
.RI "#define \fBWL33\fP   10"
.br
.ti -1c
.RI "#define \fBSL33\fP   13"
.br
.ti -1c
.RI "#define \fBWL34\fP   14"
.br
.ti -1c
.RI "#define \fBSL34\fP   6"
.br
.ti -1c
.RI "#define \fBWL35\fP   4"
.br
.ti -1c
.RI "#define \fBSL35\fP   7"
.br
.ti -1c
.RI "#define \fBWL36\fP   9"
.br
.ti -1c
.RI "#define \fBSL36\fP   14"
.br
.ti -1c
.RI "#define \fBWL37\fP   15"
.br
.ti -1c
.RI "#define \fBSL37\fP   9"
.br
.ti -1c
.RI "#define \fBWL38\fP   8"
.br
.ti -1c
.RI "#define \fBSL38\fP   13"
.br
.ti -1c
.RI "#define \fBWL39\fP   1"
.br
.ti -1c
.RI "#define \fBSL39\fP   15"
.br
.ti -1c
.RI "#define \fBWL40\fP   2"
.br
.ti -1c
.RI "#define \fBSL40\fP   14"
.br
.ti -1c
.RI "#define \fBWL41\fP   7"
.br
.ti -1c
.RI "#define \fBSL41\fP   8"
.br
.ti -1c
.RI "#define \fBWL42\fP   0"
.br
.ti -1c
.RI "#define \fBSL42\fP   13"
.br
.ti -1c
.RI "#define \fBWL43\fP   6"
.br
.ti -1c
.RI "#define \fBSL43\fP   6"
.br
.ti -1c
.RI "#define \fBWL44\fP   13"
.br
.ti -1c
.RI "#define \fBSL44\fP   5"
.br
.ti -1c
.RI "#define \fBWL45\fP   11"
.br
.ti -1c
.RI "#define \fBSL45\fP   12"
.br
.ti -1c
.RI "#define \fBWL46\fP   5"
.br
.ti -1c
.RI "#define \fBSL46\fP   7"
.br
.ti -1c
.RI "#define \fBWL47\fP   12"
.br
.ti -1c
.RI "#define \fBSL47\fP   5"
.br
.ti -1c
.RI "#define \fBWL48\fP   1"
.br
.ti -1c
.RI "#define \fBSL48\fP   11"
.br
.ti -1c
.RI "#define \fBWL49\fP   9"
.br
.ti -1c
.RI "#define \fBSL49\fP   12"
.br
.ti -1c
.RI "#define \fBWL50\fP   11"
.br
.ti -1c
.RI "#define \fBSL50\fP   14"
.br
.ti -1c
.RI "#define \fBWL51\fP   10"
.br
.ti -1c
.RI "#define \fBSL51\fP   15"
.br
.ti -1c
.RI "#define \fBWL52\fP   0"
.br
.ti -1c
.RI "#define \fBSL52\fP   14"
.br
.ti -1c
.RI "#define \fBWL53\fP   8"
.br
.ti -1c
.RI "#define \fBSL53\fP   15"
.br
.ti -1c
.RI "#define \fBWL54\fP   12"
.br
.ti -1c
.RI "#define \fBSL54\fP   9"
.br
.ti -1c
.RI "#define \fBWL55\fP   4"
.br
.ti -1c
.RI "#define \fBSL55\fP   8"
.br
.ti -1c
.RI "#define \fBWL56\fP   13"
.br
.ti -1c
.RI "#define \fBSL56\fP   9"
.br
.ti -1c
.RI "#define \fBWL57\fP   3"
.br
.ti -1c
.RI "#define \fBSL57\fP   14"
.br
.ti -1c
.RI "#define \fBWL58\fP   7"
.br
.ti -1c
.RI "#define \fBSL58\fP   5"
.br
.ti -1c
.RI "#define \fBWL59\fP   15"
.br
.ti -1c
.RI "#define \fBSL59\fP   6"
.br
.ti -1c
.RI "#define \fBWL60\fP   14"
.br
.ti -1c
.RI "#define \fBSL60\fP   8"
.br
.ti -1c
.RI "#define \fBWL61\fP   5"
.br
.ti -1c
.RI "#define \fBSL61\fP   6"
.br
.ti -1c
.RI "#define \fBWL62\fP   6"
.br
.ti -1c
.RI "#define \fBSL62\fP   5"
.br
.ti -1c
.RI "#define \fBWL63\fP   2"
.br
.ti -1c
.RI "#define \fBSL63\fP   12"
.br
.ti -1c
.RI "#define \fBWL64\fP   4"
.br
.ti -1c
.RI "#define \fBSL64\fP   9"
.br
.ti -1c
.RI "#define \fBWL65\fP   0"
.br
.ti -1c
.RI "#define \fBSL65\fP   15"
.br
.ti -1c
.RI "#define \fBWL66\fP   5"
.br
.ti -1c
.RI "#define \fBSL66\fP   5"
.br
.ti -1c
.RI "#define \fBWL67\fP   9"
.br
.ti -1c
.RI "#define \fBSL67\fP   11"
.br
.ti -1c
.RI "#define \fBWL68\fP   7"
.br
.ti -1c
.RI "#define \fBSL68\fP   6"
.br
.ti -1c
.RI "#define \fBWL69\fP   12"
.br
.ti -1c
.RI "#define \fBSL69\fP   8"
.br
.ti -1c
.RI "#define \fBWL70\fP   2"
.br
.ti -1c
.RI "#define \fBSL70\fP   13"
.br
.ti -1c
.RI "#define \fBWL71\fP   10"
.br
.ti -1c
.RI "#define \fBSL71\fP   12"
.br
.ti -1c
.RI "#define \fBWL72\fP   14"
.br
.ti -1c
.RI "#define \fBSL72\fP   5"
.br
.ti -1c
.RI "#define \fBWL73\fP   1"
.br
.ti -1c
.RI "#define \fBSL73\fP   12"
.br
.ti -1c
.RI "#define \fBWL74\fP   3"
.br
.ti -1c
.RI "#define \fBSL74\fP   13"
.br
.ti -1c
.RI "#define \fBWL75\fP   8"
.br
.ti -1c
.RI "#define \fBSL75\fP   14"
.br
.ti -1c
.RI "#define \fBWL76\fP   11"
.br
.ti -1c
.RI "#define \fBSL76\fP   11"
.br
.ti -1c
.RI "#define \fBWL77\fP   6"
.br
.ti -1c
.RI "#define \fBSL77\fP   8"
.br
.ti -1c
.RI "#define \fBWL78\fP   15"
.br
.ti -1c
.RI "#define \fBSL78\fP   5"
.br
.ti -1c
.RI "#define \fBWL79\fP   13"
.br
.ti -1c
.RI "#define \fBSL79\fP   6"
.br
.ti -1c
.RI "#define \fBWR00\fP   5"
.br
.ti -1c
.RI "#define \fBSR00\fP   8"
.br
.ti -1c
.RI "#define \fBWR01\fP   14"
.br
.ti -1c
.RI "#define \fBSR01\fP   9"
.br
.ti -1c
.RI "#define \fBWR02\fP   7"
.br
.ti -1c
.RI "#define \fBSR02\fP   9"
.br
.ti -1c
.RI "#define \fBWR03\fP   0"
.br
.ti -1c
.RI "#define \fBSR03\fP   11"
.br
.ti -1c
.RI "#define \fBWR04\fP   9"
.br
.ti -1c
.RI "#define \fBSR04\fP   13"
.br
.ti -1c
.RI "#define \fBWR05\fP   2"
.br
.ti -1c
.RI "#define \fBSR05\fP   15"
.br
.ti -1c
.RI "#define \fBWR06\fP   11"
.br
.ti -1c
.RI "#define \fBSR06\fP   15"
.br
.ti -1c
.RI "#define \fBWR07\fP   4"
.br
.ti -1c
.RI "#define \fBSR07\fP   5"
.br
.ti -1c
.RI "#define \fBWR08\fP   13"
.br
.ti -1c
.RI "#define \fBSR08\fP   7"
.br
.ti -1c
.RI "#define \fBWR09\fP   6"
.br
.ti -1c
.RI "#define \fBSR09\fP   7"
.br
.ti -1c
.RI "#define \fBWR10\fP   15"
.br
.ti -1c
.RI "#define \fBSR10\fP   8"
.br
.ti -1c
.RI "#define \fBWR11\fP   8"
.br
.ti -1c
.RI "#define \fBSR11\fP   11"
.br
.ti -1c
.RI "#define \fBWR12\fP   1"
.br
.ti -1c
.RI "#define \fBSR12\fP   14"
.br
.ti -1c
.RI "#define \fBWR13\fP   10"
.br
.ti -1c
.RI "#define \fBSR13\fP   14"
.br
.ti -1c
.RI "#define \fBWR14\fP   3"
.br
.ti -1c
.RI "#define \fBSR14\fP   12"
.br
.ti -1c
.RI "#define \fBWR15\fP   12"
.br
.ti -1c
.RI "#define \fBSR15\fP   6"
.br
.ti -1c
.RI "#define \fBWR16\fP   6"
.br
.ti -1c
.RI "#define \fBSR16\fP   9"
.br
.ti -1c
.RI "#define \fBWR17\fP   11"
.br
.ti -1c
.RI "#define \fBSR17\fP   13"
.br
.ti -1c
.RI "#define \fBWR18\fP   3"
.br
.ti -1c
.RI "#define \fBSR18\fP   15"
.br
.ti -1c
.RI "#define \fBWR19\fP   7"
.br
.ti -1c
.RI "#define \fBSR19\fP   7"
.br
.ti -1c
.RI "#define \fBWR20\fP   0"
.br
.ti -1c
.RI "#define \fBSR20\fP   12"
.br
.ti -1c
.RI "#define \fBWR21\fP   13"
.br
.ti -1c
.RI "#define \fBSR21\fP   8"
.br
.ti -1c
.RI "#define \fBWR22\fP   5"
.br
.ti -1c
.RI "#define \fBSR22\fP   9"
.br
.ti -1c
.RI "#define \fBWR23\fP   10"
.br
.ti -1c
.RI "#define \fBSR23\fP   11"
.br
.ti -1c
.RI "#define \fBWR24\fP   14"
.br
.ti -1c
.RI "#define \fBSR24\fP   7"
.br
.ti -1c
.RI "#define \fBWR25\fP   15"
.br
.ti -1c
.RI "#define \fBSR25\fP   7"
.br
.ti -1c
.RI "#define \fBWR26\fP   8"
.br
.ti -1c
.RI "#define \fBSR26\fP   12"
.br
.ti -1c
.RI "#define \fBWR27\fP   12"
.br
.ti -1c
.RI "#define \fBSR27\fP   7"
.br
.ti -1c
.RI "#define \fBWR28\fP   4"
.br
.ti -1c
.RI "#define \fBSR28\fP   6"
.br
.ti -1c
.RI "#define \fBWR29\fP   9"
.br
.ti -1c
.RI "#define \fBSR29\fP   15"
.br
.ti -1c
.RI "#define \fBWR30\fP   1"
.br
.ti -1c
.RI "#define \fBSR30\fP   13"
.br
.ti -1c
.RI "#define \fBWR31\fP   2"
.br
.ti -1c
.RI "#define \fBSR31\fP   11"
.br
.ti -1c
.RI "#define \fBWR32\fP   15"
.br
.ti -1c
.RI "#define \fBSR32\fP   9"
.br
.ti -1c
.RI "#define \fBWR33\fP   5"
.br
.ti -1c
.RI "#define \fBSR33\fP   7"
.br
.ti -1c
.RI "#define \fBWR34\fP   1"
.br
.ti -1c
.RI "#define \fBSR34\fP   15"
.br
.ti -1c
.RI "#define \fBWR35\fP   3"
.br
.ti -1c
.RI "#define \fBSR35\fP   11"
.br
.ti -1c
.RI "#define \fBWR36\fP   7"
.br
.ti -1c
.RI "#define \fBSR36\fP   8"
.br
.ti -1c
.RI "#define \fBWR37\fP   14"
.br
.ti -1c
.RI "#define \fBSR37\fP   6"
.br
.ti -1c
.RI "#define \fBWR38\fP   6"
.br
.ti -1c
.RI "#define \fBSR38\fP   6"
.br
.ti -1c
.RI "#define \fBWR39\fP   9"
.br
.ti -1c
.RI "#define \fBSR39\fP   14"
.br
.ti -1c
.RI "#define \fBWR40\fP   11"
.br
.ti -1c
.RI "#define \fBSR40\fP   12"
.br
.ti -1c
.RI "#define \fBWR41\fP   8"
.br
.ti -1c
.RI "#define \fBSR41\fP   13"
.br
.ti -1c
.RI "#define \fBWR42\fP   12"
.br
.ti -1c
.RI "#define \fBSR42\fP   5"
.br
.ti -1c
.RI "#define \fBWR43\fP   2"
.br
.ti -1c
.RI "#define \fBSR43\fP   14"
.br
.ti -1c
.RI "#define \fBWR44\fP   10"
.br
.ti -1c
.RI "#define \fBSR44\fP   13"
.br
.ti -1c
.RI "#define \fBWR45\fP   0"
.br
.ti -1c
.RI "#define \fBSR45\fP   13"
.br
.ti -1c
.RI "#define \fBWR46\fP   4"
.br
.ti -1c
.RI "#define \fBSR46\fP   7"
.br
.ti -1c
.RI "#define \fBWR47\fP   13"
.br
.ti -1c
.RI "#define \fBSR47\fP   5"
.br
.ti -1c
.RI "#define \fBWR48\fP   8"
.br
.ti -1c
.RI "#define \fBSR48\fP   15"
.br
.ti -1c
.RI "#define \fBWR49\fP   6"
.br
.ti -1c
.RI "#define \fBSR49\fP   5"
.br
.ti -1c
.RI "#define \fBWR50\fP   4"
.br
.ti -1c
.RI "#define \fBSR50\fP   8"
.br
.ti -1c
.RI "#define \fBWR51\fP   1"
.br
.ti -1c
.RI "#define \fBSR51\fP   11"
.br
.ti -1c
.RI "#define \fBWR52\fP   3"
.br
.ti -1c
.RI "#define \fBSR52\fP   14"
.br
.ti -1c
.RI "#define \fBWR53\fP   11"
.br
.ti -1c
.RI "#define \fBSR53\fP   14"
.br
.ti -1c
.RI "#define \fBWR54\fP   15"
.br
.ti -1c
.RI "#define \fBSR54\fP   6"
.br
.ti -1c
.RI "#define \fBWR55\fP   0"
.br
.ti -1c
.RI "#define \fBSR55\fP   14"
.br
.ti -1c
.RI "#define \fBWR56\fP   5"
.br
.ti -1c
.RI "#define \fBSR56\fP   6"
.br
.ti -1c
.RI "#define \fBWR57\fP   12"
.br
.ti -1c
.RI "#define \fBSR57\fP   9"
.br
.ti -1c
.RI "#define \fBWR58\fP   2"
.br
.ti -1c
.RI "#define \fBSR58\fP   12"
.br
.ti -1c
.RI "#define \fBWR59\fP   13"
.br
.ti -1c
.RI "#define \fBSR59\fP   9"
.br
.ti -1c
.RI "#define \fBWR60\fP   9"
.br
.ti -1c
.RI "#define \fBSR60\fP   12"
.br
.ti -1c
.RI "#define \fBWR61\fP   7"
.br
.ti -1c
.RI "#define \fBSR61\fP   5"
.br
.ti -1c
.RI "#define \fBWR62\fP   10"
.br
.ti -1c
.RI "#define \fBSR62\fP   15"
.br
.ti -1c
.RI "#define \fBWR63\fP   14"
.br
.ti -1c
.RI "#define \fBSR63\fP   8"
.br
.ti -1c
.RI "#define \fBWR64\fP   12"
.br
.ti -1c
.RI "#define \fBSR64\fP   8"
.br
.ti -1c
.RI "#define \fBWR65\fP   15"
.br
.ti -1c
.RI "#define \fBSR65\fP   5"
.br
.ti -1c
.RI "#define \fBWR66\fP   10"
.br
.ti -1c
.RI "#define \fBSR66\fP   12"
.br
.ti -1c
.RI "#define \fBWR67\fP   4"
.br
.ti -1c
.RI "#define \fBSR67\fP   9"
.br
.ti -1c
.RI "#define \fBWR68\fP   1"
.br
.ti -1c
.RI "#define \fBSR68\fP   12"
.br
.ti -1c
.RI "#define \fBWR69\fP   5"
.br
.ti -1c
.RI "#define \fBSR69\fP   5"
.br
.ti -1c
.RI "#define \fBWR70\fP   8"
.br
.ti -1c
.RI "#define \fBSR70\fP   14"
.br
.ti -1c
.RI "#define \fBWR71\fP   7"
.br
.ti -1c
.RI "#define \fBSR71\fP   6"
.br
.ti -1c
.RI "#define \fBWR72\fP   6"
.br
.ti -1c
.RI "#define \fBSR72\fP   8"
.br
.ti -1c
.RI "#define \fBWR73\fP   2"
.br
.ti -1c
.RI "#define \fBSR73\fP   13"
.br
.ti -1c
.RI "#define \fBWR74\fP   13"
.br
.ti -1c
.RI "#define \fBSR74\fP   6"
.br
.ti -1c
.RI "#define \fBWR75\fP   14"
.br
.ti -1c
.RI "#define \fBSR75\fP   5"
.br
.ti -1c
.RI "#define \fBWR76\fP   0"
.br
.ti -1c
.RI "#define \fBSR76\fP   15"
.br
.ti -1c
.RI "#define \fBWR77\fP   3"
.br
.ti -1c
.RI "#define \fBSR77\fP   13"
.br
.ti -1c
.RI "#define \fBWR78\fP   9"
.br
.ti -1c
.RI "#define \fBSR78\fP   11"
.br
.ti -1c
.RI "#define \fBWR79\fP   11"
.br
.ti -1c
.RI "#define \fBSR79\fP   11"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define KL0   0x00000000L"

.PP
Definition at line 58 of file rmdconst\&.h\&.
.SS "#define KL1   0x5A827999L"

.PP
Definition at line 59 of file rmdconst\&.h\&.
.SS "#define KL2   0x6ED9EBA1L"

.PP
Definition at line 60 of file rmdconst\&.h\&.
.SS "#define KL3   0x8F1BBCDCL"

.PP
Definition at line 61 of file rmdconst\&.h\&.
.SS "#define KL4   0xA953FD4EL"

.PP
Definition at line 62 of file rmdconst\&.h\&.
.SS "#define KR0   0x50A28BE6L"

.PP
Definition at line 64 of file rmdconst\&.h\&.
.SS "#define KR1   0x5C4DD124L"

.PP
Definition at line 65 of file rmdconst\&.h\&.
.SS "#define KR2   0x6D703EF3L"

.PP
Definition at line 66 of file rmdconst\&.h\&.
.SS "#define KR3   0x7A6D76E9L"

.PP
Definition at line 67 of file rmdconst\&.h\&.
.SS "#define KR4   0x00000000L"

.PP
Definition at line 68 of file rmdconst\&.h\&.
.SS "#define SL00   11"

.PP
Definition at line 71 of file rmdconst\&.h\&.
.SS "#define SL01   14"

.PP
Definition at line 73 of file rmdconst\&.h\&.
.SS "#define SL02   15"

.PP
Definition at line 75 of file rmdconst\&.h\&.
.SS "#define SL03   12"

.PP
Definition at line 77 of file rmdconst\&.h\&.
.SS "#define SL04   5"

.PP
Definition at line 79 of file rmdconst\&.h\&.
.SS "#define SL05   8"

.PP
Definition at line 81 of file rmdconst\&.h\&.
.SS "#define SL06   7"

.PP
Definition at line 83 of file rmdconst\&.h\&.
.SS "#define SL07   9"

.PP
Definition at line 85 of file rmdconst\&.h\&.
.SS "#define SL08   11"

.PP
Definition at line 87 of file rmdconst\&.h\&.
.SS "#define SL09   13"

.PP
Definition at line 89 of file rmdconst\&.h\&.
.SS "#define SL10   14"

.PP
Definition at line 91 of file rmdconst\&.h\&.
.SS "#define SL11   15"

.PP
Definition at line 93 of file rmdconst\&.h\&.
.SS "#define SL12   6"

.PP
Definition at line 95 of file rmdconst\&.h\&.
.SS "#define SL13   7"

.PP
Definition at line 97 of file rmdconst\&.h\&.
.SS "#define SL14   9"

.PP
Definition at line 99 of file rmdconst\&.h\&.
.SS "#define SL15   8"

.PP
Definition at line 101 of file rmdconst\&.h\&.
.SS "#define SL16   7"

.PP
Definition at line 104 of file rmdconst\&.h\&.
.SS "#define SL17   6"

.PP
Definition at line 106 of file rmdconst\&.h\&.
.SS "#define SL18   8"

.PP
Definition at line 108 of file rmdconst\&.h\&.
.SS "#define SL19   13"

.PP
Definition at line 110 of file rmdconst\&.h\&.
.SS "#define SL20   11"

.PP
Definition at line 112 of file rmdconst\&.h\&.
.SS "#define SL21   9"

.PP
Definition at line 114 of file rmdconst\&.h\&.
.SS "#define SL22   7"

.PP
Definition at line 116 of file rmdconst\&.h\&.
.SS "#define SL23   15"

.PP
Definition at line 118 of file rmdconst\&.h\&.
.SS "#define SL24   7"

.PP
Definition at line 120 of file rmdconst\&.h\&.
.SS "#define SL25   12"

.PP
Definition at line 122 of file rmdconst\&.h\&.
.SS "#define SL26   15"

.PP
Definition at line 124 of file rmdconst\&.h\&.
.SS "#define SL27   9"

.PP
Definition at line 126 of file rmdconst\&.h\&.
.SS "#define SL28   11"

.PP
Definition at line 128 of file rmdconst\&.h\&.
.SS "#define SL29   7"

.PP
Definition at line 130 of file rmdconst\&.h\&.
.SS "#define SL30   13"

.PP
Definition at line 132 of file rmdconst\&.h\&.
.SS "#define SL31   12"

.PP
Definition at line 134 of file rmdconst\&.h\&.
.SS "#define SL32   11"

.PP
Definition at line 137 of file rmdconst\&.h\&.
.SS "#define SL33   13"

.PP
Definition at line 139 of file rmdconst\&.h\&.
.SS "#define SL34   6"

.PP
Definition at line 141 of file rmdconst\&.h\&.
.SS "#define SL35   7"

.PP
Definition at line 143 of file rmdconst\&.h\&.
.SS "#define SL36   14"

.PP
Definition at line 145 of file rmdconst\&.h\&.
.SS "#define SL37   9"

.PP
Definition at line 147 of file rmdconst\&.h\&.
.SS "#define SL38   13"

.PP
Definition at line 149 of file rmdconst\&.h\&.
.SS "#define SL39   15"

.PP
Definition at line 151 of file rmdconst\&.h\&.
.SS "#define SL40   14"

.PP
Definition at line 153 of file rmdconst\&.h\&.
.SS "#define SL41   8"

.PP
Definition at line 155 of file rmdconst\&.h\&.
.SS "#define SL42   13"

.PP
Definition at line 157 of file rmdconst\&.h\&.
.SS "#define SL43   6"

.PP
Definition at line 159 of file rmdconst\&.h\&.
.SS "#define SL44   5"

.PP
Definition at line 161 of file rmdconst\&.h\&.
.SS "#define SL45   12"

.PP
Definition at line 163 of file rmdconst\&.h\&.
.SS "#define SL46   7"

.PP
Definition at line 165 of file rmdconst\&.h\&.
.SS "#define SL47   5"

.PP
Definition at line 167 of file rmdconst\&.h\&.
.SS "#define SL48   11"

.PP
Definition at line 170 of file rmdconst\&.h\&.
.SS "#define SL49   12"

.PP
Definition at line 172 of file rmdconst\&.h\&.
.SS "#define SL50   14"

.PP
Definition at line 174 of file rmdconst\&.h\&.
.SS "#define SL51   15"

.PP
Definition at line 176 of file rmdconst\&.h\&.
.SS "#define SL52   14"

.PP
Definition at line 178 of file rmdconst\&.h\&.
.SS "#define SL53   15"

.PP
Definition at line 180 of file rmdconst\&.h\&.
.SS "#define SL54   9"

.PP
Definition at line 182 of file rmdconst\&.h\&.
.SS "#define SL55   8"

.PP
Definition at line 184 of file rmdconst\&.h\&.
.SS "#define SL56   9"

.PP
Definition at line 186 of file rmdconst\&.h\&.
.SS "#define SL57   14"

.PP
Definition at line 188 of file rmdconst\&.h\&.
.SS "#define SL58   5"

.PP
Definition at line 190 of file rmdconst\&.h\&.
.SS "#define SL59   6"

.PP
Definition at line 192 of file rmdconst\&.h\&.
.SS "#define SL60   8"

.PP
Definition at line 194 of file rmdconst\&.h\&.
.SS "#define SL61   6"

.PP
Definition at line 196 of file rmdconst\&.h\&.
.SS "#define SL62   5"

.PP
Definition at line 198 of file rmdconst\&.h\&.
.SS "#define SL63   12"

.PP
Definition at line 200 of file rmdconst\&.h\&.
.SS "#define SL64   9"

.PP
Definition at line 203 of file rmdconst\&.h\&.
.SS "#define SL65   15"

.PP
Definition at line 205 of file rmdconst\&.h\&.
.SS "#define SL66   5"

.PP
Definition at line 207 of file rmdconst\&.h\&.
.SS "#define SL67   11"

.PP
Definition at line 209 of file rmdconst\&.h\&.
.SS "#define SL68   6"

.PP
Definition at line 211 of file rmdconst\&.h\&.
.SS "#define SL69   8"

.PP
Definition at line 213 of file rmdconst\&.h\&.
.SS "#define SL70   13"

.PP
Definition at line 215 of file rmdconst\&.h\&.
.SS "#define SL71   12"

.PP
Definition at line 217 of file rmdconst\&.h\&.
.SS "#define SL72   5"

.PP
Definition at line 219 of file rmdconst\&.h\&.
.SS "#define SL73   12"

.PP
Definition at line 221 of file rmdconst\&.h\&.
.SS "#define SL74   13"

.PP
Definition at line 223 of file rmdconst\&.h\&.
.SS "#define SL75   14"

.PP
Definition at line 225 of file rmdconst\&.h\&.
.SS "#define SL76   11"

.PP
Definition at line 227 of file rmdconst\&.h\&.
.SS "#define SL77   8"

.PP
Definition at line 229 of file rmdconst\&.h\&.
.SS "#define SL78   5"

.PP
Definition at line 231 of file rmdconst\&.h\&.
.SS "#define SL79   6"

.PP
Definition at line 233 of file rmdconst\&.h\&.
.SS "#define SR00   8"

.PP
Definition at line 236 of file rmdconst\&.h\&.
.SS "#define SR01   9"

.PP
Definition at line 238 of file rmdconst\&.h\&.
.SS "#define SR02   9"

.PP
Definition at line 240 of file rmdconst\&.h\&.
.SS "#define SR03   11"

.PP
Definition at line 242 of file rmdconst\&.h\&.
.SS "#define SR04   13"

.PP
Definition at line 244 of file rmdconst\&.h\&.
.SS "#define SR05   15"

.PP
Definition at line 246 of file rmdconst\&.h\&.
.SS "#define SR06   15"

.PP
Definition at line 248 of file rmdconst\&.h\&.
.SS "#define SR07   5"

.PP
Definition at line 250 of file rmdconst\&.h\&.
.SS "#define SR08   7"

.PP
Definition at line 252 of file rmdconst\&.h\&.
.SS "#define SR09   7"

.PP
Definition at line 254 of file rmdconst\&.h\&.
.SS "#define SR10   8"

.PP
Definition at line 256 of file rmdconst\&.h\&.
.SS "#define SR11   11"

.PP
Definition at line 258 of file rmdconst\&.h\&.
.SS "#define SR12   14"

.PP
Definition at line 260 of file rmdconst\&.h\&.
.SS "#define SR13   14"

.PP
Definition at line 262 of file rmdconst\&.h\&.
.SS "#define SR14   12"

.PP
Definition at line 264 of file rmdconst\&.h\&.
.SS "#define SR15   6"

.PP
Definition at line 266 of file rmdconst\&.h\&.
.SS "#define SR16   9"

.PP
Definition at line 269 of file rmdconst\&.h\&.
.SS "#define SR17   13"

.PP
Definition at line 271 of file rmdconst\&.h\&.
.SS "#define SR18   15"

.PP
Definition at line 273 of file rmdconst\&.h\&.
.SS "#define SR19   7"

.PP
Definition at line 275 of file rmdconst\&.h\&.
.SS "#define SR20   12"

.PP
Definition at line 277 of file rmdconst\&.h\&.
.SS "#define SR21   8"

.PP
Definition at line 279 of file rmdconst\&.h\&.
.SS "#define SR22   9"

.PP
Definition at line 281 of file rmdconst\&.h\&.
.SS "#define SR23   11"

.PP
Definition at line 283 of file rmdconst\&.h\&.
.SS "#define SR24   7"

.PP
Definition at line 285 of file rmdconst\&.h\&.
.SS "#define SR25   7"

.PP
Definition at line 287 of file rmdconst\&.h\&.
.SS "#define SR26   12"

.PP
Definition at line 289 of file rmdconst\&.h\&.
.SS "#define SR27   7"

.PP
Definition at line 291 of file rmdconst\&.h\&.
.SS "#define SR28   6"

.PP
Definition at line 293 of file rmdconst\&.h\&.
.SS "#define SR29   15"

.PP
Definition at line 295 of file rmdconst\&.h\&.
.SS "#define SR30   13"

.PP
Definition at line 297 of file rmdconst\&.h\&.
.SS "#define SR31   11"

.PP
Definition at line 299 of file rmdconst\&.h\&.
.SS "#define SR32   9"

.PP
Definition at line 302 of file rmdconst\&.h\&.
.SS "#define SR33   7"

.PP
Definition at line 304 of file rmdconst\&.h\&.
.SS "#define SR34   15"

.PP
Definition at line 306 of file rmdconst\&.h\&.
.SS "#define SR35   11"

.PP
Definition at line 308 of file rmdconst\&.h\&.
.SS "#define SR36   8"

.PP
Definition at line 310 of file rmdconst\&.h\&.
.SS "#define SR37   6"

.PP
Definition at line 312 of file rmdconst\&.h\&.
.SS "#define SR38   6"

.PP
Definition at line 314 of file rmdconst\&.h\&.
.SS "#define SR39   14"

.PP
Definition at line 316 of file rmdconst\&.h\&.
.SS "#define SR40   12"

.PP
Definition at line 318 of file rmdconst\&.h\&.
.SS "#define SR41   13"

.PP
Definition at line 320 of file rmdconst\&.h\&.
.SS "#define SR42   5"

.PP
Definition at line 322 of file rmdconst\&.h\&.
.SS "#define SR43   14"

.PP
Definition at line 324 of file rmdconst\&.h\&.
.SS "#define SR44   13"

.PP
Definition at line 326 of file rmdconst\&.h\&.
.SS "#define SR45   13"

.PP
Definition at line 328 of file rmdconst\&.h\&.
.SS "#define SR46   7"

.PP
Definition at line 330 of file rmdconst\&.h\&.
.SS "#define SR47   5"

.PP
Definition at line 332 of file rmdconst\&.h\&.
.SS "#define SR48   15"

.PP
Definition at line 335 of file rmdconst\&.h\&.
.SS "#define SR49   5"

.PP
Definition at line 337 of file rmdconst\&.h\&.
.SS "#define SR50   8"

.PP
Definition at line 339 of file rmdconst\&.h\&.
.SS "#define SR51   11"

.PP
Definition at line 341 of file rmdconst\&.h\&.
.SS "#define SR52   14"

.PP
Definition at line 343 of file rmdconst\&.h\&.
.SS "#define SR53   14"

.PP
Definition at line 345 of file rmdconst\&.h\&.
.SS "#define SR54   6"

.PP
Definition at line 347 of file rmdconst\&.h\&.
.SS "#define SR55   14"

.PP
Definition at line 349 of file rmdconst\&.h\&.
.SS "#define SR56   6"

.PP
Definition at line 351 of file rmdconst\&.h\&.
.SS "#define SR57   9"

.PP
Definition at line 353 of file rmdconst\&.h\&.
.SS "#define SR58   12"

.PP
Definition at line 355 of file rmdconst\&.h\&.
.SS "#define SR59   9"

.PP
Definition at line 357 of file rmdconst\&.h\&.
.SS "#define SR60   12"

.PP
Definition at line 359 of file rmdconst\&.h\&.
.SS "#define SR61   5"

.PP
Definition at line 361 of file rmdconst\&.h\&.
.SS "#define SR62   15"

.PP
Definition at line 363 of file rmdconst\&.h\&.
.SS "#define SR63   8"

.PP
Definition at line 365 of file rmdconst\&.h\&.
.SS "#define SR64   8"

.PP
Definition at line 368 of file rmdconst\&.h\&.
.SS "#define SR65   5"

.PP
Definition at line 370 of file rmdconst\&.h\&.
.SS "#define SR66   12"

.PP
Definition at line 372 of file rmdconst\&.h\&.
.SS "#define SR67   9"

.PP
Definition at line 374 of file rmdconst\&.h\&.
.SS "#define SR68   12"

.PP
Definition at line 376 of file rmdconst\&.h\&.
.SS "#define SR69   5"

.PP
Definition at line 378 of file rmdconst\&.h\&.
.SS "#define SR70   14"

.PP
Definition at line 380 of file rmdconst\&.h\&.
.SS "#define SR71   6"

.PP
Definition at line 382 of file rmdconst\&.h\&.
.SS "#define SR72   8"

.PP
Definition at line 384 of file rmdconst\&.h\&.
.SS "#define SR73   13"

.PP
Definition at line 386 of file rmdconst\&.h\&.
.SS "#define SR74   6"

.PP
Definition at line 388 of file rmdconst\&.h\&.
.SS "#define SR75   5"

.PP
Definition at line 390 of file rmdconst\&.h\&.
.SS "#define SR76   15"

.PP
Definition at line 392 of file rmdconst\&.h\&.
.SS "#define SR77   13"

.PP
Definition at line 394 of file rmdconst\&.h\&.
.SS "#define SR78   11"

.PP
Definition at line 396 of file rmdconst\&.h\&.
.SS "#define SR79   11"

.PP
Definition at line 398 of file rmdconst\&.h\&.
.SS "#define WL00   0"

.PP
Definition at line 70 of file rmdconst\&.h\&.
.SS "#define WL01   1"

.PP
Definition at line 72 of file rmdconst\&.h\&.
.SS "#define WL02   2"

.PP
Definition at line 74 of file rmdconst\&.h\&.
.SS "#define WL03   3"

.PP
Definition at line 76 of file rmdconst\&.h\&.
.SS "#define WL04   4"

.PP
Definition at line 78 of file rmdconst\&.h\&.
.SS "#define WL05   5"

.PP
Definition at line 80 of file rmdconst\&.h\&.
.SS "#define WL06   6"

.PP
Definition at line 82 of file rmdconst\&.h\&.
.SS "#define WL07   7"

.PP
Definition at line 84 of file rmdconst\&.h\&.
.SS "#define WL08   8"

.PP
Definition at line 86 of file rmdconst\&.h\&.
.SS "#define WL09   9"

.PP
Definition at line 88 of file rmdconst\&.h\&.
.SS "#define WL10   10"

.PP
Definition at line 90 of file rmdconst\&.h\&.
.SS "#define WL11   11"

.PP
Definition at line 92 of file rmdconst\&.h\&.
.SS "#define WL12   12"

.PP
Definition at line 94 of file rmdconst\&.h\&.
.SS "#define WL13   13"

.PP
Definition at line 96 of file rmdconst\&.h\&.
.SS "#define WL14   14"

.PP
Definition at line 98 of file rmdconst\&.h\&.
.SS "#define WL15   15"

.PP
Definition at line 100 of file rmdconst\&.h\&.
.SS "#define WL16   7"

.PP
Definition at line 103 of file rmdconst\&.h\&.
.SS "#define WL17   4"

.PP
Definition at line 105 of file rmdconst\&.h\&.
.SS "#define WL18   13"

.PP
Definition at line 107 of file rmdconst\&.h\&.
.SS "#define WL19   1"

.PP
Definition at line 109 of file rmdconst\&.h\&.
.SS "#define WL20   10"

.PP
Definition at line 111 of file rmdconst\&.h\&.
.SS "#define WL21   6"

.PP
Definition at line 113 of file rmdconst\&.h\&.
.SS "#define WL22   15"

.PP
Definition at line 115 of file rmdconst\&.h\&.
.SS "#define WL23   3"

.PP
Definition at line 117 of file rmdconst\&.h\&.
.SS "#define WL24   12"

.PP
Definition at line 119 of file rmdconst\&.h\&.
.SS "#define WL25   0"

.PP
Definition at line 121 of file rmdconst\&.h\&.
.SS "#define WL26   9"

.PP
Definition at line 123 of file rmdconst\&.h\&.
.SS "#define WL27   5"

.PP
Definition at line 125 of file rmdconst\&.h\&.
.SS "#define WL28   2"

.PP
Definition at line 127 of file rmdconst\&.h\&.
.SS "#define WL29   14"

.PP
Definition at line 129 of file rmdconst\&.h\&.
.SS "#define WL30   11"

.PP
Definition at line 131 of file rmdconst\&.h\&.
.SS "#define WL31   8"

.PP
Definition at line 133 of file rmdconst\&.h\&.
.SS "#define WL32   3"

.PP
Definition at line 136 of file rmdconst\&.h\&.
.SS "#define WL33   10"

.PP
Definition at line 138 of file rmdconst\&.h\&.
.SS "#define WL34   14"

.PP
Definition at line 140 of file rmdconst\&.h\&.
.SS "#define WL35   4"

.PP
Definition at line 142 of file rmdconst\&.h\&.
.SS "#define WL36   9"

.PP
Definition at line 144 of file rmdconst\&.h\&.
.SS "#define WL37   15"

.PP
Definition at line 146 of file rmdconst\&.h\&.
.SS "#define WL38   8"

.PP
Definition at line 148 of file rmdconst\&.h\&.
.SS "#define WL39   1"

.PP
Definition at line 150 of file rmdconst\&.h\&.
.SS "#define WL40   2"

.PP
Definition at line 152 of file rmdconst\&.h\&.
.SS "#define WL41   7"

.PP
Definition at line 154 of file rmdconst\&.h\&.
.SS "#define WL42   0"

.PP
Definition at line 156 of file rmdconst\&.h\&.
.SS "#define WL43   6"

.PP
Definition at line 158 of file rmdconst\&.h\&.
.SS "#define WL44   13"

.PP
Definition at line 160 of file rmdconst\&.h\&.
.SS "#define WL45   11"

.PP
Definition at line 162 of file rmdconst\&.h\&.
.SS "#define WL46   5"

.PP
Definition at line 164 of file rmdconst\&.h\&.
.SS "#define WL47   12"

.PP
Definition at line 166 of file rmdconst\&.h\&.
.SS "#define WL48   1"

.PP
Definition at line 169 of file rmdconst\&.h\&.
.SS "#define WL49   9"

.PP
Definition at line 171 of file rmdconst\&.h\&.
.SS "#define WL50   11"

.PP
Definition at line 173 of file rmdconst\&.h\&.
.SS "#define WL51   10"

.PP
Definition at line 175 of file rmdconst\&.h\&.
.SS "#define WL52   0"

.PP
Definition at line 177 of file rmdconst\&.h\&.
.SS "#define WL53   8"

.PP
Definition at line 179 of file rmdconst\&.h\&.
.SS "#define WL54   12"

.PP
Definition at line 181 of file rmdconst\&.h\&.
.SS "#define WL55   4"

.PP
Definition at line 183 of file rmdconst\&.h\&.
.SS "#define WL56   13"

.PP
Definition at line 185 of file rmdconst\&.h\&.
.SS "#define WL57   3"

.PP
Definition at line 187 of file rmdconst\&.h\&.
.SS "#define WL58   7"

.PP
Definition at line 189 of file rmdconst\&.h\&.
.SS "#define WL59   15"

.PP
Definition at line 191 of file rmdconst\&.h\&.
.SS "#define WL60   14"

.PP
Definition at line 193 of file rmdconst\&.h\&.
.SS "#define WL61   5"

.PP
Definition at line 195 of file rmdconst\&.h\&.
.SS "#define WL62   6"

.PP
Definition at line 197 of file rmdconst\&.h\&.
.SS "#define WL63   2"

.PP
Definition at line 199 of file rmdconst\&.h\&.
.SS "#define WL64   4"

.PP
Definition at line 202 of file rmdconst\&.h\&.
.SS "#define WL65   0"

.PP
Definition at line 204 of file rmdconst\&.h\&.
.SS "#define WL66   5"

.PP
Definition at line 206 of file rmdconst\&.h\&.
.SS "#define WL67   9"

.PP
Definition at line 208 of file rmdconst\&.h\&.
.SS "#define WL68   7"

.PP
Definition at line 210 of file rmdconst\&.h\&.
.SS "#define WL69   12"

.PP
Definition at line 212 of file rmdconst\&.h\&.
.SS "#define WL70   2"

.PP
Definition at line 214 of file rmdconst\&.h\&.
.SS "#define WL71   10"

.PP
Definition at line 216 of file rmdconst\&.h\&.
.SS "#define WL72   14"

.PP
Definition at line 218 of file rmdconst\&.h\&.
.SS "#define WL73   1"

.PP
Definition at line 220 of file rmdconst\&.h\&.
.SS "#define WL74   3"

.PP
Definition at line 222 of file rmdconst\&.h\&.
.SS "#define WL75   8"

.PP
Definition at line 224 of file rmdconst\&.h\&.
.SS "#define WL76   11"

.PP
Definition at line 226 of file rmdconst\&.h\&.
.SS "#define WL77   6"

.PP
Definition at line 228 of file rmdconst\&.h\&.
.SS "#define WL78   15"

.PP
Definition at line 230 of file rmdconst\&.h\&.
.SS "#define WL79   13"

.PP
Definition at line 232 of file rmdconst\&.h\&.
.SS "#define WR00   5"

.PP
Definition at line 235 of file rmdconst\&.h\&.
.SS "#define WR01   14"

.PP
Definition at line 237 of file rmdconst\&.h\&.
.SS "#define WR02   7"

.PP
Definition at line 239 of file rmdconst\&.h\&.
.SS "#define WR03   0"

.PP
Definition at line 241 of file rmdconst\&.h\&.
.SS "#define WR04   9"

.PP
Definition at line 243 of file rmdconst\&.h\&.
.SS "#define WR05   2"

.PP
Definition at line 245 of file rmdconst\&.h\&.
.SS "#define WR06   11"

.PP
Definition at line 247 of file rmdconst\&.h\&.
.SS "#define WR07   4"

.PP
Definition at line 249 of file rmdconst\&.h\&.
.SS "#define WR08   13"

.PP
Definition at line 251 of file rmdconst\&.h\&.
.SS "#define WR09   6"

.PP
Definition at line 253 of file rmdconst\&.h\&.
.SS "#define WR10   15"

.PP
Definition at line 255 of file rmdconst\&.h\&.
.SS "#define WR11   8"

.PP
Definition at line 257 of file rmdconst\&.h\&.
.SS "#define WR12   1"

.PP
Definition at line 259 of file rmdconst\&.h\&.
.SS "#define WR13   10"

.PP
Definition at line 261 of file rmdconst\&.h\&.
.SS "#define WR14   3"

.PP
Definition at line 263 of file rmdconst\&.h\&.
.SS "#define WR15   12"

.PP
Definition at line 265 of file rmdconst\&.h\&.
.SS "#define WR16   6"

.PP
Definition at line 268 of file rmdconst\&.h\&.
.SS "#define WR17   11"

.PP
Definition at line 270 of file rmdconst\&.h\&.
.SS "#define WR18   3"

.PP
Definition at line 272 of file rmdconst\&.h\&.
.SS "#define WR19   7"

.PP
Definition at line 274 of file rmdconst\&.h\&.
.SS "#define WR20   0"

.PP
Definition at line 276 of file rmdconst\&.h\&.
.SS "#define WR21   13"

.PP
Definition at line 278 of file rmdconst\&.h\&.
.SS "#define WR22   5"

.PP
Definition at line 280 of file rmdconst\&.h\&.
.SS "#define WR23   10"

.PP
Definition at line 282 of file rmdconst\&.h\&.
.SS "#define WR24   14"

.PP
Definition at line 284 of file rmdconst\&.h\&.
.SS "#define WR25   15"

.PP
Definition at line 286 of file rmdconst\&.h\&.
.SS "#define WR26   8"

.PP
Definition at line 288 of file rmdconst\&.h\&.
.SS "#define WR27   12"

.PP
Definition at line 290 of file rmdconst\&.h\&.
.SS "#define WR28   4"

.PP
Definition at line 292 of file rmdconst\&.h\&.
.SS "#define WR29   9"

.PP
Definition at line 294 of file rmdconst\&.h\&.
.SS "#define WR30   1"

.PP
Definition at line 296 of file rmdconst\&.h\&.
.SS "#define WR31   2"

.PP
Definition at line 298 of file rmdconst\&.h\&.
.SS "#define WR32   15"

.PP
Definition at line 301 of file rmdconst\&.h\&.
.SS "#define WR33   5"

.PP
Definition at line 303 of file rmdconst\&.h\&.
.SS "#define WR34   1"

.PP
Definition at line 305 of file rmdconst\&.h\&.
.SS "#define WR35   3"

.PP
Definition at line 307 of file rmdconst\&.h\&.
.SS "#define WR36   7"

.PP
Definition at line 309 of file rmdconst\&.h\&.
.SS "#define WR37   14"

.PP
Definition at line 311 of file rmdconst\&.h\&.
.SS "#define WR38   6"

.PP
Definition at line 313 of file rmdconst\&.h\&.
.SS "#define WR39   9"

.PP
Definition at line 315 of file rmdconst\&.h\&.
.SS "#define WR40   11"

.PP
Definition at line 317 of file rmdconst\&.h\&.
.SS "#define WR41   8"

.PP
Definition at line 319 of file rmdconst\&.h\&.
.SS "#define WR42   12"

.PP
Definition at line 321 of file rmdconst\&.h\&.
.SS "#define WR43   2"

.PP
Definition at line 323 of file rmdconst\&.h\&.
.SS "#define WR44   10"

.PP
Definition at line 325 of file rmdconst\&.h\&.
.SS "#define WR45   0"

.PP
Definition at line 327 of file rmdconst\&.h\&.
.SS "#define WR46   4"

.PP
Definition at line 329 of file rmdconst\&.h\&.
.SS "#define WR47   13"

.PP
Definition at line 331 of file rmdconst\&.h\&.
.SS "#define WR48   8"

.PP
Definition at line 334 of file rmdconst\&.h\&.
.SS "#define WR49   6"

.PP
Definition at line 336 of file rmdconst\&.h\&.
.SS "#define WR50   4"

.PP
Definition at line 338 of file rmdconst\&.h\&.
.SS "#define WR51   1"

.PP
Definition at line 340 of file rmdconst\&.h\&.
.SS "#define WR52   3"

.PP
Definition at line 342 of file rmdconst\&.h\&.
.SS "#define WR53   11"

.PP
Definition at line 344 of file rmdconst\&.h\&.
.SS "#define WR54   15"

.PP
Definition at line 346 of file rmdconst\&.h\&.
.SS "#define WR55   0"

.PP
Definition at line 348 of file rmdconst\&.h\&.
.SS "#define WR56   5"

.PP
Definition at line 350 of file rmdconst\&.h\&.
.SS "#define WR57   12"

.PP
Definition at line 352 of file rmdconst\&.h\&.
.SS "#define WR58   2"

.PP
Definition at line 354 of file rmdconst\&.h\&.
.SS "#define WR59   13"

.PP
Definition at line 356 of file rmdconst\&.h\&.
.SS "#define WR60   9"

.PP
Definition at line 358 of file rmdconst\&.h\&.
.SS "#define WR61   7"

.PP
Definition at line 360 of file rmdconst\&.h\&.
.SS "#define WR62   10"

.PP
Definition at line 362 of file rmdconst\&.h\&.
.SS "#define WR63   14"

.PP
Definition at line 364 of file rmdconst\&.h\&.
.SS "#define WR64   12"

.PP
Definition at line 367 of file rmdconst\&.h\&.
.SS "#define WR65   15"

.PP
Definition at line 369 of file rmdconst\&.h\&.
.SS "#define WR66   10"

.PP
Definition at line 371 of file rmdconst\&.h\&.
.SS "#define WR67   4"

.PP
Definition at line 373 of file rmdconst\&.h\&.
.SS "#define WR68   1"

.PP
Definition at line 375 of file rmdconst\&.h\&.
.SS "#define WR69   5"

.PP
Definition at line 377 of file rmdconst\&.h\&.
.SS "#define WR70   8"

.PP
Definition at line 379 of file rmdconst\&.h\&.
.SS "#define WR71   7"

.PP
Definition at line 381 of file rmdconst\&.h\&.
.SS "#define WR72   6"

.PP
Definition at line 383 of file rmdconst\&.h\&.
.SS "#define WR73   2"

.PP
Definition at line 385 of file rmdconst\&.h\&.
.SS "#define WR74   13"

.PP
Definition at line 387 of file rmdconst\&.h\&.
.SS "#define WR75   14"

.PP
Definition at line 389 of file rmdconst\&.h\&.
.SS "#define WR76   0"

.PP
Definition at line 391 of file rmdconst\&.h\&.
.SS "#define WR77   3"

.PP
Definition at line 393 of file rmdconst\&.h\&.
.SS "#define WR78   9"

.PP
Definition at line 395 of file rmdconst\&.h\&.
.SS "#define WR79   11"

.PP
Definition at line 397 of file rmdconst\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
