.TH "s2n/stuffer/s2n_stuffer_text.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/stuffer/s2n_stuffer_text.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'stuffer/s2n_stuffer\&.h'\fP
.br
\fC#include 'utils/s2n_safety\&.h'\fP
.br
\fC#include 'utils/s2n_mem\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBs2n_stuffer_peek_char\fP (struct \fBs2n_stuffer\fP *\fBs2n_stuffer\fP, char *\fBc\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_skip_whitespace\fP (struct \fBs2n_stuffer\fP *\fBs2n_stuffer\fP)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_read_token\fP (struct \fBs2n_stuffer\fP *stuffer, struct \fBs2n_stuffer\fP *token, char delim)"
.br
.ti -1c
.RI "int \fBs2n_stuffer_alloc_ro_from_string\fP (struct \fBs2n_stuffer\fP *stuffer, const char *str)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int s2n_stuffer_alloc_ro_from_string (struct \fBs2n_stuffer\fP * stuffer, const char * str)"

.PP
Definition at line 74 of file s2n_stuffer_text\&.c\&.
.SS "int s2n_stuffer_peek_char (struct \fBs2n_stuffer\fP * s2n_stuffer, char * c)"

.PP
Definition at line 23 of file s2n_stuffer_text\&.c\&.
.SS "int s2n_stuffer_read_token (struct \fBs2n_stuffer\fP * stuffer, struct \fBs2n_stuffer\fP * token, char delim)"

.PP
Definition at line 52 of file s2n_stuffer_text\&.c\&.
.SS "int s2n_stuffer_skip_whitespace (struct \fBs2n_stuffer\fP * s2n_stuffer)"

.PP
Definition at line 32 of file s2n_stuffer_text\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
