.TH "s2n/libcrypto-build/openssl/ssl/s3_both.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ssl/s3_both.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <limits\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'ssl_locl\&.h'\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/rand\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBssl3_do_write\fP (\fBSSL\fP *s, int \fBtype\fP)"
.br
.ti -1c
.RI "int \fBssl3_send_finished\fP (\fBSSL\fP *s, int \fBa\fP, int \fBb\fP, const char *sender, int slen)"
.br
.ti -1c
.RI "int \fBssl3_get_finished\fP (\fBSSL\fP *s, int \fBa\fP, int \fBb\fP)"
.br
.ti -1c
.RI "int \fBssl3_send_change_cipher_spec\fP (\fBSSL\fP *s, int \fBa\fP, int \fBb\fP)"
.br
.ti -1c
.RI "unsigned long \fBssl3_output_cert_chain\fP (\fBSSL\fP *s, \fBCERT_PKEY\fP *cpk)"
.br
.ti -1c
.RI "long \fBssl3_get_message\fP (\fBSSL\fP *s, int st1, int stn, int mt, long \fBmax\fP, int *ok)"
.br
.ti -1c
.RI "int \fBssl_cert_type\fP (\fBX509\fP *\fBx\fP, \fBEVP_PKEY\fP *pkey)"
.br
.ti -1c
.RI "int \fBssl_verify_alarm_type\fP (long \fBtype\fP)"
.br
.ti -1c
.RI "int \fBssl3_setup_read_buffer\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "int \fBssl3_setup_write_buffer\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "int \fBssl3_setup_buffers\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "int \fBssl3_release_write_buffer\fP (\fBSSL\fP *s)"
.br
.ti -1c
.RI "int \fBssl3_release_read_buffer\fP (\fBSSL\fP *s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int ssl3_do_write (\fBSSL\fP * s, int type)"

.PP
Definition at line 131 of file s3_both\&.c\&.
.SS "int ssl3_get_finished (\fBSSL\fP * s, int a, int b)"

.PP
Definition at line 235 of file s3_both\&.c\&.
.SS "long ssl3_get_message (\fBSSL\fP * s, int st1, int stn, int mt, long max, int * ok)"

.PP
Definition at line 343 of file s3_both\&.c\&.
.SS "unsigned long ssl3_output_cert_chain (\fBSSL\fP * s, \fBCERT_PKEY\fP * cpk)"

.PP
Definition at line 322 of file s3_both\&.c\&.
.SS "int ssl3_release_read_buffer (\fBSSL\fP * s)"

.PP
Definition at line 746 of file s3_both\&.c\&.
.SS "int ssl3_release_write_buffer (\fBSSL\fP * s)"

.PP
Definition at line 737 of file s3_both\&.c\&.
.SS "int ssl3_send_change_cipher_spec (\fBSSL\fP * s, int a, int b)"

.PP
Definition at line 305 of file s3_both\&.c\&.
.SS "int ssl3_send_finished (\fBSSL\fP * s, int a, int b, const char * sender, int slen)"

.PP
Definition at line 159 of file s3_both\&.c\&.
.SS "int ssl3_setup_buffers (\fBSSL\fP * s)"

.PP
Definition at line 728 of file s3_both\&.c\&.
.SS "int ssl3_setup_read_buffer (\fBSSL\fP * s)"

.PP
Definition at line 652 of file s3_both\&.c\&.
.SS "int ssl3_setup_write_buffer (\fBSSL\fP * s)"

.PP
Definition at line 691 of file s3_both\&.c\&.
.SS "int ssl_cert_type (\fBX509\fP * x, \fBEVP_PKEY\fP * pkey)"

.PP
Definition at line 472 of file s3_both\&.c\&.
.SS "int ssl_verify_alarm_type (long type)"

.PP
Definition at line 517 of file s3_both\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
