.TH "s2n/libcrypto-build/openssl/crypto/seed/seed_ofb.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/seed/seed_ofb.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/seed\&.h>\fP
.br
\fC#include <openssl/modes\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBSEED_ofb128_encrypt\fP (const unsigned char *\fBin\fP, unsigned char *\fBout\fP, size_t \fBlen\fP, const \fBSEED_KEY_SCHEDULE\fP *ks, unsigned char ivec[\fBSEED_BLOCK_SIZE\fP], int *\fBnum\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP SEED_ofb128_encrypt (const unsigned char * in, unsigned char * out, size_t len, const \fBSEED_KEY_SCHEDULE\fP * ks, unsigned char ivec[SEED_BLOCK_SIZE], int * num)"

.PP
Definition at line 111 of file seed_ofb\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
