.TH "s2n/libcrypto-build/openssl/demos/tunala/sm.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/demos/tunala/sm.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tunala\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBstate_machine_init\fP (\fBstate_machine_t\fP *machine)"
.br
.ti -1c
.RI "\fBvoid\fP \fBstate_machine_close\fP (\fBstate_machine_t\fP *machine)"
.br
.ti -1c
.RI "\fBbuffer_t\fP * \fBstate_machine_get_buffer\fP (\fBstate_machine_t\fP *machine, \fBsm_buffer_t\fP \fBtype\fP)"
.br
.ti -1c
.RI "\fBSSL\fP * \fBstate_machine_get_SSL\fP (\fBstate_machine_t\fP *machine)"
.br
.ti -1c
.RI "int \fBstate_machine_set_SSL\fP (\fBstate_machine_t\fP *machine, \fBSSL\fP *\fBssl\fP, int is_server)"
.br
.ti -1c
.RI "int \fBstate_machine_churn\fP (\fBstate_machine_t\fP *machine)"
.br
.ti -1c
.RI "int \fBstate_machine_close_clean\fP (\fBstate_machine_t\fP *machine)"
.br
.ti -1c
.RI "int \fBstate_machine_close_dirty\fP (\fBstate_machine_t\fP *machine)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int state_machine_churn (\fBstate_machine_t\fP * machine)"

.PP
Definition at line 87 of file sm\&.c\&.
.SS "\fBvoid\fP state_machine_close (\fBstate_machine_t\fP * machine)"

.PP
Definition at line 15 of file sm\&.c\&.
.SS "int state_machine_close_clean (\fBstate_machine_t\fP * machine)"

.PP
Definition at line 127 of file sm\&.c\&.
.SS "int state_machine_close_dirty (\fBstate_machine_t\fP * machine)"

.PP
Definition at line 150 of file sm\&.c\&.
.SS "\fBbuffer_t\fP* state_machine_get_buffer (\fBstate_machine_t\fP * machine, \fBsm_buffer_t\fP type)"

.PP
Definition at line 36 of file sm\&.c\&.
.SS "\fBSSL\fP* state_machine_get_SSL (\fBstate_machine_t\fP * machine)"

.PP
Definition at line 56 of file sm\&.c\&.
.SS "\fBvoid\fP state_machine_init (\fBstate_machine_t\fP * machine)"

.PP
Definition at line 5 of file sm\&.c\&.
.SS "int state_machine_set_SSL (\fBstate_machine_t\fP * machine, \fBSSL\fP * ssl, int is_server)"

.PP
Definition at line 61 of file sm\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
