.TH "s2n/libcrypto-build/openssl/apps/smime.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/apps/smime.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'apps\&.h'\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/pem\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <openssl/x509_vfy\&.h>\fP
.br
\fC#include <openssl/x509v3\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPROG\fP   \fBsmime_main\fP"
.br
.ti -1c
.RI "#define \fBSMIME_OP\fP   0x10"
.br
.ti -1c
.RI "#define \fBSMIME_IP\fP   0x20"
.br
.ti -1c
.RI "#define \fBSMIME_SIGNERS\fP   0x40"
.br
.ti -1c
.RI "#define \fBSMIME_ENCRYPT\fP   (1 | \fBSMIME_OP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_DECRYPT\fP   (2 | \fBSMIME_IP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_SIGN\fP   (3 | \fBSMIME_OP\fP | \fBSMIME_SIGNERS\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_VERIFY\fP   (4 | \fBSMIME_IP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_PK7OUT\fP   (5 | \fBSMIME_IP\fP | \fBSMIME_OP\fP)"
.br
.ti -1c
.RI "#define \fBSMIME_RESIGN\fP   (6 | \fBSMIME_IP\fP | \fBSMIME_OP\fP | \fBSMIME_SIGNERS\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBMAIN\fP (int, char **)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PROG   \fBsmime_main\fP"

.PP
Definition at line 72 of file smime\&.c\&.
.SS "#define SMIME_DECRYPT   (2 | \fBSMIME_IP\fP)"

.PP
Definition at line 80 of file smime\&.c\&.
.SS "#define SMIME_ENCRYPT   (1 | \fBSMIME_OP\fP)"

.PP
Definition at line 79 of file smime\&.c\&.
.SS "#define SMIME_IP   0x20"

.PP
Definition at line 77 of file smime\&.c\&.
.SS "#define SMIME_OP   0x10"

.PP
Definition at line 76 of file smime\&.c\&.
.SS "#define SMIME_PK7OUT   (5 | \fBSMIME_IP\fP | \fBSMIME_OP\fP)"

.PP
Definition at line 83 of file smime\&.c\&.
.SS "#define SMIME_RESIGN   (6 | \fBSMIME_IP\fP | \fBSMIME_OP\fP | \fBSMIME_SIGNERS\fP)"

.PP
Definition at line 84 of file smime\&.c\&.
.SS "#define SMIME_SIGN   (3 | \fBSMIME_OP\fP | \fBSMIME_SIGNERS\fP)"

.PP
Definition at line 81 of file smime\&.c\&.
.SS "#define SMIME_SIGNERS   0x40"

.PP
Definition at line 78 of file smime\&.c\&.
.SS "#define SMIME_VERIFY   (4 | \fBSMIME_IP\fP)"

.PP
Definition at line 82 of file smime\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int MAIN (int argc, char ** argv)"

.PP
Definition at line 88 of file smime\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
