.TH "s2n/libcrypto-build/openssl/crypto/des/speed.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/des/speed.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <openssl/e_os2\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/times\&.h>\fP
.br
\fC#include <openssl/des\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIMES\fP"
.br
.ti -1c
.RI "#define \fBcrypt\fP(\fBc\fP,  s)   (des_crypt((\fBc\fP),(s)))"
.br
.ti -1c
.RI "#define \fBHZ\fP   100\&.0"
.br
.ti -1c
.RI "#define \fBBUFSIZE\fP   ((long)1024)"
.br
.ti -1c
.RI "#define \fBSTART\fP   0"
.br
.ti -1c
.RI "#define \fBSTOP\fP   1"
.br
.ti -1c
.RI "#define \fBCOND\fP(d)   (count != (d))"
.br
.ti -1c
.RI "#define \fBCOUNT\fP(d)   (d)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBTime_F\fP (int s)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "long \fBrun\fP = 0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BUFSIZE   ((long)1024)"

.PP
Definition at line 112 of file speed\&.c\&.
.SS "#define COND(d)   (count != (d))"

.SS "#define COUNT(d)   (d)"

.SS "#define crypt(\fBc\fP, s)   (des_crypt((\fBc\fP),(s)))"

.PP
Definition at line 73 of file speed\&.c\&.
.SS "#define HZ   100\&.0"

.PP
Definition at line 104 of file speed\&.c\&.
.SS "#define START   0"

.PP
Definition at line 134 of file speed\&.c\&.
.SS "#define STOP   1"

.PP
Definition at line 135 of file speed\&.c\&.
.SS "#define TIMES"

.PP
Definition at line 63 of file speed\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 167 of file speed\&.c\&.
.SS "double Time_F (int s)"

.PP
Definition at line 137 of file speed\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "long run = 0"

.PP
Definition at line 113 of file speed\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
