.TH "SRP_VBASE_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SRP_VBASE_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <srp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBSRP_user_pwd\fP)*users_pwd"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBSRP_gN_cache\fP)*gN_cache"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBSRP_user_pwd\fP)*users_pwd"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBSRP_gN_cache\fP)*gN_cache"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBSRP_user_pwd\fP)*users_pwd"
.br
.ti -1c
.RI "\fBSTACK_OF\fP (\fBSRP_gN_cache\fP)*gN_cache"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBseed_key\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBdefault_g\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBdefault_N\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 100 of file srp\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBSRP_user_pwd\fP)"

.SS "STACK_OF (\fBSRP_user_pwd\fP)"

.SS "STACK_OF (\fBSRP_user_pwd\fP)"

.SS "STACK_OF (\fBSRP_gN_cache\fP)"

.SS "STACK_OF (\fBSRP_gN_cache\fP)"

.SS "STACK_OF (\fBSRP_gN_cache\fP)"

.SH "Field Documentation"
.PP 
.SS "\fBBIGNUM\fP * default_g"

.PP
Definition at line 105 of file srp\&.h\&.
.SS "\fBBIGNUM\fP * default_N"

.PP
Definition at line 106 of file srp\&.h\&.
.SS "char * seed_key"

.PP
Definition at line 104 of file srp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
