.TH "srp_ctx_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srp_ctx_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ssl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBSRP_cb_arg\fP"
.br
.ti -1c
.RI "int(* \fBTLS_ext_srp_username_callback\fP )(\fBSSL\fP *, int *, \fBvoid\fP *)"
.br
.ti -1c
.RI "int(* \fBSRP_verify_param_callback\fP )(\fBSSL\fP *, \fBvoid\fP *)"
.br
.ti -1c
.RI "char *(* \fBSRP_give_srp_client_pwd_callback\fP )(\fBSSL\fP *, \fBvoid\fP *)"
.br
.ti -1c
.RI "char * \fBlogin\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBN\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBg\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBs\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBB\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBA\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBa\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBb\fP"
.br
.ti -1c
.RI "\fBBIGNUM\fP * \fBv\fP"
.br
.ti -1c
.RI "char * \fBinfo\fP"
.br
.ti -1c
.RI "int \fBstrength\fP"
.br
.ti -1c
.RI "unsigned long \fBsrp_Mask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 849 of file ssl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBBIGNUM\fP * A"

.PP
Definition at line 859 of file ssl\&.h\&.
.SS "\fBBIGNUM\fP * a"

.PP
Definition at line 860 of file ssl\&.h\&.
.SS "\fBBIGNUM\fP * B"

.PP
Definition at line 859 of file ssl\&.h\&.
.SS "\fBBIGNUM\fP * b"

.PP
Definition at line 860 of file ssl\&.h\&.
.SS "\fBBIGNUM\fP * g"

.PP
Definition at line 859 of file ssl\&.h\&.
.SS "char * info"

.PP
Definition at line 861 of file ssl\&.h\&.
.SS "char * login"

.PP
Definition at line 858 of file ssl\&.h\&.
.SS "\fBBIGNUM\fP * N"

.PP
Definition at line 859 of file ssl\&.h\&.
.SS "\fBBIGNUM\fP * s"

.PP
Definition at line 859 of file ssl\&.h\&.
.SS "\fBvoid\fP * SRP_cb_arg"

.PP
Definition at line 851 of file ssl\&.h\&.
.SS "char *(* SRP_give_srp_client_pwd_callback)(\fBSSL\fP *, \fBvoid\fP *)"

.PP
Definition at line 857 of file ssl\&.h\&.
.SS "unsigned long srp_Mask"

.PP
Definition at line 863 of file ssl\&.h\&.
.SS "int(* SRP_verify_param_callback)(\fBSSL\fP *, \fBvoid\fP *)"

.PP
Definition at line 855 of file ssl\&.h\&.
.SS "int strength"

.PP
Definition at line 862 of file ssl\&.h\&.
.SS "int(* TLS_ext_srp_username_callback)(\fBSSL\fP *, int *, \fBvoid\fP *)"

.PP
Definition at line 853 of file ssl\&.h\&.
.SS "\fBBIGNUM\fP * v"

.PP
Definition at line 860 of file ssl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
