.TH "s2n/libcrypto-build/openssl/ssl/ssl_utst.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ssl/ssl_utst.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ssl_locl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const struct \fBopenssl_ssl_test_functions\fP * \fBSSL_test_functions\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const struct \fBopenssl_ssl_test_functions\fP* SSL_test_functions (\fBvoid\fP)"

.PP
Definition at line 67 of file ssl_utst\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
