.TH "stack_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stack_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stack\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "char ** \fBdata\fP"
.br
.ti -1c
.RI "int \fBsorted\fP"
.br
.ti -1c
.RI "int \fBnum_alloc\fP"
.br
.ti -1c
.RI "int(* \fBcomp\fP )(const \fBvoid\fP *, const \fBvoid\fP *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 66 of file stack\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int(* comp)(const \fBvoid\fP *, const \fBvoid\fP *)"

.PP
Definition at line 71 of file stack\&.h\&.
.SS "char ** data"

.PP
Definition at line 68 of file stack\&.h\&.
.SS "int num"

.PP
Definition at line 67 of file stack\&.h\&.
.SS "int num_alloc"

.PP
Definition at line 70 of file stack\&.h\&.
.SS "int sorted"

.PP
Definition at line 69 of file stack\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
