.TH "s2n/libcrypto-build/openssl/engines/vendor_defns/sureware.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/engines/vendor_defns/sureware.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSW_EXPORT\fP"
.br
.ti -1c
.RI "#define \fBSUREWAREHOOK_ERROR_FAILED\fP   \-1"
.br
.ti -1c
.RI "#define \fBSUREWAREHOOK_ERROR_FALLBACK\fP   \-2"
.br
.ti -1c
.RI "#define \fBSUREWAREHOOK_ERROR_UNIT_FAILURE\fP   \-3"
.br
.ti -1c
.RI "#define \fBSUREWAREHOOK_ERROR_DATA_SIZE\fP   \-4"
.br
.ti -1c
.RI "#define \fBSUREWAREHOOK_ERROR_INVALID_PAD\fP   \-5"
.br
.ti -1c
.RI "#define \fBSUREWARE_PKCS1_PAD\fP   1"
.br
.ti -1c
.RI "#define \fBSUREWARE_ISO9796_PAD\fP   2"
.br
.ti -1c
.RI "#define \fBSUREWARE_NO_PAD\fP   0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBSureWareHook_Init_t\fP(char *const msg, int threadsafe)"
.br
.ti -1c
.RI "typedef \fBvoid\fP \fBSureWareHook_Finish_t\fP(\fBvoid\fP)"
.br
.ti -1c
.RI "typedef int \fBSureWareHook_Rand_Bytes_t\fP(char *const msg, unsigned char *buf, int \fBnum\fP)"
.br
.ti -1c
.RI "typedef int \fBSureWareHook_Rand_Seed_t\fP(char *const msg, const \fBvoid\fP *buf, int \fBnum\fP)"
.br
.ti -1c
.RI "typedef int \fBSureWareHook_Load_Privkey_t\fP(char *const msg, const char *key_id, char **hptr, unsigned long *\fBnum\fP, char *keytype)"
.br
.ti -1c
.RI "typedef int \fBSureWareHook_Info_Pubkey_t\fP(char *const msg, const char *key_id, unsigned long *\fBnum\fP, char *keytype)"
.br
.ti -1c
.RI "typedef int \fBSureWareHook_Load_Rsa_Pubkey_t\fP(char *const msg, const char *key_id, unsigned long \fBnum\fP, unsigned long *n, unsigned long *\fBe\fP)"
.br
.ti -1c
.RI "typedef int \fBSureWareHook_Load_Dsa_Pubkey_t\fP(char *const msg, const char *key_id, unsigned long \fBnum\fP, unsigned long *pub, unsigned long *\fBp\fP, unsigned long *\fBq\fP, unsigned long *g)"
.br
.ti -1c
.RI "typedef \fBvoid\fP \fBSureWareHook_Free_t\fP(char *\fBp\fP, int destroy)"
.br
.ti -1c
.RI "typedef int \fBSureWareHook_Rsa_Priv_Dec_t\fP(char *const msg, int flen, unsigned char *from, int *tlen, unsigned char *to, char *prsa, int padding)"
.br
.ti -1c
.RI "typedef int \fBSureWareHook_Rsa_Sign_t\fP(char *const msg, int flen, unsigned char *from, int *tlen, unsigned char *to, char *prsa, int padding)"
.br
.ti -1c
.RI "typedef int \fBSureWareHook_Dsa_Sign_t\fP(char *const msg, int flen, const unsigned char *from, unsigned long *r, unsigned long *s, char *pdsa)"
.br
.ti -1c
.RI "typedef int \fBSureWareHook_Mod_Exp_t\fP(char *const msg, int mlen, const unsigned long *mod, int elen, const unsigned long *exponent, int dlen, unsigned long *\fBdata\fP, unsigned long *res)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Init_t\fP \fBSureWareHook_Init\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Finish_t\fP \fBSureWareHook_Finish\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Rand_Bytes_t\fP \fBSureWareHook_Rand_Bytes\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Rand_Seed_t\fP \fBSureWareHook_Rand_Seed\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Load_Privkey_t\fP \fBSureWareHook_Load_Privkey\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Info_Pubkey_t\fP \fBSureWareHook_Info_Pubkey\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Load_Rsa_Pubkey_t\fP \fBSureWareHook_Load_Rsa_Pubkey\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Load_Dsa_Pubkey_t\fP \fBSureWareHook_Load_Dsa_Pubkey\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Free_t\fP \fBSureWareHook_Free\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Rsa_Priv_Dec_t\fP \fBSureWareHook_Rsa_Priv_Dec\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Rsa_Sign_t\fP \fBSureWareHook_Rsa_Sign\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Dsa_Sign_t\fP \fBSureWareHook_Dsa_Sign\fP"
.br
.ti -1c
.RI "\fBSW_EXPORT\fP \fBSureWareHook_Mod_Exp_t\fP \fBSureWareHook_Mod_Exp\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SUREWARE_ISO9796_PAD   2"

.PP
Definition at line 169 of file sureware\&.h\&.
.SS "#define SUREWARE_NO_PAD   0"

.PP
Definition at line 170 of file sureware\&.h\&.
.SS "#define SUREWARE_PKCS1_PAD   1"

.PP
Definition at line 168 of file sureware\&.h\&.
.SS "#define SUREWAREHOOK_ERROR_DATA_SIZE   \-4"

.PP
Definition at line 31 of file sureware\&.h\&.
.SS "#define SUREWAREHOOK_ERROR_FAILED   \-1"

.PP
Definition at line 28 of file sureware\&.h\&.
.SS "#define SUREWAREHOOK_ERROR_FALLBACK   \-2"

.PP
Definition at line 29 of file sureware\&.h\&.
.SS "#define SUREWAREHOOK_ERROR_INVALID_PAD   \-5"

.PP
Definition at line 32 of file sureware\&.h\&.
.SS "#define SUREWAREHOOK_ERROR_UNIT_FAILURE   \-3"

.PP
Definition at line 30 of file sureware\&.h\&.
.SS "#define SW_EXPORT"

.PP
Definition at line 22 of file sureware\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef int SureWareHook_Dsa_Sign_t(char *const msg, int flen, const unsigned char *from, unsigned long *r, unsigned long *s, char *pdsa)"

.PP
Definition at line 228 of file sureware\&.h\&.
.SS "typedef \fBvoid\fP SureWareHook_Finish_t(\fBvoid\fP)"

.PP
Definition at line 49 of file sureware\&.h\&.
.SS "typedef \fBvoid\fP SureWareHook_Free_t(char *\fBp\fP, int destroy)"

.PP
Definition at line 165 of file sureware\&.h\&.
.SS "typedef int SureWareHook_Info_Pubkey_t(char *const msg, const char *key_id, unsigned long *\fBnum\fP, char *keytype)"

.PP
Definition at line 116 of file sureware\&.h\&.
.SS "typedef int SureWareHook_Init_t(char *const msg, int threadsafe)"

.PP
Definition at line 44 of file sureware\&.h\&.
.SS "typedef int SureWareHook_Load_Dsa_Pubkey_t(char *const msg, const char *key_id, unsigned long \fBnum\fP, unsigned long *pub, unsigned long *\fBp\fP, unsigned long *\fBq\fP, unsigned long *g)"

.PP
Definition at line 153 of file sureware\&.h\&.
.SS "typedef int SureWareHook_Load_Privkey_t(char *const msg, const char *key_id, char **hptr, unsigned long *\fBnum\fP, char *keytype)"

.PP
Definition at line 99 of file sureware\&.h\&.
.SS "typedef int SureWareHook_Load_Rsa_Pubkey_t(char *const msg, const char *key_id, unsigned long \fBnum\fP, unsigned long *n, unsigned long *\fBe\fP)"

.PP
Definition at line 132 of file sureware\&.h\&.
.SS "typedef int SureWareHook_Mod_Exp_t(char *const msg, int mlen, const unsigned long *mod, int elen, const unsigned long *exponent, int dlen, unsigned long *\fBdata\fP, unsigned long *res)"

.PP
Definition at line 246 of file sureware\&.h\&.
.SS "typedef int SureWareHook_Rand_Bytes_t(char *const msg, unsigned char *buf, int \fBnum\fP)"

.PP
Definition at line 67 of file sureware\&.h\&.
.SS "typedef int SureWareHook_Rand_Seed_t(char *const msg, const \fBvoid\fP *buf, int \fBnum\fP)"

.PP
Definition at line 83 of file sureware\&.h\&.
.SS "typedef int SureWareHook_Rsa_Priv_Dec_t(char *const msg, int flen, unsigned char *from, int *tlen, unsigned char *to, char *prsa, int padding)"

.PP
Definition at line 188 of file sureware\&.h\&.
.SS "typedef int SureWareHook_Rsa_Sign_t(char *const msg, int flen, unsigned char *from, int *tlen, unsigned char *to, char *prsa, int padding)"

.PP
Definition at line 210 of file sureware\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "\fBSW_EXPORT\fP \fBSureWareHook_Dsa_Sign_t\fP SureWareHook_Dsa_Sign"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Finish_t\fP SureWareHook_Finish"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Free_t\fP SureWareHook_Free"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Info_Pubkey_t\fP SureWareHook_Info_Pubkey"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Init_t\fP SureWareHook_Init"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Load_Dsa_Pubkey_t\fP SureWareHook_Load_Dsa_Pubkey"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Load_Privkey_t\fP SureWareHook_Load_Privkey"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Load_Rsa_Pubkey_t\fP SureWareHook_Load_Rsa_Pubkey"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Mod_Exp_t\fP SureWareHook_Mod_Exp"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Rand_Bytes_t\fP SureWareHook_Rand_Bytes"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Rand_Seed_t\fP SureWareHook_Rand_Seed"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Rsa_Priv_Dec_t\fP SureWareHook_Rsa_Priv_Dec"

.SS "\fBSW_EXPORT\fP \fBSureWareHook_Rsa_Sign_t\fP SureWareHook_Rsa_Sign"

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
