.TH "s2n/libcrypto-build/openssl/crypto/asn1/tasn_utl.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/tasn_utl.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBoffset2ptr\fP(addr,  offset)   (\fBvoid\fP *)(((char *) addr) + offset)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBasn1_get_choice_selector\fP (\fBASN1_VALUE\fP **pval, const \fBASN1_ITEM\fP *it)"
.br
.ti -1c
.RI "int \fBasn1_set_choice_selector\fP (\fBASN1_VALUE\fP **pval, int value, const \fBASN1_ITEM\fP *it)"
.br
.ti -1c
.RI "int \fBasn1_do_lock\fP (\fBASN1_VALUE\fP **pval, int op, const \fBASN1_ITEM\fP *it)"
.br
.ti -1c
.RI "\fBvoid\fP \fBasn1_enc_init\fP (\fBASN1_VALUE\fP **pval, const \fBASN1_ITEM\fP *it)"
.br
.ti -1c
.RI "\fBvoid\fP \fBasn1_enc_free\fP (\fBASN1_VALUE\fP **pval, const \fBASN1_ITEM\fP *it)"
.br
.ti -1c
.RI "int \fBasn1_enc_save\fP (\fBASN1_VALUE\fP **pval, const unsigned char *\fBin\fP, int inlen, const \fBASN1_ITEM\fP *it)"
.br
.ti -1c
.RI "int \fBasn1_enc_restore\fP (int *\fBlen\fP, unsigned char **\fBout\fP, \fBASN1_VALUE\fP **pval, const \fBASN1_ITEM\fP *it)"
.br
.ti -1c
.RI "\fBASN1_VALUE\fP ** \fBasn1_get_field_ptr\fP (\fBASN1_VALUE\fP **pval, const \fBASN1_TEMPLATE\fP *tt)"
.br
.ti -1c
.RI "const \fBASN1_TEMPLATE\fP * \fBasn1_do_adb\fP (\fBASN1_VALUE\fP **pval, const \fBASN1_TEMPLATE\fP *tt, int nullerr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define offset2ptr(addr, offset)   (\fBvoid\fP *)(((char *) addr) + offset)"

.PP
Definition at line 70 of file tasn_utl\&.c\&.
.SH "Function Documentation"
.PP 
.SS "const \fBASN1_TEMPLATE\fP* asn1_do_adb (\fBASN1_VALUE\fP ** pval, const \fBASN1_TEMPLATE\fP * tt, int nullerr)"

.PP
Definition at line 219 of file tasn_utl\&.c\&.
.SS "int asn1_do_lock (\fBASN1_VALUE\fP ** pval, int op, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 103 of file tasn_utl\&.c\&.
.SS "\fBvoid\fP asn1_enc_free (\fBASN1_VALUE\fP ** pval, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 151 of file tasn_utl\&.c\&.
.SS "\fBvoid\fP asn1_enc_init (\fBASN1_VALUE\fP ** pval, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 140 of file tasn_utl\&.c\&.
.SS "int asn1_enc_restore (int * len, unsigned char ** out, \fBASN1_VALUE\fP ** pval, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 184 of file tasn_utl\&.c\&.
.SS "int asn1_enc_save (\fBASN1_VALUE\fP ** pval, const unsigned char * in, int inlen, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 164 of file tasn_utl\&.c\&.
.SS "int asn1_get_choice_selector (\fBASN1_VALUE\fP ** pval, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 76 of file tasn_utl\&.c\&.
.SS "\fBASN1_VALUE\fP** asn1_get_field_ptr (\fBASN1_VALUE\fP ** pval, const \fBASN1_TEMPLATE\fP * tt)"

.PP
Definition at line 201 of file tasn_utl\&.c\&.
.SS "int asn1_set_choice_selector (\fBASN1_VALUE\fP ** pval, int value, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 86 of file tasn_utl\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
