.TH "s2n/libcrypto-build/openssl/crypto/asn1/tasn_dec.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/asn1/tasn_dec.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/asn1t\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBasn1_tlc_clear\fP(\fBc\fP)             \fBif\fP (\fBc\fP) (\fBc\fP)\->valid = 0"
.br
.ti -1c
.RI "#define \fBasn1_tlc_clear_nc\fP(\fBc\fP)       (\fBc\fP)\->valid = 0"
.br
.ti -1c
.RI "#define \fBASN1_MAX_STRING_NEST\fP   5"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "unsigned long \fBASN1_tag2bit\fP (int tag)"
.br
.ti -1c
.RI "\fBASN1_VALUE\fP * \fBASN1_item_d2i\fP (\fBASN1_VALUE\fP **pval, const unsigned char **\fBin\fP, long \fBlen\fP, const \fBASN1_ITEM\fP *it)"
.br
.ti -1c
.RI "int \fBASN1_template_d2i\fP (\fBASN1_VALUE\fP **pval, const unsigned char **\fBin\fP, long \fBlen\fP, const \fBASN1_TEMPLATE\fP *tt)"
.br
.ti -1c
.RI "int \fBASN1_item_ex_d2i\fP (\fBASN1_VALUE\fP **pval, const unsigned char **\fBin\fP, long \fBlen\fP, const \fBASN1_ITEM\fP *it, int tag, int aclass, char opt, \fBASN1_TLC\fP *\fBctx\fP)"
.br
.ti -1c
.RI "int \fBasn1_ex_c2i\fP (\fBASN1_VALUE\fP **pval, const unsigned char *cont, int \fBlen\fP, int utype, char *free_cont, const \fBASN1_ITEM\fP *it)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ASN1_MAX_STRING_NEST   5"

.PP
Definition at line 1050 of file tasn_dec\&.c\&.
.SS "#define asn1_tlc_clear(\fBc\fP)   \fBif\fP (\fBc\fP) (\fBc\fP)\->valid = 0"

.PP
Definition at line 126 of file tasn_dec\&.c\&.
.SS "#define asn1_tlc_clear_nc(\fBc\fP)   (\fBc\fP)\->valid = 0"

.PP
Definition at line 128 of file tasn_dec\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int asn1_ex_c2i (\fBASN1_VALUE\fP ** pval, const unsigned char * cont, int len, int utype, char * free_cont, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 847 of file tasn_dec\&.c\&.
.SS "\fBASN1_VALUE\fP* ASN1_item_d2i (\fBASN1_VALUE\fP ** pval, const unsigned char ** in, long len, const \fBASN1_ITEM\fP * it)"

.PP
Definition at line 137 of file tasn_dec\&.c\&.
.SS "int ASN1_item_ex_d2i (\fBASN1_VALUE\fP ** pval, const unsigned char ** in, long len, const \fBASN1_ITEM\fP * it, int tag, int aclass, char opt, \fBASN1_TLC\fP * ctx)"

.PP
Definition at line 165 of file tasn_dec\&.c\&.
.SS "unsigned long ASN1_tag2bit (int tag)"

.PP
Definition at line 117 of file tasn_dec\&.c\&.
.SS "int ASN1_template_d2i (\fBASN1_VALUE\fP ** pval, const unsigned char ** in, long len, const \fBASN1_TEMPLATE\fP * tt)"

.PP
Definition at line 151 of file tasn_dec\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
