.TH "s2n/libcrypto-build/openssl/crypto/engine/tb_ecdh.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/engine/tb_ecdh.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'eng_int\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBENGINE_unregister_ECDH\fP (\fBENGINE\fP *\fBe\fP)"
.br
.ti -1c
.RI "int \fBENGINE_register_ECDH\fP (\fBENGINE\fP *\fBe\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBENGINE_register_all_ECDH\fP ()"
.br
.ti -1c
.RI "int \fBENGINE_set_default_ECDH\fP (\fBENGINE\fP *\fBe\fP)"
.br
.ti -1c
.RI "\fBENGINE\fP * \fBENGINE_get_default_ECDH\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "const \fBECDH_METHOD\fP * \fBENGINE_get_ECDH\fP (const \fBENGINE\fP *\fBe\fP)"
.br
.ti -1c
.RI "int \fBENGINE_set_ECDH\fP (\fBENGINE\fP *\fBe\fP, const \fBECDH_METHOD\fP *ecdh_meth)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBENGINE\fP* ENGINE_get_default_ECDH (\fBvoid\fP)"

.PP
Definition at line 123 of file tb_ecdh\&.c\&.
.SS "const \fBECDH_METHOD\fP* ENGINE_get_ECDH (const \fBENGINE\fP * e)"

.PP
Definition at line 129 of file tb_ecdh\&.c\&.
.SS "\fBvoid\fP ENGINE_register_all_ECDH (\fBvoid\fP)"

.PP
Definition at line 101 of file tb_ecdh\&.c\&.
.SS "int ENGINE_register_ECDH (\fBENGINE\fP * e)"

.PP
Definition at line 92 of file tb_ecdh\&.c\&.
.SS "int ENGINE_set_default_ECDH (\fBENGINE\fP * e)"

.PP
Definition at line 109 of file tb_ecdh\&.c\&.
.SS "int ENGINE_set_ECDH (\fBENGINE\fP * e, const \fBECDH_METHOD\fP * ecdh_meth)"

.PP
Definition at line 135 of file tb_ecdh\&.c\&.
.SS "\fBvoid\fP ENGINE_unregister_ECDH (\fBENGINE\fP * e)"

.PP
Definition at line 82 of file tb_ecdh\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
