.TH "tlsextctx_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlsextctx_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBIO\fP * \fBbiodebug\fP"
.br
.ti -1c
.RI "int \fBack\fP"
.br
.ti -1c
.RI "char * \fBservername\fP"
.br
.ti -1c
.RI "int \fBextension_error\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 452 of file s_client\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int ack"

.PP
Definition at line 454 of file s_client\&.c\&.
.SS "\fBBIO\fP * biodebug"

.PP
Definition at line 453 of file s_client\&.c\&.
.SS "int extension_error"

.PP
Definition at line 850 of file s_server\&.c\&.
.SS "char* servername"

.PP
Definition at line 848 of file s_server\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
