.TH "s2n/libcrypto-build/openssl/demos/tunala/tunala.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/demos/tunala/tunala.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tunala\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_tunala_item_t\fP"
.br
.ti -1c
.RI "struct \fB_select_sets_t\fP"
.br
.ti -1c
.RI "struct \fB_tunala_selector_t\fP"
.br
.ti -1c
.RI "struct \fB_tunala_world_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSEL_EXCEPTS\fP   0x00"
.br
.ti -1c
.RI "#define \fBSEL_READS\fP   0x01"
.br
.ti -1c
.RI "#define \fBSEL_SENDS\fP   0x02"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fB_tunala_item_t\fP \fBtunala_item_t\fP"
.br
.ti -1c
.RI "typedef struct \fB_select_sets_t\fP \fBselect_sets_t\fP"
.br
.ti -1c
.RI "typedef struct \fB_tunala_selector_t\fP \fBtunala_selector_t\fP"
.br
.ti -1c
.RI "typedef struct \fB_tunala_world_t\fP \fBtunala_world_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SEL_EXCEPTS   0x00"

.PP
Definition at line 903 of file tunala\&.c\&.
.SS "#define SEL_READS   0x01"

.PP
Definition at line 904 of file tunala\&.c\&.
.SS "#define SEL_SENDS   0x02"

.PP
Definition at line 905 of file tunala\&.c\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_select_sets_t\fP  \fBselect_sets_t\fP"

.SS "typedef struct \fB_tunala_item_t\fP  \fBtunala_item_t\fP"

.SS "typedef struct \fB_tunala_selector_t\fP  \fBtunala_selector_t\fP"

.SS "typedef struct \fB_tunala_world_t\fP  \fBtunala_world_t\fP"

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 318 of file tunala\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
