.TH "s2n/libcrypto-root/include/openssl/ui_compat.h" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-root/include/openssl/ui_compat.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <openssl/opensslconf\&.h>\fP
.br
\fC#include <openssl/ui\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBdes_read_pw_string\fP(\fBb\fP,  l,  \fBp\fP,  v)   \fB_ossl_old_des_read_pw_string\fP((\fBb\fP),(l),(\fBp\fP),(v))"
.br
.ti -1c
.RI "#define \fBdes_read_pw\fP(\fBb\fP,  bf,  s,  \fBp\fP,  v)   \fB_ossl_old_des_read_pw\fP((\fBb\fP),(bf),(s),(\fBp\fP),(v))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fB_ossl_old_des_read_pw_string\fP (char *buf, int \fBlength\fP, const char *prompt, int verify)"
.br
.ti -1c
.RI "int \fB_ossl_old_des_read_pw\fP (char *buf, char *buff, int size, const char *prompt, int verify)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define des_read_pw(\fBb\fP, bf, s, \fBp\fP, v)   \fB_ossl_old_des_read_pw\fP((\fBb\fP),(bf),(s),(\fBp\fP),(v))"

.PP
Definition at line 77 of file ui_compat\&.h\&.
.SS "#define des_read_pw_string(\fBb\fP, l, \fBp\fP, v)   \fB_ossl_old_des_read_pw_string\fP((\fBb\fP),(l),(\fBp\fP),(v))"

.PP
Definition at line 75 of file ui_compat\&.h\&.
.SH "Function Documentation"
.PP 
.SS "int _ossl_old_des_read_pw (char * buf, char * buff, int size, const char * prompt, int verify)"

.PP
Definition at line 65 of file ui_compat\&.c\&.
.SS "int _ossl_old_des_read_pw_string (char * buf, int length, const char * prompt, int verify)"

.PP
Definition at line 59 of file ui_compat\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
