.TH "s2n/libcrypto-build/openssl/crypto/ui/ui_util.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/ui/ui_util.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'ui_locl\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBUI_UTIL_read_pw_string\fP (char *buf, int \fBlength\fP, const char *prompt, int verify)"
.br
.ti -1c
.RI "int \fBUI_UTIL_read_pw\fP (char *buf, char *buff, int size, const char *prompt, int verify)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int UI_UTIL_read_pw (char * buf, char * buff, int size, const char * prompt, int verify)"

.PP
Definition at line 72 of file ui_util\&.c\&.
.SS "int UI_UTIL_read_pw_string (char * buf, int length, const char * prompt, int verify)"

.PP
Definition at line 59 of file ui_util\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
