.TH "s2n/libcrypto-build/openssl/ms/uplink.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/ms/uplink.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <windows\&.h>\fP
.br
\fC#include <tchar\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'uplink\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBOPENSSL_showfatal\fP (const char *,\&.\&.\&.)"
.br
.ti -1c
.RI "\fBvoid\fP \fBOPENSSL_Uplink\fP (volatile \fBvoid\fP **table, int index)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP OPENSSL_showfatal (const char *,  \&.\&.\&.)"

.PP
Definition at line 981 of file cryptlib\&.c\&.
.SS "\fBvoid\fP OPENSSL_Uplink (volatile \fBvoid\fP ** table, int index)"

.PP
Definition at line 25 of file uplink\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
