.TH "x509_crl_method_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
x509_crl_method_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <asn1_locl\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int(* \fBcrl_init\fP )(\fBX509_CRL\fP *crl)"
.br
.ti -1c
.RI "int(* \fBcrl_free\fP )(\fBX509_CRL\fP *crl)"
.br
.ti -1c
.RI "int(* \fBcrl_lookup\fP )(\fBX509_CRL\fP *crl, \fBX509_REVOKED\fP **ret, \fBASN1_INTEGER\fP *ser, \fBX509_NAME\fP *issuer)"
.br
.ti -1c
.RI "int(* \fBcrl_verify\fP )(\fBX509_CRL\fP *crl, \fBEVP_PKEY\fP *pk)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file asn1_locl\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int(* crl_free) (\fBX509_CRL\fP *crl)"

.PP
Definition at line 131 of file asn1_locl\&.h\&.
.SS "int(* crl_init) (\fBX509_CRL\fP *crl)"

.PP
Definition at line 130 of file asn1_locl\&.h\&.
.SS "int(* crl_lookup) (\fBX509_CRL\fP *crl, \fBX509_REVOKED\fP **ret, \fBASN1_INTEGER\fP *ser, \fBX509_NAME\fP *issuer)"

.PP
Definition at line 132 of file asn1_locl\&.h\&.
.SS "int(* crl_verify) (\fBX509_CRL\fP *crl, \fBEVP_PKEY\fP *pk)"

.PP
Definition at line 134 of file asn1_locl\&.h\&.
.SS "int flags"

.PP
Definition at line 129 of file asn1_locl\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
