.TH "s2n/libcrypto-build/openssl/crypto/x509/x509_def.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/x509/x509_def.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/crypto\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBX509_get_default_private_dir\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "const char * \fBX509_get_default_cert_area\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "const char * \fBX509_get_default_cert_dir\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "const char * \fBX509_get_default_cert_file\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "const char * \fBX509_get_default_cert_dir_env\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "const char * \fBX509_get_default_cert_file_env\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* X509_get_default_cert_area (\fBvoid\fP)"

.PP
Definition at line 69 of file x509_def\&.c\&.
.SS "const char* X509_get_default_cert_dir (\fBvoid\fP)"

.PP
Definition at line 74 of file x509_def\&.c\&.
.SS "const char* X509_get_default_cert_dir_env (\fBvoid\fP)"

.PP
Definition at line 84 of file x509_def\&.c\&.
.SS "const char* X509_get_default_cert_file (\fBvoid\fP)"

.PP
Definition at line 79 of file x509_def\&.c\&.
.SS "const char* X509_get_default_cert_file_env (\fBvoid\fP)"

.PP
Definition at line 89 of file x509_def\&.c\&.
.SS "const char* X509_get_default_private_dir (\fBvoid\fP)"

.PP
Definition at line 64 of file x509_def\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
