.TH "s2n/libcrypto-build/openssl/crypto/x509/x509_r2x.c" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s2n/libcrypto-build/openssl/crypto/x509/x509_r2x.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'cryptlib\&.h'\fP
.br
\fC#include <openssl/bn\&.h>\fP
.br
\fC#include <openssl/evp\&.h>\fP
.br
\fC#include <openssl/asn1\&.h>\fP
.br
\fC#include <openssl/x509\&.h>\fP
.br
\fC#include <openssl/objects\&.h>\fP
.br
\fC#include <openssl/buffer\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBX509\fP * \fBX509_REQ_to_X509\fP (\fBX509_REQ\fP *r, int days, \fBEVP_PKEY\fP *pkey)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBX509\fP* X509_REQ_to_X509 (\fBX509_REQ\fP * r, int days, \fBEVP_PKEY\fP * pkey)"

.PP
Definition at line 68 of file x509_r2x\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
