.TH "X509_VERIFY_PARAM_ID_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
X509_VERIFY_PARAM_ID_st \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vpm_int\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSTACK_OF\fP (\fBOPENSSL_STRING\fP)*hosts"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBhostflags\fP"
.br
.ti -1c
.RI "char * \fBpeername\fP"
.br
.ti -1c
.RI "char * \fBemail\fP"
.br
.ti -1c
.RI "size_t \fBemaillen\fP"
.br
.ti -1c
.RI "unsigned char * \fBip\fP"
.br
.ti -1c
.RI "size_t \fBiplen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file vpm_int\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "STACK_OF (\fBOPENSSL_STRING\fP)"

.SH "Field Documentation"
.PP 
.SS "char* email"

.PP
Definition at line 66 of file vpm_int\&.h\&.
.SS "size_t emaillen"

.PP
Definition at line 67 of file vpm_int\&.h\&.
.SS "unsigned int hostflags"

.PP
Definition at line 64 of file vpm_int\&.h\&.
.SS "unsigned char* ip"

.PP
Definition at line 68 of file vpm_int\&.h\&.
.SS "size_t iplen"

.PP
Definition at line 69 of file vpm_int\&.h\&.
.SS "char* peername"

.PP
Definition at line 65 of file vpm_int\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
