.TH "x9_62_pentanomial_st" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
x9_62_pentanomial_st \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBk1\fP"
.br
.ti -1c
.RI "long \fBk2\fP"
.br
.ti -1c
.RI "long \fBk3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 135 of file ec_asn1\&.c\&.
.SH "Field Documentation"
.PP 
.SS "long k1"

.PP
Definition at line 136 of file ec_asn1\&.c\&.
.SS "long k2"

.PP
Definition at line 137 of file ec_asn1\&.c\&.
.SS "long k3"

.PP
Definition at line 138 of file ec_asn1\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
