.TH "ZEN_3DES_KEY" 3 "Thu Jun 30 2016" "s2n-openssl-doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZEN_3DES_KEY \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBdes3_key\fP [24]"
.br
.ti -1c
.RI "unsigned char \fBdes3_iv\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1393 of file hw_zencod\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char des3_iv[8]"

.PP
Definition at line 1395 of file hw_zencod\&.c\&.
.SS "unsigned char des3_key[24]"

.PP
Definition at line 1394 of file hw_zencod\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for s2n-openssl-doxygen from the source code\&.
